### ISSUE TITLE
Has 0.9.1 been updated on NPM? 

### ISSUE THREAD

**Issue by beatelite** [marmelab/ng-admin#1002]
I tried updating my package.json for ng-admin to 0.9.1, deleting the current folder from node_modules and then running npm update ng-admin and even npm install ng-admin --save (after deleting the version from my package.json). Node says i'm getting 0.9. but when I type angular.version in the chrome console, I still see angular 1.3.2. 

The weird thing is, if I clone the latest repo from git into my node_modules and type in the chrome console: angular.version, I see angular 1.4. However, I need proper dependency management so I'm a bit stuck. 

Is the latest truly on NPM or am I missing something?

Thanks a mill for any direction.

**Comment by fzaninotto** [comment]
Version 0.9.1 still uses angular 1.3. We've published a 1.0.0-alpha1, mostly for internal testing, which is not listed on npm (on purpose, to avoid BC breaks). This new version uses angular 1.4. You can test it by calling `npm install ng-admin@1.0.0-alpha1`.
