### ISSUE TITLE
Upgrade angular version to 1.5

### ISSUE THREAD

**Issue by gorghoa** [marmelab/ng-admin#1004]
Could we upgrade angular version to 1.5 ? I’d like to use the `component` method, used in shared directives between ng-admin and a frontend app.

see #1000 

best regards,
Rodrigue

**Comment by fzaninotto** [comment]
We've tried, and it's not easy, due to dependencies. We won't do it in the near future. 

@alexisjanvier would you mind completing with details on the dead ends we met?

**Comment by gorghoa** [comment]
Actually, given some few css selectors tweaks in the tests, all tests are green.

I’m using this custom angular 1.5 build, and so far it’s ok. I’ll continue my feedback until i’m blocked then ;)

**Comment by fzaninotto** [comment]
e2e tests have a very partial coverage. You need to test this with something like ng-admin-demo, and check regressions.

**Comment by gorghoa** [comment]
Ok, I may work on this this week if it’s useful. 

Have a nice day

**Comment by fzaninotto** [comment]
Thanks for the notice!

**Comment by gorghoa** [comment]
Ok, I’ve forked ng-admin-demo and built it with my ng-admin fork (see gorghoa/ng-admin-demo@3cd206b7985c6db7758b104595d76df46a22e1a4  ).

I’ve changed nothing on the ng-admin-demo side. 

On the ng-admin side:

- updated ui-select to the latest commit + manual build of ui-select(they didn’t have pushed their builded files…, see angular-ui/ui-select#1533)
- updated ui-bootstrap
- updated angular to 1.5.3

So far, so good. I’ve found no regression on the ng-admin-demo and in the private project I’m working on.

Maybe I’ve missed some bugs (I don’t know ng-admin and its features so well). Would you mind running and have a quick look of my ng-admin-demo fork ?
