### ISSUE TITLE
CustomTypes field are broken on master

### ISSUE THREAD

**Issue by sameerjain** [marmelab/ng-admin#1005]
Hello there, 

I downloaded latest from master branch so to use OnSubmitSuccess method on a view but that break my customtypes field and dont render them. I am not sure if its a bug or I am doing something wrong but as soon I remove OnSubmitSuccess my custometype rendered correctly and work as expected. Any idea or thought?

Edit:

I tested couple more times by redownloading latest files and it seems customtypes are all broken if used master build. Anybody with a solution to this please?

Keep It Positive
Thanks

**Comment by fzaninotto** [comment]
Can you share one of your custom types?

**Comment by sameerjain** [comment]
Its nothing fancy, I just copied filefield, renamed and use. It work with the released version but not with the master one.

**Comment by pelim** [comment]
i have the same issue - my custom type doesn't render on master

**Comment by pelim** [comment]
just found out that i have used the wrong admin config version - in the package.json for the master branch 0.11 is required

**Comment by jpetitcolas** [comment]
`master` version has evolved a lot since the 0.11 version. Closing the issue. Feel free to re-open it if the problem still occurs.
