### ISSUE TITLE
Additional GET parameters for base URL?? 

### ISSUE THREAD

**Issue by mmuruev** [marmelab/ng-admin#1007]
Seems like  
```
                    .baseApiUrl('http://api.my.local/v1/') 
                    .setDefaultRequestParams('common',{ api-key: 'my-api-key'});
```
Doesn't work. And I cant see any mention about this in the doc. And this 
`nga.application(...).setDefaultRequestParams is not a function`
make me think that this is missing. Is it possible to add this in to the project?

**Comment by djhi** [comment]
ng-admin uses [restangular](https://github.com/mgonto/restangular), see [this](https://github.com/marmelab/ng-admin/blob/master/examples/blog/config.js#L28) for an example on how to customize requests.

**Comment by mmuruev** [comment]
Well api-key and additional get params per request not so rare thing why not use nice and clean method from Rectangular??

**Comment by djhi** [comment]
As you can see [here](https://github.com/marmelab/ng-admin/blob/master/examples/blog/config.js#L25), you have direct access to the restangular provider. You can use any method it provides here, right ?

**Comment by mmuruev** [comment]
Well still not the same as sebBaseUrl() if it mocking Rectangular method see no reason why other quite ofter used thing should be in other way.

**Comment by tuxayo** [comment]
I needed to do the same thing and I ended up with:
```
myAppTodo.config(['RestangularProvider', function (RestangularProvider) {

    // use the custom query parameters function to format the API request correctly
    RestangularProvider.addFullRequestInterceptor(function(element, operation, what, url, headers, params) {
        params.apikey = 'example-API-key';
        return { params: params };
    });
}]);

```

This should add the param 'apikey=example-API-key' to each request url. I can confirm for the GET on the collection but for the rest, I'm stuck on other things.

**Comment by jpetitcolas** [comment]
@tuxayo: this is indeed the way to go. Closing the issue.

Note that if you need to add some HTTP headers, you need to use the `$httpProvider` (which will then be used by `Restangular`):

``` js
const restangularConfig = ($httpProvider, RestangularProvider) => {
    // ...
    $httpProvider.defaults.withCredentials = true;
    $httpProvider.defaults.headers.common = {
        Authorization: window.localStorage.token,
    };
};

restangularConfig.$inject = ['$httpProvider', 'RestangularProvider'];

export default restangularConfig;
```
