### ISSUE TITLE
Best Way to Consume a Service

### ISSUE THREAD

**Issue by giovanni-duarte** [marmelab/ng-admin#1008]
Examples of DEMO are entities but I need to consume only one service API **not an entity**.

For example:

> The system must send 2 parameters in the POST method and the service API returns the calculation.

I need to create the form where I will inform the two parameters.
Then send to the service API and read the API response.

**What would be the best practice I could use in my example ?**

**Comment by fzaninotto** [comment]
That's not RESt as I understand it. I don't think ng-admin fits your need.
