### ISSUE TITLE
Hide field in Edition/Creation View

### ISSUE THREAD

**Issue by shaneconnolly** [marmelab/ng-admin#1012]
I can disable editing and set a default on a field in edition and creation views with the following:
nga.field('ClientId').defaultValue(ClientId).editable(false)

I'd like to hide the field altogether, but .cssClasses(function(entry) { return 'hidden';}) only hides the input, not the entire row. I understand that this may be possible using .template but I haven't been able to get this to work. Could you possible provide a working example of a field that's given a fixed value (e.g logged in client id) but hidden in the views? Thanks in advance

**Comment by fzaninotto** [comment]
Why do you add the field to the view in the first place?

**Comment by shaneconnolly** [comment]
The API requires that field in POST and PUT requests.

**Comment by fzaninotto** [comment]
But you don't need to include the field for that. If ng-admin grabs the entry like that:

```
GET /order/123
{
  id: 123,
  foo: 'bar'
}
```

Then even if you don't include a `'foo'` field in the editionView, it will be sent (unmodified) upon submission.

**Comment by shaneconnolly** [comment]
Ah ok, I get it. What about the creationView though, lets say for the sake of argument I need to pass a fixed value in for a given field, I don't want the user selecting (or even seeing) it. Possible?

Thanks for your help, I've just discovered ng-admin a few days ago and its exactly what I need, great work.

**Comment by SebLours** [comment]
You can use the `prepareView` method of the creationView.

```js
myEntity.creationView()
    .xxxx
    .prepare((entry) => {
        entry.values.ClientId = x;
    })
;
```

**Comment by windmaomao** [comment]
wow, prepare could be very useful, thanks @SebLours
