### ISSUE TITLE
Using referenced_list with Loopbak

### ISSUE THREAD

**Issue by sm-g** [marmelab/ng-admin#1013]
I wonder, am I missing something or ng-admin does not work with standard Loopback API for filtering in `referenced_list` field?

ng-admin config:

```
businesses.creationView()
    .fields([
      nga.field('_id')
      nga.field('branches', 'referenced_list')
        .targetEntity(admin.getEntity('branches'))
        .targetReferenceField('businessid')
        .targetFields([
          nga.field('_id'),
        ])
    ]);
```

loopback config:

```
{
  "name": "Branch",
  "base": "EntityBase",
  "properties": {
  },
  "relations": {
    "business": {
      "type": "belongsTo",
      "model": "Business",
      "foreignKey": ""
    }
  },
}
```

When open business edit view with list of child branches, in `addFullRequestInterceptor` `params._filters` equals `{"businessid":5}`, which is invalid for Loopback. So I have to

```
      if (params._filters) {
        _.forEach(params._filters, function(value, entry) {
            params[`filter[where][${entry}]`]=value;
        });
        delete params._filters;
      }
```

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

Thanks for using ng-admin!
