### ISSUE TITLE
working with different REST APIs

### ISSUE THREAD

**Issue by EladRK** [marmelab/ng-admin#1015]
how can I configure ng-admin to work with several different URI endpoints?
e.g. var admin = nga.application('My Admin')
.baseApiUrl('http://localhost:6007/api/v1/');
lets me use localhost:6007 as my URI
I would like to be able to use additional URIs for other entities
(service oriented architecture - not all entities are coming from the same URI)

**Comment by Simperfit** [comment]
@EladRK You can do this by using : `
var entity = nga.entity('entity').baseURL('http://localhost:6007/api/v1/');`

ref #170

**Comment by EladRK** [comment]
thanks!
