### ISSUE TITLE
I have a pinned choice filters, the defaultValue() property is not works. 

### ISSUE THREAD

**Issue by zhaowei** [marmelab/ng-admin#1016]
```
filters([
    nga.field('category', 'choice').pinned(true).defaultValue('tech').choices([
        { label: 'Tech', value: 'tech' },
        { label: 'Lifestyle', value: 'lifestyle' }
    ]).label('Category'),
    nga.field('subcategory', 'choice').choices(subCategories).label('Subcategory')
])

```

I have a pinned choice filters, the defaultValue() property is not works.  select input is not selected

**Comment by SebLours** [comment]
A filter can not have a default value.
The filter is selected when it's applied on the list.
You can "pre-select" a filter in the url `/list?search={"category":"tech"}`

You can use the `ma-filtered-list-button` directive:
```html
<ma-filtered-list-button entity-name="entity" filter="{ category: 'tech'}">
</ma-filtered-list-button>
```

**Comment by jpradeep2003** [comment]
This seems to contradict #639 which says "You can now use defaultValue() on filter fields" Can you kindly clarify?

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

Thanks for using ng-admin!
