### ISSUE TITLE
Possible to order an embedded list via the Admin GUI?

### ISSUE THREAD

**Issue by jontonsoup** [marmelab/ng-admin#1021]
I have an embedded list that I would like to sort the order of the items. I noticed that I might be able to call `order(number|null)` on the values, but I'm not sure. 

Is there a way to do ordering via ng-admin?

Thanks!

**Comment by sam2x** [comment]
"Order" function is used to order the position of the **collection** in the dashbaord default page (this function is not used to sort/order the data inside the collection).

**Comment by jontonsoup** [comment]
@sam2x yea on further inspection it seemed that way. So I guess I'm asking about a new feature it seems.

**Comment by jpetitcolas** [comment]
@jontonsoup: I don't understand. What is the requested new feature? :)

You can already order records vie the `_order` parameter as explained by @sam2x.

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

Thanks for using ng-admin!
