### ISSUE TITLE
Is it possible to add two ng-admin apps for two different types of users?

### ISSUE THREAD

**Issue by mikes01** [marmelab/ng-admin#1022]
Hello,

I want to create two types of users, with separate admins pages.Is it possible that each ng-admin app inherits from custom ui.router state? Each  ui.router state would have a custom namespace and resolver for user's  authentication.

**Comment by sam2x** [comment]
Related to #1026. You need to build dynamically the menu list according your user role.

**Comment by fzaninotto** [comment]
Duplicate of #875
