### ISSUE TITLE
referenced_list makes successful API call, but not showing in view

### ISSUE THREAD

**Issue by geomapdev** [marmelab/ng-admin#1023]
I have a referenced_list that is making a second API call.  I can see that it's making 2 API calls, and returning 2 responses, but the referenced_list data is not coming though in my view.  Is it possible the page is loading before the second API is finished?  If so, is there a way to make it wait for all data to load?  here is the relevant snippet in my code:

```
charactersummary.showView()
    .fields([
        nga.field('characterBase'),
        nga.field('inventory', 'referenced_list')
            .targetEntity(admin.getEntity('inventory'))
            .targetReferenceField('unique_id')
            .targetFields([
                nga.field('unique_id'),
            ]),
...
```

both API calls are successful (character and inventory), but only the character data is available in my showView.  Any help is greatly appreciated!

**Comment by giovanni-duarte** [comment]
Hello, I'm a beginner
it might be better to use **".targetField"** instead of **".targetFields"**

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

Thanks for using ng-admin!
