### ISSUE TITLE
how to change request operation getList to POST

### ISSUE THREAD

**Issue by miguelslemos** [marmelab/ng-admin#1025]
how i could change type of operation getList to POST, from listView()
 E.g:
>  var user = nga.entity('users');
    // set the fields of the user entity list view
    user.listView().fields([
        nga.field('name'),
        nga.field('username'),
        nga.field('email')
    ]);
    admin.addEntity(user)<

i would like change this request to POST and passing some params,
 someone could help me please?

**Comment by SebLours** [comment]
As you can see here:
https://github.com/marmelab/ng-admin/blob/8c6d74bde7ca0281739f171f1353e8d40bfc59e6/src/javascripts/ng-admin/Crud/misc/RestWrapper.js#L34
ng-admin use Restangular `getList` method, so you must search in the Restangular doc ...

Perhaps with:
https://github.com/mgonto/restangular#addfullrequestinterceptor

**Comment by fzaninotto** [comment]
See https://github.com/marmelab/ng-admin/pull/555 for a work in progress solution for this.
