### ISSUE TITLE
How change the menu after the CONFIG?

### ISSUE THREAD

**Issue by giovanni-duarte** [marmelab/ng-admin#1029]
Hello again,

I'm trying to make my dynamic MENU. Recently I received help and 
managed to inject $HTTP on the menu as the code below.

The problem is that the **$HTTP** can only be called after the **CONFIG**.
You can see in the code that the NG-ADMIN is the MENU setting within the CONFIG .

Does anyone know tell me how do I change the menu after the CONFIG?

**File: Menu.js**
```
export default function (nga, app) {

    var initInjector = angular.injector(['ng']);
    var $http = initInjector.get('$http');
    var menu = nga.menu().title('Menu');

    $http.get('http://127.0.0.1/api/menu').then(
        function (response) {
            for (var i = 0; i < response.data.length; i++) {
                menu.addChild(nga.menu()
                    .title(response.data[i].nm_item.toString())
                    .icon('<span class="fa fa-cog fa-fw"></span>')
                    .link(response.data[i].nm_path.toString())
                    .active(path => path.indexOf(response.data[i].nm_path.toString()) === 0)
                )
            };
        }
    );

    return menu; 
}

```
**File: Main.js**
```
angular.module('myApp').config(['NgAdminConfigurationProvider', function (nga) {

    var app = nga.application('Name of System')
        .baseApiUrl('http://127.0.0.1/api/'); 

    app.menu(require('/Source/Menu')(nga, app));
    nga.configure(app);

}]);
```

**Thank you** very much!!

**Comment by Phocea** [comment]
Hello,

To get around the config phase limitation we have used a librabry called [angular-deferred-bootstrap](https://github.com/philippd/angular-deferred-bootstrap). We then have to manually bootstrap the angular app in our DOM.

Ee basically make the "configuration" call we need before to start the angular app and pass those configuration to the app.
This way you can use that data wherever you want during ther config phase.
We do this to populate dropdown menu but you probably can do the same for your menu.

**Comment by giovanni-duarte** [comment]
**Thank you, is working!**

**File: Main.js**

```
deferredBootstrapper.bootstrap({
  element: document.body,
  module: 'myApp',
  resolve: {
    APP_MENU: ['$http', function ($http) {
      return $http.get('http://127.0.0.1/api/menu');
    }]
  }
});

angular.module('myApp').config(['NgAdminConfigurationProvider','APP_MENU', function (nga, APP_MENU) {

    var app = nga.application('Name of System')
        .baseApiUrl('http://127.0.0.1/api/'); 

    app.menu(require('/Source/Menu')(nga, APP_MENU));
    nga.configure(app);

}]);
```

**File: Menu.js**

```
export default function (nga, APP_MENU) {
    var menu = nga.menu().title('Menu');
    for (var i = 0; i < APP_MENU.length; i++) { 
        menu.addChild(nga.menu()
            .title(APP_MENU[i].nm_menu)
            .icon('<span class="fa fa-cog fa-fw"></span>')
            .link(APP_MENU[i].nm_path)
            .active(path => path.indexOf(APP_MENU[i].nm_path) === 0)
        )
    };
    return menu;
}
```

**Comment by dimaklaxon** [comment]
Hello

I have tried to do as Giovanni do, but I have error "Cannot read property 'baseApiUrl' of null" and 'Cannot read property 'layout' of null'.

Any ideas?
