### ISSUE TITLE
ErrorHandler.js does not parse the error object properly

### ISSUE THREAD

**Issue by Phocea** [marmelab/ng-admin#1031]
Hello,

Sorry if i got the wrong end of the stick but I have been debugging this for a bit now and nothing else seems to make sense.

I have added Authz to my application, on the server side and return a 403 error with the following response:
{"message":"Insufficient Permissions","result":"NO_AUTH"}

But ng admin throw a notification like: State change error: undefined

Debugging it i noticed that ErrorHandler.js is trapping ui-router stateChangeError and if its not 404 send a notification error using error.message as the text of the notification.

However running this part of the code in Chrome debugger , the error object is made of several elements : config, data etcc, but not element names "message".

data does contain the 403 response, so is this just a typo and should say: error.data ?

Furthermore, can we customize this message like already done for 400 responses and described in the [Theming ](https://github.com/marmelab/ng-admin/blob/8c6d74bde7ca0281739f171f1353e8d40bfc59e6/doc/Theming.md#customizing-error-messages)section ?

Thanks!

**Comment by Phocea** [comment]
Just to add do the problem description, the same behaviour is correct on the delete approval button.
In this case the 403 error is sent to the notification message and popup. Probably because this is not handled as a stateChange

**Comment by Phocea** [comment]
Just adding the current "workaround" implementation to capture 401 / 403 responses until this is made part of the ng-admin core code (or not):

Add a http interceptor to he ng admin app that will take the user to a logout page if we receive a 401 response, and tell the user he does not have privileges to access the area he is trying to navigate to if we receive a 403 response

```
myApp.factory('httpInterceptor', ['$q', '$injector', 'notification', function ($q, $injector, notification) {
	return {
        'responseError': function(rejection) {
            if (rejection.status === 401) {
            	notification.log('Your session timed-out', { addnCls: 'humane-flatty-error' });
            	$injector.get('$state').go('logout');
            }
            if (rejection.status === 403) {
            	notification.log('You are not authorized to access this function ', { addnCls: 'humane-flatty-error' });
            	$injector.get('$state').go('dashboard');
            }
            // Replace response with rejected promise to prevent rest of execution
            return $q.reject(rejection);
        }
    };
}]);

// Add our interceptor to the App config
myApp.config(['$httpProvider',function($httpProvider) {
    $httpProvider.interceptors.push('httpInterceptor');
}]);
```

You will obviously also need to add a new route for /login

**Comment by jpetitcolas** [comment]
@Phocea: it seems indeed a good addition. Can you open a PR to officialize this interceptor? :)

**Comment by Phocea** [comment]
Salut,


Juste pour être au clair. Dans le PR, je mets la configuration d'un intercepteur pour les erreur type 401/403. Ou est ce qu'il faut modifier le errorHandler.js pour qu'il les gère ?

Ce qui "complique" la chose je pense, c'est la redirection dans chaque cas, qui risque de dépendre de ce que chacun veut faire. D'autant plus qu'il n'y a pas de route login ou logout de base dans ng-admin pour le moment...

Je pencherai plutot pour un  changement de la doc avec l'exemple du coup.


What do you think :) ?


________________________________

**Comment by jpetitcolas** [comment]
I would prefer adding it into the `errorHandler` directly. Where do intercepters intercept requests? Before or after the handler? Indeed, being able to override it is important IMO.

For the error message, we can put a very specific message, like: "A server 403 error occured. Please try again later". It would be generic enough and give more information than the current one.

**Comment by jpetitcolas** [comment]
Salut ! Je viens tout juste de te répondre sur l'issue. :)



-- 
Jonathan Petitcolas
Tél. : 06.45.88.54.95
www.marmelab.com

2016-10-03 11:04 GMT+02:00 Phocea <notifications@github.com>:

**Comment by Phocea** [comment]
J'ai vu merci .. J ai du tout rephrsser. les reponses par email se mette automatiquement sur github !


Je vais tester la soluce dans le handler directement et je poste ca dès que je peux


________________________________

**Comment by Phocea** [comment]
Interceptor do it before the handler, which cause a double message issue since the interceptor still forward the response.
I will propose something and we can discuss it then. The handler is on $stateChangeError event at the moment, meaning that if we had a login page it would still need to be handled somehow, but my opinion is that such a case would be outside the scope of ng-admin (but could find its place in the Poster Galore demo or in the doc)

**Comment by Phocea** [comment]
We are (finally) about to look at this.
I think the easiest is to be able to register a customer errorHandler instead of the current one. Like this anyone can customize the error message and most importantly add a route change in the code if needed.

What do you think @jpetitcolas , would this be an acceptable change?

**Comment by Phocea** [comment]
#917

**Comment by Phocea** [comment]
Related to #917

**Comment by Phocea** [comment]
Fixed by https://github.com/marmelab/ng-admin/issues/1273
