### ISSUE TITLE
Feature request: be able to load a listView with a filter active

### ISSUE THREAD

**Issue by lstep** [marmelab/ng-admin#1032]
The use case is that I have a huge database with a lot of entries, and each time I load it (with `listView`), it takes a very long time to load. If I could load the page with a filter for displaying "by default" only today's records, it would load much faster.

Permanent filter would be OK if it was modifiable afterwards by the user.

**Comment by Phocea** [comment]
Look at @SebLours answer on this issue https://github.com/marmelab/ng-admin/issues/1016

Also you should implement pagination on your server and wont have any display performance issues

**Comment by lstep** [comment]
I don't really have any control on the server as it's a PostgREST server, so it's just answering ng-admin's requests.

**Comment by SebLours** [comment]
I don'u understand in PostgREST you can set a limit to your query ...
```
Range-Unit: items
Content-Range → 0-14/15
```
Look at the ng-admin-postgrest demo
https://github.com/marmelab/ng-admin-postgrest/blob/master/main.js#L14

**Comment by jpetitcolas** [comment]
Closing the issue as it seems solved. Please free to ask some help on our [Gitter](https://gitter.im/marmelab/ng-admin). :)
