### ISSUE TITLE
remove param from url

### ISSUE THREAD

**Issue by ryms** [marmelab/ng-admin#1035]
I can't remove param from url. an example:
http://localhost:8080/#/users/list?sortField=users_ListView.company.name&sortDir=ASC

**Comment by sam2x** [comment]
I'm not sure there is a feature on that. If you want to remove Ng-admin parameter, either you delete them server-side (eg: in a middleware), either you use a Restangular hook (eg: addRequestInterceptor), which allow you to access to the url (https://github.com/mgonto/restangular#addrequestinterceptor).

However, I would highly suggest you to implement these parameters, they may be very useful.
