### ISSUE TITLE
I want a read only field

### ISSUE THREAD

**Issue by mosasiru** [marmelab/ng-admin#1037]
edit request to a server includes non editable fields' values.
I want to omit non editable fields, or "read only" fields.
Any other solutions to omit fields from request?

**Comment by mosasiru** [comment]
https://github.com/marmelab/ng-admin/issues/808
may be related.

**Comment by SebLours** [comment]
see #983

**Comment by mosasiru** [comment]
https://github.com/marmelab/ng-admin/issues/983#issuecomment-197881514
that's what I wanted! thanks!
