### ISSUE TITLE
One reference field(country) depending on another reference(state)

### ISSUE THREAD

**Issue by manind007** [marmelab/ng-admin#1040]
I have two reference field.
1. Country
2. State

The **state *\* should filtered based on the selected **country**

Pls help me. how can we achieve this

Hi, The below example also not working based on the expectations. Subcategories not filtered based on the selected category

``` js

    var subCategories = [
        { category: 'tech', label: 'Computers', value: 'computers' },
        { category: 'tech', label: 'Gadgets', value: 'gadgets' },
        { category: 'lifestyle', label: 'Travel', value: 'travel' },
        { category: 'lifestyle', label: 'Fitness', value: 'fitness' }
    ];

      nga.field('category', 'choice')  
            .choices([ 
                { label: 'Tech', value: 'tech' },
                { label: 'Lifestyle', value: 'lifestyle' }
            ]),

        nga.field('subcategory', 'choice')
            .choices(function(entry) {  
                return subCategories.filter(function (c) {
                    return c.category === entry.values.category
                });
            }),
```

Thanks for advance.

**Comment by manind007** [comment]
Hi, The below example also not working based on the expectations. Subcategories not filtered based on the selected category

  var subCategories = [
            { category: 'tech', label: 'Computers', value: 'computers' },
            { category: 'tech', label: 'Gadgets', value: 'gadgets' },
            { category: 'lifestyle', label: 'Travel', value: 'travel' },
            { category: 'lifestyle', label: 'Fitness', value: 'fitness' }
        ];

              nga.field('category', 'choice')  
                    .choices([ 
                        { label: 'Tech', value: 'tech' },
                        { label: 'Lifestyle', value: 'lifestyle' }
                    ]),

                nga.field('subcategory', 'choice')
                    .choices(function(entry) {  
                        return subCategories.filter(function (c) {
                            return c.category === entry.values.category
                        });
                    }),

**Comment by windmaomao** [comment]
I tested the code as well. The interesting thing is that it works if category is a fixed value. But once the category has been changed at edition view, the subcategory choices will not change accordingly. 

I know this feature might not be completed yet, but just want to find out the current implemented version.

**Comment by J28848** [comment]
+1

**Comment by manind007** [comment]
Thanks. Needed this features for me.

**Comment by maxvi** [comment]
+1

**Comment by jpetitcolas** [comment]
I wasn't able to reproduce the issue on master. Which version are you using?

For information, here is a [PlunkR](http://plnkr.co/edit/YLpk1iMhFjqsVgHttU88?p=preview) showing it is working. :)

**Comment by Kmaschta** [comment]
No response from a while here.

I close this one, feel free to open it again if needed!
