### ISSUE TITLE
Support for compound primary key

### ISSUE THREAD

**Issue by tuxayo** [marmelab/ng-admin#1047]
If it's supported, is there some doc about it?

Example of API:
To access an individual object, the URL looks like `/my-entities/province-name/year`, example: `/my-entities/Sevilla/2010`
There would be no id field in the model.

**Comment by fzaninotto** [comment]
It's not supported, and it won't be. Composite primary keys are a nightmare (I implemented such support in a previous admin generator, never again). Besides, it's far from being standardized in REST.

**Comment by tuxayo** [comment]
> Composite primary keys are a nightmare

I totally understand, thanks anyway :)
