### ISSUE TITLE
How to update the UI as new data is added?

### ISSUE THREAD

**Issue by ashleydavis** [marmelab/ng-admin#1048]
Thanks very much for ng-admin, it's awesome.

I'm new to this, sorry if you have already put this information else where.

Is it possible to have ng-admin poll the REST API for changes to the data? (eg entities added/removed, fields changes, etc).

**Comment by fzaninotto** [comment]
That's not the way it works, but if you want to try and hack ng-admin into doing it, you're welcome to try ;)
