### ISSUE TITLE
Upload image and preview

### ISSUE THREAD

**Issue by alapasset** [marmelab/ng-admin#1049]
Hi everybody,

Already I wanted to say a big thanx for your work.

Then I 'd like to know if it is possible with your tool to upload an image in a form with a preview.

Thank you in advance.

**Comment by sam2x** [comment]
Create a directive and it to ng-admin : 
http://stackoverflow.com/questions/18754943/preview-image-before-uploading-angularjs

**Comment by alapasset** [comment]
Someone have an example plz?
