### ISSUE TITLE
Can't browse away from a listView with a filter

### ISSUE THREAD

**Issue by josephwmorse** [marmelab/ng-admin#1050]
1. Go to a listView
2. Add a filter and enter a value
3. Click a different entity in the left nav

Instead of taking you to the entity you clicked on, you will just be returned to the current listView, with the filter removed.  The URL briefly updates to the correct destination, then reverts to the URL for the page you are already on (without the filter)

**Comment by Phocea** [comment]
Which version are you ujsing? becausae i cannot reproduce the error you are describing

**Comment by josephwmorse** [comment]
This is version 0.9.1, ng-admin.min.js

**Comment by Phocea** [comment]
Looks like this bug https://github.com/marmelab/ng-admin/issues/792. Try updating your version of ng-admin

**Comment by josephwmorse** [comment]
Ah yes this is fixed in 1.0.0-alpha4.  Thanks!
