### ISSUE TITLE
ma-create-button

### ISSUE THREAD

**Issue by jgrosde** [marmelab/ng-admin#1051]
Hi,

I started to use ng-admin on a REST API and it is a really great tool.
I configured several linked entities, it works like a charm.

I moved on to the creation views and I have an issue with the directive ma-create-button.
I use it the way I found on your blog and on source code : 
```javascript
profile.editionView().title('Update profile').fields(
                    [ profile.listView().fields(),
                      nga.field('label')
                          .template('<span><ma-create-button entity-name="rule" size="sm" label="Create rule"></ma-create-button></span>')]);
```

The button shows up, but when I click it, I have a lovely "Not Found" message.
I dig a bit, and when the method scope.gotoCreate is executed, the variables scope, element, attrs are not resolved.

I'm sure I am missing something obvious but I cannot find it.

If someone has an idea. Thanks a lot. And thanks for this tool.

Jerome

**Comment by Phocea** [comment]
This should work in theory, but do you have more of your code?
Where is the rule entity created.

Try to get back to the basicsand do not inherit the fields from your listview, and declare your field in the old fashion way:

`nga.field('', 'template').label('').template('<span><ma-create-button entity-name="rule" size="sm" label="Create rule"></ma-create-button></span>')`

I have code exactly like this and it is working fine

**Comment by jgrosde** [comment]
Thank you for your answer.
As I mentioned, all my entities are displayed and updated properly. It is just this create button I have trouble with (and I need it to initialize a default value).
All my configuration is in a single js file.

I just tried this (I removed non-related instructions from my js file) : 

```javascript
var admin = nga.application('Admin').baseApiUrl('XXXX/admin/'); // main API endpoint
....
// profile resource
var profile = nga.entity('profiles');
// rule resource
var rule = nga.entity('rules');
....
rule.creationView().title('Create a rule')
                .fields([ 
                      nga.field('name')
                     ]);
profile.editionView().title('Update profile').fields(
                    [ nga.field('name'),
                      nga.field('', 'template').label('').template('<span><ma-create-button entity-name="rule" size="sm" label="Create rule"></ma-create-button></span>')]);
...
admin.addEntity(profile);
admin.addEntity(rule);

// attach the admin application to the DOM and execute it
nga.configure(admin);
```

Still having this Not Found message when clicking the button :/

I forgot to mention, I use the 0.9.1 release version of ng-admin.

**Comment by Phocea** [comment]
This looks ok to me .. maybe try to update your ng admin version.

the only thing I do differently is the sequence of config. Our admin.addEntitiy are done before the actual entity configuration

```
var admin = nga.application('Admin')....
...
admin.addEntity(nga.entity('profile'));
...
// profile resource
var profile = nga.entity('profiles');
// rule resource
var rule = nga.entity('rules');
....
rule.creationView().title('Create a rule')
```

**Comment by jgrosde** [comment]
Yes, I tried that too , same result. 
Updated to the version 1.0.0-alpha2, same result
:(

I will remove this button for now, and wait to find some javascript skills to dig into this issue.

Thanks for taking some time to look at it anyway. I'm closing the issue as it's clearly not a bug as you got it working on your application.

**Comment by sam2x** [comment]
I was looking for a template that redirect to create button, and i fall in this issue. You got confused between the entity name and your variable name.

Here your entity is named 'rules' : 

     var rule = nga.entity('rules');

But in your template, you're referencing 'rule' (like your variable name), thus the error 'not found'

     nga.field('', 'template').label('').template('<span><ma-create-button entity-name="rule" size="sm" label="Create rule"></ma-create-button></span>')]);

So your 'entity-name' should be 'entity-name="rules"'.
Regards.

**Comment by jgrosde** [comment]
Thank you so much for your comment !!! Indeed, you're right, with the proper entity-name, it works !! 
Good surprise to start my day :) 

Thanks again sam2x.
