### ISSUE TITLE
reference_many Field Type overflows in show view

### ISSUE THREAD

**Issue by enorrmann** [marmelab/ng-admin#1052]
but in the edit view it is working fine

wrong: http://i.imgur.com/nXfmA88.png

right: http://i.imgur.com/pdq0vkv.png

**Comment by Phocea** [comment]
@jpetitcolas @Kmaschta What do we do with this? I cannot reproduce the reported bug by @enorrmann .
Shall we close it?

**Comment by jpetitcolas** [comment]
Let's close it for now. @enorrmann, feel free to re-open the issue if you still encounter it.
