### ISSUE TITLE
Need to set field as readonly @runtime

### ISSUE THREAD

**Issue by manind007** [marmelab/ng-admin#1060]
Hi,

For creation view, If possible to set the field as read-only at run-time based on the parent field.

Thanks,

**Comment by sam2x** [comment]
Have you taken a look at the feature **prepare**  that is run before view render ? It may solve your problem.
http://ng-admin-book.marmelab.com/doc/reference/View.html

**Comment by fzaninotto** [comment]
I suggest you use a custom directive for that.
