### ISSUE TITLE
npm 0.9.2 coming ? 

### ISSUE THREAD

**Issue by windmaomao** [marmelab/ng-admin#1061]
every time I have to manually copy the build folder, is this possible that we release npm 0.9.2 ? the last one was from last year.

**Comment by fzaninotto** [comment]
There is a v1.0.0-alpha4 release, lacking the stable tag. Feel free to test it!

**Comment by windmaomao** [comment]
thanks , how do you reference it with npm install, thanks. not sure how to update with tag.
