### ISSUE TITLE
Is it possible to invoke a custom callback from a menu?

### ISSUE THREAD

**Issue by ashleydavis** [marmelab/ng-admin#1062]
I'd like to invoke some custom code when a menu is clicked. It might look something like this in the API.

```
	var menu = nga.menu()
		.addChild(nga.menu()
                     .title("My custom menu")
                     .action(function () {
                            ... my custom code ...
                     });
                )

```

Is this possible?

**Comment by sam2x** [comment]
From the menu html template (1) & js directive (2) there is no such direct feature.
However, you can specify a template in nga.menu object to control how the menu render. From this perspective you can create a directive with a onClick handler.

(1)  https://github.marmelab/ng-admin/blob/ab80db5db9ddd87fba0a9488c72244c576cc4a27/src/javascripts/ng-admin/Main/view/menuBar.html
(2) https://github.com/marmelab/ng-admin/blob/8c6d74bde7ca0281739f171f1353e8d40bfc59e6/src/javascripts/ng-admin/Main/component/directive/maMenuBar.js

**Comment by fzaninotto** [comment]
Yep, it's not the purpose of the menu to execute code. But when the menu leads to a certain URL, and this URL corresponds to a controller, you can execute whatever you want in that controller.

As a reminder, here is how to add custom menus: https://github.com/marmelab/ng-admin/blob/1d5bb9e5ef4412ce4ca8d6443877edb2ce5f1cbc/examples/blog/config.js#L429-L431
