### ISSUE TITLE
Not working with MongoDB and strongloop API

### ISSUE THREAD

**Issue by aniruddhasm** [marmelab/ng-admin#1063]
Hello,
I am trying to integrate ng-admin. I am using Strongloop for API. The database for strongloop is mongodb.
```
myApp.config(['NgAdminConfigurationProvider', function (nga) {
    // create an admin application
    var admin = nga.application('Admin Panel')    
    .baseApiUrl('http://myServerIp:3030/api/'); // main API endpoint
```
I am using the above code to start the ng-admin.
But as soon as I start ng-admin using
```
make run
```
The api crashes & so the ng-admin stops working.

Please find details below of my server
mongodb version v3.2.4
nodejs v5.9.0

Also I found out. Instead of using my local mongodb if I am using [mlabs](https://mlab.com/) for my database. Then the ng-admin, Strongloop API is working fine.
The mongod version at mlabs is 3.0.7.

Please help I am stuck here from a long time

**Comment by fzaninotto** [comment]
Sorry, ng-admin is client-side only, I have no idea what can happen son your server.
