### ISSUE TITLE
Customizing error messages is not valid for ListView?

### ISSUE THREAD

**Issue by minixalpha** [marmelab/ng-admin#1065]
In the document [Customizing Error Messages](https://github.com/marmelab/ng-admin/blob/master/doc/Theming.md#customizing-error-messages), 

> You can use the app.errorMessage(), entity.errorMessage() or view.errorMessage() methods to customize the message displayed when an error occurred with the API.

But when I use `app.errorMessage` to custome the error message, it does not work for list view. When api server response an error,  list view display `State change error: undefined`. In edit view, the custom error message works.

**Comment by Phocea** [comment]
Related to https://github.com/marmelab/ng-admin/pull/1245
PR will allow you to better customise http error

**Comment by Phocea** [comment]
Fixed by https://github.com/marmelab/ng-admin/pull/1273
