### ISSUE TITLE
referenced_list - show all the objects instead of only referenced one

### ISSUE THREAD

**Issue by thiagofalcao** [marmelab/ng-admin#1066]
i will leave the question my reference list show all the places instead of only places that are referenced , the seller_seller_id = seller.id is not working, anyone know why?
here is the code and de JSON;.
//Show seller
seller.showView().title('Exibir Vendedor')
.fields([
nga.field('name').label('Nome'),
nga.field('email').label('E-mail'),
nga.field('id').label('id'),
nga.field('places', 'referenced_list')
.targetEntity(admin.getEntity('places'))
.targetReferenceField('seller_seller_id')
.targetFields([
nga.field('seller_seller_id'),
nga.field('id')
])
]);
"sellers": [
{
"id": 3,
"createdAt": "CURRENT_TIMESTAMP",
"updatedAt": "CURRENT_TIMESTAMP",
"name": "titi vendedorINSERT",
"email": "titi@vededor.com",
"password": 123,
"cpf": "0234923432432.234",
"admin": 2,
"active": true
},places": [
{
"id": 2,
"cnpj": 12330917234,
"name": "restaurante do chines",
"address": "Rua do carai",
"payment_method": "Dinheiroa",
"latitude": -32.423532,
"longitude": -22.4212324,
"cover_url": "http://imagepath.comadd",
"opened": true,
"place_description": "Uma breve descricao sobre o lugarbf ",
"phone_number": "(81)3323-12122",
"type": "PRODUCT",
"active": true,
"category": "Portuguesas",
"cost": 3,
"place_category_place_category_id": 14,
"seller_seller_id": 2,
"city": "teste",
"zipcode": 5959595959
},
the problem is the GET is the show view is bring all the places and not getting the right seller_seller_id . Thanks for the attention

**Comment by miguelslemos** [comment]
we expect only show places where field seller_seller_id = id, the filters doesn't work

**Comment by thiagofalcao** [comment]
Sorry about the trouble, I fixed the question. Please may review and open the issue ? Really appreciate the help.
