### ISSUE TITLE
Reference populated without singleApiCall

### ISSUE THREAD

**Issue by windmaomao** [marmelab/ng-admin#1069]
I guess when you need to make a single call to grab all records with singleApiCall, you want to save your trip to the server. 

In mongo, we have option of `populate`, so when you call fetch call, you have the joined records inline. I wonder if there's way where you can have a new entity, ex. referencePopulated, so that you can have all the functionalities of reference, except you don't have to call to fetch joined records API, skipping the singleApiCall.

**Comment by fzaninotto** [comment]
I guess what you're looking for is `embedded_list`. See the doc at http://ng-admin-book.marmelab.com/doc/Relationships.html#embedded-entities
