### ISSUE TITLE
textangular dependency update

### ISSUE THREAD

**Issue by dbankier** [marmelab/ng-admin#1071]
Can we update the textangular dependency?
(There are few fixes I would like.)
Not sure if there is an impact...

**Comment by sam2x** [comment]
I'm not ng-admin developper, but no release seems planned in short/medium time (read it from others issue). What's wrongs in updating your own textangular entry in package.json ?

**Comment by jpetitcolas** [comment]
We released a new version during last weeks which has updated textAngular to 1.4.3. Is it a correct version for you @dbankier?

**Comment by dbankier** [comment]
Yep. Fine. Thanks.
