### ISSUE TITLE
Reference error when 404

### ISSUE THREAD

**Issue by sam2x** [marmelab/ng-admin#1079]
Hey, i spotted an issue. I have :
  
- Two entities named **X** and **Y**. 
- **X** has a 'reference' field named **foreign_id** pointing to **Y** id.

When i delete Y **from the backend**, and load the view X, ng-admin fetch my Y referenced entity (who is still referenced), and got 404 error (until now, everything is "normal"). 

However i was expecting ng-admin to handle this case, and set "empty" value to my field, or red cross to this field. However, ng-admin throws the following error : 

     TypeError: t.datastore(...).getEntries(...).find is not a function
         at link (http://xxx/js/admin.js:16:25264)
         at http://xxx/js/admin.js:25:5744
         at ae (http://xxx//js/admin.js:25:5801)
         at g (http://xxx//js/admin.js:24:31621)
         at s (http://xxx//js/admin.js:24:27816)
         at g (http://xxx//js/admin.js:24:31570)
         at s (http://xxx/js/admin.js:24:27816)
         at g (http://xxx/js/admin.js:24:31570)
         at s (http://xxx/js/admin.js:24:27816)
         at $get.t (http://xxx/js/admin.js:24:27345) <ma-reference-field field="::field" value="value" datastore="::datastore" class="ng-isolate-scope"> 

Incriminated file  : https://github.com/marmelab/ng-admin/blob/8c6d74bde7ca0281739f171f1353e8d40bfc59e6/src/javascripts/ng-admin/Crud/field/maReferenceField.js

In show view it's not a big deal, but in edition view ng-admin breaks his 'list' reference feature, so i can't  select new value from the list. 
I tried to handle this with restangular by returning default value, no luck. Anyone has handled this edge case ?

**Comment by fzaninotto** [comment]
Shall we really assume that the REST backend shall not respect referential integrity? In that case, there are probably many other edge cases that should be dealt with, but it's really an edge case IMO.

**Comment by sam2x** [comment]
Hmmm i don't have relevant case where this should be legit to have default 'fallback' scenario. I left this open for 1month more, if anyone else have interesting use case. Else i'll close.

**Comment by jpetitcolas** [comment]
More than 3 months later, let's close it. :)
