### ISSUE TITLE
Use multiple fields in targetReferenceField

### ISSUE THREAD

**Issue by Emilinovich** [marmelab/ng-admin#1084]
i have an many years working database with multiple fields as primary key.
In a showview i want to show a one-to-many relationship but foreign key is a composite key with 3 fields and targetReferenceField can't assign more than 1 field i think.

Is there any way to setup a showview with a field type reference_list in any way to workaround this?

**Comment by sam2x** [comment]
"Not supported, and it wont be." https://github.com/marmelab/ng-admin/issues/1047
