### ISSUE TITLE
stateParams not reset when moving from one showView to another showView

### ISSUE THREAD

**Issue by josephwmorse** [marmelab/ng-admin#1085]
1. Navigate to page 2 (or higher) in a listView for entity A
2. Click on an entity in the list
3. In the showView or editionView, click on a detailLink reference to entity B
4. In entity B's showView or editionView, click the List button

You will now be viewing the listView for entity B, on the same page number you were on in the entity A listView.  If the page number you were on for the first listView is higher than the number of pages in the second listView, you will get a 'page not found' error.

This is release 1.0.0-alpha4

**Comment by fzaninotto** [comment]
I can't reproduce the bug in the blog example when I remove infinite pagination on post list and set `perPage(5)` on both the comment and the post list.

Fell free to reopen if you can find a reproduceable test case with the blog example.
