### ISSUE TITLE
Feature Request: Field groups

### ISSUE THREAD

**Issue by faboulaws** [marmelab/ng-admin#1087]
Hi 
First of all thanks for creating such a useful module.

There is a need for field group for:
- form section where related filed are grouped together (html fieldset or bootstrap form-group can be used )
- field group where related  field could be displayed inline.

I think that by default  all field should belong to 1 group. From there is would be easy to support the grouping functionality when there are more than 1 group.

**Comment by fzaninotto** [comment]
This would add quite a large amount of code, both for configuring and for handling groups. Besides, I believe that each developer will have their own preference as to how to display groups (tabs, wizard, fieldgroups, etc). 

ng-admin handles simple form layouts, and lets developer override everything using `.template()`. We won't go further than that.
