### ISSUE TITLE
Error banner no longer appearing

### ISSUE THREAD

**Issue by cfatt10** [marmelab/ng-admin#1094]
It seems that the red banner that used to drop down from the top when the server returned an error (400, 404, 500, etc.) is no longer appearing. I believe this first started happening when I upgraded my build files from v0.2.15 to v0.2.18. I have pulled the most recent commit to master (4faeb7d at the time of writing) and have tried those build files, but the problem is still persisting.

**Comment by Phocea** [comment]
I can concur with this we have the following code capturing business message error on deletion and after clicking the "confirm delete button" we do not have the message popping up anymore, even though the server is returning 400 with the expected payload

```
	editorialChannel.errorMessage(function (response) {
		if ((response.data.technicalMessage !== null) && (response.data.technicalMessage.length > 0)) {
			return 'Global error: ' + response.status + ' (' + response.data.technicalMessage + ')';
		}
		else {
			return 'Global error: ' + response.status + ' (' + response.data.businessMessage + ')';
		}
	});
```

**Comment by Phocea** [comment]
May be related to #1036

**Comment by Phocea** [comment]
Fixed by https://github.com/marmelab/ng-admin/pull/1197
@jpetitcolas maybe you can close this issue? :)

**Comment by jpetitcolas** [comment]
@cfatt10: can you recheck and close the issue if #1197 fixed it? :)

**Comment by cfatt10** [comment]
@jpetitcolas The error banners are now showing up again, but I have not been paying close enough attention to tell if it was specifically #1197 that fixed it.

**Comment by Kmaschta** [comment]
Thanks for the feedback!
