### ISSUE TITLE
Filter one reference combo by another one

### ISSUE THREAD

**Issue by talaviss** [marmelab/ng-admin#1095]
Lets say i have a reference dropdown with the following values: 1,2,3

when the user choose/select  1 in the first dropdown I want to show in another dropdown values which are based on the selection in the first dropdown (aka filtering).

The dropdowns vales in the edit view are based on the user selection and filters one the other.

How can I do this?

**Comment by FelixMalfait** [comment]
Hi,
Sometime you'll have to dig through the ng-admin source and copy/paste it when you want to customise templates.
In my case, I wanted to show `message_target_id` only if  `message_target_type` was equal to `employee`.

    nga.field('message_target_type', 'choice')
       .label('When a text arrives...')
       .choices(enums.phone_sms_target_type)
    nga.field('message_target_id', 'reference')
        .label('Target')
        .targetEntity(admin.getEntity('users/employees'))
        .targetField(nga.field('first_name'))
        .template(
          '<div id="row-{{ field.name() }}" class="form-field form-group has-feedback" ng-class="getFieldValidationClass()" ng-show="entry.values[\'message_target_type\'] === \'employee\' && entry.values.can_do_sms">' +
            '<label for="{{ field.name() }}" class="col-sm-2 control-label">' +
              '{{ field.label() }}<span ng-if="field.validation().required">&nbsp;*</span>&nbsp;' +
            '</label>' +
            '<div class="col-sm-10 col-md-8 col-lg-7">' +
              '<ma-reference-field field="::field" value="entry.values[field.name()]" entry="entry" entity="::entity" form="formController.form" datastore="::formController.dataStore"></ma-reference-field>' +
              '<span ng-show="fieldHasValidation()" class="glyphicon form-control-feedback" ng-class="fieldIsValid() ? \'glyphicon-ok\' : \'glyphicon-remove\'"></span>' +
            '</div>' +
          '</div>', true),

Passing `true` allows to replace the full row. In your case you might not want to hide the full row but only modify the values so it would be something shorter like this:

       .template('<ma-reference-field field="::field" value="entry.values[field.name()]" entry="entry" entity="::entity" form="formController.form" datastore="::formController.dataStore"></ma-reference-field>', false),

You can replace the template with wathever you like, say `<ma-choice-field field="::field" entry="entry" value="value" choices="myChoices | aFilter "></ma-choice-field>`

**Comment by yaring** [comment]
@FelixMalfait , is it possible to pass the `admin.getEntity('users/employees')` into my custom directive?

**Comment by faboulaws** [comment]
A clean solution to this would be the option for a custom filter function similar to the permanentFilters() .

**Comment by Phocea** [comment]
Isnt it how choices filed are suppose to work by default.
Please check out this [doc](https://github.com/marmelab/ng-admin/blob/master/doc/reference/Field.md#choice-and-choices-field-types)

Closing for now, feel free to reopen if required
