### ISSUE TITLE
Modal Search

### ISSUE THREAD

**Issue by giovanni-duarte** [marmelab/ng-admin#1096]
Hello friends, I need to open a modal window to the user search for a specific item.
Someone would have an idea of ​​how to do this in the NG- ADMIN ?

![capturar](https://cloud.githubusercontent.com/assets/2203976/15657590/9c8c5072-2688-11e6-9231-438c5f2e0615.JPG)

**Comment by jpetitcolas** [comment]
@giovanni-duarte: you would need a custom directive to achieve it. You can use for instance [Angular Bootstrap](https://angular-ui.github.io/bootstrap/).
