### ISSUE TITLE
Add pagination at the top of datagrid

### ISSUE THREAD

**Issue by xaviarias** [marmelab/ng-admin#1098]
Hi,

I'm trying to add a pagination block at the top of the datagrid by declaring a `customListLayout.html` template in the list view of an entity. I'm using **NgAdmin v0.9.1**.

The list layout renders the list by using a named `ui-view` directive:

`<div ui-view="grid"></div>`

This view seems to be defined in the file `routing.js` and calls directly to the default list template:

`import listTemplate from './list/list.html';`

Is it possible to specify a custom template for the list or create a new UI view based on `grid` which uses my list template `customList.html`?

Thanks

**Comment by Phocea** [comment]
Indeed you can: [doc](https://github.com/marmelab/ng-admin/blob/master/doc/Theming.md#customizing-the-view-template-for-a-given-entity)

Closing for now, feel free to reopen if this doesnt not fix your issue
