### ISSUE TITLE
referenced_list in listView doesn't work

### ISSUE THREAD

**Issue by mosasiru** [marmelab/ng-admin#1100]
https://github.com/marmelab/ng-admin/issues/786
To avoid above the issue, I try to referenced_list.
However, It seems that referenced_list in listView doesn't work.
Is it a specification? or just only not implemented?

**Comment by cfatt10** [comment]
From the referenced_list documentation (http://ng-admin-book.marmelab.com/doc/reference/Field.html#-referenced-list-field-type)

> However, they are only useful in showView and editionView (you can't display a datagrid in a datagrid, so this excludes the listView

**Comment by mosasiru** [comment]
thanks.
