### ISSUE TITLE
Field configuration: use field value (ex. id) as paramater (for file upload url)

### ISSUE THREAD

**Issue by blocknotes** [marmelab/ng-admin#1102]
I'm trying to configure a field for file upload.

In creationView() I have a field like this:
`nga.field('image', 'file').uploadInformation( { 'url': '/posts/4', 'method': 'PATCH' } )`

This works correctly with a static url.
Now I need to set the URL parameter dinamically.
Something like: 'url': '/posts/' + nga.field('id')

How can I achieve this?

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

Thanks for using ng-admin!
