### ISSUE TITLE
How to get original item in .map function?

### ISSUE THREAD

**Issue by fedotxxl** [marmelab/ng-admin#1103]
Hello

Server returns complex object. I wanna display it on the list page. I created field and use `map` function to get value. The problem: `map` receives transformed object - _it's flatten_!
1. How to get original (not modified) object?
2. How to disable flattening?

**Comment by jamespsterling** [comment]
Are you just trying to show the mapped value on the list page using a'reference' type field in ng-admin? 
What do you mean by flattened, do you have an example?
Do you have a configuration example of what you are trying to do?

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

Thanks for using ng-admin!
