### ISSUE TITLE
Translation problems

### ISSUE THREAD

**Issue by blocknotes** [marmelab/ng-admin#1104]
I can't make translations work... I'm following the doc:
https://github.com/marmelab/ng-admin/blob/master/doc/Translation.md

Here what I did:
- installed translate component (currently 2.11.0):
  `bower install --save angular-translate`
- added script reference after ng-admin.min:
  `<script src="bower_components/angular-translate/angular-translate.min.js"></script>`
- included component in module definition:
  `var app = angular.module( 'adminApp', [ 'ng-admin', 'pascalprecht.translate' ] );`
- setup translation in app.config:
  `app.config( [ '$translateProvider', 'NgAdminConfigurationProvider', function( $translateProvider, NgAdminConfigurationProvider ) {
    $translateProvider.translations('fr', {
      'BACK': 'Retour',
      'DELETE': 'Supprimer',
      //...
    });
    $translateProvider.preferredLanguage('fr');
    // ng admin configuration follow...
  }]);`

The translation component works, if I use a string outside ng-admin it is translated correctly:
`<p>test... {{ 'EXPORT' | translate }}</p>`

Am I missing something?

**Comment by ValentinKlinghammer** [comment]
I'm wondering about this as well, what's the correct way to translate the ng-admin keys?
I can not seem to get a handle on the translateProvider that is used by ng-admin, adding our own like described above doesn't use the keys.

**Comment by Kmaschta** [comment]
Hi,

Sorry we didn't communicate a lot about this, but we don't support Bower anymore.
The version of ng-admin on bower might be outdated.

Have you tried to install the 1.0 version with `npm` or `yarn`?

**Comment by Kmaschta** [comment]
No response from a while, I close this one.

Feel free to open it again if needed!

**Comment by 7hibault** [comment]
Hi,
I've got the same issue with npm. I have

- installed angular-translate ^2.15.1
`npm install angular-translate --save`

- added it to index.html
`<script src="node_modules/angular-translate/dist/angular-translate.min.js" type="text/javascript"></script>`

- included component in module definition:
`var app = angular.module( 'adminApp', [ 'ng-admin', 'pascalprecht.translate' ] );`

- copied exactly the config in https://ng-admin-book.marmelab.com/doc/Translation.html

As @blocknotes, a translation in index.html will be displayed with ` <p>test... {{ 'EXPORT' | translate }}</p>` but none of the ng-admin components are translated.

What am I missing?

**Comment by Kmaschta** [comment]
This issue is quite old.
In order to help you, can you open a new one and provide a Plunkr?
(all is explained in the issue template).

Feel free to check StackOverflow with the tag `ng-admin` too.

**Comment by 7hibault** [comment]
I actually can't get it to not work in Plunkr, so I suppose I have a version issue. Thanks @Kmaschta, I'll dig into it a bit more before opening a new issue
