### ISSUE TITLE
Row height animation upon triggering action

### ISSUE THREAD

**Issue by ajarbol** [marmelab/ng-admin#1107]
As seen in http://marmelab.com/ng-admin-demo/#/reviews/list when the reviews are `accepted` or `rejected` all rows are set to a greater height and animate back to the initial value. 
This gives a very confusing user experience.

**Comment by jpetitcolas** [comment]
Can you open the issue on [ng-admin-demo](https://github.com/marmelab/ng-admin-demo) instead? That's not related to ng-admin directly in my opinion. :)

**Comment by ajarbol** [comment]
Well it occurs in my (current) build of ng-admin and is not isolated to the ng-admin-demo. However I'll move this issue if you think it's best.
