### ISSUE TITLE
Chart in Dashboard

### ISSUE THREAD

**Issue by hoangtrongphuc** [marmelab/ng-admin#1113]
Any example for chart in Dashboard ?

**Comment by sam2x** [comment]
I integrated chart.js, with the help of the main dashboard page of demo (using 'resolve' to populate my charts information) : https://github.com/marmelab/ng-admin-demo

**Comment by fzaninotto** [comment]
ng-admin doesn't get in the way, create a custom directive with plain Angular.js, and use that directive as a field template.
