### ISSUE TITLE
Back& File Upload Support - JSON

### ISSUE THREAD

**Issue by tutchmedia** [marmelab/ng-admin#1115]
I'm currently trying to get the file upload working but hitting a problem in that the form is upoading the payload with multipart form data instead of a JSON object.

Back& will only accept a JSON object with filename and filedata inside but i can't figure out how to accomplish this with ng-admin.

My code currently looks like this:

`.uploadInformation(
              {
                'url': BackandProvider.getApiUrl()+'/1/objects/action/games', 
                'params': {'name':'files'}, 
                'headers': { 'Content-Type': false }, 
                'data': data
              })`

**Comment by Barnum7** [comment]
Have you made any progress on this issue? I've been seeing the same behaviour

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

Thanks for using ng-admin!
