### ISSUE TITLE
Saving Returned Uploaded URL into DB

### ISSUE THREAD

**Issue by tutchmedia** [marmelab/ng-admin#1119]
Hi guys, 

I've managed to upload images from ng-admin into my backend storage and can receive the returned URL. I'm then not able to save that into the DB. 

Does anyone have any idea how this can be done? How can I update the model? 

Thanks

**Comment by Phocea** [comment]
Are you still facing the issue?
Can you provide a plunkr example?

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

Thanks for using ng-admin!
