### ISSUE TITLE
Customize listview in ng-admin

### ISSUE THREAD

**Issue by wujunbin** [marmelab/ng-admin#1120]
I would like to customize listview in ng-admin, and then I found the [doc](https://github.com/marmelab/ng-admin/blob/master/doc/Theming.md#customizing-the-view-template-for-a-given-entity) that describes the way to customize listview. But in the doc, there is not any tip or information about how to get data in the template of listview modified by myself. Finally, I have to use an ugly method to get data in the template of listview that showed below.
![image](https://cloud.githubusercontent.com/assets/11531884/15990984/e43ed6b2-30d6-11e6-866c-2c354fc8beb1.png)
Is there any better way to get data?
Thx.

**Comment by hobywhan** [comment]
You can use entry.values.yourFieldName : (example of a template() for field) updating entry.values will update the data and if you submit the form, the data will be saved. You can use ::entry which is a copy of the entry given (I think). This can be use in list template() but it would be better to do it case by case (field by field), or modify all the template starting from the default html given in the source.
```
<div id="row-AttachedFiles" class="col-sm-12 form-field form-group has-feedback">
    <table class="grid table table-condensed table-hover table-striped" ng-if="entry.values.attachedFiles.length > 0">
        <thead>
            <tr>
                <th>{{ 'Name' | translate }}</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="attachedFile in entry.values.attachedFiles">
                <td><span>{{ attachedFile | translate }}</span></td>
            </tr>
        </tbody>
    </table>
    <label class="control-label" ng-if="entry.values.attachedFiles.length == 0">{{ 'Empty' | translate }}</label>
</div>
```

**Comment by wujunbin** [comment]
I cannot get data by ::entry and entry.values.
transportWay.listView().template(transportWayListTemplate)
I replaced the default template of listview by transportWayListTemplate.
In the transportWayListTemplate, I cannot load data from entry.values.
![image](https://cloud.githubusercontent.com/assets/11531884/16259140/d47c1dba-3893-11e6-8d30-af9d45b70e84.png)

**Comment by Phocea** [comment]
Did @hobywhan answer helped you out.
Starting from the existing listview default template may help

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

Thanks for using ng-admin!
