### ISSUE TITLE
Lazy loading admin/starting on callback.

### ISSUE THREAD

**Issue by krazik** [marmelab/ng-admin#1122]
```html
<!doctype html>
<html lang="en">
  <head>
    <title>My First Admin</title>
    <link rel="stylesheet" href="node_modules/ng-admin/build/ng-admin.min.css">
  </head>
  <body ng-app="myApp">
    <div ui-view></div>
    <script src="node_modules/ng-admin/build/ng-admin.min.js"></script>
    <script type="text/javascript">
    Api.callSomething(function(error) {
        var myApp = angular.module('myApp', ['ng-admin']);
        myApp.config(['NgAdminConfigurationProvider', function(NgAdminConfigurationProvider) {
            var nga = NgAdminConfigurationProvider;

            var admin = nga.application('My First Admin');
            nga.configure(admin);
        }]);
    });
    </script>
  </body>
</html>
```

I get error in console and app never starts.  If I init app outside of call back everything starts fine. But I'd like to control the admin configuration based on the result of the api call.

Error:  `angular.js:63 Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to:
Error: [$injector:nomod] Module 'myApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.`

**Comment by krazik** [comment]
anyone have any idea how to do this?

**Comment by Phocea** [comment]
Not sure what you are trying to achieve, but would using deferred boostrap achieve what you want to do.
See https://github.com/marmelab/ng-admin/issues/1029#issuecomment-209285741

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

Thanks for using ng-admin!
