### ISSUE TITLE
Webpack UglifyJSPlugin infinite loop when `require('ng-admin');`

### ISSUE THREAD

**Issue by krazik** [marmelab/ng-admin#1123]
I have a webpack build that publishes to S3.  If I include ng-admin in my index.html everything works fine.  if I try to require it view webpack it also works ok, until I try to run UglifyJS on it in preparation for prod build.  At that point webpack locks up in an infinite loop and I have to kill -9 the build.

**Comment by jpetitcolas** [comment]
Can you try with last version of ng-admin? We optimized it for module bundlers, and just including a:

``` require('ng-admin'); ```

should solve your issue.

**Comment by Phocea** [comment]
No update on this, closing for now.
Feel free to reopen if you are still facing the issue
