### ISSUE TITLE
2 referenced lists affecting each other

### ISSUE THREAD

**Issue by mohamed5678** [marmelab/ng-admin#1124]
Hi, in the edition/show view of my entity I have 2 refertenced lists:

```
nga.field('Photos', 'referenced_list')
.targetEntity(mediaEtablissement)
.targetReferenceField('id_etablisement')
.targetFields([
    nga.field('id').label('ID'),
    nga.field('src').label('Image').template("<img src='http://placehold.it/100x60'></img>")
])
.permanentFilters({
    type: 'image'
}),

nga.field('Vidéos', 'referenced_list')
.targetEntity(mediaEtablissement)
.targetReferenceField('id_etablisement')
.targetFields([
    nga.field('id').label('ID'),
    nga.field('src').label('Vidéo').template("<img src='http://placehold.it/100x60'></img>")
])
.permanentFilters({
    type: 'video'
})
```

As you see I want to separate the media types (video and photo)
When loading the page, the 2 lists have same results,
I made sure the filtering is working correctly in the API side.

How can I solve this?

**Comment by mohamed5678** [comment]
@fzaninotto

**Comment by perryh** [comment]
Is this related to https://github.com/marmelab/ng-admin/issues/765?

I'm facing a similar issue with duplicate data. I have 3 fields with the same name but referencing different targetFields from the same targetEntity.

```javascript
        nga.field('vehicleId', 'reference')
          .targetEntity(entities._entities.vehicles)
          .targetField(nga.field('make.name'))
          .label('Make'),
        nga.field('vehicleId', 'reference')
          .targetEntity(entities._entities.vehicles)
          .targetField(nga.field('model.name'))
          .label('Model'),
        nga.field('vehicleid', 'reference')
          .targetEntity(entities._entities.vehicles)
          .targetField(nga.field('style.trim'))
          .label('Trim')
```

**Comment by Phocea** [comment]
@mohamed5678 what are the generated url that are called when accessing each of your fields?
Can you write a plunkr to demonstrate this?

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

Thanks for using ng-admin!
