### ISSUE TITLE
How to avoid sending synthesised field to server on create?

### ISSUE THREAD

**Issue by daurnimator** [marmelab/ng-admin#1126]
I'm using http://ng-admin-book.marmelab.com/doc/FAQ.html#how-can-i-map-twice-the-same-field-in-a-list

However this extra field gets sent to the server on edit/create.
The server doesn't recognize the unknown key, and hence rejects the request.

How can I avoid sending the field?
Is there a different/better solution to the one in the FAQ?

**Comment by cfatt10** [comment]
In order to handle this, you can write a Restangular request interceptor that catches and deletes the unnecessary field.

**Comment by daurnimator** [comment]
> In order to handle this, you can write a Restangular request interceptor that catches and deletes the unnecessary field.

AFAIK, you can't modify a request body in a Restangular request interceptor.

**Comment by cfatt10** [comment]
I am using this addElementTransformer in by codebase:
`RestangularProvider.addElementTransformer('causes', function (element) {
            var baseUrl = AG.widgetBaseUrl;
            element.widgetUrl = baseUrl + "donate/" + element.slug;

            element.fullName = element.name  + renderExtraInfoForCauseOrCampaign(element);

            return element;
        });`

And this addFullRequestInterceptor removes the fields:
`RestangularProvider.addFullRequestInterceptor(function(element, operation, what, url, headers, params, httpConfig) {
            if (operation == 'put' && what == 'causes') {
                delete element.widgetUrl;
                delete element.fullName;
            }
            return { params: params };
});`

**Comment by Phocea** [comment]
Solution was provided. Closing.
If you still face the issue feel free to reopen
