### ISSUE TITLE
"400" error is ignored when deleting or bulk deleting items

### ISSUE THREAD

**Issue by RichardBradley** [marmelab/ng-admin#1129]
On the current version, if the REST backend rejects a "DELETE" request from `ng-admin` no error is displayed to the user.

There is code which appears to attempt to show an error, so I think this is a regression.
I don't see any tests (unit or e2e) for this functionality.

Repro steps:

```
Given an entity where the REST backend will return 400 "cannot delete due to xyz" for a "DELETE" request
When I view the "edit" page for that entity
And I click the "delete" button
And I click "Yes" to "are you sure?"
Then I should see an error banner including "cannot delete due to xyz"
 # but I see a success banner

Given an entity where the REST backend will return 400 "cannot delete due to xyz" for a "DELETE" request
When I view the "list" page for that entity tytpe
And I select that entity
And I click the "delete" button
And I click "Yes" to "are you sure?"
Then I should see an error banner including "cannot delete due to xyz"
 # but I see a success banner
```

**Comment by RichardBradley** [comment]
There are three bugs at play here, I think:
 1. The code uses "|" where it should use "||" [in a few places](https://github.com/marmelab/ng-admin/blob/c9dc3efdba38f8953535f2b6da715693f97c19c1/src/javascripts/ng-admin/Crud/delete/DeleteController.js#L46)
 2. The code uses angular-translate wrong if a custom error message is used as the translate key, due to https://github.com/angular-translate/angular-translate/issues/1516
 3. The "batch" delete does not attempt to check the individual success / failure results, but only checks whether the batch request succeeded. So even if there is only 1 item in the batch, it will look like a success to ng-admin

**Comment by Phocea** [comment]
#1059 
#1036

**Comment by Phocea** [comment]
#1059 #1036

**Comment by RichardBradley** [comment]
Thanks, yes, looks like a duplicate of those two. I've commented there.

**Comment by jpetitcolas** [comment]
Closing as duplicate.
