### ISSUE TITLE
ma-wysiwyg-field 

### ISSUE THREAD

**Issue by beatelite** [marmelab/ng-admin#1135]
First off, I love you. You're helping me in incredible ways. Not sure if you hear it enough but there you go!

Second, my api has this weird thing where there's a rendered version of the content which is a different endpoint than updating the content. For example:

**What I need to use to render the content:**
`<ma-wysiwyg-field field="::field" value="entry.values.content.rendered"></ma-wysiwyg-field>`

**What I need to use to update content:**
`<ma-wysiwyg-field field="::field" value="entry.values.content"></ma-wysiwyg-field>`

Is there any extra features on the wysiwig directive to work around this? Also, the <ma-input-field> directive as well as I often need it for that as well. 

I need to show the rendered content but update to just content. Super weird, I know.

**Comment by fzaninotto** [comment]
Did you already work through using `template()`, `map()` and `transform()`?

**Comment by beatelite** [comment]
Hi, it's been a bit since I posted this as I was working on something else for a bit. Getting back to this now but was wondering if you can point me to any examples of template(), map() and transform() ?
I haven't dug into the code in a bit so don't recall using them and I didn't see any in the demos.

**Comment by beatelite** [comment]
They updated the api so I can post using content.raw. closing this.
