### ISSUE TITLE
List view with permanent filter redirects to other view

### ISSUE THREAD

**Issue by sm-g** [marmelab/ng-admin#1136]
I created three menu items with urls:
- #/region/list
- #/region/list?search={"is_subway":"false"}
- #/region/list?search={"is_subway":"true"}

I want to be able to switch between last to views, but can't:
1. open url with some filter.
2. open other url with filter.
3. ng-admin redirects to `/list` view.

**Comment by Phocea** [comment]
There is a working case on the ng-admin-demo which is working properly. You may want to check it out:

http://marmelab.com/ng-admin-demo/#/commands/list?search=%7B%22status%22:%22ordered%22%7D
http://marmelab.com/ng-admin-demo/#/commands/list?search=%7B%22status%22:%22delivered%22%7D

The menu configuration for this: https://github.com/marmelab/ng-admin-demo/blob/master/js/menu.js

Closing for now, reopen if you think it necessary
