### ISSUE TITLE
angular translate function in nga.filed().label() in listview.filters() is nor working.

### ISSUE THREAD

**Issue by wujunbin** [marmelab/ng-admin#1137]
Hi,
I found that the code ,`listView().filters([nga.field('sn').label('{{"order.sn" | translate}}')])`, cannot work properly. 
![image](https://cloud.githubusercontent.com/assets/11531884/16259409/1f9e0758-3895-11e6-9dc3-8681d611f1d1.png)

In the listview.fields([nga.field('sn').label('{{"order.sn" | translate}}')]), it works well.
How can i fix the issue.

**Comment by hobywhan** [comment]
try doing : nga.field('sn').label($translate.instant('order.sn'));

**Comment by wujunbin** [comment]
I can obtain $tranlate service in Controller.
 How can i get $translate service from nga?  
thx

**Comment by hobywhan** [comment]
I don't know how your system works, but what I do is : getting the $translate in the run and create my entities and fields of entities with the variables I need.
```
  .run(function($rootScope, $translate, RightsService, Config) {
    'ngInject';
    loadEntities(nga, appInstance, $translate, modules, RightsService, Config);
```

**Comment by wujunbin** [comment]
I follow the official website. 
In ng-admin and angularjs, I am a newcomer.
I don't know what is ".run" that i cannot find in ng-admin website.
The img below is my style to load entities and configure listview, showview, creationview, etc.
![image](https://cloud.githubusercontent.com/assets/11531884/16262847/ffae3d5a-38a3-11e6-82f2-d9650b30861d.png)

Really thx, I was troubled by the issue the whole day.

**Comment by SebLours** [comment]
Label translation is provided by default for labels !
As you can see here:
https://github.com/marmelab/ng-admin/blob/master/src/javascripts/ng-admin/Crud/filter/maFilterForm.js#L23

You just have to set your translation key as label.
```js
nga.field('sn').label('MY_TRANS_KEY');
```
Add your translations configuring `translate`
https://github.com/angular-translate/angular-translate

**Comment by wujunbin** [comment]
Label translation is only taking effect in the fileds(), but not working in the filters().

**Comment by wujunbin** [comment]
@hobywhan   Very very very  thx you. 
Finally, I use your method to fix the problem.
```
myApp.run(function ($translate) {
    orderConfig(mNga, mAdmin, $translate);
});
```

**Comment by aakashbathla** [comment]
@wujunbin 

where you defined orderConfig method, will you please share a screenshot of your code?

**Comment by aakashbathla** [comment]
@wujunbin 

my issue got resolved, actually i was using the older version of ng-admin
