### ISSUE TITLE
Multi Views (States in NG-ADMIN)

### ISSUE THREAD

**Issue by giovanni-duarte** [marmelab/ng-admin#1138]
Hello friends, I am working on an advanced design using the NG- ADMIN .

I need to know how to make my Entities (**addEntity**) open in separate Views (**ui-view**), not interfering with each other .

I need to open more than one display at the same time and mater your data. **Like This:** [ui-router-extras](http://plnkr.co/edit/bFMLqLENmPFfCD0XCz8V?p=preview)

**NG- ADMIN** has helped a lot in the project, would like to keep using it.

![exemplo](https://cloud.githubusercontent.com/assets/2203976/16317984/602f2a76-3963-11e6-8ad4-8abe8c573c80.JPG)

**Comment by fzaninotto** [comment]
mmhh I don't think it's possible with the current architecture. Take a look at #759 and see if it helps.
