### ISSUE TITLE
Set controller scope value from prepare()

### ISSUE THREAD

**Issue by sm-g** [marmelab/ng-admin#1139]
I need to show [photo gallery](https://github.com/compact/angular-bootstrap-lightbox) in edit view.
In main.js I add:
```
angular.module('myApp').controller('GalleryCtrl', ['$scope', 'Lightbox', function ($scope, Lightbox) {
			//$scope.images = images
			$scope.openLightboxModal = function (index) {
			  Lightbox.openModal($scope.images, index);
			};
}])
```

 In edit view add field:

```
nga.field('', 'template')
      .template(`<ul ng-controller="GalleryCtrl">
  <li ng-repeat="image in images">
    <a ng-click="openLightboxModal($index)">
      <img ng-src="{{image.thumbUrl}}" class="img-thumbnail">
    </a>
  </li>
</ul>`)
```

and:
```
.prepare(['Restangular', 'entry', function (Restangular, entry) {
      return Restangular.all('photo?filter[where][offer_id]=' + entry.values.id)
        .getList()
        .then(photos => {
          if (photos && photos.data && photos.data.length)
            return photos.data.map(v => {
              return {
                'url': v.url,
                'caption': v.name
              }
            })
          else
            return []
        })
        .then(images => {		  
		 // TODO
}])
```

How to set images scope value from prepare promise? Or add field to view after all images got?

**Comment by hobywhan** [comment]
I think you can set entry.values.images = [] and update it, and add a field nga.field('images') which will be instantiated by this.

**Comment by sm-g** [comment]
Yes, this works, just pass images in params in `openLightboxModal` and not use `$scope.images`.

**Comment by winglight** [comment]
@sm-g I have a problem exactly like you did that's very weird: the ng-click can't be triggered even I tried to put an alert function in the ng-click. Here's my [issue](https://github.com/marmelab/ng-admin/issues/1211).
