### ISSUE TITLE
Reference field: map transforms value added to object

### ISSUE THREAD

**Issue by fedotxxl** [marmelab/ng-admin#1141]
Hello. I've got object `Company` which can have many `Tags`. I use `reference_many` to organize reference. To display tag title instead of id I use `map` function. In this case I can select tags and they are correctly displayed. But on saving ng-admin sends array with transformed tag translations instead of tag ids.

How to display transformed value on selection but save original field value (id) to object?

```
nga.field("tag_ids", "reference_many")
                .label("Tags")
                .targetEntity(nga.entity("tags"))
                .targetField(nga.field("id").map(_mapTagTranslation))
                .remoteComplete(true, {
                    refreshDelay: 300,
                    searchQuery: function(search) { return { q: search }; }
                })
                .sortField("id"),
```

**Comment by hobywhan** [comment]
For that purpose, I use : 
```
nga.field("tag_ids", "reference_many")
  .map(extractIdFromArray)
  .transform(injectIdIntoArray)
```
with functions : 
```
function extractIdFromArray(value) {
  return _.map(value, (value || {}).id);
}
function injectIdIntoArray(value) {
  return _.map(value, {id: value});
}
```

**Comment by fedotxxl** [comment]
@hobywhan can you provide full sample?

**Comment by fedotxxl** [comment]
The issue was "id" field:

`.targetField(nga.field("id").map(_mapTagTranslation))`

should be replaced by any other field

`.targetField(nga.field("ANY_FIELD_DIFFERENT_FROM_ID").map(_mapTagTranslation))`

this is very strange behaviour. Is it bug?

**Comment by Phocea** [comment]
looks like you solved your problem. Feel free to reopen if required
