### ISSUE TITLE
Prepare/onSubmitSuccess is not a function

### ISSUE THREAD

**Issue by paolodamico** [marmelab/ng-admin#1143]
Hi!

I'm trying to use the prepare function and the onSubmitSuccess callback however I keep getting an error in the console saying:

> Error: [$injector:modulerr] Failed to instantiate module adminApp due to:
> TypeError: node.editionView(...).prepare is not a function

My code:

```
node.editionView().fields(node.creationView()).prepare(['datastore', function(datastore) {
        console.log(datastore);
}]);
```

Could you help me solve this please?

Thanks!

**Comment by Kmaschta** [comment]
Potentially related to #1258

**Comment by pq771271668** [comment]
我现在需要新增一条信息验证通过之后点击提交就回到list视图，但是我现在点击提交只有信息保存成功提示，页面视图并没有返回到list视图，不知道这是什么原因，然后我用onSubmitSuccess结果显示onSubmitSuccess is not function 。

**Comment by pq771271668** [comment]
这里我的代码
user.creationView()
        .actions(['list'])
        .fields([
	        nga.field('name').label('姓名')
	            .validation({ required: true, minlength: 2, maxlength: 10 }),
	        nga.field('sex', 'choice').label('性别')
	            .attributes({ placeholder: '请选择' })
	            .choices([
			        { value: '男', label: '男' },
			        { value: '女', label: '女' },
			      ])
	            .validation({ required: false,}),
	        nga.field('tel').label('电话')
	            .validation({ required: false,pattern: '^1[0-9]{10}$'}),
	        nga.field('addr', 'text').label('地址')
	            .validation({ required: false,}), 
	        nga.field('dec','wysiwyg').label('描述')
	            .validation({ required: false,}),
	        nga.field('time','date').label('时间')
	            .validation({ required: false,})
        ])
        post.editionView().onSubmitSuccess(['progression', 'notification', '$state', 'entry', 'entity', function(progression, notification, $state, entry, entity) {

		  // stop the progress bar
		  progression.done();
		  // add a notification
		  notification.log(`Element #${entry._identifierValue} successfully edited.`, { addnCls: 'humane-flatty-success' });
		  // redirect to the list view
		  $state.go($state.get('list'), { entity: entity.name() });
		  // cancel the default action (redirect to the edition view)
		  return false;
		}])
        .title('新增用户信息');


谢谢！！

**Comment by pq771271668** [comment]
Hello! I need to add a message is verified by clicking the submit to the list view now, but now I only save the information and click the submit success tips page view and did not return to the list view, do not know what reason is this, then I use onSubmitSuccess onSubmitSuccess is not function results show. Thanks

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

Thanks for using ng-admin!
