### ISSUE TITLE
[Bug] Reference fields do not work inside Embedded List

### ISSUE THREAD

**Issue by dowlingw** [marmelab/ng-admin#1145]
ng-admin version: 0.9.1

Using `reference` fields inside an `embedded_list` does not appear to work correctly.

Reading the guide, it's not clear whether this is supported behaviour:

> Ng-admin renders `embedded_list` fields as a datagrid in read context (`showView`), and as a list of embedded forms in write context (`creationView` and `editionView`). This won't issue any additional query to the REST API, since the related entities are already embedded.

And in practice this seems to be inconsistently implemented:

1. `showView` does not perform any retrievals of `reference` objects for rendering
2. `creationView` and `editionView` both load listings and perform remote completion as expected
3. `editionView` does not retrieve the `reference` object for rendering. However if the object is returned in the listing of objects used to render the dropdown, this *does* work as expected.
4. If this is not supported configuration, then there are no errors thrown from the `nga` object when providing an invalid configuration.

I'm hoping the intent is for this to work, as most of the functionality works already. In which case it looks like this might be a small bug rendering `reference` fields in the scope of an `embedded_list`.

If not, it would be good to clarify the documentation and possibly generate a warning or error from the configuration API in this situation.

**Comment by dowlingw** [comment]
This looks like it might be a duplicate or related to #817 or #956.
Sorry, I did have a look at the bug tracker - but didn't include closed bugs.

I'll have to see if this is fixed in the 1.0 alphas, though I've had other issues trying those out :(

**Comment by dowlingw** [comment]
Confirming this is still an issue in `1.0.0-alpha4`

**Comment by etdev** [comment]
There's also https://github.com/marmelab/ng-admin/issues/786.

I'd like to try and implement this if anyone can offer a high-level explanation of how to do so (i.e. what files need to be updated etc.)

**Comment by dowlingw** [comment]
Yes, this looks like a duplicate of #786 
Closing and adding notes there.
