### ISSUE TITLE
entryCssClasses is not a function

### ISSUE THREAD

**Issue by quangle** [marmelab/ng-admin#1148]
```
houses.listView()
      .entryCssClasses(function(entry) {
          return (entry.views > 300) ? 'is-popular' : '';
      })
```

I am trying to get `entryCssClasses` to work with the `listView()`. But the console shows: `TypeError: houses.listView(...).entryCssClasses is not a function`. Is there anything wrong with the way I am using `entryCssClasses`? I am currently using the code from the master branch.

**Comment by remborg** [comment]
I'm having the same issue, using it the same way as you are.

**Comment by quangle** [comment]
I am resorting to adding classes to the field as an alternative:
```
nga.field('_id')
  .cssClasses(function(entry) {
    ...
  }),
```
Probably a current bug with the `master` branch.

**Comment by Phocea** [comment]
I am not seeing this issue using the latest master branch. @quangle can you check if this is still happening?

**Comment by fzaninotto** [comment]
No feedback from some time, closing.
