### ISSUE TITLE
Refresh RefrencedList

### ISSUE THREAD

**Issue by Manel17** [marmelab/ng-admin#1152]
Hello,
I need to refresh a referencedList once it gets updated from the server side.
I thaught about using setInterval, but I couldn't figure out where in ng-admin the api gets called to load the referencedList data, so I could put my code there.
Does any of you know how to solve this problem?
Thank you.

@fzaninotto

**Comment by fzaninotto** [comment]
Don't use a `referenced_list` in that case: the data fetching logic is deeply linked to the router. If you need to reload at will, you'll have to write a custom directive.
