### ISSUE TITLE
Is it possible to have several list views for an entity?

### ISSUE THREAD

**Issue by aaxx** [marmelab/ng-admin#1153]
Searched issues, but have not found anything on this topic. 

I would like to have several list views for an entity, let's say, for User: 
- default
- leads
- individuals
- business

It's all the same business entity User, but with different settings inside each view - different columns, actions etc. Let's assume that editing shall be the same for this case. Each view shall use different API endpoint (/User/{leads|individual|business}) and shall be referenced separately throughout application (menu etc).

Is it possible to achieve that setting with ng-admin, and how?

**Comment by SebLours** [comment]
The easiest way is to create an entity per profile !
Each one will be configurable like you want it.

**Comment by aaxx** [comment]
Thanks, it could solve the problem indeed. Let's say there will be User, UserLeads, UserIndividuals, UserBusiness entities. How to use User's update/read/create views for UserIndividuals, UserBusiness etc entities? Otherwise it gonna be a huge bloatware :)

**Comment by SebLours** [comment]
You can define your `User` view fields and use them in other views.

```js
var user =  admin.getEntity('users');
var userLead =  admin.getEntity('user_leads');

userLead.editionView().fields(user.editionView().fields());
```
Other view configuration can be specific.

**Comment by aaxx** [comment]
Fantastic, thanks a lot!

**Comment by nschirmer** [comment]
Also, since this wasn't already mentioned, you can make all of those extra user entities use the same API endpoint by using the `url` method found here: https://github.com/marmelab/ng-admin/blob/master/doc/reference/Entity.md

This way you can have them all use /users/ part of your backend API, and then just pass some other identifier for whether it's leads or something else.
