### ISSUE TITLE
Bug - button export csv sort auto by id DESC

### ISSUE THREAD

**Issue by hobywhan** [marmelab/ng-admin#1154]
Hello, 
I didn't see that before but I get an error while pushing the button for export in csv my data, because it is sorted by id in DESC, which is not the identifier I chose, nor in my entity identifier, nor in my listView sortField and sortDir. I don't know how to resolve this.
Thanks

**Comment by fzaninotto** [comment]
use the `.sortField()` and `.sortDir()` methods to choose the sorting field.
