### ISSUE TITLE
reference field isn't displayed

### ISSUE THREAD

**Issue by geof62** [marmelab/ng-admin#1156]
> Hello,

I've a field which is a reference in a showView

```js
        nga.field('user', 'reference')
            .label('Email')
            .targetEntity(user_m)
            .targetField(nga.field('email').map(function(value, entry){
                console.log(entry);
                return ('ok');
            })),
```

The label "Email" is correctly displayed, but not the value ?
In my console, the result of console.log(entry) is good.

Do you know what is the problem ?

Have a good day.

**Comment by jpetitcolas** [comment]
Which value is displayed? Have you any other errors? What does your API return?

**Comment by fzaninotto** [comment]
No feedback for some time, closing. Feel free to reopen if you have more details.
