### ISSUE TITLE
enhancement: Add issue template and contributing guidelines

### ISSUE THREAD

**Issue by RichardBradley** [marmelab/ng-admin#1157]
Might I suggest adding a "new issue" template to help users raise new issues better?

When raising a new issue it would be really handy to have a link to a http://plnkr.co/ page with the ng-admin example app pre-loaded so I can fork it to demo the bug.

GitHub's docs on how to do this:
 * https://help.github.com/articles/creating-an-issue-template-for-your-repository/
 * https://help.github.com/articles/setting-guidelines-for-repository-contributors/

An example from another project: https://github.com/atom/atom/issues/new

I'll see if I can create a PR for this

**Comment by RichardBradley** [comment]
Do you have a link to a nice basic ng-admin demo in plnkr?

**Comment by fzaninotto** [comment]
Fixed by #1159
