### ISSUE TITLE
filefield template to show image thumbnail

### ISSUE THREAD

**Issue by genxstylez** [marmelab/ng-admin#1160]
Hi, I would like to modify the file field template to show the uploaded image thumbnail in editionView and preview thumbnail in creationView, any guides or examples?

Thanks

**Comment by PolCPP** [comment]
Check the demo source. https://github.com/marmelab/ng-admin-demo

You should be looking at js/products/zoomInModal.js and js/products/config.js

**Comment by genxstylez** [comment]
How do I integrate that with existing file field? I need a browse button to select the file

**Comment by PolCPP** [comment]
I just added another field for it. Because i was lazy.

The clean way would be to create a copy of FileField, call it ImageField for example and just replace the angular templates

**Comment by genxstylez** [comment]
oh ok, can you show me an example? kinda new to angular. not sure how to add my custom field

**Comment by gartner** [comment]
Did you solve the problem, since you closed this issue?
If you solved it, how?
