### ISSUE TITLE
EditionView doesn't redirect anywhere if loaded directly.

### ISSUE THREAD

**Issue by PolCPP** [marmelab/ng-admin#1161]
I stumbled onto this accidentally.

Basically, instead of opening the main uri then navigate to items and edit one of those, i load myapp/admin/#/items/edit/2 directly save, and it stays on the same view.

Is it by design by any case?

**Comment by fzaninotto** [comment]
It's by design. We use `back()` if you have history (to be able to return either to the list, or to another edition view if that's where you come from), and refresh otherwise.
