### ISSUE TITLE
Bug - export data

### ISSUE THREAD

**Issue by justquanyin** [marmelab/ng-admin#1162]
When reference field is same , but this value is diffrent , this export data's fields will wrong .
example : 
`nga.field('broker', 'reference').targetEntity(adminUser).targetField(nga.field('name'))`
`nga.field('broker', 'reference').targetEntity(adminUser).targetField(nga.field('age'))`

that export file will own two `age` field.

**Comment by fzaninotto** [comment]
ng-admin doesn't support that. Use an interceptor to duplicate the `broker` field, as explained in https://ng-admin-book.marmelab.com/doc/API-mapping.html
