### ISSUE TITLE
editionview save changes problem

### ISSUE THREAD

**Issue by pfdx44** [marmelab/ng-admin#1165]
If  you have ma-create-button in your editionview 

after click it 

if you click to "Save Changes" button and

if it is success it goes to ma-create-button page (previous state). 

Actually I want to stay in same page. 

But how?

Any help would be appreciated.

Thank you.

**Comment by MLauri** [comment]
Hello,
you can use the onsubmitsuccess hook.
You can find more details in the doc.

Il 27 lug 2016 6:00 PM, "pfdx44" <notifications@github.com> ha scritto:

**Comment by pfdx44** [comment]
Thank you.

It worked.
