### ISSUE TITLE
.onSubmitSuccess not work on editionView

### ISSUE THREAD

**Issue by Taharbenmedjbour** [marmelab/ng-admin#1166]
Hi,

I want to override the default behavior after editing an entity, ng-admin redirects to the previous page (list view) instead of staying on the edition view.
 to reverse this behavior, I added .onSubmitSuccess() on EditionView and it works.
like 
.onSubmitSuccess(['progression', function(progression) {
   // stop the progress bar
   progression.done();
   // enable the default redirect to the list view
   return false;
}])
**But,** when I use the same on creationView() the behavior is not changed, it redirect me to /list after the creation.

Is there anything to modify/add to fix it ?

Thanks

**Comment by SebLours** [comment]
You need to reload the current state if you want to your changes (new API call).
Inject `$state` in your `onSubmitSuccess` callbak.

```js
$state.reload();
```

**Comment by fzaninotto** [comment]
Did you test with the master build?

**Comment by Taharbenmedjbour** [comment]
Hi,
what do you mean by the master build?
I tested it with on all environnement of ded, local, dev.....prod, and the hock is only work on editionView not on creation.

**Comment by jpetitcolas** [comment]
@Taharbenmedjbour, he meant using `marmelab/ng-admin` as a dependency in your `package.json`.

**Comment by Taharbenmedjbour** [comment]
Thank's

**Comment by Taharbenmedjbour** [comment]
Thanks

**Comment by fzaninotto** [comment]
No feedback on this one, closing. Feel free to reopen if you can reproduce.
