### ISSUE TITLE
Is this project still active

### ISSUE THREAD

**Issue by avifatal** [marmelab/ng-admin#1169]
Hi,
I want to use it in another big project of mine and I want to know if its still under active development and support.
Amazing product!
Thanks

**Comment by theyoux** [comment]
Hi there,
I do hope so too :)
@fzaninotto could you provide some status about the plans for ng-admin?

**Comment by zhaown** [comment]
+1 Hope so too

**Comment by fzaninotto** [comment]
It is active. But mid-July to mid-August is traditionally a calm period 😄

**Comment by avifatal** [comment]
Thanks! 
We love this project!
