### ISSUE TITLE
ReferenceError: notification is not defined

### ISSUE THREAD

**Issue by fakharkhan** [marmelab/ng-admin#1171]
When use validation i see the following error:
<img width="404" alt="screen shot 2016-08-02 at 7 41 56 pm" src="https://cloud.githubusercontent.com/assets/1877752/17393672/acb93e1c-5a3e-11e6-8545-ca8706bf9e51.png">

**Comment by fzaninotto** [comment]
Can you confirm that 8a56831fd19317b013ade93e98f5c648d8e1fc7c fixes the issue?

**Comment by Phocea** [comment]
Duplicate of https://github.com/marmelab/ng-admin/issues/1019
See my comment on 1019, javascript error does not occur anymore, but expected behavior on required field is not entirely correct.

Shall those report be closed and another specific one for the choice field opened?
