### ISSUE TITLE
show totalItems on listview

### ISSUE THREAD

**Issue by genxstylez** [marmelab/ng-admin#1174]
as titled, I am struggling with it, not too familiar with Angular, please help.

**Comment by fzaninotto** [comment]
It is shown in the pagination (bottom zone)

![image](https://cloud.githubusercontent.com/assets/99944/17561249/7e210ddc-5f25-11e6-8d5f-c5d83968ed1e.png)

**Comment by genxstylez** [comment]
@fzaninotto 
I am using infinite scrolling, can I show it in infinite scrolling mode?

**Comment by genxstylez** [comment]
@fzaninotto can you help?
