### ISSUE TITLE
NG-Admin How to get the value to template - Count1.count value i need for html tempate

### ISSUE THREAD

**Issue by rakylegend** [marmelab/ng-admin#1178]
```
.addCollection(nga.collection(count1)
                .name('name')
                .title('Renewal Request')
                .fields([
                    **nga.field('count')**                           
                ])                
             )
            .template(`            
    ```
<div class="row dashboard-starter"></div> 
    <div class="row">
        <div class="col-lg-3">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-user-plus fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-right">
                            <div class="huge ng-binding">{**_{ count1.count }_**}
                  </div>
                            <div>Registered Users</div>
                        </div>
                    </div>
                </div>
```

```

**Comment by beatelite** [comment]
I would check out this: https://github.com/marmelab/ng-admin-demo/blob/3a0944acbcb12dc20dc8a4a860c6c9f8da9c1645/js/customers/config.js#L14

**Comment by fzaninotto** [comment]
Or better: 

* query for the dashboard: https://github.com/marmelab/ng-admin-demo/blob/3a0944acbcb12dc20dc8a4a860c6c9f8da9c1645/js/dashboard/dashboardSummary.js
* Display in the dashboard: https://github.com/marmelab/ng-admin-demo/blob/3a0944acbcb12dc20dc8a4a860c6c9f8da9c1645/js/dashboard/dashboardSummary.html
