### ISSUE TITLE
I am using fakerest fake data in ng-admin now i want to use my mysql db in ng-admin how do i use plz help me.

### ISSUE THREAD

**Issue by TechieJacobs** [marmelab/ng-admin#1182]
I am using fakerest fake data in ng-admin now i want to use my mysql db in ng-admin how do i use plz help me.

**Comment by SebLours** [comment]
It's not a `ng-admin` issue ...
You need to create a Rest Api that's consuming your MySql db !

**Comment by TechieJacobs** [comment]
how do i do that. shall i make a php script and get the data and encode
that on json and den what should i do.

Thanks and Regards
*Manish Dewani*.
Software Engineer
Bioenable Technologies Pvt Ltd.
manish@wirelessintegrated.com
Ph.: 020-66813773

On Tue, Sep 6, 2016 at 2:25 PM, Sébastien Lourseau <notifications@github.com

**Comment by faresbh** [comment]
You can use node.js to make a server app delivering a REST endpoint easily using npm package mysql-to-rest.

**Comment by jpetitcolas** [comment]
This is indeed not a ng-admin issue. You need to write your own API either using Node, PHP or every other language you like.
