### ISSUE TITLE
Any intents to move to Datatables?

### ISSUE THREAD

**Issue by suricactus** [marmelab/ng-admin#1183]
Hello. Is there any reason ng-admin is not using [Datatables](https://datatables.net/) as table plugin for list views? Do you have any intents to move to datatables? The first thing I miss from Datatables is multicolumn sorting. There is much more: reordering, column freezing, inline editing etc.

**Comment by Phocea** [comment]
Check out https://github.com/marmelab/ng-admin/issues/1056 this may give you an idea.
But you will need to rewire all the features you are talking about to bind them with REST api calls

**Comment by fzaninotto** [comment]
There are about a gazillion grid plugins for angular. We don't plan to test them all. So no, thanks.
