### ISSUE TITLE
Adding a refresh button about the grid and grid editing

### ISSUE THREAD

**Issue by avifatal** [marmelab/ng-admin#1185]
Hi,
1. Is it possible to have a refresh button above the grid (including referenced list)?
You need to refresh the browser / sort  / navigate out and in to do that.
1. I want to put a date picker on the grid to edit a date the rows, is it possible?

Thanks

**Comment by fzaninotto** [comment]
You just need to create a custom button, based on a directive that calls `$state.go($state.current(), { reload: true})` or `$state.reload()` or something like that. Check the ng-router doc.

**Comment by ludoo0d0a** [comment]
In the doc, I missed the `customTemplate `method to insert directive tag in Listview template listLayout.html.

```
    //Add reload button
    admin.customTemplate(function(viewName) {
        if (viewName === 'ListView') {
            return listTemplate;
        }
    });
```

```
/**
 * Link to reload
 *
 * Usage:
 * <ma-reload-button entity="entity"></ma-reload-button>
 */
export default function maReloadButtonDirective($state) {
    return {
        restrict: 'E',
        scope: {
            
        },
        link: function (scope, element, attrs) {
            scope.send = function () {
                $state.reload();
            };
        },
        template:
` <a class="btn btn-default" ng-click="send()">
<span class="fa fa-refresh" aria-hidden="true"></span>&nbsp;<span class="hidden-xs">Reload</span>
</a>`
    };
}

maReloadButtonDirective.$inject = ['$state'];
```

Great !
Thanks !
