### ISSUE TITLE
Reference field to non-existing entity cannot be edited

### ISSUE THREAD

**Issue by gotthardp** [marmelab/ng-admin#1188]
First of all, thank you for this great piece of software.
### Prerequisites

I am using the `master` branch.

I have a table (`devices`) that contains a simple reference to (a primary key of) another table (`applications`).

``` javascript
    var devices = nga.entity('devices')
        .identifier(nga.field('deveui'));
    var applications = nga.entity('applications')
        .identifier(nga.field('name'));

    devices.editionView().fields([
        nga.field('app', 'reference')
            .targetEntity(applications)
            .targetField(nga.field('name'))
            .validation({ required: true }),
   ...
```
### Description

When I delete the `applications` entry that was referenced in some of the `devices` the ng-admin doesn't allow me to modify the affected devices and update the reference.
### Steps to Reproduce
1. Create an application A
2. Create a device D and reference the application A
3. Delete the application A and create application B
4. Now edit the device D and try to update the reference to (non-existing) A and change it to (existing) B

**Expected behavior:** In the Edit Device dialog I would expect to see a drop-down box listing valid references, select B and submit. The standard behaviour.

**Actual behavior:**
- If the referenced `application` does not exist, the drop-down list of references remains empty. According to the debugging console the ng-admin fails to GET the referenced A and says `no element found`. It GETs the valid references, but (probably due to the previous error) does not display them. Hence I cannot select a valid reference.
- When trying to submit the dialog nothing happens but no error is displayed. The debugging console says `Error: notification is not defined`. I even cannot enter the correct reference manually: nothing happens, no error shown.

**Comment by fzaninotto** [comment]
ng-admin assumes that you cascade deletes on the API side. Handling all cases where your data integrity isn't preserved is outside of the ng-admin scope.
