### ISSUE TITLE
View not rendering

### ISSUE THREAD

**Issue by Wtower** [marmelab/ng-admin#1201]
### Scope

The `ui-view` is not rendered in the latest 1.0.0-alpha6 release when following the example https://ng-admin-book.marmelab.com/doc/Getting-started.html

### Prerequisites

* `ng-admin@1.0.0-alpha6`
* Documentation: https://ng-admin-book.marmelab.com/doc/Getting-started.html
* No previous issue for this has been found

### Description

When implementing exactly the example in the above link, a blank page is shown. The same does not apply with alpha5.

**Expected behavior:** A view saying "All dependencies are set...."

**Actual behavior:** Blank page

**Comment by jpetitcolas** [comment]
Indeed, we introduced a BC break with named views. Updating the doc.

**Comment by Waog** [comment]
#1202 fixed the problem for me

**Comment by jpetitcolas** [comment]
To sum up, you should replace:

``` <div ui-view></div>```

by 

```<div ui-view="ng-admin">```
