### ISSUE TITLE
A link to a showView does not make the proper API request

### ISSUE THREAD

**Issue by Wtower** [marmelab/ng-admin#1203]
### Scope

When opening an entity from a `listView`, it is expected that the REST request is a `GET /entity/:id` according to the [documentation](https://ng-admin-book.marmelab.com/doc/Getting-started.html).

Instead, a `GET /entity/` request is made.

### Prerequisites

* `ng-admin@1.0.0-alpha5`
* `ng-admin@1.0.0-alpha6` cannot be tested because of #1201 
* [Documentation: Getting started](https://ng-admin-book.marmelab.com/doc/Getting-started.html)
* No previous issue for this has been found

### Description

The documentation mentions:

> Here are these views, and how they map to REST resources:

>     ...
>     showView      => GET    /users/:id

Therefore, it is expected that when trying to open a `showView`, the appropriate request will be made. This is not the case with `1.0.0-alpha4`

**Expected behavior:** An API request `GET /entity/:id`

**Actual behavior:** An API request `GET /entity/`

**Comment by jpetitcolas** [comment]
@Wtower: can you show us your related entity code?

**Comment by Wtower** [comment]
Unfortunately I haven't kept my experiments, I was using the ng-admin examples anyway.

**Comment by fzaninotto** [comment]
Impossible to diagnose without code. The show view works in our implementations, and in the demos. Feel free to reopen if you can show us a plunker (forked from http://plnkr.co/edit/xiRijR1CeETB2qoz8krp) with the bug.

**Comment by davidpenn** [comment]
I am also having this same problem, and is shown in the plunker linked above. When clicking on ['show'] for "John" the page is empty. The rest of the users render correctly.
