### ISSUE TITLE
Allow CSV export of template field

### ISSUE THREAD

**Issue by Kmaschta** [marmelab/ng-admin#1206]
### Description

Currently, an export of a template field will include the HTML template in the CSV file instead of the real value.

### Steps to Reproduce

Configure an admin as following:
```js
entity.listView()
        .actions(['filter', 'export'])
        .fields([
            nga.field('id', 'number').format('0'),
            nga.field('active_tokens', 'template')
                .label('Active sessions')
                .template('<cl-sessions entry="entry" tokens="entry.values[field.name()]"></cl-sessions>'),
        ])
```

Click on Export button.

**Expected behavior:**

| ID | Active tokens |
|-----|-------------------|
| 1   | 3                    |
| 2   | 5                    |

**Actual behavior:**

| ID | Active tokens |
|-----|-------------------|
| 1   | `<cl-sessions entry="entry" tokens="entry.values[field.name()]"></cl-sessions>`  |
| 2   | `<cl-sessions entry="entry" tokens="entry.values[field.name()]"></cl-sessions>` |

**Comment by Phocea** [comment]
Dikd you follow the recommendation in the [doc](https://github.com/marmelab/ng-admin/blob/master/doc/reference/View.md)
This was fixed by https://github.com/marmelab/ng-admin/pull/949/

**Comment by Kmaschta** [comment]
If I write this:
```js
entity.listView()
        .actions(['filter', 'export'])
        .fields([
            nga.field('id', 'number').format('0'),
            nga.field('active_tokens', 'template')
                .label('Active sessions')
                .template(entry => `<cl-sessions entry="entry" tokens="${entry.values[field.name()]}"></cl-sessions>`),
        ])
```
How do I get the `field` variable ? And even, if I manage this field, the exported value will be:
`<cl-sessions entry="entry" tokens="5"></cl-sessions>`

I really need a different value for the export and for the template.

**Comment by jpetitcolas** [comment]
You are mixing up `listView` and `exportView`. You can export a templated field in `listView` and another string template in `exportView`.

**Comment by Phocea** [comment]
If I am not mistaken, there is an example in the blog app:

https://github.com/marmelab/ng-admin/blob/master/examples/blog/config.js

**Comment by Kmaschta** [comment]
It works like a charm, thank you!
