### ISSUE TITLE
I can't load a module in ng-admin

### ISSUE THREAD

**Issue by winglight** [marmelab/ng-admin#1211]
Here's init code:

```
var myApp = angular.module('myApp', ['ng-admin', 'bootstrapLightbox']);
```

Here's field config:

```
nga.field('images')
                .label('Images')
                .template(entry => '<a class="btn btn-default" ng-click="Lightbox.openModal('${ entry.values.images }');">Show Images</a>')
```

The view can be loaded and the button is clicked without any error, but no any response. I tried to set log into the function openModal that seems not to be visited. Any hint will be appreciated.

I tried to set alert in the ng-click that didn't work either. Is there any other config to add a button in the listview?

**Comment by winglight** [comment]
Here's the new status:
I found the only problem was ng-click not triggered in the template and onclick can be triggered but without ng context.
I have no idea why a normal ng-click can't work like in the other angularjs project?

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

Thanks for using ng-admin!
