### ISSUE TITLE
Allow Access controlle header not preset in post request 

### ISSUE THREAD

**Issue by animationatul** [marmelab/ng-admin#1212]
hi,

I had make api in Laravel with barryvdh Cors plugin implemented which add headers automativally

List view and single record view is working fine but 
Post Through this error but the api is working fine in PostMan

`
XMLHttpRequest cannot load http://127.0.0.1:8000/api/products/category. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:9000' is therefore not allowed access.
`

Put Through this error but the api is working fine in PostMan

`Error: Expecting an object parameter
    at i (ng-admin.min.js:7823)
    at Function.value (ng-admin.min.js:278)
    at t.value (ng-admin.min.js:485)
    at ng-admin.min.js:13617
    at l (ng-admin.min.js:18349)
    at ng-admin.min.js:18358
    at h.$eval (ng-admin.min.js:18703)
    at h.$digest (ng-admin.min.js:18658)
    at h.$apply (ng-admin.min.js:18729)
    at ng-admin.min.js:18549`

I am trying to solve this problem for more that 10 days now but not found any solutions

**Comment by animationatul** [comment]
I can be able to delete and update the record but post is again throwing same error

`XMLHttpRequest cannot load http://127.0.0.1:8000/api/products/category. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:9000' is therefore not allowed access.`

Any Help Plz !!!!

**Comment by jpetitcolas** [comment]
@animationatul: it seems your API doesn't allow `Access-Control-Allow-Origin`. That's more a Laravel issue than an ng-admin one.

I don't know Laravel, but after a [quick search](http://stackoverflow.com/questions/38749605/cors-access-control-allow-origin-on-laravel), try to add something like:

``` php
header('Access-Control-Allow-Origin: http://localhost:8080');
```

Or whatever cleaner Laravel method. :)
