### ISSUE TITLE
Reference list ui-select drop down not populated

### ISSUE THREAD

**Issue by Phocea** [marmelab/ng-admin#1213]
### Description

Reference list ui-select drop down not populated correctly on 1.0.0-alpha7

### Steps to Reproduce
With @jpetitcolas  help I got plunkr working and can validate this bug occurs since the Alpha 6 release

Code working on Alpha5: http://plnkr.co/edit/f9rIMxVwG1FVP54fgmKk

Code not working in Alpha 7: http://plnkr.co/edit/JkgrLFgvz7jP6Ee6w0m9

Culprit is this part of the code not rendering in the updated ui-select component:

```
nga.field('boss_id', 'reference')
       .label('Boss')
      .targetEntity(bosses)
      .targetField(nga.field('id')),
```

**Expected behavior:** 
The drop down list of Bosses ID is displayed when clicked on it, in the edit view of a User
The user 'Cathy' Boss ID (1) is displayed in the edit view of this user

**Actual behavior:** 
The drop down list of Bosses ID is not displayed when clicked on it, in the edit view of a User
The user 'Cathy' Boss ID is not displayed in the edit view of this user

**Comment by Phocea** [comment]
With @jpetitcolas  help I got plunkr working and can validate this bug occurs since the Alpha 6 release

**Expected behavior:** 
The drop down list of Bosses ID is displayed when clicked on it, in the edit view of a User
The user 'Cathy' Boss ID (1) is displayed in the edit view of this user

**Actual behavior:** 
The drop down list of Bosses ID is not displayed when clicked on it, in the edit view of a User
The user 'Cathy' Boss ID is not displayed in the edit view of this user

Code working on Alpha5: http://plnkr.co/edit/f9rIMxVwG1FVP54fgmKk
Code not working in Alpha 7: http://plnkr.co/edit/JkgrLFgvz7jP6Ee6w0m9

**Comment by jpetitcolas** [comment]
Ping @Kmaschta.

**Comment by Kmaschta** [comment]
I have noted that the Choice field works, even if it use `ui-select` too. It isn't a dependency fault.

I have added a field `grade` (Junior / Senior) to your example in order to illustrate this.
You can cleary see that with the alpha7 you can edit the grade but not the boss.

- Alpha5: [http://plnkr.co/edit/nYEq9i8DKLllBmJYHJlM?p=preview](http://plnkr.co/edit/nYEq9i8DKLllBmJYHJlM?p=preview)
- Alpha7: [http://plnkr.co/edit/VhzA2xIwetAuqtWlyf2J?p=preview](http://plnkr.co/edit/VhzA2xIwetAuqtWlyf2J?p=preview)

**Comment by Phocea** [comment]
Comparing the rendered HTML i also noticed a few difference. Not sure if it is relevant, but the main one is the input type.

- Alpha5: `<input type="text"`
- Alpha7: `input type="search"`

ng-hide condition is also different,

- Alpha5: `$select.open`
- Alpha7: `$select.open &amp;&amp; $select.searchEnabled"`

Could it have to do with any of those 2 commits since the referenceField use the choice directive:
https://github.com/marmelab/ng-admin/commit/09e9c2c63ded5f2ba89e2e3ed2947ebc60a92467#diff-de05d20a380cf0442219226d1c2446cf
https://github.com/marmelab/ng-admin/commit/4c186b48c6a6a8e56d8ce98c750fbdf3bcc43a01#diff-de05d20a380cf0442219226d1c2446cf

**Comment by Kmaschta** [comment]
I've found the issue and I'll make a PR tomorrow.
In simple words, the `scope.choices` is not refreshed all time.

Thank you for your investigation, much appreciated sir!

**Comment by jpetitcolas** [comment]
![image](https://cloud.githubusercontent.com/assets/688373/18922178/fe041564-85a7-11e6-9c32-5a78dc3da140.png)

**Comment by Phocea** [comment]
Super @Kmaschta !

**Comment by gotthardp** [comment]
Hello, I have the same issue with the current master. Are you sure this issue is fixed?

**Comment by Kmaschta** [comment]
Yes, I use it in production.
Be sure to install the version `1.0.0-beta1`.

**Comment by Kmaschta** [comment]
I'm sorry @gotthardp, you're right the build `1.0.0-beta1` is corrupted.
We've just published another one to fix the issue, you can install it with:

```bash
npm install ng-admin@1.0.0-beta2
```
