### ISSUE TITLE
Multiple Search/Filter Boxes

### ISSUE THREAD

**Issue by yrameshk26** [marmelab/ng-admin#1218]
Hi I was wondering if ng-admin is capable of producing multiple search bars. Each search bar for different purpose and also to serve such as ID greater than 100, Between 2000-3000 and User Names that doesn't contains "***" etc.

**Comment by fzaninotto** [comment]
Only if your API supports it. See for instance how it's done in Posters Galore : https://github.com/marmelab/ng-admin-demo/blob/744a553c1682e8fc12bc04a99d71a8b60deaf241/js/commands/config.js#L43-L46
