### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by samanmohamadi** [marmelab/ng-admin#1219]
Hi, After updating to latest version(beta1) admin panel doesn't show any thing and ng-view is empty.
No Error

**Comment by jpetitcolas** [comment]
Have you updated your layout according to the [UPGRADE file](https://github.com/marmelab/ng-admin/blob/master/UPGRADE-1.0.md)? 

```
<div ui-view="ng-admin">
<!-- instead of: <div ui-view> -->
```

**Comment by samanmohamadi** [comment]
Tanx @jpetitcolas .
