### ISSUE TITLE
How to choose multiple files in File Field

### ISSUE THREAD

**Issue by datafibers** [marmelab/ng-admin#1227]
nga.field('picture', 'file').uploadInformation({ 'url': 'your_url', 'apifilename': 'picture_name' })
How to choose and upload multiple files?
The example can only allow single file upload

**Comment by Orlo666** [comment]
Hi, i am using
```
nga.field('picture', 'file').uploadInformation({ 'url': 'your_url', 'apifilename': 'picture_name', 'multiple'=true })
```

**Comment by datafibers** [comment]
thanks

**Comment by sdben** [comment]
Hi, i've some trouble on uploading multiple files..
using `nga.field('picture', 'file').uploadInformation({ 'url': 'your_url', 'apifilename': 'picture_name', 'multiple'=true })`
it allows me to upload multiple files but I'cant get file keys on backend body.

this is my body class:

public class ImportGalleryImages
{
        public string[] FileName { get; set; }
}

thanks
