### ISSUE TITLE
How to limit the size of files uploaded in field with file type?

### ISSUE THREAD

**Issue by datafibers** [marmelab/ng-admin#1230]
```
nga.field('picture', 'file').uploadInformation({ 'url': 'your_url', 'apifilename': 'picture_name' })
```

How to limit the size of files uploaded in field with file type?

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

Thanks for using ng-admin!
