### ISSUE TITLE
One search box for multiple filters

### ISSUE THREAD

**Issue by sean-hill** [marmelab/ng-admin#1231]
One thing I dislike about `ng-admin` (right now anyways) is that I have to have a filter for each column. Is it possible to have one search box that searches across multiple columns? 

For example, say I have a list of users with names and emails. Instead of having two search boxes stacked, one for the name, one for the email. Is it possible to just have one search box, that searches both by name and by email?

**Comment by fzaninotto** [comment]
It's already possible, provided your REST API supports it. See for instance http://marmelab.com/ng-admin-demo/#/customers/list
