### ISSUE TITLE
Custom page Not Found

### ISSUE THREAD

**Issue by edupre** [marmelab/ng-admin#1233]
I would like to add a custom page as seen in the blog example.

Here is my code:

```
var myApp = angular.module('myApp', ['ng-admin'])

// ng-admin config
myApp.config(['NgAdminConfigurationProvider', function (nga) {
  var admin = nga.application('Test Admin');

  admin.menu(nga.menu().addChild(nga.menu().title('Billing').link('/billing')));

  nga.configure(admin);
}]);

// billing controller
myApp.controller('billingController', ['$scope', function($scope) {
  $scope.errorMessage = 'billing error';
}]);

// billing state
var tpl = '<div>BILLING</div><div>' +
  '<div ng-if="errorMessage != \'\'">Error: {{errorMessage}}</div>';

myApp.config(['$stateProvider', function($stateProvider) {
  $stateProvider
    .state('billing', {
      parent: 'ng-admin',
      url: '/billing',
      template: tpl,
      controller: 'billingController'
    });
}]);
```

If I click on "Billing" in the menu, I have this message: 

> Not Found 
> The page you are looking for cannot be found. Take a break before trying again.

If I comment `parent: 'ng-admin',`, my page is displayed but not included into `ng-admin`.

Do you have any idea of what I'm doing wrong?

Thanks.

**Comment by ajmalmsali** [comment]
I have a similar problem with the new version,

`    $stateProvider.state('login', {
        abstract: true,
        url: '/login',
        controller: loginController,
        controllerAs: 'controller',
        template: loginControllerTemplate
    });`

This was showing the login page without any parent, now it fails.

**Comment by fzaninotto** [comment]
What version of ng-admin are you using? The documentation references the latest beta, which changes the way we do that (see [Upgrade to 1.0](https://github.com/marmelab/ng-admin/blob/defaa6ca31afe24d7f2fab1530fe5e574c0cf6a9/UPGRADE-1.0.md))

**Comment by fzaninotto** [comment]
bump. Any feedback on this one?

**Comment by edupre** [comment]
My version: `"ng-admin": "^1.0.0-alpha2"`
Thanks to the upgrade note I fix my issue with: `parent: 'main',`
I think we can close it.

**Comment by Phocea** [comment]
Thanks for the feedback
