### ISSUE TITLE
Reference link field without additional API call

### ISSUE THREAD

**Issue by jamesjwarren** [marmelab/ng-admin#1237]
### Description

Creating a reference field always makes another API call to get the referenced entity. This call adds unnecessary overhead if we just want to create a link from the ID (stored in parent entity) to the referenced entity. This has significant impact using a `reference` field in a list view.
### Steps to Reproduce
1. In a list view, create a reference field with the target field `id` or whatever the field you already have in the parent entity is.
2. Navigate to the list view
3. Observe the unnecessary extra calls to the referenced entities 

**Expected behavior:**
Removing the targetField method should just use the id field already present in the parent entity, when displaying with link/read widgets, and thus no other API call be made.

**Actual behavior:** [What actually happened]
Extra call is unavoidable using the existing reference field type.

My initial naive thoughts are this could be achieved with an additional slightly altered version of the `reference` field type or even better with the existing `reference` field type when no `targetField` is specified.

**Comment by fzaninotto** [comment]
Why don't you use a simple `string` or `numeric` field, and override the template to include the hyperlink?

**Comment by jamesjwarren** [comment]
I was initially re-using the reference field from the create view in the list, but replacing this with a simple `string` field + template is a good idea. Thanks!
