### ISSUE TITLE
Inherit template without side bars

### ISSUE THREAD

**Issue by renatomefi** [marmelab/ng-admin#1244]
### Scope

Due to the new ui-view it's not possible to make a new page which doesn't have the side bar.

### Description

On old versions you could have:
```
    $stateProvider
        .state('login', {
            url: '/login',
            templateUrl: '/template/login',
            controller: 'loginController',
            controllerAs: 'lc'
        });
```

Now you are required to:
```
    $stateProvider
        .state('login', {
           parent: 'ng-admin',
            url: '/login',
            templateUrl: '/template/login',
            controller: 'loginController',
            controllerAs: 'lc'
        });
```

Which make it not possible to have a new template without the top and sidebars.

**Expected behavior:**
I'd expect another level in the template engine, one which could inherit the old main template.
I tried to create one myself but didn't find a nice solution

Thanks for the help

**Comment by Phocea** [comment]
And what about defining your html like so:
```
...
<div ui-view></div>
<div ui-view="ng-admin"></div>
...
```

And your route like so:
```
    $stateProvider
        .state('login', {
            url: '/login',
            templateUrl: '/template/login',
            controller: 'loginController',
            controllerAs: 'lc'
        });
```

Works for me

**Comment by renatomefi** [comment]
@Phocea worked, thanks for it!

I tried creating something similar but giving the ui-view a name and didn't work, funny tho!
