### ISSUE TITLE
Different URL for editionView for data fetch and update

### ISSUE THREAD

**Issue by mintu19** [marmelab/ng-admin#1262]
When we enter editionView data is first fetched from url and then displayed and allowed to make changes and on submit is updated. But in my api I have different url for fetching and updating data. On setting custom url to editionVew(), one of them has to fail this way as they both uses same url instead of different ones. So can we make data fetch using url from showView instead or setting another url for show?

**Comment by Phocea** [comment]
Did you try to use a custom Restangular interceptor to handle you case ?
You could "require" PUT call for your resource inside the interceptor to make a call to the correct URL

**Comment by mintu19** [comment]
But the problem i think is with fetching of data. Editionview tries to fetch data using same url as it uses for put request. Although this seems ideal case but is not always true. Sometimes different endpoints might exist for both requests. If i override API calls in interceptor it would me to check all GET (not PUT) requests and to correct them. A better solution will be if EditionView have two urls, one for get and other for put (as EditionView always fetch before update). Or other approach might be to use url from showView for GET request.

**Comment by Phocea** [comment]
Can you configure this server side?
I looked a bit more into your use case and think its far easier to have the server redirect your request wherever it may have to go.

For instance, if you perform your search (GET) on an indexed server (ElasticSearch or other), but do the edit (PUT), create (POST), delete (DELETE) directly on the source DB server, then still target all your request (GET, POST, PUT, DELETE) to the same URL, and have this URL redirect the call.
This can be done in Java, or directly using nginx

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

Thanks for using ng-admin!
