### ISSUE TITLE
no comments shown with example code from "getting started" tutorial

### ISSUE THREAD

**Issue by chkuendig** [marmelab/ng-admin#1263]
### Description
I just tried to go through the Getting Started Tutorial, but for some reason i can't get the referenced_lists thing to work: https://ng-admin-book.marmelab.com/doc/Getting-started.html
 

### Steps to Reproduce
http://plnkr.co/edit/uq1ZFiXUPuqg1o749k6O?p=preview (copy-pasted admin.js from the bottom of the Getting Started page)
click on one of the posts, you'll see an empty list with 5 rows

**Expected behavior:** 
![Getting Started Example](https://ng-admin-book.marmelab.com/doc/images/post_show_view_with_related_comments.png) 

**Actual behavior:** 
click on one of the posts, you'll see an empty list with 5 rows
<img width="527" alt="screen shot 2016-12-05 at 18 49 59" src="https://cloud.githubusercontent.com/assets/748698/20895879/9ad9c318-bb1b-11e6-9789-4ca7d6a36376.png">

**Comment by Phocea** [comment]
The error in the plunkr shows

```
ng-admin.min.js:7 Error: Unable to find entity "comments"
    at e.value (https://unpkg.com/ng-admin@1.0.0-beta3/build/ng-admin.min.js:26:25661)
    at pre (https://unpkg.com/ng-admin@1.0.0-beta3/build/ng-admin.min.js:45:9654)
    at https://unpkg.com/ng-admin@1.0.0-beta3/build/ng-admin.min.js:7:9042
    at ae (https://unpkg.com/ng-admin@1.0.0-beta3/build/ng-admin.min.js:7:9099)
    at g (https://unpkg.com/ng-admin@1.0.0-beta3/build/ng-admin.min.js:7:2673)
    at s (https://unpkg.com/ng-admin@1.0.0-beta3/build/ng-admin.min.js:6:31254)
    at https://unpkg.com/ng-admin@1.0.0-beta3/build/ng-admin.min.js:6:30901
    at link (https://unpkg.com/ng-admin@1.0.0-beta3/build/ng-admin.min.js:45:3072)
    at https://unpkg.com/ng-admin@1.0.0-beta3/build/ng-admin.min.js:7:9042
    at ae (https://unpkg.com/ng-admin@1.0.0-beta3/build/ng-admin.min.js:7:9099) <ma-referenced-list-column field="::field" datastore="::datastore" class="ng-scope ng-isolate-scope">
```
The comments entity has not been defined anywhere, however the document does state

> As a side note, you can see that it's possible to create a reference to a non-existent entity (nga.entity('comments) creates the related entity for the occasion).

@fzaninotto did we loose that functionality at some point ?
@chkuendig if you define the comments entity in your configuration then your Getting Started will work. You also look at this [plunkr] (http://plnkr.co/edit/jaXppV) as an example, or the [ng-admin-demo](http://marmelab.com/ng-admin-demo/#/dashboard)

**Comment by fzaninotto** [comment]
I believe linking to a nonexistent entity han't been possible for some time. It's probably the documentation that is outdated.
