### ISSUE TITLE
Upload picture corrupted Data

### ISSUE THREAD

**Issue by xmtlx** [marmelab/ng-admin#1264]
Hello,

When i use this code below, i receive a corrupted data on my webservice

`nga.field('thumbPath', 'file')
.label('Picture')
.uploadInformation({ 
'url': 'http://localhost:8080/rest/postFoto',
'apifilename': 'msg',
'accept': '.png'
}),`

**Comment by Phocea** [comment]
Can you provide a plunkr example of your problem. There is not enough details in your report to help you.

**Comment by xmtlx** [comment]
Hello! thank's for help!

Here is my server side code, It able to accept multipart/formdata, but generate a invalid file(with same size of the original). When i upload with another tool, it's work fine.

	@POST
	@Consumes(MediaType.MULTIPART_FORM_DATA)
	@Produces(MediaType.APPLICATION_JSON + ";charset=utf-8")
	public Response postFoto(InputStream stream) {
		if (stream != null) {
			try {
				System.out.println(stream);
				byte bytes[] = IOUtils.toByteArray(stream);
				System.out.println(bytes);
				InputStream in = new ByteArrayInputStream(bytes);
				String path = UploadS3.upload(in);
				System.out.println("https://*****.amazonaws.com/*****/" + path);
				return Response.Ok("https://******.amazonaws.com/******/" + path);

			} catch (Exception e) {
				e.printStackTrace();
				return Response.Error("Error");
			}

		}
		return Response.Error("Invalid");
	}

**Comment by xmtlx** [comment]
Hello,
I found the problem, ng-admin upload a file with this text below, when i remove this text (with text editor) the picture open fine:

```
------WebKitFormBoundaryQqfa5NcKZfgXhknR
Content-Disposition: form-data; name="file"; filename="20.PNG"
Content-Type: image/png

<**Original content**>

------WebKitFormBoundaryQqfa5NcKZfgXhknR--
```

How can i remove this header?

**Comment by Phocea** [comment]
ng-admin is using ng-file-upload for this, if you look on their git repo you will find your issue being discusseed in several places.
Have a look at https://github.com/danialfarid/ng-file-upload/issues/67 & https://github.com/danialfarid/ng-file-upload/issues/640, it should help you out with your configuration

**Comment by fzaninotto** [comment]
As this is not an ng-admin issue, I'm closing it.
