### ISSUE TITLE
2 listView  inside the same entity

### ISSUE THREAD

**Issue by MahmoudEllouze** [marmelab/ng-admin#1276]
Hey guys. Thank you for your hard work.
I was wondering if it was possible to have 2 listViews in the same page. One is linked to the entity "user" for exemple and the other is linked to the entity "author". And each of these lists have their own fields.
Of course each enity will have its own baseApiUrl.

**Comment by Phocea** [comment]
Have a look at how the [dashboard template] (https://github.com/marmelab/ng-admin/blob/master/doc/Dashboard.md#dashboard-template) is working. Its doing more or less what you are requesting

**Comment by MahmoudEllouze** [comment]
Thank you, that's what I've been looking for. I guess I need to add <ma-create-button> on each dashboard to add the create button relative to author and user.

**Comment by Phocea** [comment]
Great. Will close this for now. Reopen it, or open another ticket if needed.
