### ISSUE TITLE
Extend validation() to support other validation rules.

### ISSUE THREAD

**Issue by thachp** [marmelab/ng-admin#1277]
I would like to extend field validation to support other client-side validation rules from [validatejs](https://validatejs.org/#validators-numericality).  How should I best approach this?  

For example, I would like to use the numericality validator _greaterThan_  in [validatejs](https://validatejs.org/#validators-numericality) in the context of, the current field must have a value greater than another field in the same entity. 

In my perfect world, I expect to simply define greaterThan property in the validation object.

```javascript
 field.validation({
      onlyInteger: true,
      greaterThan:  anotherField
})
```
Perhaps, we could also add another hook similar to onSubmitError(), but for _before_ sending HTTP requests. 

```javascript
    editionView().onBeforeSubmit([Array|Function])
````

https://ng-admin-book.marmelab.com/doc/reference/View.html

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

Thanks for using ng-admin!
