### ISSUE TITLE
Multiple entity listview in single page with filters and pagination supports

### ISSUE THREAD

**Issue by manind007** [marmelab/ng-admin#1285]
Hi,

If possible to show Multiple entity listview in single page with filters and pagination supports?.

For example, From Invoice entity showView to display their payments listview with filters and pagination supports?.

Thanks for advance

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

Thanks for using ng-admin!
