### ISSUE TITLE
problem with wysiwyg field

### ISSUE THREAD

**Issue by rasparac** [marmelab/ng-admin#1296]
in edit view i have wysiwyg it looks like this
```js
newsPosts.editionView()
            .fields([
                nga.field('title'),
                nga.field('post', 'wysiwyg'),
                nga.field('news_category_id', 'reference')
                    .label('Category')
                    .targetEntity(nga.entity('newscategorys'))
                    .targetField(nga.field('name'))
                    .singleApiCall(function(ids) { return { 'id': ids } })
                    .perPage(undefined)
                    .isDetailLink(true),
                nga.field('image_url', 'file').template('<img width="200" height="200" src="{{entry.values.image_url}}"  class="img-responsive"/>')
            ])
            .title('Edit Post # {{ ::entry.values.title }}');
```
but i get this error for post field. Can you help me?

```trace
TypeError: s.match is not a function
    at ng-admin.min.js:98
    at Array.J (ng-admin.min.js:98)
    at Object.<anonymous> (ng-admin.min.js:25)
    at p.$digest (ng-admin.min.js:24)
    at ng-admin.min.js:24
    at o (ng-admin.min.js:22)
    at ng-admin.min.js:22
```

**Comment by Kmaschta** [comment]
Hi, thanks for taking the time to report an issue.

Can you provide a Plnkr which reproduce your error?
It will ease the way we can help you.

See the [ISSUE_TEMPLATE](https://github.com/marmelab/ng-admin/blob/master/ISSUE_TEMPLATE.md) for an example.

Thanks.

**Comment by rasparac** [comment]
my fault. I had column post in my database table and when i get response form the database Restangular overrides my post column with the Restangular.post() method and i get function instead of text.

**Comment by Kmaschta** [comment]
Thanks for taking the time for  update the issue and glad to hear that you resolved it.

I close this one!
