### ISSUE TITLE
[Question] Filters object

### ISSUE THREAD

**Issue by Phocea** [marmelab/ng-admin#1301]
### Scope

I would like to rebuild the filter section of a ListView using a function rather than a static configuration.
I also would like to be I have a few questions than may help me in my analysis

### Description
* Item 1
* Dynamically writing the filters seems easy enough. The filters() method in [Listview.js](https://github.com/marmelab/admin-config/blob/master/src/View/ListView.js) is expecting an array of Fields which a custom method could provide.
  * Would you see added value to have an utility method inside ng-admin, able to deserialize a JSON into a Field ?
* If I write a directive which can access the entity object (similar to the Create button). From there I can get the listview list of defined filters, but
  * Will that filter object contains the current state of the filters, i.e. the selected filters and their current values, or only the initial configuration of the filters?

Thanks for the help :)

**Comment by Phocea** [comment]
@fzaninotto, @jpetitcolas any hints if you have a minute ?

Specifically regarding the second above point, I can access the listview filters using a directive, but not the current values of the filters. How could we go easily about grabbing this without reinventing the wheel ?

**Comment by Phocea** [comment]
FYI problem was solved by using the llCtrl.search in our directive. Using this binding we can easily dynamically retrieve the filters

**Comment by chenyaoyi110** [comment]
Hi @Phocea , I have the same problem, could you tell me what did you do for this? thank you very much
