### ISSUE TITLE
AngularJS 2 version

### ISSUE THREAD

**Issue by johnwen18** [marmelab/ng-admin#1304]
hello
I would like to know is there a ng-admin version support AngularJS 2 ?

**Comment by SebLours** [comment]
Answer is here:
https://marmelab.com/blog/2017/01/27/ngadmin-1.0-is-out.html#roadmap-and-future-of-ng-admin

**Comment by jpetitcolas** [comment]
@SebLours is right:

> Ng-admin relies on Angular 1.x, a technology we used heavily at marmelab. Yet, we didn’t make the switch to Angular2, as we preferred to dive in the awesome React ecosystem. So, we will probably never port ng-admin to Angular 2.0.

But feel free to fork this project if you need to. :)
