### ISSUE TITLE
Date field cannot be typed in

### ISSUE THREAD

**Issue by Joe-Edwards** [marmelab/ng-admin#1305]
If you have a 'date' field, you can no longer type the date in it explicitly. Attempting to modify an existing date also just deletes it.

You can see the behaviour in the ng-admin demo - https://marmelab.com/ng-admin-demo/index.html#/customers/edit/485 - try changing the birthday without opening the picker.

I think this was broken by https://github.com/marmelab/ng-admin/issues/899 - it used to work in an older version of ng-admin.

The problem is because maDateField watches both value and rawValue:

```
            scope.$watch('rawValue', function(newValue) {
                scope.value = field.parse()(newValue);
            });

            scope.$watch('value', (newValue, oldValue) => {
                if (newValue === oldValue) {
                    return;
                }

                if (!newValue) {
                    scope.rawValue = null;
                    return;
                }

                scope.rawValue = scope.value instanceof Date ? scope.value : new Date(scope.value);
            });
```

The problem is, if at any point an invalid date string is in the box - suppose the string 'foo'. The following sequence happens:
- `$watch('rawValue'` sees `foo`. This is not a date object, so `parse` leaves it unchanged, and `value` is set to `foo`.
- `$watch('value'` sees `foo` and attempts to construct a new Date object using it. This ends up setting `rawValue` to an `Invalid Date` object.
- `$watch('rawValue'` sees `Invalid Date`. This is a date object, so `parse` tries to manipulate it, but fails and ends up setting the value to `null`. 
- `$watch('value'` sees `null` and correspondingly sets `rawValue` to `null`
- `$watch('rawValue'` sees `null` and correspondingly sets `value` to `null`
- `$watch('value'` sees `null`, this is the same as the last value, and the cycle ends!

The net result is `null` - which removes the text you tried to write from the box.

----

This is related to https://github.com/marmelab/ng-admin/issues/1271 which will be caused by a similar loop. However in that case, if you are in a timezone, the value/rawValue watches will loop, and because the 'parse' method applies a timezone correction the value never stabilises (resulting in the infinite loop).

**Comment by mosasiru** [comment]
In many use cases, operators want to manage hour and minutes,  but it is not enabled now by the degration.
These cases are more popular than https://github.com/marmelab/ng-admin/issues/899, so  https://github.com/marmelab/ng-admin/issues/899 should be reverted once.

**Comment by aikizoku** [comment]
Please  fix me (T_T)

**Comment by matheo** [comment]
I patched my DateField to be able to work with the date selector fixing the timezone diff:
```
scope.rawValue = scope.value instanceof Date ? scope.value : new Date(new Date(scope.value).getTime() + (new Date().getTimezoneOffset() * 60 * 1000));
```
https://github.com/marmelab/ng-admin/blob/master/src/javascripts/ng-admin/Crud/field/maDateField.js#L32

**Comment by Phocea** [comment]
@matheo, if your patch fix both issues, can you create a PR for it please ?

**Comment by matheo** [comment]
Done ;) https://github.com/marmelab/ng-admin/pull/1317

**Comment by Kmaschta** [comment]
Yup, the infinite loop is now fixed with my PR #1318.

It will be published soon!

**Comment by Kmaschta** [comment]
I misunderstood the issue, it's about **manually** edit the date field.
The relation with the PR #1317 was confusing.

I re-open the issue, sorry for the inconvenience !

**Comment by jamespsterling** [comment]
Also when you use the datepicker and then click into another field, the date changes 'magically'.

![ng-admin-datepicker-strangeness](https://cloud.githubusercontent.com/assets/6403652/24117287/a2395980-0d77-11e7-870f-9ab9c0c0241c.gif)
