### ISSUE TITLE
Reference field type with editable(false) does not work as expected

### ISSUE THREAD

**Issue by tomy2105** [marmelab/ng-admin#1313]
Reference field type with editable(false) does not work as expected.

Create reference field with editable(false), to me it doesn't show dropdown or anything.
Without editable(false) it works ok.

**Comment by Phocea** [comment]
@tomy2105 , can you please provide a plunker as described in the issue template to illustrate the problem.
Thanks

**Comment by tomy2105** [comment]
Tried this with newest version of ngAdmin and now it works as expected, closing.
