### ISSUE TITLE
reference_many field and many-to-many association

### ISSUE THREAD

**Issue by daniel-pinciuc** [marmelab/ng-admin#1314]
Hi,

I have 2 sails(v.10.5) models: **Association** and **Canton**. Association has and belongs to many Canton and vice versa. On the ng-admin dashboard I added something like this:

var association = nga.entity('association');
var canton = nga.entity('canton');
app.addEntity(association);
app.addEntity(canton);

association.creationView()
                    .fields([
.........

nga.field('cantons', 'reference_many')
                      .targetEntity(canton)
                      .targetField(nga.field('displayValue'))
                      .attributes({ placeholder: 'Select some cantons...' })
                      .sortField('searchValue')
                      .sortDir('ASC')
.........
]).

The problem is that I can select multiple values (cantons) from the choices field type and they are saved in the join table database (I checked the database and also the api url and I get the list of cantons for that association being created/edited) but when I came back again I do not get any of the cantons.

I guess that I need to tell Restangular to make some transformations on the cantons fields, because the cantons are not on the association collection, but on the join table assocations_cantons that was automatically generated.

Can you give a solution for this? Thank you very much.

**Comment by Phocea** [comment]
@daniel-pinciuc if you could provide a plunker illustrating your question, it would be useful

**Comment by daniel-pinciuc** [comment]
The problem was that the cantons collection was not populated for the Association entity when editing. So I overrided the GET /api/association/:id route and added populated values for cantons collection when get the association from database. That solved my problem.

**Comment by Phocea** [comment]
Thanks for the feedback.
Closing this then!
