### ISSUE TITLE
Add custom page can not be achieved

### ISSUE THREAD

**Issue by pq771271668** [marmelab/ng-admin#1325]
Hello
According to the official website of https://ng-admin-book.marmelab.com/doc/Custom-pages.html, I can not add a custom page
This is my code
Here is a menu bar

   .addChild(nga.menu().template('<a href="#/table"><span class="glyphicon glyphicon-cog"></span>column2</a>'))

Route here
MyApp.config (function ($stateProvider, $urlRouterProvider) {
$stateProvider.state ('table', {)
Parent:'ng-admin',
Url:'/table',
Params: {id: null},
Controller: sendPostController,
ControllerAs:'controller',
TemplateUrl:'static/table.html'
});
});
Function sendPostController ($stateParams, notification) {
};
Excuse me, do you have any mistakes? How to solve the routing? How do I feel good ui-router not the same? Thanks

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

Thanks for using ng-admin!
