### ISSUE TITLE
datepicker throws error, decrements on clicking dropdown

### ISSUE THREAD

**Issue by jamespsterling** [marmelab/ng-admin#1326]
Datepicker changes after selecting date from the picker and click into another field on the form. 

Running latest version of master as of 3/20/2017

### Steps to Reproduce
1. Goto: https://marmelab.com/ng-admin-demo/index.html#/customers/edit/485
2. Click into the datepicker 'Birthday' field
3. Select any date
4. Click into another input field on the form (any)
5. Observe as clicking into any other field changes the date in the 'Birthday' input field 

**Expected behavior:**
Datepicker input to not change

**Actual behavior:**
Datepicker input changes when clicking into another input field

**GIF Demo:**
![ng-admin-datepicker-strangeness](https://cloud.githubusercontent.com/assets/6403652/24117414/2719180c-0d78-11e7-9ba2-4b5772d4829f.gif)

[console.log.txt](https://github.com/marmelab/ng-admin/files/856104/console.log.txt)

**Comment by Kmaschta** [comment]
On which timezone do you are?

**Comment by jamespsterling** [comment]
@Kmaschta CST

**Comment by dlemphers** [comment]
@Kmaschta I'm experiencing the same, and in the debug console I get a:

 `10 $digest() iterations reached. Aborting!` error.

My TZ is USA/CST

**Comment by Kmaschta** [comment]
@jamespsterling @dlemphers Do you confirm that the PR https://github.com/marmelab/ng-admin/pull/1334 has fixed this issue?

**Comment by dlemphers** [comment]
@Kmaschta I'm on 1.0.5 and I still have issues:

1. The date shown in the input box is correct, but when you select the popout, the date is the day before:

![image](https://cloud.githubusercontent.com/assets/1016114/24717420/084e5e1e-19f8-11e7-8207-bdd18af30ea8.png)

2. At this point if I select a new value, I get the 10 $digest() iterations reached error:

![image](https://cloud.githubusercontent.com/assets/1016114/24717459/2b478e4a-19f8-11e7-812a-ba64a3910dcc.png)

3. And lastly, clicking on the dropdown changes the date by itself, decrementing 11 days at a time. For example, I just click on the calendar icon, then click off focus without selecting a date, and repeat that, and the date just changes by itself.

![image](https://cloud.githubusercontent.com/assets/1016114/24717484/44784da0-19f8-11e7-8ee9-51195f9cbbc4.png)

![image](https://cloud.githubusercontent.com/assets/1016114/24717498/4c428fdc-19f8-11e7-8bc2-acf0d9779043.png)

![image](https://cloud.githubusercontent.com/assets/1016114/24717509/54223748-19f8-11e7-9333-9ea190543493.png)

![image](https://cloud.githubusercontent.com/assets/1016114/24717515/5aebfaaa-19f8-11e7-8fc5-4a9d8e8d7b22.png)

**Comment by marceloodjusto** [comment]
Is this bug fixed? I have the same problem here.

**Comment by renanrv** [comment]
Same problem here.

**Comment by amitstein** [comment]
I guess that the cause of this bug is when the date is created from a string that only contain the date part (not the time) https://github.com/marmelab/ng-admin/blob/e3a49fe6798c7b9fe93498f80353ed1420275ae2/src/javascripts/ng-admin/Crud/field/maDateField.js#L6 
Since it is created from UTC time, so with negative timezone offsets the date resulted it's the day before.
So, after that it starts an infinite loop between the watches of `values` and `rawValue`

**Comment by thanhbuiea** [comment]
Any progress on this bug? It has been present for more than a while.

**Comment by Kmaschta** [comment]
@thanhbuiea I'm sorry, but we are focusing our efforts in a new project: [marmelab/react-admin](https://github.com/marmelab/react-admin), and we haven't the time to address all the ng-admin issues.

But we'd be glad to help any contribution.

**Comment by sarvaniupadrasta** [comment]
@here Issue is not reproducible now.  This can be closed
