### ISSUE TITLE
onSubmitSuccess entry._identifierValue is unidentified

### ISSUE THREAD

**Issue by jamespsterling** [marmelab/ng-admin#1327]
Based on the example code mentioned in the [Docs](https://github.com/marmelab/ng-admin/blob/49fdc56a8dc50d8623b5ebf4b4d1cdcf0b8e1857/doc/reference/View.md#editionview-and-creationview-settings), we're expecting ```entry``` to contain the ID value, but it does not.

_Using latest master as of 3/20/2017._ 

```javascript
  post.editionView().onSubmitSuccess(['progression', 'notification', '$state', 'entry', 'entity', function(progression, notification, $state, entry, entity) {
      // stop the progress bar
      progression.done();
      // add a notification
      notification.log(`Element #${entry._identifierValue} successfully edited.`, { addnCls: 'humane-flatty-success' });
      // redirect to the list view
      $state.go($state.get('list'), { entity: entity.name() });
      // cancel the default action (redirect to the edition view)
      return false;
  }])
```

```Console.log(...)``` shows us the ```_identifierValue``` is unidentified in this context. 
![image](https://cloud.githubusercontent.com/assets/6403652/24117799/9aff321e-0d79-11e7-9842-cf047002ec80.png)

... Thus the ```entry._identifierValue``` is unidentified in the notification, 

```javascript
notification.log(`Element #${entry._identifierValue} successfully edited.`,
```

**Comment by Kmaschta** [comment]
Hi @jamespsterling,

Can you provide a [Plunkr](http://plnkr.co/edit/xiRijR1CeETB2qoz8krp) that reproduce this error?
It'll help us a lot to understand the issue.

**Comment by jamespsterling** [comment]
I think I realized this is my bug, the PUT I'm doiing is not returning a copy of the 'edited' object.
