### ISSUE TITLE
Filter value is not updated based on search url parameter  

### ISSUE THREAD

**Issue by tpaan** [marmelab/ng-admin#1328]
### Description

If you are on a view with filters and you click on a link that changes the search url parameter value then the view is filtered correctly based on the new search value, but the displayed filter value is not updated.

This used to work correctly in v1.0.0-beta3 and is broken since version 1.0. I believe this commit is at fault: https://github.com/marmelab/ng-admin/commit/4fc19b1143080aed86c64f254748d18ddf0c090a 

### Steps to Reproduce

1. Open this Plunkr demo: http://plnkr.co/edit/1SQO4nqnwuG0FTCZTFwl?p=preview
2. Click on menu link "Users with filter 'John'"
3. Change name filter to Cathy
4. Click on menu link "Users with filter 'John'" again

**Expected behavior:** Name filter should show correct value John

**Actual behavior:** Name filter stays as Cathy

Gif demo:
![filters](https://cloud.githubusercontent.com/assets/23719097/24201162/eb3f89a0-0f17-11e7-8c9e-118098bfe2f6.gif)

**Comment by Phocea** [comment]
I noticed this also and am not entirely sure what the behaviour should be.
If a user changed the default filter then navigate away and come back. Shall it retain the value he entered or the default one that was set ?

That odd behavior can also be seen on the [ng admin demo](https://marmelab.com/ng-admin-demo/#/commands/list?search=%7B%22status%22:%22ordered%22%7D)

@djhi whats your input on those use cases ?

**Comment by fzaninotto** [comment]
Should be solved by #1333

**Comment by Kmaschta** [comment]
It should now be fixed. We'll publish a release soon!
