### ISSUE TITLE
[WIP] Enhance pinned filter so they can be removed

### ISSUE THREAD

**Issue by Phocea** [marmelab/ng-admin#1332]
### Scope

Current pinned functionality is limitative since you define a default behavior where a filter is going to be pinned to the top of a listview, but the user has no way of removing this filter if he is not interested in it.

Being able to remoe a "pinned" filter would be great if you want to implement a way for the user to save its filter preferences, and then modify them later on!

### Description
I am proposing to either:

- add a second attribute to the pinned() method of [Field.js](https://github.com/marmelab/admin-config/blob/8e774c8801d765438ccd3ecd9b9fa927e4409779/src/Field/Field.js#L209), defining if its removable or not. False by default.
- add a new method for filters, called "active", which will do the same as pinned but allowing it to be removed.

First option would make the actual [form filter condition](https://github.com/marmelab/ng-admin/blob/39757abe864f96b2084ec914f7a69308d211fd00/src/javascripts/ng-admin/Crud/filter/maFilterForm.js#L20) a bit more complex.

@fzaninotto , @jpetitcolas , @Kmaschta I would appreciate your opinion before to make those changes

**Comment by fzaninotto** [comment]
I don't think that having unpinnable filters without user preferences makes sense, and I don't want to take the path of user preferences (too big, and too far from the initial goal of ng-admin).

Besides, if *all* the pinned filters can be unpinnable, than the implementation is quite easy in userland, by overriding the `maFilterForm` template.

So this won't be added to the core.
