### ISSUE TITLE
How to configure the submenu active

### ISSUE THREAD

**Issue by pq771271668** [marmelab/ng-admin#1337]
Like demo inside Visitors below Leads and Customers

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

However, feel free to look at the related [demo source code](https://github.com/marmelab/ng-admin-demo/blob/master/js/menu.js#L6) for example.

Thanks for using ng-admin!
