### ISSUE TITLE
filter option in listView actions in documentation

### ISSUE THREAD

**Issue by edgarmarkosov** [marmelab/ng-admin#1338]
Please add `filter` option in the documentation for `listView` `actions` field, because when I use only `batch` in actions and add some not pinned filters they are not shown. They are shown when I also add `filter` in actions array.

**Comment by Kmaschta** [comment]
You are right, the default `listView.actions` are: `filter`, `export` and `create`.

If you configure some filters with `listView.filters()` and you don't add the action `filter`, the filters are not shown.
