### ISSUE TITLE
inherit query parameters to reference api calls

### ISSUE THREAD

**Issue by saimirg** [marmelab/ng-admin#1340]
During the workflow of the application, the following page is called to enter a new record: .../subscriptions/create?defaultValues={"login_id":7}

When data entry form is loaded, two of the fields are references to two different entities. How can we pass the parameter {"login_id":7} to the other two API URLs being called during load ?

**Comment by Kmaschta** [comment]
Hi @saimirg,

Sadly, as explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests only. We no longer accept questions here.
So I close this issue, but feel free to write it on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

And please add additional explanations or examples to your StackOverflow question to help people help you. I didn't understand what are the "other two API URLs" that you mention.
