### ISSUE TITLE
possible to add url link within field template?

### ISSUE THREAD

**Issue by ghiewa** [marmelab/ng-admin#1342]
like,

```js
nga.field('Download', 'template')
            .template((entry) => `<a href="http://testurl.com/${entry.values.id}" />`),
```

aim to have a link in showView, can lead user to down some file from the server. Or alternative way to go?

**Comment by Kmaschta** [comment]
Yes it is. Just format a valid tag such as:

```diff
nga.field('Download', 'template')
-    .template((entry) => `<a href="http://testurl.com/${entry.values.id}" />`)
+    .template((entry) => `<a href="http://testurl.com/${entry.values.id}">Download</a>`),
```

I make it work in a [Plunker snippet](http://plnkr.co/edit/UpCqSjENYnUcUWqEijBK?p=preview) (see Users list).

I close the issue, feel free to ask your next questions on [StackOverflow](http://stackoverflow.com/questions/tagged/ng-admin) with the tag `ng-admin`.
