### ISSUE TITLE
Feature: Possibility to add custom actions

### ISSUE THREAD

**Issue by mrded** [marmelab/ng-admin#1348]
Hi there,

It will be great if it's possible to add custom actions, next to existing `.listActions(['show', 'edit', 'delete'])` on `showView` and `listView`.

![](https://i.imgur.com/i2E4iKz.png)
![](https://i.imgur.com/Bu4Qvz6.png)

## Use case

We have several ways to delete users. By default users can delete them self my sending `DELETE /user/{id}`. However, we also have possibility to ban spammers by sending `DELETE /user/{id}?spam=true`.

Currently there is no way to ban spammers.

It's just one example, but you may also have several end points which you want to trigger from 
`showView` or `listView`.

As I see, currently [these buttons are hardcoded](https://github.com/marmelab/ng-admin/blob/39757abe864f96b2084ec914f7a69308d211fd00/src/javascripts/ng-admin/Crud/show/show.html#L4-L8 ).

**Comment by Kmaschta** [comment]
I'm not sure it is documented but you can do such a custom button by inserting a directive like:

```js
entity.listView()
    .listActions(['show', 'delete', '<custom-directive></custom-directive>']);
```

You just have to add you directive to the angular app:

```js
app.directive('customDirective', require('./path/to/directive'));
```
If you have some issue to implement a custom list action, you can ask on StackOverflow with the tag `ng-admin`.

**Comment by mrded** [comment]
@Kmaschta thank you for your reply, it was quick :)
I've updated my issue. There is no problem with adding a custom directive on `listView` you're right. The problem is with `showView`. These action buttons are hardcoded in the template, [look here](https://github.com/marmelab/ng-admin/blob/39757abe864f96b2084ec914f7a69308d211fd00/src/javascripts/ng-admin/Crud/show/show.html#L4-L8).

**Comment by Kmaschta** [comment]
Yup, sorry I wrote a little fast.

Look at this Plunkr: [http://plnkr.co/edit/YbWetcmzBQ4qaI3qFuK3?p=preview], go to User List > Show a user

You can do a custom action in the showView.

**Comment by mrded** [comment]
Thanks a lot! :)
