### ISSUE TITLE
Example from documentation not working

### ISSUE THREAD

**Issue by SankySyS** [marmelab/ng-admin#1356]
Hi!

I tried to write example app using documentation(https://ng-admin-book.marmelab.com/doc/Getting-started.html). But when i open index.html file i see next image:

![image](https://user-images.githubusercontent.com/3475179/28667292-9aa7f548-72d3-11e7-8bda-96c5e11ef754.png)

but expected as in documentation:
![image](https://user-images.githubusercontent.com/3475179/28667314-a8df1f06-72d3-11e7-8055-05fbb021ca01.png)

**Comment by jpetitcolas** [comment]
Are you sure you embedded your configuration file in your app?

Share us your code. Blindly helping you is too much challenging! :)

**Comment by SankySyS** [comment]
Hi Jonathan,
please sorry that I misled everyone. It is my mistake. I run it locally from hard disk without using any web servers. Now it's work. 

Sorry again.
