### ISSUE TITLE
How to generate a three-level menu？

### ISSUE THREAD

**Issue by Holyangelmom** [marmelab/ng-admin#1359]
i want to generate three-level menu, the following code does not work:

`

	admin.menu(nga.menu().addChild(
                       nga.menu(A).addChild(

				nga.menu(B)).addChild(

					nga.menu(C)))
        );	
`

How can i do that?

**Comment by Kmaschta** [comment]
Short answer: you can't.

ng-admin doesn't have this feature, unless with code it yourself with [a custom theme](https://ng-admin-book.marmelab.com/doc/Theming.html).

**Comment by Holyangelmom** [comment]
thx 
l'll go to see custom theme.
