### ISSUE TITLE
Upgrade to Angular 5

### ISSUE THREAD

**Issue by kgish** [marmelab/ng-admin#1381]
The ng-admin project is based on an outdated version of Angular.

It'd be really great if a newer version of ng-admin were created which is compatible with the most recent Angular version.

Any plans in the near future?

**Comment by beatelite** [comment]
Pretty sure they're moving on to https://github.com/marmelab/react-admin

**Comment by jpetitcolas** [comment]
Hi,

Indeed, we are moving our efforts on `admin-on-rest` now. We still maintain this project to fix bugs and security issues (as we are still using it on several of our projects). But we won't implement new features. 

Yet, feel free to fork this project to use Angular 5. :)
