### ISSUE TITLE
Edit view in row list (with collapse bootstrap)

### ISSUE THREAD

**Issue by narigua** [marmelab/ng-admin#147]
I was working on this spec for my project, but since last update it's break. Submit button doesn't work.
Have you done some changes on routes ? I need to call another state in listView ?

**Comment by narigua** [comment]
Yes i'm on it, just try to get formController in ListView.

**Comment by narigua** [comment]
Since the last update, it's cool for me to custom layout, and templates.

Just a little explanation:

I don't use require in my project, but i found how to integrate all custom view via directives.
I make directive for layout (works), but i test a directive for listView of an entity, it doesn't work for data. I think my problem is the controller: How can i call differents controller of ng-admin ?

Some code:
```
app.directive('customCustomersList', ['$location', function ($location) {
        return {
            templateUrl: '/ng/customers/list',
            controllerAs: 'DatagridController'
        };
    }]);
```
DatagridController ?
[...]
```
var customerCustomList = '<custom-customers-list></custom-customers-list>';
```
[...]
```
app.customTemplate(function(viewName, what) {
            if (viewName === 'ListView') {
                return customerCustomList;
            }
            if (viewName === 'EditView') {
                return customerCustomEdit;
            }
        })
```

**Comment by narigua** [comment]
No need to inject controllers, i just use my customTemplate based on listView ng-admin.
For my editRow, i use ng-repeat-start and ng-repeat-end to inject edit between each row, just with angular and bootstrap css.

**Comment by fzaninotto** [comment]
OK, can you close the issue if it's OK for you? 

Moreover, I think other ng-admin users would love to read about your customization. If you have a blog, would you mind writing a few lines about it?

**Comment by narigua** [comment]
Just to illustrate:

```
<tr ng-repeat-start="customer in customers">
    <td ng-click="collapseRows = !collapseRows" class="collapsible-row">{{customer.UserName}}</td>
</tr>
<tr ng-repeat-end ng-hide="collapseRows">
    <td>Edit Form</td>
</tr>
```

**Comment by narigua** [comment]
Sorry friend, but I never had time to make me a blog, and it's not envy that I am missing :(
