### ISSUE TITLE
Identifier set, but id sent

### ISSUE THREAD

**Issue by Caligone** [marmelab/ng-admin#165]
Hi there,

I started to use _ng-admin_ few days later to quick scaffold a nice GUI admin with an API built with Hapi and Mongoose. But I encountered an issue with the _Entity.identifier()_ method.

I have set my identifier field as following :

``` javascript
var user = new Entity('user').identifier(new Field('_id'));
```

But here is the request from the edit form :

```
Request URL: http://localhost:3000/v1/user/5482e8405e6d4bbf1d8656f1
Request Payload: 
    email: "usertest@mail.com"
    id: "5482e8405e6d4bbf1d8656f1"
    language: "548342cd7d4ada54720d9cc0"
    password: "password"
    pseudo: "UserTest"
```

As you can see the identifier is correctly set on the URL, but the payload still have the default one as `id` instead of `_id`.

**Comment by osiloke** [comment]
So what was the fix? Is there an additional option?
