### ISSUE TITLE
Question to pagination

### ISSUE THREAD

**Issue by firla** [marmelab/ng-admin#174]
Hi, I'm a backend developer and have no experiences with JS/AngularJS/... stuff and so I have simple question:

The backend API accepts requests like this: ?page=0 / ?page=1 / ...
The number of items per page is fixed in the backend to 10.

Please show me the corresponding pagination function. I have tried many settings and can fetch the items from the API, but the previous/next pagination arrows on the website are always disabled.

Thank you, ng-admin is really great!

**Comment by yaoelcn** [comment]
please read:
http://ng-admin-book.marmelab.com/doc/API-mapping.html
