### ISSUE TITLE
Customizing way that errors are displayed

### ISSUE THREAD

**Issue by jpetitcolas** [marmelab/ng-admin#180]
Currently, our API returns an error like:

``` js
{ error: "My error message" } 
```

The JSON body is displayed rawly in the error notification. It would be great if we could pass `ng-admin` a callback in order to display only the `body.error` property.

**Comment by endel** [comment]
Currently the only way I found to customize it was registering a Restangular error interceptor, like this:

```javascript
RestangularProvider.setErrorInterceptor(function(response, deferred, responseHandler) {
  if (response.data.error) {
    response.data = response.data.error;
  }
  return true;
});
```
