### ISSUE TITLE
transform post/put queries

### ISSUE THREAD

**Issue by cvlmtg** [marmelab/ng-admin#195]
Hi! I see the transformParams() function allows to modify only the query parameters. would it be possible to have a way to transform the post/put queries too?

let's suppose I have an object with two fields, "a" and "b". at the moment a post/put query will send this payload:

{ "a": "value1", "b": "value2" }

I'd like to be able to transform this to, e.g.

{ "fields": { "a": "value1", "b": "value2" } }

thanks in advance!

**Comment by fzaninotto** [comment]
Fixed by #211

**Comment by cvlmtg** [comment]
thanks for the patch! I've started playing a bit with the new version and it's looking great :)
