### ISSUE TITLE
Infinitive pagination in editView/showView

### ISSUE THREAD

**Issue by thangngoc89** [marmelab/ng-admin#209]
Just like the title. If I continue to scroll down in editView/showView . ng-admin sends requests to server.

**Comment by fzaninotto** [comment]
Yep, marked as bug.

**Comment by fzaninotto** [comment]
Can't reproduce the bug on master. Infinite pagination is normally off by default now.

**Comment by fzaninotto** [comment]
No I can see it, reopening.
