### ISSUE TITLE
pagination and X-Total-Count

### ISSUE THREAD

**Issue by cvlmtg** [marmelab/ng-admin#210]
I've modified my REST server to provide the X-Total-Count header as described in the ng-admin doc, but it seems restangular somehow doesn't handle it correctly.

![schermata 2015-01-06 alle 14 24 00](https://cloud.githubusercontent.com/assets/6401008/5629111/32ccc08c-95b0-11e4-87f5-fdbe18e66767.png)

as you can see chrome shows the header, but ng-admin doesn't recognize it. I've added this function to the listview:

```
listView.totalItems(function(response) {
     console.log(JSON.stringify(response.headers()));
     return response.headers('X-Total-Count');
 });
```

and it shows just these headers:

```
{"date":"Tue, 06 Jan 2015 13:20:45 GMT","content-length":"12373","content-type":"application/json"}
```

is there a solution or a workaround for this? I've checked my code to see if I accidentally set some wrong configuration but I really can't figure it out...
any help is really appreciated :)

**Comment by thangngoc89** [comment]
You need to exposure X-Total-Count header

**Comment by cvlmtg** [comment]
I'm doing it. see attached screenshot

**Comment by thangngoc89** [comment]
No. You need to set it via header Access-Control-Expose-Header , add x-total-count to that header and you are good to go. What you see in Development Tool is what browser see. Not what a javascript can see

**Comment by cvlmtg** [comment]
there's always too much too learn -__-
now it's working, thanks! I really didn't know about it...

**Comment by jamespsterling** [comment]
This helped me too. I think this should be part of the documentation... to avoid some hair-pulling.

**Comment by fzaninotto** [comment]
It is... see the tip in https://github.com/marmelab/ng-admin/blob/master/doc/API-mapping.md#total-number-of-results

**Comment by fzaninotto** [comment]
Added a FAQ page with it: Documentation added in FAQ: https://github.com/marmelab/ng-admin/blob/master/doc/FAQ.md#my-api-exposes-x-total-count-but-ng-admin-doesnt-see-it

**Comment by anerivala** [comment]
![screen shot 2017-10-05 at 12 34 07 pm](https://user-images.githubusercontent.com/24691822/31214609-95df95ac-a9c9-11e7-8b7c-1da2b5236298.png)
I can't get x-pagination-total-count what to do??

**Comment by romankhymych** [comment]
http
  .get<any>('url', {observe: 'response'})
  .subscribe(resp => {
    console.log(resp.headers.get('X-Total-Count'));
  });
