### ISSUE TITLE
Bug on customTemplate

### ISSUE THREAD

**Issue by narigua** [marmelab/ng-admin#213]
Hi team,

When i want to had a customTemplate for my entity, i've an error on require function :
```
var customerCustomList = require('text!./ng/customers/list');
```
TypeError: undefined is not a function

I have think that was requirejs, but it's loaded in app.

any idea ?

**Comment by fzaninotto** [comment]
Does your code start with a closure like the following:

```js
define(function (require) {
  // your code here using require
});
```

Anyway, this is not a ng-admin related problem, I invite you to look for help on requirejs boards.

**Comment by narigua** [comment]
Thank you !

**Comment by narigua** [comment]
Update, now i see that the function customTemplate work perfectly, but i don't find the way to include requirejs in my project without errors.

**Comment by lukemarsh** [comment]
@narigua to get requirejs to work with ng-admin you'll need to do something like this:

http://plnkr.co/edit/N4lbcAlvNKje6oo2qcYM?p=preview

@fzaninotto it might be worth updating the docs to include this

**Comment by narigua** [comment]
Thank you for this stuff @lukemarsh ;)

**Comment by fzaninotto** [comment]
@manuquentin Is this the way requirejs is supposed to be loaded?
