### ISSUE TITLE
pagination: X-Total-Count not being read 

### ISSUE THREAD

**Issue by endel** [marmelab/ng-admin#227]
I'm trying to retrieve my response headers but it actually seems to be a problem with Restangular, I'm trying to figure it out.

At this screenshot you can see the headers properly defined, but only "Content-type" can be read.

![screen shot 2015-01-13 at 6 02 15 pm](https://cloud.githubusercontent.com/assets/130494/5728035/6ba2011c-9b4e-11e4-9289-f7c2551e5c8b.png)

Any thoughts?

**Comment by endel** [comment]
Actually, it is required to add `Access-Control-Expose-Headers: x-total-count` in the response headers. It is documented on Restangular here https://github.com/mgonto/restangular#setfullresponse

Sorry :)

**Comment by fzaninotto** [comment]
I'm surprised because it works without this header on other applications. @manuquentin any insight?

**Comment by manuquentin** [comment]
Yes, [that's required](https://github.com/typicode/json-server/pull/22/files#diff-3ca5e313cdf02368ce63986a36207c94R39)

**Comment by fzaninotto** [comment]
Ok, it seems to be required when the API is on another domain. We should add an advice about it in the documentation, so I'm reopening the Issue.

As a side note, you should adapt ng-admin to your API, not the other way around, so if the page count is sent another way, use Restangular's interceptors to map it.

**Comment by brikou** [comment]
I've open an issue in PostgREST https://github.com/begriffs/postgrest/issues/148

**Comment by fzaninotto** [comment]
Documentation added in FAQ: https://github.com/marmelab/ng-admin/blob/master/doc/FAQ.md#my-api-exposes-x-total-count-but-ng-admin-doesnt-see-it

**Comment by mmuruev** [comment]
I have the same issue adding header makes no effect.

> Access-Control-Allow-Credentials: true
> Access-Control-Expose-Headers: x-total-count
> X-Pagination-Total-Count: 123
> X-Pagination-Page-Count: 7
> X-Pagination-Current-Page: 1
> X-Pagination-Per-Page: 20

I've got only  1 - 20 on 20 on the page and no pagination icons.

**Comment by anerivala** [comment]
I do have same problem can you please tell me what to do???

**Comment by anerivala** [comment]
I have a same problem can you please suggest any solution?

**Comment by romankhymych** [comment]
http
  .get<any>('url', {observe: 'response'})
  .subscribe(resp => {
    console.log(resp.headers.get('X-Total-Count'));
  });
