### ISSUE TITLE
Relative base API URL

### ISSUE THREAD

**Issue by thangngoc89** [marmelab/ng-admin#228]
I hope ng-admin will support relative base api url instead of absolute one.
It'll make the deployment much easier

**Comment by manuquentin** [comment]
Hello,
You can set relatives URLs with :
```
app.baseApiUrl('');
```

When using ng-admin on the page : `http://localhost:8000/`, requests will be executed on this host, like :
`http://localhost:8000/tags?_end=30&_start=0`.

**Comment by thangngoc89** [comment]
My API Endpoint is `http://quiz.dev/api/v2`
My ng-admin endpoint is `http://quiz.dev/admincp`
I set `app..baseApiUrl('api/v2/')`
ng-admin request this api:
`http://quiz.dev/api/v2/api/v2/category?_sort=id&page=1&per_page=10 `

I tried to edit into `/api/v2` or `/api/v2/` but none of them work.

**Comment by narigua** [comment]
Same for me.

**Comment by manuquentin** [comment]
Hello,
Restangular doesn't allows relative URLs.
You can reuse your host & port with :

```js
app.baseApiUrl(location.protocol + '//' + location.hostname + (location.port ? ':' + location.port : '') + '/')
```

**Comment by narigua** [comment]
Thank you Manu !

**Comment by thangngoc89** [comment]
@manuquentin  thank you

**Comment by 2anandkr** [comment]
@manuquentin Thank You for this simple solution.

**Comment by Shazam14** [comment]
Hello,
does it apply to sails also? because i tried to use http://localhost:1337 but it is giving me the same ?_sort=id&page=1&per_page=10

**Comment by fzaninotto** [comment]
@Shazam14 posting the same question at several places at once (cf #695) actually *decreases* your chances of getting an answer. Please don't do that anymore.
