### ISSUE TITLE
Feature request: csv data export

### ISSUE THREAD

**Issue by endel** [marmelab/ng-admin#230]
It would be very useful to have a export button on list view, to export the entire result-set, or the results matching a filter.

Implementation reference here: http://stackoverflow.com/a/14966131/892698

**Comment by fzaninotto** [comment]
What to export? My 2c: 

- use filters (users expect, if the list displays 5 results among 500, to download only these 5)
- don't use pagination (users expect, if the list displays 5 pages, to download all pages in a single file)

**Comment by endel** [comment]
@fzaninotto exactly! The same configuration of fields on listView could be used for that.

**Comment by Xennis** [comment]
Maybe just as another implementation reference: For `ng-table` a plugin called `ng-table-export` (https://github.com/esvit/ng-table-export) exists, which adds such an button.

**Comment by fzaninotto** [comment]
cc @ThieryMichel

**Comment by fzaninotto** [comment]
Implemented in #316
