### ISSUE TITLE
Customize main layout template

### ISSUE THREAD

**Issue by endel** [marmelab/ng-admin#234]
As I've seen in the docs, it's currently not possible to override the [main layout template](https://github.com/marmelab/ng-admin/blob/ac9a4ddc56941b149e386087bb9197e56ca57dec/src/javascripts/ng-admin/Main/view/layout.html).

I'm integrating ng-admin with an authentication system, so it will be needed to add some elements in the main header.

**Comment by Xennis** [comment]
Same here with the integration of an authentication system. Therefore it would be nice to have the possibly to modify the main layout, i.e. to add elements in the main navigation bar.

**Comment by alejandro145** [comment]
How can I get the layout file?

https://github.com/marmelab/ng-admin/commit/2597a8d4ec0fef8269bb6f604703eae9ded86679
```javascript
require('text!./path/to/layout.html');
```
require is undefined

**Comment by fzaninotto** [comment]
This is RequireJS at work:

```js
define(function(require) {
  // now you can use define
});
```

Reference: http://requirejs.org/docs/api.html#cjsmodule
