### ISSUE TITLE
Concerning "notification"

### ISSUE THREAD

**Issue by narigua** [marmelab/ng-admin#236]
How can i modify messages or customize with another solution like <a href="https://github.com/jirikavi/AngularJS-Toaster">AngularJS Toaster</a> ?

If you give me the way, i can do it directly on ng-admin if you want ?

**Comment by manuquentin** [comment]
Hello,
You can easily decorate the `notification` service like :
```js
app.config(function (NgAdminConfigurationProvider, Application, Entity, Field, Reference, ReferencedList, ReferenceMany, RestangularProvider, $stateProvider, $provide) {

        $provide.decorator('notification', function ($delegate) {
            $delegate.log = function (message) {
                alert(message);
            };

            return $delegate;
        });

        // ...
}); 
```

**Comment by narigua** [comment]
Hello @manuquentin,

Good stuff !

Now, how can i search for all messages type (success, error, etc..), in log ?

**Comment by fzaninotto** [comment]
This is a general Angular question, closing the ng-admin issue.
