### ISSUE TITLE
PHP

### ISSUE THREAD

**Issue by ThunderTeasers** [marmelab/ng-admin#249]
Hello, can you explain me how I can refactor code for using with PHP instead of Node.js?
Regards, Maxim.

**Comment by narigua** [comment]
I use it with Symfony2 PHP framework, it's work well.
Just you need to adapte Twig in my example.

**Comment by fzaninotto** [comment]
Hi Maxim, ng-admin is a client-side library, executed by the browser. There is no node.js code inside. The server-side part, to build the REST api, can use the language you want.
