### ISSUE TITLE
Lazy-load heavy dependencies

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/ng-admin#250]
Currently, all the code necessary for all features is compiled into the `ng-admin.min.js` and `ng-admin.min.css` files. These files are already BIG (the JS is 350kB... and counting). As we add more sophisticated features (rich text editor, JSON editor), the code will grow... even if developers don't use these features. 

We need to be more conservative on the compiled file size, and let ng-admin load additional scripts when needed. A combination of something like [angular-load](https://github.com/urish/angular-load/blob/master/angular-load.js) and compiled files for "plugins" should do the trick.

**Comment by MarZab** [comment]
Or letting the developer load the modules he needs, something like ngStrap aproach, load all if you dont care or load just the parts that you need.

Related to this, I see the CSS is compiled from Bootstrap-SASS, FontAwesome and SB-Admin-2. Would it be sensible to just include them from bower, that way one could use the existing (custom) boostrap and would lead the way to custom ng-admin templates :)

**Comment by jpetitcolas** [comment]
Closing this issue as we refactored recently the whole build process, exposing two flavors of ng-admin:

* Standalone version, embedding all the dependencies in `ng-admin.min.js`
* Lite version including only `ng-admin` in `ng-admin-only.min.js`
