### ISSUE TITLE
Validation for Reference field

### ISSUE THREAD

**Issue by lukemarsh** [marmelab/ng-admin#255]
I have a creationView which has a few fields and a Reference.

For fields I know you can write validation like this:

new Field('name')
    .validation({ required: true})

But when I do the same for Reference, the error message only displays in a modal with the message "invalid form"

new Reference('status_id')
                    .label('Status')
                    .targetEntity(status)
                    .targetField(new Field('name').map(truncate))
                    .validation({required: true}),

How can I change this validation to include a message or add a class to the field when there in an error?

**Comment by fzaninotto** [comment]
@manuquentin any clue?
