### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by narigua** [marmelab/ng-admin#263]
Hi team,

Can i use in customTemplate html bases of ng-admin, like list ?
How can i inject my entity in this List for example ?

What i want to do ? Just modify somes event on List, like a click on a row.

**Comment by fzaninotto** [comment]
Hi,

Why don't you use `listActions()` with a custom directive then?

**Comment by narigua** [comment]
Hi,

Because it's not my need.
What i want it's to use your base of listView, modify it to customise my editRow system.

Is it possible ?

**Comment by fzaninotto** [comment]
Well, yes, since you can override the view template for a given entity, you can include there your own directives.

```
myEntity.listView().template(myTemplate);
```

**Comment by narigua** [comment]
I see this in documentation, what i want to know it's how can i integrate your base List layout, to modify it a little. Not use to all overide.
Thank you.

**Comment by fzaninotto** [comment]
Copy the [base list template](https://github.com/marmelab/ng-admin/blob/master/src/javascripts/ng-admin/Crud/list/list.html) into a new file, modify this file at will, and use this new template inside `myEntity.listView().template(myTemplate)`. I don't understand your difficulty.

**Comment by narigua** [comment]
I've do it like this ! Problem is that all actions on list don't work.

Do you know if by the template method, all needs controllers are injected ?

**Comment by fzaninotto** [comment]
I don't understand what doesn't work. Can you paste the custom template you inject, the action you try to do, and what it outputs?

**Comment by narigua** [comment]
All my problems was my order declaration on my entity.listview, i put in first template instead of last thing.
With good order, all works well.
Thank you @fzaninotto

**Comment by fzaninotto** [comment]
OK, so I close the issue.
