### ISSUE TITLE
Allow listActions on a ReferencedList field

### ISSUE THREAD

**Issue by Xennis** [marmelab/ng-admin#269]
I think, it would be nice to have the possibility to use the `listActions` option from the `listView` also on a `ReferencedList` field. Hence it would be possible to jump form the `ReferencedList` table to the edtion, show and/or delete view of the corresponding item.

Since the directive `<ma-datagrid>` is used  for the `ReferencedList` too, this shouldn't be a big change in the existing code. I wasn't able to do it, probably because of a lack of knowledge about Angular binding and compiling issues.

In [maColumn.js](https://github.com/marmelab/ng-admin/blob/master/src/javascripts/ng-admin/Crud/column/maColumn.js) from line 20 on: Instead of parsing an empty array for `listActions`  you would parse then the new added variable `listActions` from the `ReferencedList` instance.

```javascript
                if (scope.type == 'ReferencedList') {
                    // special case to avoid recursion
                    element.append(
                        '<ma-datagrid name="{{ field.getReferencedView().name() }}"' +
                             'entries="field.entries"' +
                             'fields="field.getReferencedView().fields()"' +
                             'entity="field.getReferencedView().entity"' +
                             'listActions="[]">' +
                        '</ma-datagrid>'
                    );
                    $compile(element.contents())(scope);
                    return;
                }
```

**Comment by fzaninotto** [comment]
Yes sir, very easy to add.

**Comment by Xennis** [comment]
Thanks for your always fast support.

(I think my mistake was, that I didn't use the to two colons in front of `field` (in the line `list-actions="::field.listActions()"`.)

**Comment by leonardorame** [comment]
Is this already implemented? I pulled the repository today and I noticed the files were updated but this aparently does not work.

Also. Can you post an usage example?.
