### ISSUE TITLE
refresh the browser get 404

### ISSUE THREAD

**Issue by intoxicated** [marmelab/ng-admin#271]
Hello,

I'm trying to use ng-admin to create admin panel. It's kinda working (except it doesn't show any data from backend -- i'm still trying to figure it out how to use it). My question is, when I refresh the browser on example.com/admin (where ng-admin app being used) which redirected to /dashboard and because I do not have route to /dashboard, it ended up get 404 page that provided by sails js. Is this expected behavior or should I configure some file to make it work ? Thanks

**Comment by fzaninotto** [comment]
ng-admin redirects to `#/dashboard`, not to `/dashboard` ([see the demo](http://ng-admin.marmelab.com/#/dashboard)). There must be something wrong in your angular setup.

**Comment by intoxicated** [comment]
Ah thanks! I accidentally added unnecessary routes in module. Removing that fixed the issue.
