### ISSUE TITLE
Support for PATCH verb

### ISSUE THREAD

**Issue by rall** [marmelab/ng-admin#279]
Have you considered supporting the http PATCH action for partial updates? My API requires it.

**Comment by Xennis** [comment]
According to the [documentation](https://github.com/marmelab/ng-admin/blob/master/doc/API-mapping.md):
>ng-admin makes some assumptions about how your API is designed. All of these assumptions can be overridden by way of Restangular's request and response interceptors.

ng-admin uses [Restangular](https://github.com/mgonto/restangular), hence all modification to map you API in the right way need do be done with Restangular. So may you check Restangular for the PATCH support.

**Comment by fzaninotto** [comment]
PATCH will definitely part of ng-admin in the future. It's not a top priority, though. Can't a request transformer do the job for you?

**Comment by rall** [comment]
Seemingly not possible with a request interceptor:

https://github.com/mgonto/restangular#setfullrequestinterceptor

But is a request transformer something different? Excuse my ignorance :-)

**Comment by GeBeater** [comment]
I have replaced PUT with PATCH by using a decorator. This is certainly not the best solution but for my particular case still better than using full updates. Maybe it helps someone until the PATCH method is implemented in ng-admin.

```javascript
app.config(function($provide) {
    $provide.decorator('UpdateQueries', function ($delegate) {
        /**
         * Decorate the origin method for entity update purposes with a decoration that
         * using PATCH instead of PUT in order to provide partial entity updates.
         *
         * @param {View}   view      the formView related to the entity
         * @param {Object} rawEntity the entity's object
         *
         * @returns {promise} the updated object
         */
        $delegate.updateOne = function (view, rawEntity) {
            var entityId = rawEntity[view.getEntity().identifier().name()];

            return this.Restangular
                .oneUrl(view.entity.name(), this.config.getRouteFor(view, entityId))
                .patch(rawEntity)
                .then(function (response) {
                    return view.mapEntry(response.data);
                });
        };
        return $delegate;
    });
});
```

**Comment by shikelong** [comment]
mark

**Comment by shikelong** [comment]
I use `addFullResquestInterceptor` to change the http verb. but In fact it not  changed.

**Comment by GeBeater** [comment]
@shikelong Did you read that it's apparently not possible with a table request interceptor (see above)? Can you post your implementation please. Is a general replacement of POST with PATH using a decorator an option (see above) for your use case?

**Comment by fzaninotto** [comment]
See 54f50e8e9b647966014dec3ec91bc6282cc57b65, you can now override the method for creates/updates. Combined with an interceptor, it should now allow for partial updates.
