### ISSUE TITLE
problem with one to many mapping by using reference class

### ISSUE THREAD

**Issue by intoxicated** [marmelab/ng-admin#280]
I have models something like this with one to many relationship in waterline,

Video:

    module.exports = {
      attributes: {
        ... (some attributes)
        createdBy:{
          model: "user"
        }
      }
    };

User:

    module.exports = {
      attributes: {
          ... (some attributes)
        videos:{
          collection: "video",
          via: "createdBy"
        },
      }
    };

Obviously, User can have multiple video and its one to many relationship. I wanted to create listview for video so I did following:

    video.listView()
        .title('video')
        .fields([
            new Field('title').label('title'),
            new Field('createdAt').type('date'),
            new Reference('createdBy')
                .targetEntity(user)
                .targetField(new Field('id')),
            new Field('state').label('State')
        ])
        .listActions(['show','edit','delete']);
    
but I got error on request  http://localhost:1337/api/v1.0/user/[object%20Object] and no clue where [object%20Object] came from. When I used Field('createdBy') instead of Reference, i got User model display on that field without any one to many or many to many fields 

    {"user_type":1,"id":1,"createdAt":"2015-01-20T22:30:45.248Z","updatedAt":"2015-01-20T22:59:28.678Z"}

I'd appreciate any helps

**Comment by intoxicated** [comment]
I noticed that reference class works on editionView but once I saved the value and revisit again, it showed me blank value..

**Comment by fzaninotto** [comment]
I don't know about waterline, but can you look at the response of your API and paste an example here? From the JSON you've copied, it seems there is no apparent reference ng-admin can rely on.

**Comment by intoxicated** [comment]
This is response, and I guess createdBy field is automatically populated..

{
  "createdBy": {
    "display_name": "geegeeplayer",
    "user_type": 3,
    "id": 5,
    "createdAt": "2015-01-21T03:36:04.832Z",
    "updatedAt": "2015-02-03T04:35:02.671Z"
  },
  "title": "test video",
  "url": "http://localhost",
  "description": "testing submission",
  "view": 102,
  "id": 5,
  "createdAt": "2015-02-03T01:16:20.640Z",
  "updatedAt": "2015-02-03T04:34:26.726Z"
}

**Comment by intoxicated** [comment]
and when I fixed backend to pass non-populated data (i.e. id to other table), weird url came from nowhere (in RestangularProvider, url was like `http://localhost:1337/api/v1.0/user/[object Object]`

**Comment by mickadoua** [comment]
I have the same problem,
My API send me my many to one class

**Comment by shahar3012** [comment]
I have the same problem.
My API return an object with array of objects, like this:
```json
{
   "id":"df8f7573-399f-4ff8-8c4d-1532fcb83bc0",
   "createDate":"2015-10-16T20:34:19.106Z", 
   "updateDate":"2015-10-17T08:35:55.849Z",
   "items":
    [ 
      { 
        "id":"18e9db68-08ff-44ee-a35a-feba9bb0327a",
        "createDate":"2015-10-16T21:31:14.376Z",
        "updateDate":"2015-10-16T21:31:14.376Z" 
      }
    ]
}
```
`RestangularProvider` shows that the url is `http://localhost:8080/items/[object Object]` when ng-admin trying to fetch the data of the nested object.

both `GET http://localhost:8080/items/18e9db68-08ff-44ee-a35a-feba9bb0327a` and `GET http://localhost:8080/items/df8f7573-399f-4ff8-8c4d-1532fcb83bc0` working fine.

**Comment by fzaninotto** [comment]
The new [`embedded_list` field type](https://marmelab.gitbooks.io/ng-admin/content/doc/reference/Field.html#-embedded-list-field-type) should answer your need.
