### ISSUE TITLE
Template for filters

### ISSUE THREAD

**Issue by lukemarsh** [marmelab/ng-admin#283]
It would be nice to use a template for filters:

.filters([
    new Field('reg_number')
    .type('template')
    .template('reg number template')
])

Is this something that already works / am i missing anything?

**Comment by fzaninotto** [comment]
Ah, you're right. It's an easy fix.

**Comment by fzaninotto** [comment]
Could you test #285?

**Comment by fzaninotto** [comment]
Fixed by #285
