### ISSUE TITLE
creating custom directives

### ISSUE THREAD

**Issue by cvlmtg** [marmelab/ng-admin#290]
when creating a custom directive is it possible to know if it is rendering in a creation/edition view or show view? built-in fields can be defined once, inserted in all views and they can correctly render as, e.g., input fields or span depending on the view. I wonder if it is possible to do the same with a custom directive, as I've found nothing in the scope.

thanks in advance!

**Comment by fzaninotto** [comment]
Not now, but I proposed a refactoring to make this possible. See #294.
