### ISSUE TITLE
[RFC] Field Factories

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/ng-admin#294]
# RFC: Field Factories

Now that's 0.5 is out, it's time to think about 1.0. There is a breaking change in the Configuration API that I think is necessary, and we should do that before 1.0 is released. Read on to understand the rationale.

## Problems

1. We add more and more methods to the generic `Field` class that are specific to a certain field type (e.g. `choices()`, `uploadInformation()`)
2. We can't add custom fields easily (forced to use the `template`) field
3. We can't override an existing field by a custom one
4. We can't use a different directive for the ShowView and for the ListView
5. We have three classes for references, but not yet any ability to define variants for view (autocomplete, options list, etc.)
6. We have to inject a lot of classes to the configuration function (`app.config(function (NgAdminConfigurationProvider, Application, Entity, Field, Reference, ReferencedList, ReferenceMany) { ... })`)

## Proposal

- Introduce a factory object to replace all calls to `new`

```js
// before
app.config(function (NgAdminConfigurationProvider, Application, Entity, Field) {
    var admin = new Application('ng-admin backend demo')
        .baseApiUrl('http://localhost:3000/');
    var post = new Entity('posts');
    post.listView()
        .fields([
            new Field('title'),
            new Field('is_published').type('boolean')
        ]);
    admin.addEntity(post);
    NgAdminConfigurationProvider.configure(admin);
});

// after
app.config(function (NgAdminConfigurationProvider) {
    var nga = NgAdminConfigurationProvider;
    var admin = nga.application('ng-admin backend demo')
        .baseApiUrl('http://localhost:3000/');
    var post = nga.entity('posts'); /
    post.listView()
        .fields([
            nga.field('title'),
            nga.field('is_published', 'boolean')
        ]);
    admin.addEntity(post);
    nga.configure(admin);
});
```

- `nga.field` instanciates subclasses of `Field` based on the type (which explains why the type must be in the signature).

```js
nga.field('title') // new TextField('title')
nga.field('is_published', 'boolean') // new BooleanField('is_published')
```

- Create subclasses of the `Field` class. Each subclass can add any field-specific method without cluttering the main `Field` class.

```js
// es6 syntax, could be es5 prototype, doesn't matter for now.
class NumberField extends TextField {
    format(formatString) {
        return ... // format number based on string
    }
}
```

- Store the directive to be used in each view in `FieldView` classes and subclasses.

```js
// es6 syntax, could be es5 prototype, doesn't matter for now.
class NumberFieldView extends TextFieldView {
    getWidgetForListView() {
      return '<ma-string-column value="value | format(field.format())"></ma-string-column>';
    }
    // inherited from TextField
    //getWidgetForShowView() {
    //  return getWidgetForListView();
    //}
    // inherited from TextField
    //getWidgetForDashboardView() {
    //  return getWidgetForListView();
    //}
    getWidgetForEditionView() {
      return '<ma-input-field type="number" field="::field" value="entry.values[field.name()]"></ma-input-field>';
    }
    // inherited from TextField
    //getWidgetForCreationView() {
    //  return getWidgetForEditionView()
    //}
}
```

- `Reference` is a subclass of `Field`, so developers can use the same factory

```js
// before
comment.editionView()
    .fields([
        new Field('body').type('wysiwyg'),
        new Reference('post_id')
            .targetEntity(new Entity('post'))
            .targetField(new Field('title').map(truncate)),
        new Field('author'),
        new Field('created_at').type('date').label('Posted')
    ])
// after
comment.listView()
    .fields([
        nga.field('body', 'wysiwyg'),
        nga.field('post_id', 'reference')
            .targetEntity(nga.entity('post'))
            .targetField(nga.field('title').map(truncate)),
        nga.field('author'),
        nga.field('created_at', 'date').label('Posted')
    ])
```

- To customize the way a field translates into widgets, specialize the field. For instance, to display a `Reference` as a list of options instead of a dropdown:

```js
// dropdown
nga.field('post_id', 'reference')
    .targetEntity(nga.entity('post'))
    .targetField(nga.field('title').map(truncate)),
// list of options
nga.field('post_id', 'reference_options')
    .targetEntity(nga.entity('post'))
    .targetField(nga.field('title').map(truncate)),
```

- Fields are registered in the main registry, and can be manupulated by the developer in the configuration.

```js
app.config(function (NgAdminConfigurationProvider) {
    var nga = NgAdminConfigurationProvider;
    // register new type
    var MyCustomField = require('MyCustomField');
    var MyCustomFieldView = require('MyCustomFieldView');
    nga.registerFieldType('custom', MyCustomField, MyCustomFieldView);
    // override built-in number type
    var MyCustomNumberField = require('MyCustomNumberField');
    var MyCustomNumberFieldView = require('MyCustomNumberFieldView');
    nga.registerFieldType('number', MyCustomNumberField, MyCustomNumberFieldView);
});
```

### Why separate Field and FieldView?

A FieldView (could also be named "Field Widget") concerns the frontend presentation of a field.

A Field defines a maping to the API, and isn't tied to any presentation. We could imagine another Frontend engine using the same Field definitions, but displaying them using jQuery instead of AngularJS. In Practice, a Fiew is inside the `main` module, and a `FieldView` is in the `crud` module.

Also, it alows to override the view without necessarily overriding the field logic.

### Why use fields and not directly widgets?

It could be possible to skip the `FieldView` layer completely, and add widgets instead of fields:

```js
comment.editionView()
    .fields([
        nga.widget('body', 'rich_text_input'), // a rich text editor
        nga.widget('post_id', 'reference_input') // a dropdown list
            .targetEntity(nga.entity('post'))
            .targetField(nga.field('title').map(truncate)),
        nga.widget('author', 'text_input'), // a text input
        nga.widget('created_at', 'date_input').label('Posted') // a date widget
    ])
```

However, we couldn't reuse field definition between views. For instance, The `showView` should use read-only widgets, with different types: 

```js
comment.editionView()
    .fields([
        nga.widget('body', 'rich_text'), // a non-escaped html string
        nga.widget('post_id', 'reference') // a link to the reference
            .targetEntity(nga.entity('post'))
            .targetField(nga.field('title').map(truncate)),
        nga.widget('author', 'text'), // a text 
        nga.widget('created_at', 'date').label('Posted') // a date
    ])
```

Besides, this creates a coupling between the config and the view. It is harder to document and to learn (more widgets to describe).

I'm not entirely sure about this choice, so feedback is welcome.

## Conclusion

The proposed change breaks BC but solves a lot of problems in an elegant way, without making the Configuration API harder to use. It hides the inner architecture, and makes it easy to refactor in the future, reducing the risk of another major BC break.

What do you think?

**Comment by fzaninotto** [comment]
Should fix #258, #261

**Comment by jpetitcolas** [comment]
:+1:

Looks good to me. I especially like the inheritance easing greatly custom behavior for project-specific components.

**Comment by Xennis** [comment]
Sounds like a good plan.

**Comment by ThieryMichel** [comment]
:+1:  I thing this go in the right direction.
