### ISSUE TITLE
the style of pagination controls

### ISSUE THREAD

**Issue by unknownsky** [marmelab/ng-admin#296]
I don't want to show all the pagination controls. In the middle, can replace to '...'. How can I do?
![7fb6602e-e54f-4c7c-b772-9f6cd7bca3d2](https://cloud.githubusercontent.com/assets/3964498/6075587/5f94fae4-ae10-11e4-87a4-eb0fa4a3e41e.png)

**Comment by fzaninotto** [comment]
err... that's a bug.

**Comment by fzaninotto** [comment]
@jpetitcolas any progress?
