### ISSUE TITLE
Implementing login

### ISSUE THREAD

**Issue by leonardorame** [marmelab/ng-admin#299]
Hi, I'm trying to implement redirection to a login form every time the server response is 401. To do this, I added an app.run handler this way:

    app.run(['Restangular', '$location', function(Restangular, $location){
        Restangular.setErrorInterceptor(function(response, deferred, responseHandler) {
            if(response.status === 401){
                $location.path('/login');
                console.log($location.path()); // this prints /login
                return false;
            }
        });
    }]);

The code above works ok (the path is logged in the console). But it does'n redirect to the /login route :(

Now, I defined the routes in the app.config function by first injecting the $routeProvider and configuring it this way:

    app.config(
        function ($routeProvider, NgAdminConfigurationProvider, Application, Entity, Field, Reference, ReferencedList, ReferenceMany, RestangularProvider) {
       $routeProvider
            .when('/login', {
                templateUrl: 'login.html',
                controller: 'loginController'
            });
    ....

I also created the login.html file and a login.js containing my loginController, but as I stated the controller is never executed nor the view is updated. 

Any hint?.

**Comment by endel** [comment]
Hi @leonardorame, I've done this recently to integrate with [our backend](https://github.com/doubleleft/hook). 

Here is the source code, it's kinda ugly but it works. You may substitute the `hook` calls with your API: https://gist.github.com/endel/fd2652384f9dfcc34270

If anybody has a better implemetation for this, I would be very happy to see it. :)

**Comment by endel** [comment]
It seems that the last version now has support to override the main template layout (https://github.com/marmelab/ng-admin/issues/234).

I haven't updated my code to use the feature yet, but it will help you implement yours.

**Comment by crimsonronin** [comment]
Thanks for the tip @endel.

I ended up using your approach along with https://github.com/iandotkelly/angular-basicauth

**Comment by leonardorame** [comment]
Thanks @endel, it seems that ng-admin is not friendly with routeProvider. I simply had to change it to $stateProvider and it worked as I expected.

**Comment by fzaninotto** [comment]
Hey guys, don't hesitate to share your implementation in a Gist or in a blog post, many other ng-admin users would be interested!

**Comment by leonardorame** [comment]
Please, check this: https://gist.github.com/leonardorame/762f4978edbf7a4633b0
