### ISSUE TITLE
JS Object instead JSON in requests

### ISSUE THREAD

**Issue by PaulMaly** [marmelab/ng-admin#300]
Hello guys! First of all, thanks for this awesome tool for building admin/control panels!

I discover Demo application and paid attention that POST and PUT requests send entity data as a Javascript object instead of JSON. See network log:

```javascript
{body: "<p>sdgdsgsdgdsg</p>", published_at: "2015-02-09", teaser: "sgsddsgsdg", title: "sgsdsdgdsgdsgsgd"}
```

Is it correct? My backend system written on PHP and for me it not conveniently, becouse I can't use json_decode() function to map JSON object to PHP object. Thanks for any help!

**Comment by fzaninotto** [comment]
Hi Paul, and thanks for the report.  @jeromemacias can you take a look?

**Comment by fzaninotto** [comment]
I can't seem to reproduce that. Here is what is sent when saving the [first post in the demo](http://ng-admin.marmelab.com/#/edit/posts/1):

```
{
  "id":1,
  "title":"Accusantium qui nihil voluptatum quia voluptas maxime ab similique",
  "teaser":"In facilis ... illum.",
  "body":"<p>Rerum velit... dolorem.</p>",
  "published_at":"2012-08-06",
  "tags":[1,3],
  "pictures":{"first":{"name":"the picture name","url":"http://www.photo-libre.fr/paysage/1.jpg","metas":{"title":"This is a great photo","definitions":["72","300"],"authors":[{"name":"Paul","email":"paul@email.com"},{"name":"Joe","email":"joe@email.com"}]}},"second":{"name":"better name","url":"http://www.photo-libre.fr/paysage/2.jpg"}},
  "views":143
}
```

That's full JSON. Does your network log show already interpreted data? Does your PHP backend complain?

**Comment by PaulMaly** [comment]
Sorry, it was my own misstake. Feel free to close this issue. Thanks!
