### ISSUE TITLE
listActions in ReferencedList only on Show?

### ISSUE THREAD

**Issue by leonardorame** [marmelab/ng-admin#301]
I added listActions in a ReferencedList, but it only work in the showView of the parent entity. How can I make it work on the editView also?.

**Comment by leonardorame** [comment]
BTW, there's no "Create" button in the ReferencedList.

**Comment by fzaninotto** [comment]
Yes, there is no create button in the ReferenceList. There is no pagination control or filters, either. To create an embedded datagrid just like in the listView, you'll have to create a custom type.
