### ISSUE TITLE
listActions enhancement (mix custom and normal actions)

### ISSUE THREAD

**Issue by ThieryMichel** [marmelab/ng-admin#302]
Actually we can pass a list of button names among 'show', 'edit', and 'delete' to listActions, or we can pass a template string to add custom actions. 
But if we want to mix both normal actions and custom one, we need to pass a template with the normal actions directive mixed with the custom one.
What I propose is to modify listAction, to accept both action name and template in its array form.
```
.listActions(['edit', '<my-custom-directive></my-custom-directive>'])
```

**Comment by fzaninotto** [comment]
Low priority IMO.
