### ISSUE TITLE
Would PostgREST combine well with ng-admin?

### ISSUE THREAD

**Issue by StefanScott** [marmelab/ng-admin#306]
Hi -

I've been looking at a new project on github called PostgREST, which provides a REST API for any Postgres database:

"**PostgREST** serves a fully RESTful API from any existing PostgreSQL database. It provides a cleaner, more standards-compliant, faster API than you are likely to write from scratch."

https://github.com/begriffs/postgrest

demo: 
https://postgrest.herokuapp.com/
https://postgrest.herokuapp.com/speakers
https://postgrest.herokuapp.com/speakers?id=eq.10
etc.

For someone who has an existing Postgres database and wants to quickly add an AngularJS CRUD admin GUI, it seems that ng-admin + PostgREST would be an excellent combination!

**Comment by endel** [comment]
Yes, it fits perfectly. You just need to configure Restangular to use PostgREST query parameters properly.

**Comment by fzaninotto** [comment]
@endel would you mind sharing the Restangular config for that mapping in a Gist?

**Comment by rall** [comment]
That's exactly what I'm attempting in fact. I've come across a few problems so far:

1. updates are sent as PUT requests where postgrest expects PATCHes
2. postgrest (for now) expects id params in the query string
3. ng-admin doesn't see the pagination parameters in the header

Here's are the request and response interceptors I'm using (work in progress)
https://gist.github.com/rall/69c9b9acb69c8b7c573d

hope this helps.

**Comment by rall** [comment]
also, here's the decorator I'm using to monkeypatch ng-admin to use PATCH

https://gist.github.com/rall/b3301438ff44de5ee68d

**Comment by fzaninotto** [comment]
We've just published a working [demo](https://github.com/marmelab/ng-admin-postgrest) and a [blog post](http://marmelab.com/blog/2015/03/23/using-ng-admin-with-postgrest.html) on the subject.

**Comment by fab1an** [comment]
Btw. now you just need to use `bookEntity.updateMethod('patch');` to fix the updating issue.
