### ISSUE TITLE
Embedded documents with reference

### ISSUE THREAD

**Issue by crimsonronin** [marmelab/ng-admin#308]
Hi there,

Firstly, thanks for the great software.

Secondly, this is a question more than an issue. I have the following data model:

**Event**
```js
{
    data: {
        casualties: {
            death: {
                number: Number,
                cause: String
            },
            injury: {
                number: Number,
                cause: String
            }
        },
        punishment: {
            number: Number,
            penalty: String
        }
    }
}
```

**Causality**
```js
{
    name: {type: String, index: true},
    createdBy: {type: [String]},
    updatedBy: {type: [String]}
}
```

**Punishment**
```js
{
    name: {type: String, index: true},
    createdBy: {type: [String]},
    updatedBy: {type: [String]}
}
```

I want to create a field in an edit view that has:

`Death | field: number of deaths | reference to causality entity as a dropdown: cause`
`Injury | field: number of injuries | reference to causality entity as a dropdown: cause`
`Punishment | field: number of punishments | reference to penalties entity as a dropdown: penalty`

I tried to create the following:

In `config.js`
```js
...
.addField(new Reference('data')
      .type('template')
      .targetEntity(new Entity('casualties.casualties'))
      .targetField(new Field('name'))
      .template(function () {
        return '<dataedit field="::field"></dataedit>';
      }))
...
```

However, when I tired to get the `field.choices()` in the `data-edit` directive, it returns an empty list, but it should contain entries.

I'm not sure if I'm going about this in the right way.

Any help would be greatly appreciated!

**Comment by fzaninotto** [comment]
Fixed by #714
