### ISSUE TITLE
cssClasses on a ReferenceMany entry within the list view ?

### ISSUE THREAD

**Issue by ponsfrilus** [marmelab/ng-admin#309]
Hi all,
    is there any chance to be able to use "```cssClasses()```" method on a ReferenceMany entry within the list view, e.g. to be able to theme the tags entries in the ng-admin backend demo ?

The ```field.getCssClasses(entry)``` seems not accessible in https://github.com/marmelab/ng-admin/blob/e922c6da083c49754b4d25e648ffcb73bd3e917d/src/javascripts/ng-admin/Crud/column/maReferenceManyLinkColumn.js#L28

Thanks !

**Comment by fzaninotto** [comment]
Hi Nicolas,

The CSS class is added to the `<td>` tag surrounding the field, for all field types. Are you sure it's not in your markup?

**Comment by ponsfrilus** [comment]
My bad! You are right, my apologies... was looking on the `<span>` as I wanted to change it.
Thanks for mentionning the `<td>` !
