### ISSUE TITLE
Angular error after bower update Uncaught Error: [$injector:modulerr] 

### ISSUE THREAD

**Issue by 4levels** [marmelab/ng-admin#310]
Dear ng-admin team,

I've had some issues using the ng-admin module from scratch (read not using the demo).
I keep getting error messages in angular about the ngRoute module not being found.  When running bower, I also keep getting warnings that there are different angular versions available and code incompatibilities may occur:
```
Please note that,
    angular-bootstrap#0.12.0 depends on angular#>=1 <1.3.0 which resolved to angular#1.2.28 textAngular#1.2.2 depends on angular#~1.2.x which resolved to angular#1.2.28
    angular-cookies#1.3.13, angular-resource#1.3.13, angular-sanitize#1.3.13 depends on angular#1.3.13 which resolved to angular#1.3.13
    ng-admin#746094f686 depends on angular#~1.3.1 which resolved to angular#1.3.13
    angular-ui-router#0.2.13 depends on angular#>= 1.0.8 which resolved to angular#1.3.13
    ngInflection#1.0.0 depends on angular#>1.0.0 which resolved to angular#1.3.13
    angular-ui-codemirror#0.2.3 depends on angular#~1.3 which resolved to angular#1.3.13
    restangular#1.4.0 depends on angular#* which resolved to angular#1.3.13
Resort to using angular#~1.3.1 which resolved to angular#1.3.13
Code incompatibilities may occur.
```
When following the link in the console, the resolution is to include the ngRoute module but there is already a router module in the bower components: `angular-ui-router`
I've tried searching for solutions online but I can't seem to get the right answer.  I do have to add that I'm a beginning angular developer..

Is there a more in-depth installation guide for people using ng-admin from scratch?

Even after following the Angular help about installing ngRoute module, I'm still getting this error.
My bower.json is as follows (`bower install --save` added the `angular-route` dependency):
```
{
  "name": "ng-admin demo",
  "dependencies": {
    "ng-admin": "master",
    "angular-route": "~1.3.13"
  },
  "resolutions": {
    "angular": "~1.3.1"
  }
}
```

Kind regards,

Erik aka 4levels

**Comment by fzaninotto** [comment]
Unfortunately, I can't reproduce the bug on a fresh install of the ng-admin demo.

Perhaps you're using an old (cached) version of one of the dependencies? Try running `bower cache clean`, then remove the `bower_components` directory, and run `bower install`again to make sure you're using the same versions as in the demo.

Also, our code doesn't use ngRoute, perhaps that's why. Why don't you use angular-ui-router (which is much better)?

**Comment by 4levels** [comment]
Dear Francois,

thank you for your reply, I've tried the steps to clear the bower cache, remove the bower_components directory and to run the bower install script again.  This didn't change anything.
As I stated in my initial issue, when cloning the ng-admin demo repo (not this repo) I don't have this issue.  This only happens when I try to include ng-admin as angular module in my own project.  I've managed to set up your microrest.php project and this works as expected.. 

Can you please try to use the ng-admin module from a new project (not the ng-admin demo) and see if you're running into the same issue?

Kind regards,

Erik aka 4levels

**Comment by fzaninotto** [comment]
Hi Erik,

We’ve done that on numerous other projects without problems. In order to identify your issue, it’d be easier if you could set up a test project ans post it, for instance as a multiple Gist.

**Comment by 4levels** [comment]
Hi Francois, thank you for your feedback.  I'll setup a new test project and put it on github for you to see.
As a first question, when installing ng-admin through bower, I'm offered the following choice during the first run on an empty project:

```
Unable to find a suitable version for angular, please choose one:
    1) angular#>=1 <1.3.0 which resolved to 1.2.28 and is required by angular-bootstrap#0.12.0 
    2) angular#~1.2.x which resolved to 1.2.28 and is required by textAngular#1.2.2 
    3) angular#1.3.13 which resolved to 1.3.13 and is required by angular-cookies#1.3.13, angular-resource#1.3.13, angular-sanitize#1.3.13 
    4) angular#~1.3.1 which resolved to 1.3.13 and is required by ng-admin#0.5.0 
    5) angular#>1.0.0 which resolved to 1.3.13 and is required by ngInflection#1.0.0 
    6) angular#>= 1.0.8 which resolved to 1.3.13 and is required by angular-ui-router#0.2.13 
    7) angular#~1.3 which resolved to 1.3.13 and is required by angular-ui-codemirror#0.2.3 
    8) angular#* which resolved to 1.3.13 and is required by restangular#1.4.0Prefix the choice with ! to persist it to bower.json
```
I'm going for the first choice this time - angular-1.2.28 (previously I selected option 3 to use angular version 1.3.13)
I'll keep you posted here..

Kind regards,

Erik

**Comment by 4levels** [comment]
Dear Francois,

I've setup a new repo with the exact steps I took to set up ng-admin in a blank project..
I must be somehow overseeing something but I don't get it..
I'm still trying my luck with the demo as well which seems to work perfectly

I'll keep you posted..

**Comment by fzaninotto** [comment]
ng-admin requires angular 1.3.x at least, please reinstall dependencies.

**Comment by Ozonid** [comment]
Hello,

I encountered the same problem while installing ng-admin with bower. No matter which angular version I choose (1.2.x or 1.3.x), I get the same error as Erik.
Also, the provided demo runs just fine.

**Comment by 4levels** [comment]
As a side note:
When installing the components through bower, I initially received git errors as some repo's where being fetched via git:// url, which doesn't work if one has no commit permissions to the specific repo's.
I had to add the following to my global .gitconfig file to make it work:
```
[url "https://"]
        insteadOf = git://
```

**Comment by 4levels** [comment]
As far as I can think of, the issue seems related to the documentation here and the app.js content of the demo app.  The difference in creating the app itself seems to be the culprid:
readme.md:
```
app.config(function (NgAdminConfigurationProvider) {
    var nga = NgAdminConfigurationProvider;
    var app = nga.application('ng-admin backend demo') // application main title
    ...
```
vs app.js of ng-admin-demo:
```
    app.config(function (NgAdminConfigurationProvider, Application, Entity, Field, Reference, ReferencedList, ReferenceMany, RestangularProvider, $stateProvider) {
    var app = new Application('ng-admin backend demo') // application main title
    ...
```
I'm still trying to refactor my app.js to match the approach of the demo to see if this resolves my issue.

**Comment by 4levels** [comment]
Ok, it seems that this resolves the issue, the documentation in the readme.md is simply outdated as the demo uses a whole different style to configure the app.  The most obvious differences are the app, field and entity initialization methods and the lack of a global nga variable.
```
nga.app => new Application
nga.field => new Field
nga.entity => new Entity
```

With the app.js file syntax from the demo app, I don't get this issue anymore, so I'm closing it.  I'm sure you're aware of the outdated installation instructions in the readme.md file so I'm not opening a new issue for this one.  I just hope new adopters can rely on this thread to avoid the setup struggle I just experienced.

Kind regards and keep up the great work on ng-admin!

Erik aka 4levels

**Comment by fzaninotto** [comment]
What? No, the `new Application()` syntax is outdated and should be replaced by the `nga.app()`(see https://github.com/marmelab/ng-admin/blob/master/UPGRADE-0.6.md). The problem is that you're probably using an old version of the ng-admin library. I'll update the demo accordingly.

**Comment by fzaninotto** [comment]
https://github.com/marmelab/ng-admin-demo/pull/2
