### ISSUE TITLE
Infinite Scroll should not be tied to a precalcaulated total page count

### ISSUE THREAD

**Issue by osiloke** [marmelab/ng-admin#318]
Hi,
An example scenario, i would like to get 30 entries during the first call and then 10 entries for subsequent queries. Based on the current code, this can't be done. 
Another scenario would be continuous updates to a list of entries.

**Comment by fzaninotto** [comment]
Hi Osiloke,

ng-admin doesn't support pages of various sizes (whether on normal or infinite pagination), and we never felt the need for it. Could you explain why this is a requirement for you?

Also, I don't understand the "continuous updates to a list of entries". Could you be more specific?

**Comment by osiloke** [comment]
Just a side note, i'm integrating to use a Key Value data store backend to ng-admin, which is why i'm using infinite scroll. Since there is no concept of pagination in key value stores rather you can retrieve x amount of entries from a starting key.

Right, so i felt that i could improve the user experience by first loading enough entries to fill the page and then load smaller number of entries as the user scrolls. This way the user may not notice any loading lag while scrolling. 

Regarding continuous updates
In a situation where an entities resource is updated periodically i .e more data is pushed to the backend. Once the user views the list view of an entity, the number of pages is calculated. If more data is pushed to the backend, the user does not get these updates while scrolling.

**Comment by fzaninotto** [comment]
In your first scenario, if 30 rows is enough to fill the screen the first time, why do you want to load smaller batches afterwards? It would make sense to load them 30 by 30 (i.e. one screen at a time).

For the second scenario, this is a something that we chose to no support for now, because ng-admin's only requirement is to have a REST API, and such a backend doesn't support realtime scenarios.

**Comment by osiloke** [comment]
That works if you are moving through pages, but infinite scrolling is supposed to give the illusion that all data is already loaded and you are just scrolling through what already exists. Its more of a UX perspective. I can always fork and make my changes.

Thanks
