### ISSUE TITLE
API auto-discovery ?

### ISSUE THREAD

**Issue by sroze** [marmelab/ng-admin#32]
Hi there, very good idea to share the missing AngularJS administration !

Did you think about API auto discovery ? 
There's a lot of initiatives to make APIs hypermedia, such as:
- HAL (http://stateless.co/hal_specification.html)
    - A PHP implementation [Hateoas library](https://github.com/willdurand/Hateoas) by @willdurand
- JSON API (http://jsonapi.org/format/)
- HYDRA (http://www.markus-lanthaler.com/hydra/)
    - A PHP implementation [HydraBundle](https://github.com/lanthaler/HydraBundle) by @lanthaler

That could be even more easy than describing the API in a JS file :)

**Comment by fzaninotto** [comment]
For Symfony, there is https://github.com/marmelab/NgAdminGeneratorBundle. Anyway, I don't think it's the purpose of ng-admin to do that, so I'm closing the issue.

**Comment by abstratt** [comment]
:+1:  on having this kind of feature built on top of ng-admin as extensions, not bolted on. There are quite a few different mechanisms for describing APIs. Beyond those mentioned, I would add [RestfulObjects](http://www.restfulobjects.org/) and Kirra (which I develop). All I would expect from ng-admin itself is that it works well in use cases where the back-end API neeeds to be described dynamically.
