### ISSUE TITLE
Cannot use same field more than once

### ISSUE THREAD

**Issue by leonardorame** [marmelab/ng-admin#324]
I would like to use the same field in a view more than once, but aparently field names can be used only one time.

For example. I have a view displaying the field "ImgPath" once for showing a picture (template <img src.../>) and a second time for displaying the value of that field.

**Comment by fzaninotto** [comment]
It's not possible for now, and it's a know problem. 

But, using an ElementTransformer (as explained [here](https://github.com/marmelab/ng-admin/blob/master/doc/API-mapping.md#entry-format)), you can duplicate a value from the API response under two separate keys, and map to the second key in your config:

```js
app.config(function(RestangularProvider) {
    RestangularProvider.addElementTransformer('myElement', function(element) {
        element.key2 = element.key1;
        return element;
    });
});

var myElement = nga.entity('my_element');
bookEntity.editionView()
    .fields([
        nga.field('key1'), 
        nga.field('key2')
    ]);
```
