### ISSUE TITLE
Edit identity (primary key) field

### ISSUE THREAD

**Issue by vasiakorobkin** [marmelab/ng-admin#332]
**Given:**
* a **product** entity element with *name* custom primary key, which set as entity identifier using entity method *.identifier()*
*  Let *name* value to be *"abc"*, so we can edit this element by sending PUT request to  ***/product/abc*** URL

**Problem:**
When I try to edit *name* custom primary key setting it to, for example, *"def"*, ng-admin sends modified entity element via PUT request to ***/product/def*** URL. But no corresponding entity element does exist on this URL at the moment, so back-end fails to save changes.

**Suggested solution:**
To make ng-admin send PUT request to ***/product/abc*** URL, using the original *name* value *"abc"* even if it was modified to *"def"*. I think this should be default behavior.

**Comment by fzaninotto** [comment]
Good point, that will need to be addressed some time in the future. Until we face the problem ourselves, would you like to work on a patch?

**Comment by vasiakorobkin** [comment]
Well, that wasn't a part of my plans... But I'll try to spare some of my time on it.
