### ISSUE TITLE
Pagination on referenced_list

### ISSUE THREAD

**Issue by nathanclevenger** [marmelab/ng-admin#338]
I have a referenced_list field on a showView, and while perPage successfully sets the amount visible, there are no pagination controls to change pages.  What am I missing?

Thanks in advance!

**Comment by fzaninotto** [comment]
It's just not a feature we've implemented yet. Pagination is only implemented in listView.

I don't think it makes sense to embed a full datagrid, together with filters and pagination, in an edit or a show view. Would you mind sharing your use case?

**Comment by nathanclevenger** [comment]
I would agree a full data grid wouldn't be necessary, but simple pagination would be quite valuable. My data model has contacts and categories.  There are 120k contacts, which makes managing that directly in a listView a little out of control, and each contact can be within 'n' categories, but each category only has 5 to 500 contacts within it.  I was hoping to use the category showView to manage the referenced contacts.

Without pagination, I just tried setting perPage(500) which will work for my use case, but is probably not ideal.

Thanks

**Comment by fzaninotto** [comment]
Do you know that you can also link to the filtered listView? I generally find it much more user friendly, because then it's a complete datagrid that the user can modify.

**Comment by nathanclevenger** [comment]
I didn't realize that - it's a great solution.  Thanks
