### ISSUE TITLE
Link to "Custom Page" in the menu

### ISSUE THREAD

**Issue by ponsfrilus** [marmelab/ng-admin#343]
Maybe there is already a way to do it, but if not consider it as an enhancement. It will be helpfull to link a CustomPage in the menu (https://github.com/marmelab/ng-admin/blob/master/doc/Custom-pages.md).

Thanks,
ponsfrilus

**Comment by fzaninotto** [comment]
It's not possible right now, but not hard to implement. Definitely a must have.

**Comment by jpetitcolas** [comment]
It is now possible, see [demo](https://github.com/marmelab/ng-admin/blob/master/examples/blog/config.js#L282-L282).

**Comment by ponsfrilus** [comment]
@jpetitcolas thanks !
