### ISSUE TITLE
Demo: deleting post with comments

### ISSUE THREAD

**Issue by jpetitcolas** [marmelab/ng-admin#346]
On [ng-admin.marmelab.com](http://ng-admin.marmelab.com/), if you remove a post having comments, you are not able to see comments list anymore (as it tries to fetch related erased post).

Low priority, as demo database is resetted every 15 minutes.

**Comment by fzaninotto** [comment]
Ah, this is because the json-server doesn't have a ON DELETE CASCADE. This should be fixed on the ng-admin side though: it's possible that a related entity doesn't exist.
