### ISSUE TITLE
Possible bug in reference field sortDir, sortField

### ISSUE THREAD

**Issue by gergelyke** [marmelab/ng-admin#350]
Hey,

just ran into the following issue.

```
  nga.field('country_id', 'reference')
        .label('Country')
        .sortField('title')
        .sortDir('ASC')
        .perPage(100)
        .targetEntity(country)
        .targetField(nga.field('title')),
```

When done this, the actual request sent out is using `sortDir=DESC&sortField=id`. What are we missing? 

Thanks!

cc @ozonid

**Comment by fzaninotto** [comment]
That's a small bug, I just pushed a PR to fix it.
