### ISSUE TITLE
Failing tests on master

### ISSUE THREAD

**Issue by jpetitcolas** [marmelab/ng-admin#358]
Tests are failing on master:

> Running "karma:unit" (karma) task
[...]
PhantomJS 1.9.8 (Linux) ERROR
  SyntaxError: Parse error
  at /home/travis/build/marmelab/ng-admin/src/javascripts/ng-admin/es6/lib/View/ListView.js:36

It seems to occur only on Travis.

**Comment by fzaninotto** [comment]
It's trying to parse an ES6 file...

I've rebuilt the `.min` files, let's see if it fixes the problem.

**Comment by jpetitcolas** [comment]
Tests are still failing. I'm looking at it.

**Comment by fzaninotto** [comment]
Fixed in #361
