### ISSUE TITLE
Force HTTP Method

### ISSUE THREAD

**Issue by paulogr** [marmelab/ng-admin#362]
I know that it's not right but can I force a POST method in the listView type ?

I got a API that only works with POST method and I need to force all requests to POST.

Thanks
Paulo

**Comment by fzaninotto** [comment]
Hi Paulo,

You can't for now - Restangular interceptors allow you to override many aspects of an HTTP request, but not the method. A similar concerned is being addressed in #286, feel free to work on something on your side and send us a pull request if you succeed.

**Comment by paulogr** [comment]
Ok man, thanks.

**Comment by fzaninotto** [comment]
#555 tries to do what you ask
