### ISSUE TITLE
referenced_list is currently broken

### ISSUE THREAD

**Issue by cvlmtg** [marmelab/ng-admin#363]
I think there's one commit from around march 6th onward (more or less) that has broken the referenced_list field, because my code works with an older version of ng-admin but stops working with the latest version.

I've checked more than once my field definition with the examples given in the docs, and I'm pretty sure it is correct, and it facts it works with the version of ng-admin I commited in my project on march 5th. it no longer works with the latest version of ng-admin

there are no error messages, the only thing I see is that ng-admin doesn't even make the xhr to the configured endpoint to ask for the referenced data.

If you need more data feel free to ask :) thanks in advance for the help!

**Comment by fzaninotto** [comment]
Could you paste your configuration? There's been a change in the way we describe `referenced_lists`, explained in https://github.com/marmelab/ng-admin/blob/master/UPGRADE-0.6.md#factories. If you follow these changes (which become compulsory in 0.7, the current development branch), then referenced_lists should work (they do on our apps).

**Comment by cvlmtg** [comment]
hi, I'm really sorry for the delay, but it's been a very busy week...

```coffeescript
users = nga.entity 'users'
users.identifier nga.field 'id'
users.baseApiUrl 'http://...'

usersList = nga.field 'users', 'referenced_list'
usersList.targetReferenceField 'eventCode'
usersList.label 'Utenti iscritti'
usersList.targetEntity users
usersList.targetFields [
  nga.field 'userId'
  nga.field('registeredAt', 'datetime').format 'dd/MM/yyyy HH:mm:ss'
]

event.showView().addField usersList
```

**Comment by fzaninotto** [comment]
It's hard for me to read this code (is it coffeescript), but I don't see any obvious mistake. I know there were some changes in `addField(), so maybe try with `fields([])`.

If this doesn't work, I see two options:

* use `git bisect`to find which commit broke your configuration
* Post a gist with a working example triggering the bug.

**Comment by cvlmtg** [comment]
thanks, I'll try to sort it out :)

**Comment by cvlmtg** [comment]
Hi, I tried the fields() method but nothing has cnahged. I've tried to debug it a bit further. what I can say is that I've defined a full request interceptor and it gets called for the entity, for its "reference" fields, but _not_ for the "referenced_list" fields...

could you please point me to the function that should start the requests for the referenced fields? I tried to place a breakpoint and follow the code, but it seems both chrome and firefox ignore the sourcemaps...

thanks!

**Comment by cvlmtg** [comment]
ok I think I found the culprit. it's a call to app.getEntity() which fails for the referenced_list fields... it doesn't fail for the other entities though.

**Comment by cvlmtg** [comment]
digging a bit furher it seems in previous versions of ng-admin, getEntity() didn't raise an exception when the entity was not found, while it does now. a try/catch solved the problem :)
