### ISSUE TITLE
[list view] use entity identifier field as default sort field

### ISSUE THREAD

**Issue by brikou** [marmelab/ng-admin#366]
`id` is hardcoded but we should use `entity.identifier()` instead.

see https://github.com/marmelab/ng-admin/blob/master/src/javascripts/ng-admin/es6/lib/View/ListView.js#L13

**Comment by brikou** [comment]
Another approach would be to set `_sortField = null` instead (better fix IMO, because doesn't need to know the entity when first rendering)

**Comment by fzaninotto** [comment]
The related code has been moved to admin-config.
