### ISSUE TITLE
Complex object reference

### ISSUE THREAD

**Issue by paulogr** [marmelab/ng-admin#369]
{
   "author": {
    "id": "c082760e-ad97-462f-bff3-4987fdfb6719", 
    "name": "Manoel de Barros"
   }, 
   "id": "2f85f85d-d02e-4a42-acb5-d22a4cf09a55", 
   "text": "bla blah blah"
}

My service returns the JSON above.

How can I add a field with the value of author.name ????

I tried nga.field('author.name') without success :+1: /

thank you

**Comment by fzaninotto** [comment]
Use an element transformer from Restangular (cf https://github.com/marmelab/ng-admin/issues/324#issuecomment-75522399, https://github.com/marmelab/ng-admin/blob/master/doc/API-mapping.md#entry-format)
