### ISSUE TITLE
Unknown provider for dateParser

### ISSUE THREAD

**Issue by ihrigb** [marmelab/ng-admin#371]
I am getting an error on any edit form views:

http://errors.angularjs.org/1.3.15/$injector/unpr?p0=aProvider%20%3C-%20a%20%3C-%20dateParser%20%3C-%20datepickerPopupDirective

Not sure if any dependency or source file is not correctly loaded or built.

**Comment by fzaninotto** [comment]
I think it's the same bug as #373, which is now fixed. Can you test with the latest master build?

**Comment by ihrigb** [comment]
Yep, looks fine!
