### ISSUE TITLE
Remove Column from sorting

### ISSUE THREAD

**Issue by sureshvarman** [marmelab/ng-admin#372]
Is there any options to remove a particular column from sorting

**Comment by fzaninotto** [comment]
Nope, not at the moment. What is your use case?

**Comment by sureshvarman** [comment]
my requirement is simple that i don't want sorting for a column which is a template column

**Comment by fzaninotto** [comment]
One may want to allow sorting by template, since the sort param can be tweaked in a request interceptor... We'll leave it like that.

**Comment by 0xDCA** [comment]
I believe this should be supported. In my case, the backend does not allow to sort by some fields, so trying to click on the column header just shows an error.

It would be cool if we could explicitly disable sorting for some fields

**Comment by thachp** [comment]
I am open to debate on how we can best implement this enhancement.  Though, I think the following adjustments would do. 

@fzaninotto  - Can you commit these changes part of the core codes?  I am dealing with the same problem as @0xDCA.  

In admin-config, field.js

    // https://github.com/marmelab/admin-config/blob/master/lib/Field/Field.js
    add to class field attributes
    this._disableSort = false; // line 9

    // Add a set method and a get method.    

    isDisableSort() {
        return this._disableSort;
    }

    disableSort() {
        this._disableSort = true;
        return this;
    }

Update ng-repeat in grid template in src/javascripts/ng-admin/Crud/list/maDatagrid.js

    <th ng-repeat="field in fields() track by $index"
    ng-class="field.getCssClasses()" class="ng-admin-column-{{ ::field.name() }} ng-admin-type-{{ ::field.type() }}">

        // disable sort
        <a ng-if="field.isDisableSort() == false" ng-click="datagrid.sortCallback(field)">
            <span class="glyphicon {{ datagrid.sortDir === 'DESC' ? 'glyphicon-chevron-down': 'glyphicon-chevron-up' }}" ng-if="datagrid.isSorting(field)"></span>
            {{ field.label() }}
        </a>

        // remove ng-click event and replace a tag with span.    
        <span ng-if="field.isDisableSort() == true">
            {{ field.label() }}
        </span>
    </th>

**Comment by seasick** [comment]
Use-case for me is, that I don't want to sort fields which are references. The displayed values will not appear sorted in most cases, because its sorted by the underlying value and not by the displayed value (e.g. sort messages by user-id, but display user-name from reference).

**Comment by RichardBradley** [comment]
+1 from me -- I have an {{ng-admin}} CRUD table which is backed by an Elasticsearch table: some columns are not sortable, and some are. I'd like to be able to disable sorting on selected fields.

**Comment by RichardBradley** [comment]
I'll create a PR for this. 

As a matter of coding style, why does `ng-admin` require that `Field` declare getters and setters for the `disableSort` property in the separate `admin-config` project? That seems to add a lot of github administration overhead. It also seems to unnecessarily couple the two projects together: the `admin-config` project doesn't need to know anything about field sorting, but in the current pattern it would need to declare this field just to support `ng-admin`.

Would a PR which omitted that change and directly set a `field.disableSort = true` untyped property be acceptable?

**Comment by RichardBradley** [comment]
(If anyone else is waiting for this, you might like to have a go at tidying up my PR at #373 (see comments on that thread for what's outstanding). I'm not sure when I'll be able to get around to it.)

**Comment by mebibou** [comment]
:+1:

**Comment by mosasiru** [comment]
👍

**Comment by allentc** [comment]
+1

This is so obviously necessary it's difficult to understand how it is still dragging on over a year later.

**Comment by RichardBradley** [comment]
> This is so obviously necessary it's difficult to understand how it is still dragging on over a year later.

It's not really that difficult to understand -- the project is open source and free, and the maintainers work on a voluntary basis. 
There is a fix available at PR #984 -- you can build and use that fork if you are in a hurry.
I'm sure the maintainers will merge it in and release a new version in due course.

(While I'm on the subject -- thanks for making `ng-admin`; it's saved me hundreds of hours!)
