### ISSUE TITLE
Introducing a float type?

### ISSUE THREAD

**Issue by jpetitcolas** [marmelab/ng-admin#375]
We often have to customize the `number` type to be able to deal with float numbers, using something similar to:

``` js
nga.field('float_attribute', 'number').attributes({ step: 'any' }).format('0.000');
```
What about offering a `float` type out of the box, including the previous configuration?

**Comment by fzaninotto** [comment]
Great idea, and quite easy to achieve.

**Comment by jpetitcolas** [comment]
PR merged. Closing.
