### ISSUE TITLE
Display boolean field of referenced type in listView or dashboardView

### ISSUE THREAD

**Issue by ihrigb** [marmelab/ng-admin#383]
Is there any posibility to display a boolean field of a referenced type in the listView or dashboardView?

This is the approach I tried, but it didn't work out:

```
entity.listView()
    .fields([
        nga.field('id', 'number').label('ID'),
        nga.field('name', 'string'),
        nga.field('referenced_entity', 'reference')
            .targetEntity(referencedEntity)
            .targetField(nga.field('option', 'boolean'))
    ]);
```

**Comment by fzaninotto** [comment]
No, it's currently not possible for now. A refactoring of the internals of references is necessary to enable it. It's on our todo list.

**Comment by fzaninotto** [comment]
I don't know since when, but now it works fine.
