### ISSUE TITLE
Support embedded form for one-to-one relationships

### ISSUE THREAD

**Issue by jpetitcolas** [marmelab/ng-admin#390]
Considering an API returns the following response:

``` js
// GET /api/posts
[{
    id: 1,
    title: "Cake is a lie!",
    metadata: {
        id: 4,
        source: "GladOS"
    }
}]
```

With a one-to-one relationship between `Post` and `Metadata`. We need to be able to embed a metadata form into the post form, as we have to save them simultaneously.

**Comment by fzaninotto** [comment]
Fixed by #549

**Comment by Phocea** [comment]
Thanks fot the dot notation support.
However how does this apply to embedded one-to.many relationship?

// GET /api/posts
[{
    id: 1,
    title: "Cake is a lie!",
    metadata: [ {
        key: 4,
        value: "GladOS"
    },
  {
        key: 10,
        value: "HopeOS"
    }],
}]

**Comment by fzaninotto** [comment]
Nope, not for now. But if you're looking for an element at a fixed position in a sub-array, I think an [ElementTransformer](https://github.com/marmelab/ng-admin/blob/master/doc/API-mapping.md#entry-format) is the way to go.

**Comment by Phocea** [comment]
Ok, thanks for the reply.
What I need is to display all the key/value of an entity, exactly as if it was an external 1-n relationship. Also need to be able to edit a value, or add a key/value.
I will look into this....

**Comment by fzaninotto** [comment]
So this is somehow related to #241
