### ISSUE TITLE
Restangular setRequestSuffix doesn't work

### ISSUE THREAD

**Issue by fbrinkworth** [marmelab/ng-admin#392]
Hi, 

I tried implement the blog demo on Firebase, then I need put ".json" suffix in all api call, then I added this line

```javascript
RestangularProvider.setRequestSuffix('.json');
```
before 

```javascript
// use the custom query parameters function to format the API request correctly
        RestangularProvider.addFullRequestInterceptor(function(element, operation, what, url, headers, params) {
            if (operation == "getList") {
                // custom pagination params
                if (params._page) {
                    params._start = (params._page - 1) * params._perPage;
                    params._end = params._page * params._perPage;
                }
                delete params._page;
                delete params._perPage;
                // custom sort params
                if (params._sortField) {
                    params._sort = params._sortField;
                    delete params._sortField;
                }
                // custom filters
                if (params._filters) {
                    for (var filter in params._filters) {
                        params[filter] = params._filters[filter];
                    }
                    delete params._filters;
                }
            }
            return { params: params };
        });
```
And obviulsly I have changed the API url to firebase in

```javascript
        var admin = nga.application('ng-admin backend demo') // application main title
            .baseApiUrl('https://<my-firebase>.firebaseio.com/'); // main API endpoint
```

But when I tace the request, the url doesn't have ".json" suffix.

What I doing wrong?

Thanks!

(sorry for my english)

**Comment by fzaninotto** [comment]
I can reproduce the bug on my side. Looks like a Restangular issue. Would you like to open an issue in their bugtracker?

**Comment by fzaninotto** [comment]
Although, looking at the Restangular source, it seems that it ignores the `suffix` when using `allUrl` instead of `one`, which is what ng-admin does. I don't know why the suffix feature is limited that way by Restangular, but that means that Restangular won't let you add a suffix in ng-admin.

**Comment by netconsult** [comment]
Thanks @fzaninotto !

Sorry for my delay, but I thought that github will send a notification about activity on this issue. I saw your response just today.

I tried your suggestion, and this had worked with a minimal modification:

```javascript
        var post = nga.entity('posts').url(function(view, entityId) {
            var url = fireRootUrl + '/posts.json';
            if (entityId) {
                url = fireRootUrl + '/posts/' + entityId + '.json';
            }
            return url;
        });
```

Where fireRootUrl is a root of my firebase.

I want to tell you too that you have made a great job with ng-admin.

Thanks!

**Comment by fbrinkworth** [comment]
I'm sorry, I wrote the last post with another account.

**Comment by fzaninotto** [comment]
Thanks for your feedback!

**Comment by vivaladan** [comment]
I'm actually still finding this to be a problem myself. 

For the work around, entityId is coming through as 'ListView', which results in the URL /posts/ListView.json

I could conditionally exclude ListView but it makes me wonder what else might have changed.

Was a bug logged with Restangular in the end?

**Comment by sporkd** [comment]
@vivaladan Seems url function now as different argument list. See https://github.com/marmelab/ng-admin/blob/4298be81cd16406701ebd9e838e3d4b9e2537cd5/UPGRADE-0.8.md.
