### ISSUE TITLE
Menus not working off of bower install

### ISSUE THREAD

**Issue by mikeblakeney** [marmelab/ng-admin#402]
I've done a bower install and it looks like bower is pulling version 0.6, which I don't think includes the custom menu options that are described in the README.  I tried changing my bower.json to pull ~0.7.0 ,but bower responds saying that it can't find the matching tag...  any suggestions?

**Comment by fzaninotto** [comment]
Menus will be in 0.7, not yet released. In the meantime, use the master tag!

**Comment by mikeblakeney** [comment]
ok, that's what I thought, just wanted to make sure I wasn't missing anything.  Thanks!
