### ISSUE TITLE
app.header() not defined

### ISSUE THREAD

**Issue by alessioEdudoc** [marmelab/ng-admin#406]
I'm trying to override the header, but the header function is not defined in the application object.

```javascript
var customHeaderTemplate =
'<div class="navbar-header">' +
    '<a class="navbar-brand" href="#" ng-click="appController.displayHome()">' +
        My Custom Title
    '</a>' +
'</div>' +
'<p class="navbar-text navbar-right">' +
    '<a href="https://github.com/marmelab/ng-admin/blob/master/examples/blog/config.js">' +
        '<span class="glyphicon glyphicon-sunglasses"></span>&nbsp;View Source' +
    '</a>' +
'</p>';
var app = nga.application('My Application');
app.header(customHeaderTemplate);
```

doesn't work

**Comment by fzaninotto** [comment]
@ThieryMichel I think the built files weren't updated since the PR got merged. Could you push an update to master?

**Comment by jeromemacias** [comment]
Built files have just been updated, `app.header` should be available.

**Comment by alessioEdudoc** [comment]
I'm sorry, the problem persists. There's no header method in the
application object.

On Mon, Apr 27, 2015 at 9:57 AM, Jérôme Macias <notifications@github.com>
wrote:

> Built files have just been updated, app.header should be available.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marmelab/ng-admin/issues/406#issuecomment-96573448>.
>



-- 
<https://mail.google.com/mail/u/0/#inbox>Alessio Scalici | Edudoc LTD
alessio@edudoc.ie

**Comment by jeromemacias** [comment]
Do you use the ng-admin master ?

**Comment by alessioEdudoc** [comment]
I have installed it through bower, I guess I'm using that...

On Mon, Apr 27, 2015 at 2:01 PM, Jérôme Macias <notifications@github.com>
wrote:

> Do you use the ng-admin master ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/marmelab/ng-admin/issues/406#issuecomment-96642216>.
>



-- 
<https://mail.google.com/mail/u/0/#inbox>Alessio Scalici | Edudoc LTD
alessio@edudoc.ie

**Comment by jpetitcolas** [comment]
Bower installs the last stable version by default, ie the `v0.6.0` version for now. You can check it looking into your `bower.json` file:

``` js
{
  "dependencies": {
    "ng-admin": "~0.6.0"
  }
}
```
If you want to use master, you should replace previous configuration by:

``` js
{
  "dependencies": {
    "ng-admin": "master"
  }
}
```
Master version may have some bugs into it. Use it with caution! :)

@fzaninotto, it is a long time since the last version update. Perhaps could we tag a new `0.7.0` release including last features (CSV export, batch selection, and so on)?

**Comment by jpetitcolas** [comment]
No feedback. Closing the issue. Feel free to re-open it if you still encounter the issue.
