### ISSUE TITLE
IE 11 failed to instantiate module

### ISSUE THREAD

**Issue by triplebeta** [marmelab/ng-admin#408]
Hi,

I recently installed the ng-admin demo as one of my first node.js projects and ít works well on Chrome version 42 and Firefox version 31. However, when I use Internet Explorer 11, I get an error:

JavaScript runtime error: [$injector:modulerr] Failed to instantiate module myApp due to:
TypeError: Object doesn't support property or method 'order'
   at addField.value (http://localhost:3000/bower_components/ng-admin/build/ng-admin.min.js:26:18714)

Because of this, the ng-admin UI does not appear at all.

Sincerely,
Jeroen

**Comment by fzaninotto** [comment]
On my test, the UI appears, but navigating away from the dashboard fails with the following error:

> State Change Error: 'Promise' is undefined

![image](https://cloud.githubusercontent.com/assets/99944/7985593/01af82cc-0ad2-11e5-9d92-65a41c461b7e.png)

@jpetitcolas are we missing a shim?

**Comment by jpetitcolas** [comment]
Indeed, we need a Promise shim: https://github.com/github/fetch/issues/114

Will look at it later today.
