### ISSUE TITLE
Nested REST APIs

### ISSUE THREAD

**Issue by spfjr** [marmelab/ng-admin#409]
Hey guys,

I really like your project. I see from the documentation and from testing out the project that it works great for top-level entities. However, I haven't been able to figure out a way to get it working with nested entities. Is it possible to access a REST entity with a path of /firstEntity/<firstEntityId>/secondEntity/<secondEntityId>?

Thanks!

**Comment by fzaninotto** [comment]
Hi spfjr,

We're relying on Restangular for that, and I'm not sure it allows to modify the URLs as you wish. I've found a related issue (https://github.com/mgonto/restangular/issues/310), let me know if it works for you.

**Comment by spfjr** [comment]
Francois,

I actually saw that Restangular issue. Unfortunately, like the creator of that ticket, I don't think that would work for my needs. I already tried to modify the path in a fullRequestInterceptor() function, but I figured I would see if there was some other possible configuration before deciding whether or not I wanted to refactor my REST API.

Thank you for the quick response!

**Comment by sebest** [comment]
You don't plan on adding this feature?

**Comment by fzaninotto** [comment]
If we need it for our own projects, we will. In the meantime, you're welcome to try and implement it, and submit a PR for it.

**Comment by sebest** [comment]
My angular/js skill is really low, that's also why this project was really appealing until i hit this wall.

**Comment by fzaninotto** [comment]
The solution is described in #711
