### ISSUE TITLE
datetime field error

### ISSUE THREAD

**Issue by mickadoua** [marmelab/ng-admin#411]
Hey guys,
I have a error when I try to use datetime option,
My code
discount.creationView()
    .fields([
        new Field('name')
            .attributes({ placeholder: 'the title' })
            .validation({ required: true, minlength: 3, maxlength: 100 }),
        new Field('description'), 
        nga.field('timeStart', 'datetime'),…
    ]);

And the error 
Uncaught Error: [$injector:modulerr] Failed to instantiate module starter due to:
Error: Unkown field type "datetime"
Thanks !

**Comment by fzaninotto** [comment]
Are you using the master branch?

**Comment by mickadoua** [comment]
with 0.7.0 version,  my problem is resolve
but, I would like to have a datepicker with hour and minutes 
with date and datetime, I have the same result.

**Comment by fzaninotto** [comment]
The datepicker allows to edit hours and minutes in the field. We looked for an alternative, but couldn't find a good datetimepicker with support for our version of angular.js.

If you feel like giving a try at implementing your own, now that ng-admin accepts custom fields, don't hesitate!

**Comment by Gijs-Koot** [comment]
@fzaninotto, you mentioned "The datepicker allows to edit hours and minutes in the field.". However, if I actually want to do this, I have to add a 'T' myself in the middle, otherwise it doesn't work. Is that correct? Thx!

**Comment by fzaninotto** [comment]
the DateTime filed expects a valid JavaScript date, so yes I suppose is implies a timezone.

**Comment by srinivaskommu** [comment]
@fzaninotto @Gijs-Koot 
Can you please post some code sniffet for parsing "2016-01-18 11:13:31 GMT" date format??
