### ISSUE TITLE
Using Loopback standard filters for pagination

### ISSUE THREAD

**Issue by philippdhh** [marmelab/ng-admin#414]
Hello,

I am trying to connect my ng-admin instance to a RESTful API powered by loopback.io framwork.
The basic operations work out of the box (listing, edit, show, delete) which is really great.

When it comes to pagination of the listing ng-admin seems to use the query parameters ?_perPage=x and &_page=y by default. Unfortunately loopback supports this by filters which are used like ?filter[limit]=x and &filter[offset]=y

A GET URL would look like http://localhost:3000/api/questions/?filter[limit]=5&filter[offset]=2

I found this code snippet which should be used to customize attribute names in ng-admin avoiding a customization of the api itself:

``` js
app.config(function(RestangularProvider) {
    RestangularProvider.addFullRequestInterceptor(function(element, operation, what, url, headers, params, httpConfig) {
      if (operation == 'getList' && what == 'entityName') {
        params.offset = (params._page - 1) * params._perPage;
        params.end = params._perPage;
        delete params._page;
        delete params._perPage;
      }
      return { params: params };
    });
  });
```

I think it would be possible to build an URL like http://localhost:3000/api/questions/?limit=5&offset=2 but nothing like http://localhost:3000/api/questions/?filter[limit]=5&filter[offset]=2 with this solution.

Is there already a clean approach to adopt ng-admin to the loopback pagination pattern?

Maybe there is a very simple solution which I don't see at the moment as I am just diving into the Javascript world.

Thank you in advance
Philipp

**Comment by sgimeno** [comment]
I faced the same problem when trying to connect ng-admin with a SailsJS powered API which uses `limit` and `skip` keywords for pagination. Bounding the param names to a concrete backend framework sounds like a bad idea... I'd say a solution could be to make this configuration available from `NgAdminConfigurationProvider` and provide some default fallback param names?

**Comment by jpetitcolas** [comment]
@sgimeno, you can already customize how your URL should look like, using [request interceptors](https://github.com/marmelab/ng-admin/blob/master/examples/blog/config.js#L18-L42). Here is an example to respond to @philippdhh question (sorry for the delay btw):

``` js
RestangularProvider.addFullRequestInterceptor(function(element, operation, what, url, headers, params) {
    if (operation == "getList") {
        // add new parameters
        params['filter[limit]'] = params._perPage;
        params['filter[offset]'] = params._page;

        // remove old obsolete ones
        delete params._perPage;
        delete params._page;
    }

    return { params: params };
});
```
