### ISSUE TITLE
date bug

### ISSUE THREAD

**Issue by effyroth** [marmelab/ng-admin#420]
create_time is timestamp

nga.field('create_time', 'datetime') will always parse to 1970-01-17 without

.map(function (value, entry) {
                return new Date(value*1000);
            })
is it my timestamp format problem?

btw, datetime default format('yyyy-MM-dd HH:mm:ss') looks like not work

**Comment by manuquentin** [comment]
Hello,
Can you give us the value of `create_time` returned by your API ?

Thanks

**Comment by effyroth** [comment]
like this 
create_time: 1431460602

so I must transform time unit from second to ms?

**Comment by fzaninotto** [comment]
Yep, JavaScript understands timestamps with milliseconds. If you rely on another format, you'll have to map a transformer, like you did. Note that you can make it reusable, like so:

```js
function transformToJsTimestamp(ts) {
  return ts * 1000;
}
// later
nga.field('create_time', 'datetime').map(transformToJsTimestamp)
```

As for the default datetime format, what you you mean "it doesn't work"?

**Comment by effyroth** [comment]
the doc say:

datetime Field Settings

format(string ['yyyy-MM-dd HH:mm:ss' by default])

but it will show yyyy-MM-dd without  format('yyyy-MM-dd HH:mm:ss')

**Comment by fzaninotto** [comment]
Located the bug, PR in progress.
