### ISSUE TITLE
"NgAdminProvider" instead of "nga" ?

### ISSUE THREAD

**Issue by Crackboom** [marmelab/ng-admin#421]
Hi,
I'm pretty new in nodejs in general, and ng-admin in particular, so I apologize in advance in case of mistake.

README.md (line 65): does "NgAdminProvider.configure(app);" should be "nga.configure(app);" instead ?

Thanks.

**Comment by jpetitcolas** [comment]
You're right, it should either be `nga` or `NgAdminConfigurationProvider`, that's the same. Fixing it.
