### ISSUE TITLE
Dashboard list links lead to "Page Not Found"

### ISSUE THREAD

**Issue by stephenkubovic** [marmelab/ng-admin#423]
Clicking an entity list link in the dashboard results in a "Page Not Found".  This looks to be due to a trailing slash in the `goToList()` function within the `maDashboardPanel` directive.  Click "Recent posts", "Last comments", or "Recent tags" in the [demo app](http://ng-admin.marmelab.com/#) to observe this behaviour.

Relevant code:

https://github.com/marmelab/ng-admin/blob/master/src/javascripts/ng-admin/Main/component/directive/maDashboardPanel.js#L21

```javascript
scope.gotoList = function () {
    $location.path(scope.entity().name() + '/list/');
};
```

**Comment by dekhaus** [comment]
I have version 0.7.0 of ng-admin and I'm still experiencing this bug - aka the trailing '/'.   How do I get the fix/patch ?

Thanks
Dave

**Comment by fzaninotto** [comment]
You need to use the master branch, we haven't released a new version for it.

**Comment by dekhaus** [comment]
Hi

I just upgraded to the latest 'master' version and the above links issue is fixed.  Thanks.

I do have an additional question .... in the prior release, if I didn't explicitly configure a Dashboard page - I got a page with a link for every managed resource.  Using the current release - how can I replicate this feature of the previous release ?

Thanks
Dave

**Comment by fzaninotto** [comment]
@dekhaus I'm in the process of revamping the dashboard API. You'll have a populated dashboard by default, with the ability to customize everything (resizing panels, adding your owns, etc). Watch the pull request notifications for updates.

**Comment by dekhaus** [comment]
Thanks
