### ISSUE TITLE
Unmodified date fields missing from PUT payload

### ISSUE THREAD

**Issue by jseppi** [marmelab/ng-admin#432]
In the editionView for an entity, if any 'date'-type fields are not modified they will be missing from the PUT payload. (ie, they are completely not present in the payload object).

**Comment by manuquentin** [comment]
Hello,

I can't your issue on the admin demo : http://ng-admin.marmelab.com/#/posts/edit/12
The value of `published_at` is sent even if I don't change the value.

What is the version of your ng-admin ?

**Comment by jseppi** [comment]
`0.7.0`

Strange, it does appear to work fine on the admin demo.

Here are some screenshots of my app:

Relevant section of the Edit form, with field `Date`:
![Field 'Date' unmodified](https://cloud.githubusercontent.com/assets/697848/7654431/9d8195be-fae2-11e4-8df3-ac49580a24e2.png)

And here's the PUT payload, with `Date` missing:
!['Date' missing from payload](https://cloud.githubusercontent.com/assets/697848/7654436/ac15186c-fae2-11e4-8601-d34f6d58f58b.png)

Here's my field definition:

```js
nga.field('Date', 'date')
      .validation({required: true})
```

**Comment by JoseMiguel** [comment]
I'm experiencing the same issue, but instead I'm trying to PUT dates empty.

**Comment by mkozlov1** [comment]
+1

**Comment by nschirmer** [comment]
A year later, I am experiencing the same issue.

I open up a fresh edit page where a date value already exists, hit save, and the input is missing entirely from the PUT data unless I modify the date.

**Comment by laptevn** [comment]
The same issue with version 0.9.1.

**Comment by laptevn** [comment]
Admin demo also has this issue -  http://ng-admin.marmelab.com/#/posts/edit/12 and  http://ng-admin.marmelab.com/#/posts/edit/16
But backend works fine with date missing.
It really looks like an intentional "feature".

**Comment by Kmaschta** [comment]
I can't reproduce the bug.
Feel free to reopen the issue if you face it again with the master version.
