### ISSUE TITLE
Creating custom field

### ISSUE THREAD

**Issue by avifatal** [marmelab/ng-admin#436]
Hi,
I just built amazingly fast an app with this tool.
But I cant seem to create new field, based on this: https://github.com/marmelab/ng-admin/blob/master/doc/Custom-types.md nothing happend, and I can understand why...
var DateFieldView = {.....
who knows about DateFieldView ..... 

Can you please explaing or give a link to an example that actually works?

Thanks

**Comment by fzaninotto** [comment]
Did you register your new field view?

**Comment by avifatal** [comment]
Yes I did, Do you provide paid support? waiting for an answer takes too long for me.
Can you offer anything like that?
Thanks

**Comment by fzaninotto** [comment]
@avifatal please contact me by Skype (francois.zaninotto) so that we sort this problem out together.

**Comment by manuelnaranjo** [comment]
Would you mind providing an example for this? require is a feature not available on the browser, making it hard to achieve
