### ISSUE TITLE
Getting ` Duplicates in a repeater are not allowed `

### ISSUE THREAD

**Issue by poolebu** [marmelab/ng-admin#443]
Hello, 

First of all, this is a great project and I'm grateful you made it, here is my issue

We use a Java / Spring MVC backend with Jackson.

Because we use a complex domain model, we use `JsonIdentityInfo` to generate the @Id field to handle circular  references, but this fields are not the real id's, eg:

``` json
"@Id":"9af72173-1496-40be-b66a-d6102784b96b",
      "appListId":1,
      "appListDomain":"eurogroup.bambusoluciones.com",
      "appListApplicationSettings":{  
         "appListId":1,
         "appList":"9af72173-1496-40be-b66a-d6102784b96b",
.
.
.
```

note that `"@Id":"9af72173-1496-40be-b66a-d6102784b96b"` =` "appList":"9af72173-1496-40be-b66a-d6102784b96b",`

And we are getting this error when the request is received by the application

```
Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys
```

I was wondering, if there is a way to avoid the error, we don't need this deep reverse reference in the admin application, and we don't need to use the admin for all of our entities, can you think of a work around for this ? maybe avoid loading some fields ? or telling the application to use another field as id ?

Thank you very much, I hope we can use this great tool you made.

**Comment by fzaninotto** [comment]
Hi poolebu, and thanks for your feedback!

Would you know where approximately the error is thrown, in the minified code (an extract would be great), and in the app (the list view? the dashboard? the edition view?).

**Comment by perezb** [comment]
Hello, 

I have the same error thrown on the dashboard and the list view. I'm using the master version.
I'm trying to parse a json that looks like this:

```
"result":{
     "categories":[
          {
          },
          {

}
```

**Comment by perezb** [comment]
Hello,

I have the same error thrown on both the dashboard and the list view. I'm using the master version.
I'm trying to parse a json that looks like this:

```
{
  "result":{
    "categories":[
      {
        "key":"...",
        "label":"...",
        "feeds":[
          "..."
        ]
      },
      {
        "key":"...",
        "label":"...",
        "feeds":[
          "...",
          "..."
        ]
      },
      {        
        "key":"...",
        "label":"...",
        "feeds":[
          "...",
          "..."
        ]
      }
    ]
  }
}
```

I'm rather new to angularjs and ng-admin so I'm probably missing something.

Thanks for your work!

**Comment by fzaninotto** [comment]
@perezb which field did you declare as the identifier of your `categories` entity?

**Comment by perezb** [comment]
@fzaninotto The ```key``` field is my identifier.

**Comment by fzaninotto** [comment]
Weird. The datagrid component, used in the list view, already uses the identifier:

```
<tr ng-repeat="entry in entries track by entry.identifierValue">
```

The warning you get means that the JSON response may contain several entries with the same `key` value. Can you please check that?

**Comment by perezb** [comment]
My bad, your previous answer made me realise that I declared the identifier wrongfully. It now works. Thank you very much!
