### ISSUE TITLE
Consider using a named ui-view

### ISSUE THREAD

**Issue by sgimeno** [marmelab/ng-admin#446]
First of all props to all maintainers for the great job on this angular module. I'm already using it in a couple of projects.

When writing a simple Angular web app to display ng-admin views as a "backoffice" for some data source I can't build other angular-ui-router `ui-view`'s because ng-admin needs an unamed `ui-view`. Wouldn't be nice to be able to embed ng-admin views in a separated and named `ui-view`? Is there any other approaches I'm missing or is this out of the scope of the project?

So far I also found this article which encourages to use named `ui-view`'s:
http://www.toptal.com/angular-js/top-18-most-common-angularjs-developer-mistakes#common-mistake-5-not-using-named-views-with-ui-router-for-power

**Comment by fzaninotto** [comment]
Hi Sergio, and thanks for your feedback.

Yes, we are aware of this issue, and using a not-main view is indeed the solution. The only problem is that it would break existing applications.

I guess the best way (and the only BC way) would be to add a second parameter to the `configure()` call, specifying the named view to use (and it would be `main` by default). 

@jpetitcolas any feedback on this?

**Comment by fzaninotto** [comment]
Related to #335

**Comment by jpetitcolas** [comment]
Passed parameter is already called `config`. I think we can simply add a new attribute `uiViewName` to this object, like we added the [debug](https://github.com/marmelab/ng-admin/blob/master/examples/blog/config.js#L44-L46) one recently.

Moreover, isn't the name `main` too generic? I would name it `nga-main` to prevent from collisions.

**Comment by fzaninotto** [comment]
The `main` state replaces the default (nameless) ui-view. It's required for BC. 

I'm +1 with your suggestion to add a parameter to the `config` object.

**Comment by sgimeno** [comment]
+1

**Comment by amejias101** [comment]
+1

**Comment by Siafu** [comment]
So what's the work around ? My app is currently configured as follows. 
app.js
![image](https://cloud.githubusercontent.com/assets/632024/9538673/f4de84b4-4d14-11e5-978c-310f36d0d15f.png)

admin.module
![image](https://cloud.githubusercontent.com/assets/632024/9538687/0f127cc8-4d15-11e5-9072-7845ef388ee7.png)

admin.route
![image](https://cloud.githubusercontent.com/assets/632024/9538691/1be1690a-4d15-11e5-8346-4bedd9abb8dc.png)

admin html
![image](https://cloud.githubusercontent.com/assets/632024/9538695/2c628b60-4d15-11e5-8b23-df428c639687.png)

**Comment by fzaninotto** [comment]
No workaround for now, I think.

**Comment by ruben0909** [comment]
+1

**Comment by giovanni-duarte** [comment]
+1

**Comment by JunkMyFunk** [comment]
+100

**Comment by jpetitcolas** [comment]
It should be solved with last master version, which breaks backward compatibility to use a named view. You now have to name your admin div as:

```<div ui-view="ng-admin">```
