### ISSUE TITLE
Entity without listView still shows list buttons

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/ng-admin#447]
Use case: I define an entity with only a showView, accessible from a related entity (e.g. comments, accessible only from the commented post). On purpose, I decide to not define a listView. 

The problem is that the showView still contains a "List" action button, leading to an empty list.

This is a use case we must support.

**Comment by manuquentin** [comment]
Views in ng-admin are [enabled by default](https://github.com/marmelab/ng-admin/blob/a312bdc3a1d2505dc403449c36597a8e1f78099f/src/javascripts/ng-admin/es6/lib/View/View.js#L11).

You have to disable them manually.

We can disable them by default & enable them when using customization methods like `fields()`,  `title()`.
But if someone doesn't customize the deletionView for instance, the view won't be enabled.
