### ISSUE TITLE
Bug Report: Map will not work if its coming after other function like label

### ISSUE THREAD

**Issue by avifatal** [marmelab/ng-admin#452]
this will work:  nga.field('TestDefault', 'json').map(......
this will not work  nga.field('TestDefault', 'json').label("bla bgla").map(....

**Comment by fzaninotto** [comment]
I can't reproduce the problem. `map()` works fine when called first, and when called after `label()`. Could you tell me which browser you're using?

**Comment by fzaninotto** [comment]
No feedback, closing.
