### ISSUE TITLE
Bug Report: Map function will not work on new entries

### ISSUE THREAD

**Issue by avifatal** [marmelab/ng-admin#453]
If you create a new entry, and you want to set a value if the user left it empty, you cannot do it because map will only work on not null values.

**Comment by fzaninotto** [comment]
I can't reproduce this error. Here is my test `map` function:

```js
nga.field('test').map(function(value) {
  if (!value) return 123; // default value
  return value;
});
```

This field definition in a creation view properly sets the default value to 123 when not set.

Also, note that the advised way to set a default value is to use:

```js
nga.field('test').defaultValue(123);
```

Feel free to reopen if I'm missing something.
