### ISSUE TITLE
Multiple servers for multiple endpoints

### ISSUE THREAD

**Issue by dekhaus** [marmelab/ng-admin#462]
Hi

I'm trying to modify the ng-admin-demo code and add an additional endpoint ('recipes') that 'points' to a local server.  I'm trying to determine if its possible to have ng-admin manager endpoints from different servers.  For example the endpoints 'products' & 'categories' could be managed by ServerA (http://prodcategories.com:8080) and 'widgets' by ServerB (http://widgetsrus.com:9000).

Is this possible ?

I've got the ng-admin-demo working locally and tried adding a local endpoint.  Ng-admin runs and renders - but its not adding my local endpoint.

Thanks
Dave

**Comment by jpetitcolas** [comment]
Yes, you can already do that using `baseURL` method of entities. For instance, in your case:

``` js
var recipes = nga.entity('recipes').baseURL('http://local.server.com');
var products = nga.entity('products').baseURL('http://prodcategories.com:8080');
```

**Comment by dekhaus** [comment]
Hi

I tried doing that and while the page renders (see attachment) my 'recipes' don't appear in the dashboard.  Here's a link to a pastie (http://pastie.org/10204063) with the modified ng-admin-demo code (only app.js).

Thanks
Dave


![screen shot 2015-05-23 at 12 30 17 pm](https://cloud.githubusercontent.com/assets/7830/7785516/aa0b7082-0147-11e5-8ab8-a4d6b2ca7f28.png)

**Comment by jpetitcolas** [comment]
Have you any error message in the console?

I think I've succeeded in reproducing the issue. It seems there is some outdated doc. Can you try using `baseApiUrl` instead of `baseURL`?

**Comment by dekhaus** [comment]
Hi

    I noticed the outdated api call - specifically that baseURL should be replaced by baseApiUrl before posting my original question.  In fact you can see my use of the correct baseApiUrl call in the pastie ( http://pastie.org/10204063 ).

    I've confirmed that there are no console errors.  

    I've also confirmed by reviewing the logs and the network stats in the Chrome console that my 'external' recipes endpoint is being accessed.  In short - I know the data from the additional endpoint is being requested and is being received.  

    The issue is that the 'Recipes' link isn't being listed in the ng-admin Dashboard.

    I think this tool is awesome and has lots of potential.  I really appreciate any help you can provide in resolving this important issue.

Thanks
Dave

**Comment by jpetitcolas** [comment]
So it is just a menu issue? Looking at your pastie more precisely, you redefine menu (at line 271):

``` js
        admin.menu(nga.menu()
            .addChild(nga.menu(post).icon('<span class="glyphicon glyphicon-file"></span>')) // customize the entity menu icon
            .addChild(nga.menu(comment).icon('<strong style="font-size:1.3em;line-height:1em">✉</strong>')) // you can even use utf-8 symbols!
            .addChild(nga.menu(tag).icon('<span class="glyphicon glyphicon-tags"></span>'))
            .addChild(nga.menu().title('Other')
                .addChild(nga.menu().title('Stats').icon('').link('/stats'))
            )
        );
```

You override the menu, so it won't display all entities by default, but only those you specified explicitly. Adding a child with `nga.menu(recipe)` should solve your issue.

**Comment by dekhaus** [comment]
Now I'm embarrassed.  Thanks for the your help.  Really looking forward to using ng-admin.

**Comment by jpetitcolas** [comment]
No problem. Do not hesitate if you have other issues. We're always glad to help! :)
