### ISSUE TITLE
Provide additional data on file upload

### ISSUE THREAD

**Issue by DmitryPogodaev** [marmelab/ng-admin#463]
Hello!
```javascript
pack.editionView().
...
  nga.field('new_cards', 'file').uploadInformation({ 'url': 'admin/upload/', 'multiple': true, 'data': {'packId': ???}}) 
```
I'm trying to send entity id on file upload. How i can do it?

**Comment by DmitryPogodaev** [comment]
Question is: how to set entity._id in options declaration

**Comment by DmitryPogodaev** [comment]
In https://github.com/danialfarid/ng-file-upload#upload-service
it's done like this 
```javascript
fields: {key: $scope.myValue, ...},
```
But in NGA $scope is not defined yet

**Comment by fzaninotto** [comment]
ping @jeromemacias

**Comment by DmitryPogodaev** [comment]
Hi all. Actually, a made uploading in different way, so i don't need this feature.
