### ISSUE TITLE
Export to .csv Firefox & Safari

### ISSUE THREAD

**Issue by F3L1X79** [marmelab/ng-admin#464]
Hello to everyone,
Thanks a lot for this wonderful soft - it is pretty awesome in all ways.
I actually use the master-branch of ng-admin and noticed that the export button on listView is only working on google Chrome - not on Firefox & Safari (I also don't get any errors on clicking, so I was wondering if this is really a bug or just me...).
Thanks again for all the hard work you did on ng-admin.
Regards,
Felix.

**Comment by JoseRoman** [comment]
![image](https://cloud.githubusercontent.com/assets/4240075/7803167/ad317b8c-0316-11e5-8227-5e38edf94989.png)

Export button is not working for me either on Chrome (42.0.2311.152 m)

**Comment by F3L1X79** [comment]
To be more specific, this is what happening to me in the console after clicking the export Button on the listView - using the three browsers on MacOs Yosemite:

![after clicking export button](https://cloud.githubusercontent.com/assets/9592639/7807679/c349e02c-038d-11e5-8b82-e604a16a2b1e.png)

I am using the latest branch of ng-admin.
Chrome is saving a .csv with entity name (it's all good); Safari is displaying an error; Firefox launches a GET Request with no error but isn't dowloading any .csv.
Hope this helps.

**Comment by manuquentin** [comment]
Hello guys,
Thanks for your report.

I've fixed a download issue with the export button.
Can you try with the new version of the master branch ?

Regards

**Comment by F3L1X79** [comment]
Brilliant,
works fine on Firefox now.
(But i guess you removed the standalone version of ng-admin).

For your information, on Safari, it is not really downloading the .csv, but it's displaying its content directly in the browser.

Indeed, thanks a lot!

**Comment by Xennis** [comment]
(The standalone version was just renamed in 1fce094fd1a27a18d1efe814e98771134cbb9cd6)

**Comment by jpetitcolas** [comment]
In fact, we just changed naming. Standalone version is now in `ng-admin.min.js` file, and the light one is in `ng-admin-only.min.js`. It was renamed for backward compatibility issues.
