### ISSUE TITLE
Not all related entries appear in select control

### ISSUE THREAD

**Issue by PaulMaly** [marmelab/ng-admin#470]
Hello guy! Thanks for this awesome tool!

I've some interesting question. I use select controls in filters and on item creation page. This selects give me ability to set relation between to entries. 

For example, I want to set target Post when I'm creating a Comment. But when I had many Posts entries, I learned that not all of them is appear in select control. So now I can't assign Comments to some Posts. And this is very big problem.

I checked Ajax request which gets Post for this control and learned that this request have the same pagination params as requests to getting List View items. I believe it's not a good idea, becouse there is not way to get pagination in select control.

I don't know is this a bug or design intent, but I will be very appreciated if you give me some workaround for this. Thanks a lot!

**Comment by fzaninotto** [comment]
Hi Paul,

This is indeed a feature. REST APIs usually apply a default pagination, to avoid sending too large responses. The `reference` field type has a default pagination, too (30 items), that you can override with the `perPage()`parameter, as follows:

```js
nga.field('post_id', 'reference')
                .label('Post')
                .targetEntity(nga.entity('posts'))
                .targetField(nga.field('name'))
                .perPage(50)
```

Hope this helps.
