### ISSUE TITLE
Customizing individual HTTP requests or HTTP Header

### ISSUE THREAD

**Issue by dekhaus** [marmelab/ng-admin#472]
Hi

My ng-admin is communicating with several Ruby on Rails backends.  Most of my Rails endpoints function the 'Rails' way and add a 'root' to 'index' responses.  For example - if a request is made of an api/inventories endpoint - the current response looks like this ...

``` json
{
  "inventories": [
    {
      "id": 1,
      "name": "Other",
      "location": "Inventory Lab",
      "latest_schema": null
    }
  ]
}
```

Ng-admin doesn't like this as it expects the above response to just be a json array.

My challenge is that ng-admin is not the only client of my endpoints - so I'd like to either configure ng-admin to include a query parameter with each request indicating 'root=false' or better yet - include some custom http header value indicating that this is request from ng-admin and that no 'root' key should be included in the response.  

Is this possible ?

Thanks
Dave

**Comment by dekhaus** [comment]
I think I have an answer to my own question - specifically use Restangular (https://github.com/mgonto/restangular).  Correct ?

**Comment by dekhaus** [comment]
Restangular is definitely the way to go - but I'm having trouble configuring it correctly.

The ng-admin-demo code works (which uses Restangular) - but when I modified my ooffeescript to use Restangular it breaks on the first attempt to access the RestangularProvider object.

I've posted the abridged versions of both the working ng-admin-demo code and my code in the same pastie.  I'm sure this is a configuration issue and given my relative inexperience with AngularJS - I need some help.  Here's the pastie -> http://pastie.org/10211094#17

Thanks
Dave

**Comment by jpetitcolas** [comment]
Correct: if you want to fetch the `inventories` item from your response, you need a Restangular response interceptor, something like:

``` js
RestangularProvider.addResponseInterceptor(function(data, operation, what) {
    if(operation === 'getList' && what === 'inventories') {
        return data.inventories;
    }

    return data;
});
```
You can then apply it on specific API, using the `what` parameter.

**Comment by jpetitcolas** [comment]
For your other issue, I'm not familiar with CoffeeScript. Can you try the following code?

``` coffeescript
@app.config([
    'RestangularProvider',
    (RestangularProvider) -> console.log RestangularProvider
])
```

Moreover, you should [use $stateProvider instead of $routeProvider](http://stackoverflow.com/questions/27645202/what-is-the-difference-between-routeprovider-and-stateprovider-in-angularjs), switching your code to something like:

``` coffeescript
@app.config(['$stateProvider', function($stateProvider) {
    $stateProvider.state('home', {
        url: '/',
        templateUrl: 'home.html',
        controller: 'HomeController'
    })
}])
```
It should fix an error `$routeProvider is not defined` I have using your code.

PS: for configuration help, we got a [Gitter room](https://gitter.im/marmelab/ng-admin). It would perhaps be more easy to fix your problem. :)

**Comment by dekhaus** [comment]
I converted my app to js and now it works fine.

Thanks
Dave
