### ISSUE TITLE
Problem reading API response

### ISSUE THREAD

**Issue by perezb** [marmelab/ng-admin#473]
Hello,

This is more a question than an issue. I'm trying to read my API response who looks like this:

```
"result":{
   "article":[
      "num":1,
      "date":"2015-05-28",
      "title":"sample title",
      "text":"sample text",
      "images":[
         "url":"myimageurl.com/image.jpg"
       ]
   ]
}

```

So I use result as an entity since I can't seem to use article. I've been using addResponseInterceptor like described in the documentation of restangular:

```
        RestangularProvider.addResponseInterceptor(function(data, operation, what, url, response) {
            var resp;

            if (operation === "getList")
            {
                resp = data[0];
                return resp;
            }

            return data;
        });
```

But I still have a few problems. I can't access the "images" array, and I can't use the show view or edit view. The dashboard and the Listview work fine.

I'm new to angularjs and ng-admin so i'm probably missing something.

Thanks!

Adrien

@manuquentin Sorry, I sent my message before finishing typing it.

**Comment by manuquentin** [comment]
Hello,
You should use `addResponseInterceptor ` like described in the [documentation](https://github.com/marmelab/ng-admin/blob/0945d2ccb4cb392e3ec7e1eee26a7c53fbbeac30/doc/API-mapping.md) or in #472

Regards
