### ISSUE TITLE
Template field in CSV ExportFields list

### ISSUE THREAD

**Issue by lucval** [marmelab/ng-admin#474]
It looks like that currently it is not supported.

I've made a patch that you can find here: https://gist.github.com/lucval/e1db83a73c90c56104bb#file-gistfile1-txt

**Comment by fzaninotto** [comment]
Hi, would you like to submit a PR so that we can merge your patch, but keeping you as the author?

**Comment by jpetitcolas** [comment]
Any update on it @lucval? :)

We can also make the PR ourselves, but your name won't appear in contributors list then. :(

**Comment by lucval** [comment]
...finally #761

**Comment by fzaninotto** [comment]
Fixed by #761
