### ISSUE TITLE
Routing question

### ISSUE THREAD

**Issue by dekhaus** [marmelab/ng-admin#475]
Hi

I noticed that after I successfully update or create a 'resource' (aka the Product(s) returned by my api/products endpoint) - that I'm still 'on' the respective 'edit' / 'new' page.   Is there a way to configure where the user is redirected to after a given 'action' ?

Thanks
Dave

**Comment by endel** [comment]
Hey @dekhaus,

That's unusual. Could you please tell the operation system are you using, and the output of the entire CURL command?

I've just installed it successfully on my local machine and the output was the following: https://gist.github.com/endel/39a53f5fa4370f76d872

**Comment by fzaninotto** [comment]
Not at the time. This is not something we had any customer requirement for.

If you're interested in that feature, would you like to try and implement it yourself, than submit a PR?
