### ISSUE TITLE
help!,Failed to instantiate module ng-admin

### ISSUE THREAD

**Issue by shikelong123** [marmelab/ng-admin#476]
I import all required scripts in my project.

but when I start my project. It's run error in the  ng-admin-only.min.js

Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to:
Error: [$injector:modulerr] Failed to instantiate module ng-admin due to:
Error: [$injector:modulerr] Failed to instantiate module main due to:
TypeError: e.useApplyAsync is not a function

help.
![default](https://cloud.githubusercontent.com/assets/4499997/7877657/799da46a-0610-11e5-8d68-3f8b10b16869.png)

**Comment by jeromemacias** [comment]
On which browser did you tried to run it ?

**Comment by shikelong123** [comment]
chrome  -v  44.0.2398.0 dev-m (64-bit) 

@jeromemacias

**Comment by manuquentin** [comment]
Hello, `useApplyAsync` is a new feature of angular 1.3.
Which version of angular do you use ?

**Comment by shikelong123** [comment]
I use angular 1.2.28.  then I use the version 1.3.x 。 It's run well. thanks.
