### ISSUE TITLE
Questions about Reference_fields

### ISSUE THREAD

**Issue by F3L1X79** [marmelab/ng-admin#492]
Hi guys,
I got a question about Reference_fields, not really an issue I guess.
In my app, a Post is related to an User so I need to use <b>Reference</b> like this:

```js
post.listView()
            .sortField('created_at')
            .sortDir('DESC')
            .infinitePagination(true)
            .fields([
                nga.field('id').label('ID'),
                nga.field('created_at', 'date')
                nga.field('content').map(truncate),
                nga.field('wuserId', 'reference')
                    .label('User')
                    .targetEntity(user)
                    .targetField(nga.field('email'))
            ])
            .listActions(['show', 'edit', 'delete']);
```

In the example above, in my targetField, i'd like to concatenate two values (user.firstname and user.lastname) instead of the only field <b>email</b>. I was wondering if this was possible.

Also, while the code above is working great on a listView, it's not displaying the email field on the dashboard View - ie:

```js
post.dashboardView() 
            .title('10 last Posts')
            .order(1)
            .perPage(10)
            .sortField('created_at')
            .fields([
                nga.field('content').isDetailLink(true).map(truncate),
                nga.field('created_at', 'date'),
                nga.field('wuserId', 'reference')
                    .label('User')
                    .targetEntity(user)
                    .targetField(nga.field('email'))
            ]);
```

Is this normal? And if it is - it would we be great to add this feature in a next release.

Best regards.

**Comment by fzaninotto** [comment]
You can use `map()` to modify a field, the following way:

```js
                nga.field('wuserId', 'reference')
                    .label('User')
                    .targetEntity(user)
                    .targetField(nga.field('email').map(function (value, entry) {
                         return entry.firstname + ' (' + entry.lastname + ')';
                    }))
```

As for references in the dashboardView, I think it's been fixed recently (#488). Could you test with the latest master? If not, please open a dedicated issue.

**Comment by F3L1X79** [comment]
It's all working. Thanks a lot!

**Comment by jamespsterling** [comment]
@fzaninotto is this possible with a reference field on edit/create view?

**Comment by F3L1X79** [comment]
@jamespsterling yes it is actually working on the creationView() et editionView().

**Comment by jamespsterling** [comment]
@F3L1X79 how are you using it? When I do 

```
.map(function (value, entry) {
                         return entry.firstname + ' (' + entry.lastname + ')';
 })
```

It only shows me one entry for the preselected item in the reference list (dropdown).
