### ISSUE TITLE
How to define optgroup for choices() function

### ISSUE THREAD

**Issue by PaulMaly** [marmelab/ng-admin#495]
Hello guys! Thanks for this great tool!

Could you please, provide me the way how can I add "optgroup" tags to  "select" tag generated by choices() function? Thanks!

**Comment by fzaninotto** [comment]
Hi Paul, thank you for your feedback!

Option groups are not implemented at the moment. Since we don't have an immediate need for it, it may take some time. Would you like to give it a try on your side ?
