### ISSUE TITLE
Question about custom attributes

### ISSUE THREAD

**Issue by mayke5421** [marmelab/ng-admin#497]
How I can use <code>field('zip').attributes({'ui-br-cep-mask' : 'ui-br-cep-mask'})</code> ?

**Comment by fzaninotto** [comment]
Well, it should work as you configured it. Is the problem on the edit view? The list view? Can you check that the attribute isn't added to one of the parent elements? Which browser are you using?

**Comment by mayke5421** [comment]
I'm using the Chrome browser, only attr "placeholder" works with attributes function, but, I need to use a lot of custom controls, I'm using the template function of nd-admin and it's working very well with my custom directives and other html elements :D, thanks you for the great tool :)

**Comment by fzaninotto** [comment]
That's a bug. I'll submit a PR to fix it. Thanks for the report.
