### ISSUE TITLE
Sorted list impact sorted referenced list

### ISSUE THREAD

**Issue by ThieryMichel** [marmelab/ng-admin#500]
The list sort impact order applied on referenced_list in edition and show view.
Example: 
![anim](https://cloud.githubusercontent.com/assets/4034399/8057657/96eaa4f4-0eb3-11e5-9c4b-f4ea723c077c.gif)

**Comment by fzaninotto** [comment]
@jeromemacias I believe this is a regression, this used to work before your refactoring. Can you take a look?

**Comment by jeromemacias** [comment]
I'm on it.
