### ISSUE TITLE
Question about reference_many Fields

### ISSUE THREAD

**Issue by F3L1X79** [marmelab/ng-admin#512]
Hi again team ng-admin,

I was wondering if it is possible to make the reference_many field working with an array of objects instead of just an array of strings?

Here is an example of how it works actually:
In your blog example in the config file:

nga.field('tags', 'reference_many') // ReferenceMany translates to a select multiple
                    .targetEntity(tag)
                    .targetField(nga.field('name'))

and the JSON your receive is:

..."published_at":"2012-08-06","tags":[1,3]}

---

I'd like to know if there is a config file that would work with a JSON constructed like this:

..."published_at":"2012-08-06","tags":[{"id":"1","name":"Photo"}, {"id":"3","name":"Sport"}]}

Sincerely,
Felix.

**Comment by jpetitcolas** [comment]
You can use a Restangular response interceptor, as shown [here](https://github.com/marmelab/NgAdminGeneratorBundle/blob/master/Tests/Command/expected/config.js#L42-L50).

**Comment by F3L1X79** [comment]
Thanks a LOT!
