### ISSUE TITLE
Question about file upload

### ISSUE THREAD

**Issue by F3L1X79** [marmelab/ng-admin#517]
Hi guys,

I managed to upload a file in the folder I wanted, but is it possible to change the filename before the file is uploaded?
I'd like the file associated to a post gets the name <strong>POSTID.jpg</strong> when uploaded (where POSTID is the post id...).

Here's my code atm:

``` js
        post.creationView()
            .fields([
                nga.field('created_at', 'date')
                    .defaultValue(new Date()) 
                    .validation({ required: true }), 
                nga.field('content', 'text'),
                nga.field('image', 'file').uploadInformation({ 'url': 'MYBASEAPIURL/api/containerPosts/posts/upload/'}), //i'd like to have an image named: nga.field('id') + '.jpg' - Is this possible?
                nga.field('userId', 'reference')
                    .targetEntity(user)
                    .targetField(nga.field('email')
                    .validation({ required: true })
            ]);
```

Best regards.

**Comment by jpetitcolas** [comment]
I never played with the `file` field, but did you try to add a `apifilename` attribute to `uploadInformation`, as evoked by the [documentation](https://github.com/marmelab/ng-admin#file-field-settings)?

**Comment by F3L1X79** [comment]
Oh yes sorry, I tried to use the apifilename attribute, and nothing changed.

**Comment by jpetitcolas** [comment]
After re-reading, I understood the aim of this option. However, may you try `fileName` as shown in the [other accepted options](https://github.com/danialfarid/ng-file-upload#upload-service)?

**Comment by F3L1X79** [comment]
Damn, how come I missed that? 
It works.

Sorry, and thank you again - you really made my day!

**Comment by jpetitcolas** [comment]
No problem. We're always glad to help! :)

**Comment by Dev2014** [comment]
Hi,

As mentioned by @F3L1X79 i was unable to get my post id to use as image name. How I can get the same? I tried 
	nga.field('logo', 'file').uploadInformation({
	    url: admin.baseApiUrl() +
	            directoryBrand.name() +
	            '/upload',
	    accept: 'image/*',
	    fileName: nga.field('id')
	})

but
    nga.field('id') // this returns json not the value, 
    nga.field('id').value() //as enhancement, this at runtime can be helpful

Currently using::
	nga.field('logo', 'file').uploadInformation({
	    url: admin.baseApiUrl() +
	            directoryBrand.name() +
	            '/upload',
	    accept: 'image/*',
	    fields: {
	        imgName: getUniqueID()
	    }
	})

**Comment by FelixMalfait** [comment]
Same question as @dsinghr I'm unable to get the entity id. Did you find a solution?

**Comment by dsinghr** [comment]
@FelixMalfait Now I am not using this plugin. I am non-angular guy, although I was able to understand most of the part of this plugin. But still plugin seems not to be production ready as per my requirements so now I am not using it. I wish this was in pure javascript or backbone because recently a newer angular version had launched so its not worth the time to learn this plugin.

**Comment by FelixMalfait** [comment]
@dsinghr Okay thanks for your answer! Besides the file upload implementation that could be improved I'm very happy with this plugin, I guess it's meant to be ready-to-use for non-angular developer who have simple needs and not for people who want the latest technology

@F3L1X79 Any chance you can tell me how you did?

**Comment by F3L1X79** [comment]
Oh sorry, in my case the file renaming was working fine, but I wasn't able to get the entity ID since the file is uploaded BEFORE the entity is persisted to the database - at the moment I wasn't trying to implement the code. 
I finally dropped the ng-admin file-upload implementation to create my own on another custom page, sorry.

**Comment by FelixMalfait** [comment]
@F3L1X79 Okay thanks for the super fast answer

**Comment by gonzamace** [comment]
@FelixMalfait did you find any solution to get entity ID?? What I need is to pass the entity ID in the url to save the image en DB.

**Comment by ledfusion** [comment]
Got it working by writing a directive like this:

```
app.directive('uploader', ['$http', '$q', 'notification', '$state', function ($http, $q, notification, $state) {
	return {
		restrict: 'E',
		scope: {
			prefix: '&',
			suffix: '&'
		},
		link: function ($scope) {
			$scope.uploaded = false;

			$scope.onFileSelect = function ($files) {
				if (!$files || !$files.length) return;
				$scope.file = $files[0];
			};
			$scope.upload = function () {
				if (!$scope.file) return;

				var pattern = /^#\/[a-zA-Z0-9\-_]+\/(edit|show)\/([0-9a-fA-F]+)$/;
				var data = location.hash.match(pattern);
				if (!data) return alert("Unable to detect the entry ID");

				var id = data[2];
				var URL = $scope.prefix() + id + $scope.suffix();

				var fd = new FormData();
				fd.append('file', $scope.file);
				return $http.post(URL, fd, {
					transformRequest: angular.identity,
					headers: { 'Content-Type': undefined }
				})
				.then(function (res) {
					$scope.file = null;
					$state.reload();
					notification.log(res.data.error || "Image uploaded", { addnCls: 'humane-flatty-success' });
				})
				.catch(function (res) {
					notification.log(res.data.error || "Could not upload", { addnCls: 'humane-flatty-error' });
				});
			};
		},
		template: `<div class="row">
				<style>
					.uploader {
						color: #333;
						background-color: #f7f7f7;
						display: inline-block;
						margin-bottom: 0;
						font-weight: 400;
						text-align: center;
						vertical-align: middle;
						touch-action: manipulation;
						background-image: none;
						cursor: pointer;
						border: 1px dashed #ccc;
						white-space: nowrap;
						padding: 24px 48px;
						font-size: 14px;
						line-height: 1.42857;
						border-radius: 4px;
						-webkit-user-select: none;
						-moz-user-select: none;
						-ms-user-select: none;
						user-select: none;
					}
					.uploader.bg-success {
						background-color: #dff0d8;
					}
					.uploader.bg-danger {
						background-color: #f2dede;
					}
				</style>
				<div class="col-md-4" ng-hide="file">
					<div class="uploader"
						ngf-drop
						ngf-select
						ngf-drag-over-class="{pattern: 'image/*', accept:'bg-success', reject:'bg-danger', delay:50}"
						ngf-pattern="image/*"
						ngf-max-total-size="'1MB'"
						ngf-change="onFileSelect($files)"
						ngf-multiple="false">Select an image or drop it here</div>
				</div>
				<div class="col-md-4" ng-show="file">
					<button type="button" class="btn btn-success btn-lg" ng-click="upload()">
						<span class="glyphicon glyphicon-upload"></span> Upload the image
					</button>
				</div>
		</div>`
	};
}]);
```

And using it like this:

```
	nga.field('upload', 'template')
		.label('Upload image')
		.template(`<uploader prefix="'/api/images/'" suffix="'/file'"/>`),
```
