### ISSUE TITLE
Customizing Edit view

### ISSUE THREAD

**Issue by dekhaus** [marmelab/ng-admin#518]
Hi

I have a 'parent' resource that has many 'children' - say a Product has_many Categories.  I'd like to extend the edit Category page to include a list of all the Products that belong to the current Category and add a checkbox that the user has to check before saving the current Category.  Is this possible to do without creating a custom page ?  If so - how ?

Thanks
Dave

**Comment by dekhaus** [comment]
I spent the afternoon researching this and I believe that I can extend the edit page by using a custom directive containing my ... custom content.

My Categories editionView can be written as follows ...

category.editionView()
	.title('Edit Category "{{ entry.values.name }}"')
        .fields(item_template_type.creationView().fields())
        .fields([nga.field(null, 'template')
          .label('')
          .template('<products-content entry="entry"></products-content>')
        ]);

where 'products-content' is a custom directive containing whatever content I want to display.

I think this will work.  Will report back when I've got it working

**Comment by dekhaus** [comment]
Hi All

  After spending some time researching how to extend the edit page that ng-admin generates for me - it appears as though it is very doable.  To help make this question clearer - let's say ng-admin is managing two resources, Categories and Products.  Furhterore - a Category has many Products, so there's a parent -> child relationship between the two.
  
  I need to extend the edit Category page by forcing the user to confirm that they've reviewed the affected Products (aka the 'children' of the current Category) - before allowing the 'update' to proceed.  
  
  What I'd like to do is add the following fields in the following order to the edit Category page (beneath the Category fields but before the 'Save Changes' button) ...
  
  1) A Bootstrap 'alert' (aka 'div') containing instructions
  
  2) A checkbox with a 'Confirm' label to the right of the checkbox
    
If the user clicks the 'Save Changes' button a validation is performed on the checkbox (item #2 above) and if the checkbox is not checked - then the 'Save Changes' is aborted and an appropriate error message is returned.
    
  3) A 'Products' link that when pressed toggles a viewable 'region' containing a listbox of all the Products associated with the current Category
  
  I only need help with #3.
  
  Here's what I've got so far
  
      category.editionView()
              .title('Edit Category')
              .fields(category.creationView().fields())
              .fields([nga.field(null, 'template')
                .label('')
                .template('<instructions-message entry="entry"></instructions-message>')
              ])
              .fields(
              [
              nga.field('confirm', 'boolean')
                 .label('')
                 .validation({
                   required: false,
                   validator: function(confirm) {
                     if (!confirm) {
                       throw new Error ('Please check the confirm checkbox');
                     }
                   }
                 })
                ]
              )
              .fields([nga.field(null, 'template')
                 .label('Products')
                 .template('<category-products entry="entry"></category-products>')
              ]);
  
       app.directive('instructionsMessage', ['$location', function ($location) {
         return {
            restrict: 'E',
            scope: { entry: '&' },
            template: '<div class="alert alert-info" role="alert">Review the affected Products by clicking the \'Products\' link and if satisfied - check the checkbox below</div>',
         };
       }]);  

  # ****************************************************************************************************
  # This is where things stop working ...
  # ****************************************************************************************************
  
       app.directive('categoryProducts', ['$location', function ($location) {
          var category_id = ????
          return {
             templateUrl: '#/category/' + category_id + '/products'
             controllerAs: aController
          };
      }]);  


Based on this issue url -> https://github.com/marmelab/ng-admin/issues/147, it seems like I should be able to define a 'categoryProducts' directive that allows me to add dynamic content to the pages DOM.  I'm relatively new to AngularJS - having quite a bit of experience with jQuery - so I'm not sure if ...
  
  a) what I want to do is possible and
  b) if it is possible - how to do it.
  
  Sorry for the longish post - but I always err on the side of clarity.  So - can someone please provide some guidance on how to extend a resources 'edit' page with dynamic content added to the pages DOM.
  
Thanks
Dave

**Comment by dekhaus** [comment]
Here's a graphic of the new fields I want to add ...

![screen shot 2015-06-18 at 9 54 15 pm](https://cloud.githubusercontent.com/assets/7830/8247381/a3e1a8d0-1604-11e5-9843-a19889e9232e.png)

**Comment by jpetitcolas** [comment]
If I sum up more briefly, you want to display a list of all products belonging to a category on your category edition page, and add a checkbox to confirm the edition, right? 

You can indeed use a custom directive for the product list, but that's a little bit overkill in this case. You can use a `referenced_list` instead. Something like:

``` js
            nga.field('products', 'referenced_list')
                .targetEntity(product)
                .targetReferenceField('category_id')
                .targetFields([
                    nga.field('id'),
                    nga.field('name')
                ])
```

For the checkbox, you should indeed use a custom directive.

In you above code, you can retrieve the `category_id` through the `entry` value. But first you should isolate the directive scope:

``` js
app.directive('categoryProducts', ['$location', function ($location) {
    return {
            restrict: 'E', // Just accept <category-products> as element, not attribute
            scope: { entry: '&' }, // Map to your given entry (passed by entry="entry" attribute)
            templateUrl: '/path/to/template', // Path to template. You'll get category values through {{ entry.values }} attribute
            link: function (scope) {
                // Add some functions or computed variable to directive scope here
            }
        };
}]);
```

This is a not tested code, but it should be something like that. You can find more information on [custom directives on Angular doc](https://docs.angularjs.org/guide/directive) and some [custom directives in sample configuration](https://github.com/marmelab/ng-admin/blob/master/examples/blog/config.js#L289-L313).

**Comment by dekhaus** [comment]
Thanks for the help - your suggestion worked perfectly
