### ISSUE TITLE
Formatting of date fields not working as expected

### ISSUE THREAD

**Issue by stucki** [marmelab/ng-admin#520]
I fail to to change the default format of a date field. My defaultValue is set to ```new Date()```. When the page has loaded, this is displayed as:
```
Fri Jun 19 2015 09:00:01 GMT+0200 (CEST)
```
As soon as I select a date using the date picker, the format is correctly changed to the correct (default) format (```yyyy-MM-dd```):
```
2015-06-19
```
This can easily be reproduced in the demo application at
http://ng-admin.marmelab.com/#/comments/create

When I try to set the defaultValue to something like ```2015-06-19``` (which is probably wrong because it's just a string now) then at least the value is displayed correctly. However, when the form is submitted, then an empty value is sent (it's empty even if the field is marked as required):
```
    nga.field('startdate', 'date')
        .format('yyyy-MM-dd')
        .defaultValue('2015-06-19')
        .validation({ required: true });
```

What is the right way to change the default format and value of a date field?

**Comment by jpetitcolas** [comment]
This a [known bug](https://github.com/angular-ui/bootstrap/issues/2659) of Angular Bootstrap. I'm looking to update this lib.

**Comment by stucki** [comment]
Thank you!
