### ISSUE TITLE
where is the 'admin-config' directory?

### ISSUE THREAD

**Issue by hxlniada** [marmelab/ng-admin#521]
I'm learning ng-admin and research it's source code. It's very awesome. but I have a problem.
![image](https://cloud.githubusercontent.com/assets/3838586/8270058/fe47fc12-17fc-11e5-9a07-39327c94fbd1.png)
I can't find out where this file is. Is it not open source?

**Comment by hxlniada** [comment]
Oh , you made it a seperated npm module.
sorry i missed it.
![image](https://cloud.githubusercontent.com/assets/3838586/8270069/0c43bd46-17fe-11e5-96a1-c1f4371520e3.png)

**Comment by jpetitcolas** [comment]
We indeed splitted it into a dedicated module, as it is common to both ng-admin and an on construction [react-admin].
