### ISSUE TITLE
how can i post/put a complex json

### ISSUE THREAD

**Issue by effyroth** [marmelab/ng-admin#524]
just like:

    {
        "name": "effyroth111",
        "phoneNum": "15271919400111",
        "_id": "5589a8854b454cc33b5ac4f8",
        "__v": 0,
        "expertise": [],
        "qa": {
            "1": {
                "a": "",
                "q": ""
            },
            "2": {
                "a": "",
                "q": ""
            },
            "3": {
                "a": "",
                "q": ""
            }
        },
        "image": {
            "1": "",
            "2": "",
            "3": ""
        },
        "background": [],
        "description": "",
        "year": 0
    }

**Comment by fzaninotto** [comment]
The answer to your question is... in the doc.

https://github.com/marmelab/ng-admin/blob/master/doc/API-mapping.md#entry-format
