### ISSUE TITLE
Access sub-attribute via dot notation ("address.street")

### ISSUE THREAD

**Issue by Xennis** [marmelab/ng-admin#525]
Hey,

my API returns data in the format (extract only):

``` js
[
        {
            "id": 1,
            "address": {
                "street": "Heidberg",
                 "postal_code": "75385"
            }
        },
        {
            "id": 2,
            "address": {
                "street": "Heinrich-Böll-Str.",
                "postal_code": "70707"
            }
        },
        ...
]
```

How can I access for instance the `street` attribute? It would be nice, if I could access it directly by `nga.field('address.street')`, but that does not seems to work. Of course I could define the field as `template` field and write a directive. But when I've many of such fields, that would not be so nice. Or is there another, simple way?

**Comment by karantan** [comment]
I think this is what you are looking for:

```
app.config(function(RestangularProvider) {
    RestangularProvider.addElementTransformer('books', function(element) {
        for (var key in element.values) {
            element[key] = element.values[key];
        }

        return element;
    });
});
```
I copy paste this from the [documentation](https://github.com/marmelab/ng-admin/blob/master/doc/API-mapping.md)

**Comment by jpetitcolas** [comment]
Indeed, we can do it currently the way @karantan suggested. ng-admin doesn't support the dot notation. But that's indeed a good idea. I keep the issue opened to not forget it. :)

**Comment by fzaninotto** [comment]
Related to #68 and #390

**Comment by fzaninotto** [comment]
Good news: that's now possible in the master branch, thanks to #549 being merged.
