### ISSUE TITLE
Making a PUT query in a custom directive ?

### ISSUE THREAD

**Issue by perezb** [marmelab/ng-admin#530]
Hello,

I've made a custom directive for the show view of one of my entities and i'm trying to make this directive execute a PUT query.

The problem is, I don't really know how to do it.

I have my api PUT endpoint like this: mydomain.com/api/validateComment/:id which works fine, but I can't figure how to call it in my custom directive.

Here is my custom directive:

```
	app.directive('validateComment', ['$location', function ($location) {
		return {
			restrict: 'E',
			scope: { comments: '&' },
			template: '<a class="btn btn-default" ng-click="validate()">Validate</a>',
			link: function (scope) {
				scope.validate = function () {
					$location.path('/getComment/show/' + scope.comments().values.comment_id);
				};
			}
		};
	}]);
```

I'd like it to work like the edition view (click on the button, execute the PUT query, and stay on the same page (the last part works with my $location.path() call), but i'd prefer not to use an edition view (and it's not really necessary since there is only one field I want to change, and it's a boolean).

Should I use directly restangular ? Or is there already a solution with ng-admin ?

Regards

**Comment by karantan** [comment]
Isn't this GET request? Try with angular [$http](https://docs.angularjs.org/api/ng/service/$http)

**Comment by perezb** [comment]
Hey, thanks for your reply

So I've used $http.post in my directive and it works perfectly, but I can't figure how to "refresh" my show view by clicking on the button, I actually have to do it manually to see my field updated on my page.

Any idea ?

**Comment by karantan** [comment]
Yes this might be a problem... I think this is because the scope is different. You need to set up some communication service.

e.g.

```
.service("NotifyingCache", ["$rootScope",  function($rootScope){

    var cache = {};

    this.put = function(key, value){
        var oldValue = this.get(key);
        cache[key] = value;
        $rootScope.$broadcast(
        "cache.item.updated",
            { key: key, newValue: value, oldValue: oldValue });
    };

    this.remove = function(key){
        var value = this.get(key);
        delete cache[key];
        $rootScope.$broadcast(
            "cache.item.removed", { key: key, value: value });
    }

    this.get = function(key){
//        return cache[key] || null;
        return cache[key];
    }
```

**Comment by perezb** [comment]
Hi,

I tried your solution but I didn't manage to get it to work, I'm not an angular master yet so I've probably done something wrong though.

I have used $windows.location.reload() instead. It's probably not the best thing to do but at least it works :).

**Comment by fzaninotto** [comment]
My 2c: avoid reloading the entire page. ng-admin uses ui-router, so you can force the reload of the page (minus the constant parts like the header and sidebar) using `$state.go(stateName)` (see the `Crud/routing.js` file for an overview of current states).

Also, if you don't want to use the show view, ng-admin supports custom pages, see https://github.com/marmelab/ng-admin/blob/master/doc/Custom-pages.md. You can do pretty much anything you want there.
