### ISSUE TITLE
ngRepeat:dupes Error

### ISSUE THREAD

**Issue by bishopsmove** [marmelab/ng-admin#531]
I am running into an error when the Dashboard or ListView is loaded:

```javascript
Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: 
entry in entries track by entry.identifierValue, Duplicate key: undefined, Duplicate value: 
{"_entityName":"addresses","values":
{"city":"Atlanta","state":"GA","country":"USA","postalCode":"30326","createdOn":null,"updatedOn":null,
"version":null,"route":"addresses","reqParams":null,"restangularized":true,"fromServer":true,
"parentResource":null,"restangularCollection":false},"listValues":{}}

```

I am trying to programmatically load the entities into ng-admin but I run into this same issue when I revert to hard-coding the entity in-question as well.

The data return looks like this:

```javascript
[
  {
    "id": 8,
    "line1": "1234 Main St.",
    "line2": null,
    "city": "Marietta ",
    "state": "GA",
    "country": "USA",
    "postalCode": "30066",
    "createdOn": null,
    "updatedOn": null,
    "version": null
  },
  {
    "id": 9,
    "line1": "555 Market Drive",
    "line2": null,
    "city": "Atlanta",
    "state": "GA",
    "country": "USA",
    "postalCode": "30326",
    "createdOn": null,
    "updatedOn": null,
    "version": null
  }
]
```

This was working last week, when it was hard-coded, so I'm not sure what has happened.

Any suggestions would be appreciated. It feels like I am missing something but the views do load, only without data.

Cheers.

**Comment by jpetitcolas** [comment]
Not sure, but it may be related to introduction of ui-select. Can you post your related configuration? I'll try to reproduce it on my side.

**Comment by Mr-Luo** [comment]
add the identifier to entity e.g. your id is an unique,so,try to do like below
## nga.entity('buyer').identifier(nga.field('id'));

**Comment by jpetitcolas** [comment]
We recently merged some updates to the choices component. Can you retry with the last master version to check if it work?

**Comment by fzaninotto** [comment]
No news for a month, closing.
