### ISSUE TITLE
Ng include as view template

### ISSUE THREAD

**Issue by SebLours** [marmelab/ng-admin#532]
Hi,
I try to customize a list view template.
I would like to use the base ng admin list view template and customize it.

``` JS
        task.listView()
            .title('Listes des tâches')
            .fields([
                fields.id,
                fields.user_reference,
                fields.name,
                nga.field('priority', 'template')
                    .label('Priorité')
                    .template('<div ng-include="\'task.list._priority.html\'"></div>')
            ])
            .listActions([
                'edit',
                'delete'
            ])
            .template('<div ng-include="\'task.list.html\'"></div>')
            .perPage(10)
        ;
```

The view title is ok, pagination is ok but ``` <ma-datagrid> ``` is not working ...

I'm not an Angular ninja ... is there a better way to do this ?

Thanks
![ng-admin](https://cloud.githubusercontent.com/assets/5138394/8375691/e937f9b0-1bff-11e5-80f2-d1d1de21fcf3.png)

**Comment by jpetitcolas** [comment]
Indeed, it seems that `ng-include` doesn't work with our `template` function. Looking at it.

Meanwhile, you can use some custom directives to achieve it, which would bring you more flexibility IMO.

**Comment by jpetitcolas** [comment]
My bad, after testing more in details, it seems to work (I forgot the inner quotes in the `ng-include` attribute).

Testing your configuration worked. Can you post your template contents? Have you any JS errors?

**Comment by SebLours** [comment]
It's works ...
I'll take the template in the master branch and my app is in 0.7 ...
Sorry for the noise !
Thanks for your answer !

![ng-admin](https://cloud.githubusercontent.com/assets/5138394/8379402/1101b8e4-1c20-11e5-9fcf-2e21145e2ad1.png)
