### ISSUE TITLE
Cannot disable entity's MenuView

### ISSUE THREAD

**Issue by vasiakorobkin** [marmelab/ng-admin#533]
I need to disable MenuView for some entity.
[This is the only solution I found](https://github.com/marmelab/ng-admin/issues/197#issuecomment-68187004), but it doesnt work.

My ng-adimin version is installed via bower using "master" as version.

I've looked at the sources, and it seems to me that [this line is the reason of my problem](https://github.com/marmelab/admin-config/blame/master/lib/View/MenuView.js#L11). It looks like you erroneously used disjunction instead on conjunction in this line. But maybe there was a worthy reason to use disjunction there?

Please, take a look at this problem -  it shouln't take too much time to fix it, imho.

**Comment by jpetitcolas** [comment]
Looking at the referenced line, I guess you still have an enabled list view. What is your use case for not displaying the menu item in this case?

The logic behind this OR operator is to always display the menu if the list view is enabled. Otherwise, how would you reach it? But I wonder if the `enabled` method of `MenuView` makes sense in this case.

**Comment by vasiakorobkin** [comment]
Yes, I still have enabled list view. My case is that I want to reference this entity (let's say *images*) from other entity (let's say *posts*) and view it via "referenced_list" type of field. One posts may have many images. The only action I need for this *images* is delete (you can either upload or delete image, no other actions involved). So I don't need no other view than ListView (where I define the only "delete" action) for this entity. And I don't want to see it in menu because it may be confusing for end user.
Anyways, if you think that ListView should be the only thing that defines visibility of entity in meenu, so why would you need MenuView._enabled property and MenuView.disable() method then?

**Comment by jpetitcolas** [comment]
Normally, you don't need an enabled list view to use a `referenced_list`. Can you try to disable your image list view and check if it works?

I agree with you about the `MenuView._enabled` property. We got an inconsistency here. I would suggest to remove the `enabled` property of the menu view to use only the `listView.enabled` property. @fzaninotto, what do you think about it?

**Comment by vasiakorobkin** [comment]
Oh, sorry, I've misunderstood that. You're absolutely right. `listView` doesn't have any relation to the `referenced_list` view, so I can just disable it and it solves my problem.

But I see nothing wrong in [changing disjunction to conjunction here](https://github.com/marmelab/admin-config/blame/master/lib/View/MenuView.js#L11).
The only case you should avoid is to leave broken menu link for end user (when `menuView` is enabled and `listView` is disabled) - and your current code still makes this case possible. While in my situation (where I can have working `listView` with no entry in menu for it) end user unlikely will notice it.
It seems to be more logical for me to just replace disjunction with conjunction, than break generic View properties and methods for `listView`.

**Comment by vasiakorobkin** [comment]
By the way, can you tell me how can I add "Delete" button to the the each entry of `refernced_list` view? Why does field of type `refernced_list` have no `.listActions()` mehod?

I've tried to add field of `template` type to the referencing entity, and paste `<ma-delete-button entry="::entry" entity="::entity" size="xs"></ma-delete-button>` directive as template, but it doesn't work because entity is not visible in field's scope.

**Comment by jpetitcolas** [comment]
The proposed fix for the menu has just been merged. Closing.

**Comment by fzaninotto** [comment]
#23 has been reverted. The right solution for your problem is to use the new [Menu configuration](https://github.com/marmelab/ng-admin#menu-configuration). `MenuView` is deprecated and will be removed soon.
