### ISSUE TITLE
Delete button directive-params are overriden by state-params

### ISSUE THREAD

**Issue by vasiakorobkin** [marmelab/ng-admin#535]
[Here you can see](https://github.com/marmelab/ng-admin/blob/master/src/javascripts/ng-admin/Crud/button/maDeleteButton.js#L19) that directive params (`entity` and `id`) are always overriden with state params (`entry` and `id` from object which is returned from `$state.params` call).
In practice it causes wrong behaviour whenever we try to place `Delete` button in other entity's view. For example I have `Post` which may have many `Images` and use `referenced_list` field type to view list of related `Images`  in `Post`'s edit view. If i place `<ma-delete-button entry="::entry" entity="::entity()" size="xs"></ma-delete-button>` directive to the `refernced_list` table (as `template` field type), delete button will direct user to the `Post` deletion view, not `Image` deletion view. This is a bug, and I've made a fix for it: vasiakorobkin/ng-admin@2534ba38da30413ad62d5cae59934f696b18672a

**Comment by jpetitcolas** [comment]
Fixed by #642.
