### ISSUE TITLE
Error: $interpolate:interr

### ISSUE THREAD

**Issue by karantan** [marmelab/ng-admin#540]
When I .field() in createView() or editView() I get this error:

```
Error: [$interpolate:interr] Can't interpolate: row-{{ field.name() }}
TypeError: v2.name is not a function
http://errors.angularjs.org/1.4.1/$interpolate/interr?p0=row-%7B%7B%20field.name()%20%7D%7D&p1=TypeError%3A%20v2.name%20is%20not%20a%20function
    at angular.js:68
    at Function.$interpolateMinErr.interr (angular.js:10579)
    at interpolationFn (angular.js:10854)
    at attrInterpolatePreLinkFn (angular.js:8525)
    at invokeLinkFn (angular.js:8642)
    at nodeLinkFn (angular.js:8121)
    at compositeLinkFn (angular.js:7534)
    at nodeLinkFn (angular.js:8137)
    at compositeLinkFn (angular.js:7534)
    at compositeLinkFn (angular.js:7538)
```
 and this error:

```
Error: [$interpolate:interr] Can't interpolate: {{ field.name() }}
TypeError: v2.name is not a function
http://errors.angularjs.org/1.4.1/$interpolate/interr?p0=%7B%7B%20field.name()%20%7D%7D&p1=TypeError%3A%20v2.name%20is%20not%20a%20function
    at angular.js:68
    at Function.$interpolateMinErr.interr (angular.js:10579)
    at interpolationFn (angular.js:10854)
    at attrInterpolatePreLinkFn (angular.js:8525)
    at invokeLinkFn (angular.js:8642)
    at nodeLinkFn (angular.js:8121)
    at compositeLinkFn (angular.js:7534)
    at nodeLinkFn (angular.js:8137)
    at compositeLinkFn (angular.js:7534)
    at nodeLinkFn (angular.js:8137)
```

for every field I add. However this doesn't happen when I use my own template fields (via my directives).

Everything works fine and it doesn't break any code (as far as I know) but it still bothers me...
![screenshot 2015-06-30 17 07 01](https://cloud.githubusercontent.com/assets/7062631/8434314/fdb9d892-1f4a-11e5-83ef-1d15ffa41350.png)

**Comment by fzaninotto** [comment]
Could you share your config?

**Comment by karantan** [comment]
https://www.dropbox.com/s/wgbeu4rt9qvt2yf/admin.js?dl=0

**Comment by jpetitcolas** [comment]
I can't see anything wrong in your configuration. However, what is your `v2` mentionned in your error message?

**Comment by karantan** [comment]
I didn't use v2 variable in any of my code. I think this is angular's variable...

Anyway here is my bower.json if it helps (probably not...)

```
{
  "name": "assets",
  "version": "0.0.0",
  "dependencies": {
    "angular": "^1.3.0",
    "bootstrap": "^3.2.0",
    "angular-animate": "^1.3.0",
    "angular-cookies": "^1.3.0",
    "angular-resource": "^1.3.0",
    "angular-route": "^1.3.0",
    "angular-sanitize": "^1.3.0",
    "angular-touch": "^1.3.0",
    "ng-admin": "~0.7.0",
    "underscore": "~1.8.3",
    "angular-underscore": "~0.5.0",
    "notifyjs": "~0.3.2",
    "angular-ui-router": "~0.2.15",
    "ladda": "~0.9.8",
    "angular-ladda": "~0.2.2"
  },
  "devDependencies": {
    "angular-mocks": "^1.3.0"
  },
  "appPath": "app",
  "moduleName": "assetsApp"
}
```

**Comment by jpetitcolas** [comment]
Can you try with the latest version of `ng-admin`, using `dev-master` version? You are indeed using dashboard configuration, which is not available in 0.7. I think you based on master documentation using an older version of our lib. :)

**Comment by nheinbaugh** [comment]
I'm getting this same error with version 0.7.0

**Comment by lukemarsh** [comment]
Hey @jpetitcolas any update on this? The error is happening on 0.7.0

**Comment by FairlieAgile** [comment]
I have just created a pull request for this. Replacing calls to field.name() to field.label() in  src/javascripts/ng-admin/Crud/field/maField.js resolved the issue

**Comment by jpetitcolas** [comment]
I finally succeeded in getting this error. It is indeed an issue with Angular version. To reproduce it, you have to embed Angular.js before the ng-admin one:

``` js
<script src="bower_components/angularjs/angular.min.js"></script>
<script src="bower_components/ng-admin/build/ng-admin.min.js"></script>
```

Looking at it.

**Comment by jpetitcolas** [comment]
As this is an Angular 1.4 related issue, I am closing this ticket and opening a new one dedicated to 1.4 migration. We are going to make the 1.4 the default supported version in 0.8.
