### ISSUE TITLE
BUG - Multiple relationship

### ISSUE THREAD

**Issue by FedeG** [marmelab/ng-admin#544]
When an entity has more of one relationship with another entity, the views fails.

For example if in ng-admin-demo add a field tags-2 to posts

In post.listView add a field:
```js
nga.field('tags-2', 'reference_many')
  .targetEntity(tag)
  .targetField(nga.field('name'))
```

In post.editionView add a field:
```js
nga.field('tags-2', 'reference_many')
  .targetEntity(tag)
  .targetField(nga.field('name'))
  .cssClasses('col-sm-4')
```

Steps to generate this bug:
------------------------------------------

1- View post
![Show]( http://oi62.tinypic.com/2eppueg.jpg "Show")

2- Add tags and tags-2 in post
![Edit]( http://oi62.tinypic.com/j78aac.jpg "Edit")

3- Save post
![Save]( http://oi58.tinypic.com/2r5yge9.jpg "Save")

4- List all post
![List]( http://oi59.tinypic.com/1g26w1.jpg "List")

5- View edited post
![Show2]( http://oi59.tinypic.com/2qu2g0h.jpg "Show 2")

6- Edit post
![Edit2]( http://oi58.tinypic.com/142aaeo.jpg "Edit 2")

When you add the second relationship to the entity, in listView and showView the relations can't be viewed. Only one of the two relationships is visible but in the editionView can be seen well.

**Comment by jpetitcolas** [comment]
Thanks for this detailed report. I can reproduce the problem. Looking at it.

**Comment by AgustinCroce** [comment]
There is any advance in this bug? I am experimenting the same issue.

**Comment by fzaninotto** [comment]
Now fixed in master.
