### ISSUE TITLE
BUG-Filter operation

### ISSUE THREAD

**Issue by Mr-Luo** [marmelab/ng-admin#545]
I have three filter conditions. nickname,joindate,logindate.
1 i choosed nickname,then clicked Filter button.
   the request like this "xxxxxxxx?_limit=30&_start=0&nickname=add",that's right
2 i choosed nickname and joindate,then clicked Filter button
   the request like this "xxxxxxx?_limit=30&_start=0&joindate=2015-07-03&nickname=add
3 i choosed . nickname and joindate and logindate,then clicked Filter button
   the request like this "xxxxxxx?_limit=30&_start=0&logindate=2015-07-01&nickname=add
why the third request' params didn't contained joindate value.
PS.I didn't Clear the values.

**Comment by jpetitcolas** [comment]
All fields seems to be in URL, if you try on the [demo](http://ng-admin.marmelab.com/#/comments/list).

Can you share us your configuration?

**Comment by Mr-Luo** [comment]
thanks,here is my configuration.
buyer
     .listView()   
     .title('All buyer')                                          // 标题
     .description('List of buyer')                          // 标题下面的描述
     .fields([
          nga.field('Nickname'),
          nga.field('Country'),
          nga.field('Province'),
          nga.field('City'),
          nga.field('Sex')
      ])   

     .listActions(['show','<inb-to-application entry="entry"></inb-to-application>','<inb-buyer-msn-list entry="entry" op-type="buyerList" ></inb-buyer-msn-list>']) //要获得Id必须要把entry传入
     .filters([
         nga.field('nickname', 'string').label('昵称'),
         nga.field('joindate', 'date').label('').attributes({
             'placeholder': '加入时间'
         }),
         nga.field('logindate', 'date').label('').attributes({
             'placeholder': '登录时间'
         }),
         nga.field('hasapplication', 'boolean').label('是否有7天内的application')
     ]).batchActions(['<inb-add  selection="selection" entry="entry" ></inb-add>']);

**Comment by fzaninotto** [comment]
The code and the UI for filters has been updated in the latest master (see the [demo](http://ng-admin.marmelab.com/#/comments/list)). Could you re-test, and report here if you still have a problem?

**Comment by Mr-Luo** [comment]
Ok,I will try to do that,thanks.

**Comment by jpetitcolas** [comment]
Any news on this topic?

**Comment by fzaninotto** [comment]
No news for about a month, closing.
