### ISSUE TITLE
Adding two references in the listview

### ISSUE THREAD

**Issue by perezb** [marmelab/ng-admin#547]
Hello,

I have trouble adding two reference targeting the same entity but different fields in a listview. 

The output is that both of the reference will display the one called in second position.

```
			.fields([
				nga.field('id_message').label('ID Message'),
				nga.field('log').label('Reporteur'),
				nga.field('id_message', 'reference')
					.label('Auteur')
					.isDetailLink(false)
					.targetEntity(comments)
					.targetField(nga.field('log')),
				nga.field('id_message', 'reference')
					.label('Commentaire')
					.isDetailLink(false)
					.targetEntity(comments)
					.targetField(nga.field('text')),
				nga.field('dateheure').label('Date'),
				nga.field('origine').label('Origine')

```

For example this code will display twice the *text* field from the *comment* entity. Is it a bug or is there a different way to  do this ?

Regards

**Comment by jpetitcolas** [comment]
What is your use case?

As far as I can guess, I think `referenced_list` may be better for you, something like:

``` js
nga.field('messages', 'referenced_list')
    .targetEntity(comments)
    .targetReferenceField('relationship_column')
    . targetFields([
        nga.field('log').label('Auteur'),
        nga.field('text').label('Commentaire')
    ]);
```

**Comment by perezb** [comment]
I'm not quite sure of what you mean by my use case.

I'm just trying to display the listview, and each row has two references to the same entity, who both display the data of the last reference called, even though they are both linked to different fields.

I looked up referenced_list, and it seems to fit my needs :), but again I don't know what to give as first parameter (where you called 'messages' in you example). Is it the entity name, a field name, or something else ?

**Comment by jpetitcolas** [comment]
So, you just want to display a list of related entities. That's why we created the `referenced_list`. :)

For the first argument, it doesn't really matter. It will be used just for retrieving automatically a label, but you can also specify it with the `label()` method.
