### ISSUE TITLE
Add default filter parameter (non removable) to datagrids

### ISSUE THREAD

**Issue by mdhooge** [marmelab/ng-admin#548]
It'd be nice to be able to add “any param” to a view, that could then be handled by a Restangular Interceptor.

My need is to have several collections in the dashboard on the same entity, with forced filters.
I cheated with a dummy sort filter (and an object as direction). This works well as long as I don't try to sort the collection with another column, of course.
So, it'd be nice…

**Comment by fzaninotto** [comment]
The real need being pre-sorted lists, I totally agree with you. It's a much needed feature. As your issue title mentions a solution more than a requirement, I took the liberty to rename it.

We'll look into it shortly.

**Comment by mdhooge** [comment]
I don't mind changing the title ;-)

But maybe it is also interesting to be able to send "hints" to Interceptors. Because this is a very powerful way to adapt the admin to any need! I could open another issue…
