### ISSUE TITLE
How to change button's text? 

### ISSUE THREAD

**Issue by shikelong** [marmelab/ng-admin#550]
for example:
I want to change the `create` buttons's text to `create a new ...`
Is only can I rewrite the button's directive?

**Comment by fzaninotto** [comment]
Did you try overriding the `label` attribute?

```js
myEntity.listView().actions(['batch', 'export', '<ma-create-button entity="::entity" label="Create new FooBar"></ma-create-button>'])
```

**Comment by shikelong** [comment]
thank you. I have overriding the label attribute.
