### ISSUE TITLE
bug: reference_many field

### ISSUE THREAD

**Issue by karantan** [marmelab/ng-admin#552]
I found a bug with reference_many field. When you edit e.g. Post and remove all Tags then save this Post you cannot assign any Tags to this Post because they do not appear.

Here is a link to the video that shows this bug: http://www.youtube.com/watch?v=iohsdt2VBG0

edit: this bug appreas only in version 0.8.0. In 0.7.0 this is OK because this field is a list...

**Comment by denkhaus** [comment]
I have the same issue. Its obvious since commit "5e16a3c30ec5ce6f913a1dd7d393d2397a30fbd3"

**Comment by jpetitcolas** [comment]
Indeed, that's a bug. Looking at it.

Note that you can still choose a tag by entering first letters on it.
