### ISSUE TITLE
Using MySQL database, boolean values are always displayed as true

### ISSUE THREAD

**Issue by stucki** [marmelab/ng-admin#558]
My data is fetched from a MySQL database where I'm using tinyint(1) for boolean fields. This results in a response like this:

```
[{"id":"1","title":"test1","ensure":"1"},{"id":"2","title":"test2","ensure":"0"}]
```

Apparently this does not work because the value "0" is evaluated as true. In the list view, both entries are displayed as checked.

If I manually set the value to NULL, then it works as expected. However, new rows are again stored with the value "0".

Is this a problem of my database scheme (how to fix it?) or should ng-admin evaluate "0" as false?

**Comment by fzaninotto** [comment]
This is debatable. One could argue that "0" is truthy, it depends on the backend. 

Is it ng-admin's role to decide how to map a string to a boolean? I don't think so. 

However, you can decide how to do the mapping yourself using an ElementTransformer (cf https://github.com/marmelab/ng-admin/blob/master/doc/API-mapping.md).
