### ISSUE TITLE
JSON field

### ISSUE THREAD

**Issue by NTag** [marmelab/ng-admin#561]
Hello,

I have a problem with JSON field. My object is :
```json
{
  "coords": [
    {
      "lat": 48.8796851,
      "lng": 2.3221576
    },
    {
      "lat": 48.873972,
      "lng": 2.297018
    },
    {
      "lat": 48.873912,
      "lng": 2.315992
    }
  ],
  "parkingCoords": {
    "lat": 48.8796851,
    "lng": 2.3221576
  },
  "id": 41
}
```

coords and parkingCoords are JSON field. coords is correctly displayed (with a beautiful table, thank you :) ).

```js
nga.field 'coords', 'json'
.label 'Coordonnées'

nga.field 'parkingCoords', 'json'
.label 'Coordonnées du parking'
```

However, parkingCoords displays nothing :/ (in list view or in edition view).

Thank you very much!

**Comment by jpetitcolas** [comment]
Indeed, I reproduced the issue, and the problem is even more general: JSON field doesn't display JSON object. But JSON arrays work fine. Looking at it.

**Comment by fzaninotto** [comment]
I isolated and fixed the bug in admin-config. PR is waiting for review.
