### ISSUE TITLE
Get single entity

### ISSUE THREAD

**Issue by lakshmiaswath** [marmelab/ng-admin#571]
The call for fetching a single entity is  - baseApiUrl/entityname/id .
Where as my requirement is - baseApiUrl/entityname?id . Id should be passed as params .Is there way as how we could/change this ?

**Comment by jpetitcolas** [comment]
You can try using a full request interceptor ([documentation](https://github.com/mgonto/restangular#addfullrequestinterceptor) and [use sample](https://github.com/marmelab/ng-admin/blob/master/examples/blog/config.js#L19-L44)), but I'm not sure you can override the called URL. That's more a [Restangular](https://github.com/mgonto/restangular) issue than a ng-admin one thus. :)

**Comment by lakshmiaswath** [comment]
@jpetitcolas  : Thank you .Will look into restangular :)

**Comment by fzaninotto** [comment]
Note that Restangular doesn't allow to modify the URL (cf https://github.com/mgonto/restangular/issues/603). The solution is to use a interceptor on Angular's `$http` service, as described in #711.
