### ISSUE TITLE
Reference field sortDir and sortField are being overridden somewhere

### ISSUE THREAD

**Issue by ulikus** [marmelab/ng-admin#576]
cannot get them to work
here is the code snippet, 
```
login.editionView()
    .fields([
        nga.field('username'),
        nga.field('password'),
        nga.field('user', 'reference')
            .perPage(10)
            .sortDir("ASC")
            .sortField("nickname")
            .label('User')
            .targetEntity(user)
            .targetField(nga.field('nickname'))
    ]);
```
but the actual request is sent with "id" and "DESC"
i guess its a bug?

**Comment by BearTM** [comment]
I found that you can specify the (default) .sortField('xxx') in the listView() creation. This appears to work across all views for that entity.

The following should (hopefully) work for you.
```javascript
user.listView()
    .fields([
        ...
    ])
    .sortDir("ASC")
    .sortField("nickname");
```
I don't know why the field specification doesn't apply the sortField() correctly.
