### ISSUE TITLE
Valid icon doesn't disappear when boolean fields are unchecked

### ISSUE THREAD

**Issue by wilk** [marmelab/ng-admin#579]
The issue is this:

```
  nga.field('test', 'boolean').label('Test');
```

I check it on and the right valid green flag appears but when I uncheck it, it doesn't disappear.
Even the label still remains green.
I also added a validation (required: false) but it didn't worked.

Is there any work around?

**Comment by fzaninotto** [comment]
Am I understanding correctly? You have a boolean field, and you want to give it the value 'undefined', not true or false. If this is your problem, it's related to #225.

**Comment by fzaninotto** [comment]
No reply for two weeks, besides the handling of boolean fields has changed since #629. Closing.
