### ISSUE TITLE
custom fields type 

### ISSUE THREAD

**Issue by flug** [marmelab/ng-admin#580]
Hi, 
I use admin-ng on a project and I would like to make a custom field for a json using this library: [json-editor](https://github.com/jdorn/json-editor)
I watch doc but I not clear how I should train my duties so I can inject. You currently do a "require" but it seems that's nodejs?
How I can do to inject a new custom field?

**Comment by fzaninotto** [comment]
Use Angular's dependency injection. As for how to manage scripts loading, that's up to you and your build pck (browerify, webpack, requirejs).
