### ISSUE TITLE
Remap a json fields on the corresponding field

### ISSUE THREAD

**Issue by flug** [marmelab/ng-admin#581]
I need help to find out how the cleaner. I currently have a field in my database type "json" which serves to moderation of a data change my user. In "ng-admin" I retrieves this field and I love that when one commits the changes, which the json be remapped on good fields.
an idea ?

**Comment by fzaninotto** [comment]
Either use a `json`field type, or map a field to properties of the JSON. For instance, if your REST API returns an entity looking like:

```js
{
  id: 1,
  title: "hello",
  address: {
    street: "bar",
    number: 2
  }
}
```

Then you can map subfields with:

```js
listView.fields([
  nga.field ('id'),
  nga.field ('title'),
  nga.field ('address.street'),
  nga.field ('address.number', 'number')
]);
```

as an alternative to:

```js
listView.fields([
  nga.field ('id'),
  nga.field ('title'),
  nga.field ('address', 'json')
]);
```
