### ISSUE TITLE
Multiple references field loses choices

### ISSUE THREAD

**Issue by GSeva** [marmelab/ng-admin#591]
This happens if you edit some entity that has references saved in a reference-many-field. If you delete some choice from reference field, you can't select it back clicking, you have to go back and reenter the editing form.

For example in the demo application:

1) Go to the posts list and edit any post with tags.
![screen1](https://cloud.githubusercontent.com/assets/2244417/9094294/540d851a-3b87-11e5-9347-6f5df3122916.png)

2) Delete any tag. You can't select it back:
![screen2](https://cloud.githubusercontent.com/assets/2244417/9094709/d07c51ce-3b89-11e5-8b2a-dff4f26f6931.png)

3) Sometimes i also experience this behavior, but it's not persistent. It happens when i go back to dashboard while editing via changing the url manually and pressing enter, and going back to edit form:
![screen3](https://cloud.githubusercontent.com/assets/2244417/9094602/2bc4fee2-3b89-11e5-887b-7545136d64ff.png)

Anyway, if you type something, the list refreshes and everything start working fine, so i don't know if it's a bug or that's the expected behavior.

By the way, the README for ng-admin-demo tells you to go to localhost:3000 but the server.js runs on port 3001.

**Comment by jpetitcolas** [comment]
Thanks for this detailed report. This is indeed a bug. I'm looking at it. 

For the port, how do you launch the demo? I access it at [http://localhost:8000/](http://localhost:8000/) URL.

**Comment by GSeva** [comment]
The port problem was due to me playing around with the master branch of [ng-admin-demo](https://github.com/marmelab/ng-admin-demo/tree/master). It's README tells you to use the 3000 port while running on 3001. But actually it's default branch changed, so nevermind.

**Comment by fzaninotto** [comment]
This is most probably a bug with ui-select. I hope that Upgrading it will fix the bug.

**Comment by fzaninotto** [comment]
No it doesn't, and it's even worse (see https://github.com/angular-ui/ui-select/issues/1398 by the way). Looking into an alternative solution.

**Comment by beatelite** [comment]
I read somewhere that the ui-select gents abandoned it since google's material design elements will probably be highly adopted by the angularjs community. https://material.angularjs.org/latest/demo/select

I still don't see they have multi-select so I don't really get it but I'm sure it will come out soon enough.
