### ISSUE TITLE
Help with Handling of nested API call inside fields

### ISSUE THREAD

**Issue by clowNay** [marmelab/ng-admin#595]
I am trying to get an image inside a nested object, which needs to get from another api to get image.

This is my editView object:

```json
{ 
    "title": "TheTitle",
    "body": "<p>body text</b>",
    "image": {
        "file": {
            "uri": "http://another-endpoint.com/entity_file/1", 
            "id": "1"
       }
   }
}
```

The image.file.uri, is an API which return the image url, which i need to show and be able to edit.
I'm unsure how i would be able to show/edit that image?

The API for updating an image is them same as the image.file.uri:  http://another-endpoint.com/entity_file/1

It needs to be showed and able to change inside a field

```javascript
nga.field('image.file.uri', 'file')
    .label('Picture')
,
```

Anyone able to help me?

**Comment by fzaninotto** [comment]
You'll need to write a custom directive. See ng-admin's Field directives (e.g. `maInputField`) and write the one you need.
