### ISSUE TITLE
Support nested entity route definition in menu

### ISSUE THREAD

**Issue by ace-han** [marmelab/ng-admin#596]
I would like to keep the route pattern in a consistent way according to menu item nested pattern.

e.g.:
```
menu1
  |--menu11
  |--menu12
menu2
  |--menu21
  |--menu22
  |--menu23
...
```

I'd like the route for `menu23` to be `http://foo.com/#/menu2/menu23/` instead of `http://foo.com/#/menu23/`

I found the `link()` for that menu item's `ng-click=gotoLink(menu)` is bound for `entity(entityName)`

Help me out if I miss out anything to achieve that, thx.

**Comment by fzaninotto** [comment]
If your menu leads to an entity list view, you don't have the choice over the route. ng-admin decides it. 

If your menu leads to a custom route of your own, use teh `menu.link()` method, as explained in https://github.com/marmelab/ng-admin/blob/master/doc/Menus.md.
