### ISSUE TITLE
File field for file upload

### ISSUE THREAD

**Issue by tsdima** [marmelab/ng-admin#597]
I am using ng-admin file field for file upload. 
When I use ng-admin-master version 24/06/2015 everything is working ok. In all browsers: IE, FF, Chrome.
But when I try to use later ng-admin-master version (for example 19/07/2015 or 06/08/2015) file upload does not work. In all browsers also.
What is wrong? What can cause this problem?

**Comment by fzaninotto** [comment]
@jeromemacias would you mind to take a look?

**Comment by tsdima** [comment]
Thanks
