### ISSUE TITLE
Chain multiple Reference Fields on the same ID

### ISSUE THREAD

**Issue by F3L1X79** [marmelab/ng-admin#600]
I was wondering if it is just me, but I can't chain Reference fields with the same ID - there is a duplication bug.

I'll use the example of the blog:
``` js
comment.listView()
            .title('Comments')
            .perPage(10) // limit the number of elements displayed per page. Default is 30.
            .fields([
                nga.field('created_at', 'date')
                    .label('Posted'),
                nga.field('author.name')
                    .label('Author'),
                nga.field('body', 'wysiwyg')
                    .stripTags(true)
                    .map(truncate),
                nga.field('post_id', 'reference')
                    .label('Post')
                    .map(truncate)
                    .targetEntity(post)
                    .targetField(nga.field('title').map(truncate)),
                //here is the second Reference Field I add with the post_id
                nga.field('post_id', 'reference')
                    .label('Views')
                    .targetEntity(post)
                    .targetField(nga.field('views'))
            ])
``` 
If I also want the 'Views' of a Post - the title which was fine also displays the Views number.
Is this a bug, or is there another way to code this?
Thanks a lot.

**Comment by fzaninotto** [comment]
Short answer: it's a feature. 

As ng-admin uses field names to build a Hash of values, you can't define two fields on the same name. 

The solution is to add an ElementTransformer (as explained in https://github.com/marmelab/ng-admin/blob/master/doc/API-mapping.md) to duplicate the entry into `post_id_2` for instance.

**Comment by F3L1X79** [comment]
And it's a nice answer, thank you!
