### ISSUE TITLE
Deleted reference field is not updated

### ISSUE THREAD

**Issue by F3L1X79** [marmelab/ng-admin#601]
On the latest branch, when you remove a reference field (which is not mandatory) on editionView(), then save - the field is not updated.

**Comment by fzaninotto** [comment]
I managed to reproduce the bug. Looking at it.

**Comment by fzaninotto** [comment]
Related to https://github.com/mgonto/restangular/issues/553: ui-select sets the value to `undefined` instead of `null` when removing the selection, and restangular strips the undefined values from the PUT query.
