### ISSUE TITLE
How " merge" referenced entity fields with appropriate fields of some entity

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [marmelab/ng-admin#602]
I have Person entity , which has embedded PersonCars object with information about car number and year and reference(id) for Car entity which contains information about abstract Car model - model name, producing country e.t.c. PersonCar is not entity it's just embedded reference table like M:M tabke in relational databases.

I want to get full information about Person in an edition/show views and even be able to do some custom actions with PersonCars .

I may render person name and last name via ```nga.field()``` and I may extract PersonCars by ```nga.field('cars','referenced_list')``` but **I can't complement references table with appropriate car_ref_table info like year and number**.  How to do it? 

I mean, ```nga.field``` with referenced type prints something like
```id model country ```
```1 bwm  German```
and printing complex cars json field which is actually PersonCars with 
```nga.field('cars').map(){grab required info from json array}``` gives me required information in ugly representation, one after one. I want to merge it in one table looking like
```id name, country number year```
```1 bmw german   A111NNN 2012```

where name,country taken from Car entity (by REST) and number and year taken from embedded json field and merge by id.

I'm planning to use templates and directives as it allows me to write custom HTML with custom actions but how add `nga.field("referemce') ` result (table, created from REST call results) to directive HTML?

 something like 

       app.directive('managePersonCars', ['$location', function ($location) {
        return {
            restrict: 'E',
            scope: { person: '=' },
            template: combine(person_json_html, reference_table_html)
            link: function (scope) {
                scope.send = function () {
                    console.log(scope.person);
                };
            }
        };
    }]);

where ```person_json_html``` is easy to me part and reference_table_html (which I don;t know hot to get ) is html of 

                nga.field('cars', 'referenced_list') // display list of related comments
                    .targetEntity(car)
                    .targetReferenceField('countryId')
                    .targetFields([
                        nga.field('id').isDetailLink(true),
                        nga.field('name').label('Model')
                    ]),

**Comment by fzaninotto** [comment]
Did you try adding a `reference` field type in the `targetFields`?

**Comment by BaurzhanSakhariev** [comment]
``reference`` field requires target entity and corresponding id. 
If I got you properly you mean cross reference like

     //person config
    nga.field('carRefs', 'referenced_list') // display list of related comments
                .map(truncate)
                .targetEntity(car)
                .targetReferenceField('id')
                .targetFields([
                    nga.field(id,'reference') // your suggestion
                        .targetEntity(person)
But  car.id not referenced to person id, it references to one of the embedded PersonCar objects. 

What I want to implement is support of embedded objects, key point is extract info from incoming JSON and use REST call with ``reference`` fields only for complementing embedded info.

**Comment by fzaninotto** [comment]
I'm not sure I understand what you want. If you just want to create a field based on an embedded object, just use the dot notation. So for instance if your Person object looks like:

```js
{
  id: 1234
  name: "John Doe",
  PersonCars: {
    number: "345 XZ 23",
    year: 2004,
    id: 3456
  }
}
```

Then you can create a reference to `PersonCars.id` as follows:

```js
nga.field('PersonCars.id', 'reference')
  .label('Car')
  .targetEntity(car)
  .targetField(nga.field('name'))
```

**Comment by Benew** [comment]
Hi! This is quite interesting!
I have a different use case. My object looks like this : 
```
{
  id: 1234
  name: "John Doe",
  PersonCars: [
    {
      number: "345 XZ 23",
      year: 2004,
      id: 3456
    },
    {
      number: "345 XZ 23",
      year: 2004,
      id: 3456
    }
  ]
}
```
and I'd like to declare a field like this : 
```
nga.field('PersonCars.id', 'reference_many')
  .label('Car')
  .targetEntity(car)
  .targetField(nga.field('name'))
```
How is that possible?
Also, I'm still looking for directions on how to implement a custom field type...

**Comment by BaurzhanSakhariev** [comment]
@fzaninotto I have array of person cars. I don't think reference is godd here. My data is the same as @Benew posted above. I exctracted carIds from nested json array via interceptor, but 
``nga.field('carIds', 'reference)`` didn't worked.  ``nga.field('carIds', 'reference_many)`` works but my goal is combining reference_many output (abstract model data) with concrete instance data such as year, number. 

Looks like custom type is the only solution but I didn't get from docs should I rebuild sources each time after I rewrite core sources? If I should rebuild is there Windows ``make`` alternative? It seems make works only under Linux what about building on Windows.

Thanks for your pervious clarifications.

**Comment by Benew** [comment]
@BaurzhanSakhariev Thanks for the interceptor, I already implemented that as it's the only valid solution.

**Comment by fzaninotto** [comment]
The new [`embedded_list` field type](https://marmelab.gitbooks.io/ng-admin/content/doc/reference/Field.html#-embedded-list-field-type) should cover this use case. Closing.
