### ISSUE TITLE
Authentication module for ng-admin

### ISSUE THREAD

**Issue by akagadovskiy** [marmelab/ng-admin#603]
Hi. I've created module for ng-admin called ng-admin.jwt-auth that allows to use JWT-based authentication. <a href="https://github.com/akagadovskiy/ng-admin-jwt-auth">Here</a> is the module. 
Check out <a href="https://github.com/akagadovskiy/ng-admin-jwt-auth-demoapp/">demo application</a> of ng-admin configured with this module.
I'd like to get some feedback about this idea and the module. Thanks!

**Comment by toxsick** [comment]
Nice, I will definitely give it a try..

**Comment by fzaninotto** [comment]
There is also https://gist.github.com/leonardorame/762f4978edbf7a4633b0

**Comment by toxsick** [comment]
I tried it and it works pretty nice with my eve based api. Thank you very much. Is it standard to send the credentials as `{"_username": <username>, "_password": <password>}` as payload during login?

**Comment by akagadovskiy** [comment]
Sure. I guess you use demo application. Check file public/app.js line 19. This is configuration of custom template. Check out public/customLoginTemplate.html lines 6 and 10. There are properties (ng-model)  that you can redefine, for example you need to send "pass" field instead of "_password"
change this
<pre>
<input type="password" id="inputPassword" class="form-control" placeholder="Password" ng-model="loginController.data._password" ng-required="true" ng-minlength="4" ng-enter="loginController.login()">
</pre>
to this
<pre>
<input type="password" id="inputPassword" class="form-control" placeholder="Password" ng-model="<b>loginController.data.pass</b>" ng-required="true" ng-minlength="4" ng-enter="loginController.login()">
</pre>

**Comment by toxsick** [comment]
Change what to what :) But, ok that's where I can customize the payload. Was just curious if `_username` and `_password` is the default in jwt-auth.

One more thing. What kind of response do I have to return to get the error message displayed? My api returns a 401 when using wrong credentials, but the red banner only shows `undefined`.

Thanks

**Comment by akagadovskiy** [comment]
@toxsick No, <pre>_username</pre> and <pre>_password</pre> isn't default in JWT-auth. About 401 response - if you are not authenticated and you are try to get secured url module automatically redirects you on login page. I suppose you send not valid data for your application. You need to configure login and password fields and may be configure header information (Authorization) - module allows to configure header.

**Comment by toxsick** [comment]
@akagadovskiy thanks for the info, but I think you misunderstood me. Everything works fine. I was only wondering what the response payload for 401 has to be in order to get a message shown in the red banner:

![bildschirmfoto 2015-08-27 um 11 14 30](https://cloud.githubusercontent.com/assets/951466/9516993/ce91b708-4cac-11e5-8ebf-22863c340d2b.png)

**Comment by akagadovskiy** [comment]
@toxsick for unsuccessful authentication you need to return JSON with field <pre>message</pre>

**Comment by toxsick** [comment]
Cool, thanks for the info!

**Comment by akagadovskiy** [comment]
@toxsick you are welcome :)

**Comment by fzaninotto** [comment]
The new demo application has a (naive) authentication that you can use as an example: https://github.com/marmelab/ng-admin-demo/blob/2fe01ea005e6332f843337d7c9e049ec6790f948/index.html#L12-L19

**Comment by cmnstmntmn** [comment]
@fzaninotto how more precisely make ng-admin use jwt? 
i can't figure it out where i can start looking into api_flavour.js

the *naive* authentication seems clear enough; but what about setting the auth API edge; 
does a user container should be made? does extra plugins are required?
thank you.

**Comment by fzaninotto** [comment]
@cmnstmntmn try the different links provided by other contributors in this discussion. Authentication isn't the core domain of ng-admin, so I won't have more details to provide, sorry.

**Comment by akagadovskiy** [comment]
@cmnstmntmn Hi. You can try to use <a href="https://github.com/akagadovskiy/ng-admin-jwt-auth/issues">this</a> module. It will help you to create JWT-authentication.
Feel free to open issues <a href="https://github.com/akagadovskiy/ng-admin-jwt-auth/issues">here</a>

**Comment by cmnstmntmn** [comment]
@akagadovskiy :+1: thank you, it works great

**Comment by anagrath** [comment]
This almost works with loopback which would be very nice.  The only things that are needed:

1. ability to set the login field to email or username (or whatever library user wants)
2. it complains that the token is not a JWT token because it does not have three parts.

If you did that then it would work with a broad set of token authenticated apps and would be really nice.
https://docs.strongloop.com/display/public/LB/Making+authenticated+requests
