### ISSUE TITLE
transform function is undefined on Field

### ISSUE THREAD

**Issue by dctdevelop** [marmelab/ng-admin#609]
Hi guys, the transform function is not available on the Field entity, as per the documentation. 

to reproduce on a fresh install, 

inside config:
```javascript
nga = NgAdminConfigurationProvider
field = nga.field('groups')
console.log(field.transform == undefined)
/*Throws error*/
field.transform(function(value){return value})
```

Great work on everything, really awesome implementation.

**Comment by fzaninotto** [comment]
The version you installed from npm (0.7.0) didn't have `Field.transform()` yet. I've just published 0.8.0-beta1, can you try again ?

**Comment by dctdevelop** [comment]
Hi @fzaninotto. 

I don't think you have pushed tags yet on the repo.

Im getting a not found error on bower when running update and changing the dependency to ng-admin#0.8.0-beta1

Regards

**Comment by fzaninotto** [comment]
@dctdevelop Fixed, sorry.

**Comment by dctdevelop** [comment]
@fzaninotto Thanks a lot, things are working as expected.
