### ISSUE TITLE
Uncompressed version of ng-admin.js and ng-admin-only.js

### ISSUE THREAD

**Issue by ace-han** [marmelab/ng-admin#614]
Please package the uncompressed version of `ng-admin.js` and `ng-admin-only.js` with release package.

For those people like me who are new to `ng-admin` it's good to have the uncompressed version as a good material to  learn from or debug when sth is wrong and the wiki not having it doc-ed 

Or please share with me how to package `ng-admin` with the src code via `webpack.config.js`. I did try but ended up with weird error on `WebSock`

![image](https://cloud.githubusercontent.com/assets/1177332/9459644/6b0fdb1a-4b30-11e5-8a00-59f8549ce708.png)

How to package an uncompressed version with webpack caveat like below

![image](https://cloud.githubusercontent.com/assets/1177332/9459697/e99b15b2-4b30-11e5-955a-1299f70ed53b.png)

plz kindly help me out, thx

**Comment by jpetitcolas** [comment]
A PR has already been created for this issue. Will be merged soon.

**Comment by fzaninotto** [comment]
In fact, that won't help you. The non-minified files are already transpiled from ES6, so they're barely readable. What you actually need are sourcemaps.

**Comment by fzaninotto** [comment]
Sourcemaps were added in #619
