### ISSUE TITLE
Configure reference_many to render table like in  references_list

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [marmelab/ng-admin#615]
Is it possible to configure ``reference_many`` ouput like in ``referenced_list``? 

I mean, render table with target fields as columns and accumulate all entities in this table.

Currently it looks not possible as ``reference_many`` config even hasn't targetFields only one targetField. 

If it not possible with standtart functions and I have to overwrite some sources could you please tell me, what  ``.js`` files should be modified? Is there any non-uglified built sources? (I want to combine rest calls from reference_many and rendering table from referenced_list)

**Comment by fzaninotto** [comment]
No, not for now. You'll have to build a custom type for that (see https://github.com/marmelab/ng-admin/blob/master/doc/Custom-types.md). 

There are no non-uglified built sources, but you now have a sourcemap!

**Comment by BaurzhanSakhariev** [comment]
Wow, you changed docs, thanks!
