### ISSUE TITLE
What js code should be written in registerFieldType pointing file?

### ISSUE THREAD

**Issue by BaurzhanSakhariev** [marmelab/ng-admin#617]
[Custom types doc](https://github.com/marmelab/ng-admin/blob/eb30bc1cf00ec1fe6b9fd1405d030fc16b2e6e03/doc/Custom-types.md) contains info about registering FieldView and example of custom FieldView javascript file contents.

Is there any example of code which I have to write in ``path/to/MyCustomDateField``?

I suggest it should be something similar to ma...Field.js files located in ``ng-admin/src/javascripts/ng-admin/Crud/field/`` but I'm not sure because I didn't manage to find ``nga.registerFieldType`` usages in ng-admin repository.

**Comment by fzaninotto** [comment]
I tried to make it clear in 8b9d186. Hope this helps.

**Comment by BaurzhanSakhariev** [comment]
Thanks!
