### ISSUE TITLE
Custom type definition directions

### ISSUE THREAD

**Issue by Benew** [marmelab/ng-admin#622]
Hey all!
I need directions to create a custom field type.
I store arrays of json objects in one of my models and I need a field to sort that array.
It would basically display a sortable list.
Problem is, the directions given in `doc/Custom-types.md` don't say in what environment to work.
Should I fork `admin-config` and add my new type in there, then fork `ng-admin`, update the `admin-config` dependency to match my repository and build the minified js??

As you can see, I'm pretty lost here.

Thanks in advance and cheers to your work!

**Comment by Benew** [comment]
The this I'm trying to accomplish is "pretty simple" : a sortable reference_many field type with the possibility of having objects of different types (entity) in the reference array : 

The feed gives me : 
```
{
    "appId": "55e00f7c7a988f9660cdc442",
    "name": "First category",
    "categories": null,
    "children": [
      {
        "type": "category",
        "id": "55e013727a988f9660cdc446"
      },
      {
        "type": "category",
        "id": "55e013907a988f9660cdc448"
      },
      {
        "type": "post",
        "id": "55e013b17a988f9660cdc449"
      },
      {
        "type": "post",
        "id": "55e013b97a988f9660cdc44a"
      }
    ],
    "id": "55e0135a7a988f9660cdc445"
  }
```
And I need to display each object of `children` in a sortable list and be able to save that array.
as you can see, `type` references the entity the object refers to.

I guess I have to create a custom field type but I don't know whether I'll need to for both ng-admin and ng-config or just extend a view...

**Comment by sylvainlap** [comment]
+1

**Comment by fzaninotto** [comment]
This really depends on which tools you're using (requirejs, browserify, webpack). Let me work on an example for webpack and publish it so that you can see a reference implementation.

**Comment by Benew** [comment]
yay! I guess I'll need to work on sources and build on the fly then? Thanks! I'm really looking forward to this!
