### ISSUE TITLE
How do I disable a couple of fields in an editionView? 

### ISSUE THREAD

**Issue by ahmedsuffian** [marmelab/ng-admin#623]

**Comment by fzaninotto** [comment]
Please provide more information, your question is too short. Example REST response, current configuration, and screenshot of the output are necessary to help you.

**Comment by ahmedsuffian** [comment]
Here is the editionView of a resource called 'Payments'. 
I just want to display the user ID (as shown in the screenshot), but I dont want it to be an editable field.

So how do I disable the user ID field? 

this is what I've coded
payments.editionView ()
.fields([
	nga.field('userId').label('User ID')
        ......
   ])'

![capture](https://cloud.githubusercontent.com/assets/11270047/9493098/b4b27e08-4c16-11e5-8ad2-f04d616f4591.PNG)

**Comment by fzaninotto** [comment]
Try adding the user id as a template field:

```js
nga.field('userId', 'template')
  .label('User ID')
  .template('{{ entry.values.userId }}')
```

**Comment by jpetitcolas** [comment]
Or simpler, you can use the `editable` method:

``` js
nga.field('userId').editable(false);
```

See related part in the [documentation](https://github.com/marmelab/ng-admin/blob/master/doc/Configuration-reference.md#general-field-settings).

**Comment by fzaninotto** [comment]
yep, @jpetitcolas' answer is better ;) !

**Comment by ahmedsuffian** [comment]
Thank you :)
