### ISSUE TITLE
infinitePagination does not resolve reference fields

### ISSUE THREAD

**Issue by toxsick** [marmelab/ng-admin#624]
Hey guys,

in my listView I use reference fields like this:

```
nga.field('make', 'reference')
    .map(truncate)
    .targetEntity(make)
    .targetField(nga.field('name').map(truncate))
```

This works absolutely fine with normal pagination. But if I use `.infinitePagination(true)` the references are only resolved for the first page. When the second page is loaded no calls are triggered to resolve the references. That's why only data is visible that had been already requested on the first page.

Here you can see what this looks like:

![angular_admin_und_datadock_und_datadock](https://cloud.githubusercontent.com/assets/951466/9500050/72d35d38-4c23-11e5-98af-58d6cdcd68b2.png)

HELP?

Best Regards
Hannes

**Comment by fzaninotto** [comment]
That's a bug, we'll need to investigate. In the meantime, please use normal pagination.
