### ISSUE TITLE
Pre-populate fields (for referenced_list)

### ISSUE THREAD

**Issue by TimoSolo** [marmelab/ng-admin#627]
Is there a way to create an "add" button on a referenced_list that links to the creation page with the targetReferenceField prepopulated with the current id?

**Comment by fzaninotto** [comment]
Nope, note at the time, but that's a good idea for a PR ;)

**Comment by TimoSolo** [comment]
might have to dig in the code and add it then ;)

**Comment by TimoSolo** [comment]
The listView idea would also help with another problem i have where I need to specify a url for a referenced_list. For example the api has a user: /users/123 and a list of friends at /users/123/friends/ 

I got it to work with an ugly hack: 
```
var users = nga.entity('users')
                        .url(function(entity, view, id, element) {
                            window.user_id = id;
                            return 'users/v1/users/' + ( id ? id+"/" : "" )
                        });
var friends = nga.entity('friends')
                        .url(function(entity, view, id, element) {
                            var user_id = window.user_id || "0"
                            return 'users/'+user_id+'/friends/' + ( id ? id+"/" : "" )
                        });
```
but would prefer a more elegant solution

**Comment by fzaninotto** [comment]
Use another entity object for your referenced_list?

**Comment by TimoSolo** [comment]
thats what im doing above ("friends" are also "user" objects), but the url to access them is different, so I had to create a new entity.

**Comment by Benew** [comment]
Maybe these issues should go to StackOverflow? François?

**Comment by TimoSolo** [comment]
I have asked on SO - no answers yet :(
http://stackoverflow.com/questions/tagged/ng-admin

**Comment by fzaninotto** [comment]
That's a perfectly valid solution, not a hack ;)
