### ISSUE TITLE
Guidelines for development environment

### ISSUE THREAD

**Issue by Benew** [marmelab/ng-admin#631]
I'd like to know how to contribute (create a custom post type) but it seems I'll have to build ng-admin.min.js every time I want to test my code.
I feel this is not how you core devs do it.
Am I right?

**Comment by jpetitcolas** [comment]
Indeed, it would be so painful!

To develop, we are using Webpack. Just use a `make run` command, and then connect on the demo at [http://localhost:8000](http://localhost:8000). You're ready to go! You can of course modify the sample configuration to test your custom developments.

Webpack dev server (on port 8080) would then rebuild automatically all required assets once they are changed, and a live-reload would even be made to prevent you from pressing F5. Lazy? Yes, we are! :)

**Comment by fzaninotto** [comment]
I updated https://github.com/marmelab/ng-admin/blob/master/README.md#running-the-example-app for more clarity.

**Comment by Benew** [comment]
Awesome! Thank you a whole lot! Et vive les devs ;-)

**Comment by Benew** [comment]
Well I don't know what's wrong but I'm getting this error when trying to `make run` : 
```
make: grunt: Permission denied
make: *** [run] Error 1
```
Any hints?
I never need root privileges to run node modules

**Comment by Benew** [comment]
That was it. You need grunt-cli installed (on OSX at least)

**Comment by Benew** [comment]
Well I can't seem to `make` it `run`.
I installed `grunt` and `grunt-cli` globally. It seemed I needed those.
What could be wrong now? Here is what the shell tells me : 
```sh
$ make run
Running "json_server:stub" (json_server) task
Loading database from examples/blog/stub-server.json
http://0.0.0.0:3000/postshttp://0.0.0.0:3000/commentshttp://0.0.0.0:3000/tagsStarted json rest server on http://0.0.0.0:3000

Running "connect:dev" (connect) task
Started connect web server on http://0.0.0.0:8000

Running "exec:webpack_watch" (exec) task
http://localhost:8080/webpack-dev-server/
webpack result is served from http://localhost:8080/
content is served from /Users/armellarcier/Code/ng-admin
>> Exited with code: 0.
Warning: Task "exec:webpack_watch" failed. Use --force to continue.

Aborted due to warnings.
make: *** [run] Error 3
```

**Comment by fzaninotto** [comment]
Very weird. Maybe a rights problem? Are you using a particular user?

**Comment by fzaninotto** [comment]
did you `make install` before?

**Comment by Benew** [comment]
Yes. I cloned your repo again instead of my fork and it's working. Will investigate.
Thanks!

**Comment by Benew** [comment]
@fzaninotto j'aurais besoin de ton avis sur la pertinence de l'utilisation de ng-admin pour mon projet. Possible de discuter 5 minutes?

**Comment by fzaninotto** [comment]
Try Gitter https://gitter.im/marmelab/ng-admin?utm_source=share-link&utm_medium=link&utm_campaign=share-link
