### ISSUE TITLE
create field for object key

### ISSUE THREAD

**Issue by JacerOmri** [marmelab/ng-admin#64]
hello,
the db model i'm using has a 'details' object where specific user details are stored. I couldn't create a field for its items.

creating a field using 'details' as a name would show the json string of it. i tried to create a field with 'details.key', but it didn't work. Any idea?

**Comment by fzaninotto** [comment]
Does the new `json` field fit your needs?

**Comment by alejandro145** [comment]
nga.field('profile', 'json')
this shows the entire profile field

how can you show only one profile property, eg. "profile.name" ?

**Comment by fzaninotto** [comment]
Using an element transformer, as in https://github.com/marmelab/ng-admin/blob/master/doc/API-mapping.md#entry-format

**Comment by alejandro145** [comment]
Thanks @fzaninotto && ng-admin.

**Comment by cmnstmntmn** [comment]
```json
"data": [
   {
      "stats": {
          "OPEN": {
                   "count":0
           }
      }
   }
]
```

you would have:

```javascript
nga.field('bounce_count').map((v, e) => e.data[0].stats.OPEN.count)
```
