### ISSUE TITLE
camelCase in parent attribute while accesing it's child attribute not working

### ISSUE THREAD

**Issue by dsinghr** [marmelab/ng-admin#646]
```javascript
nga.field('deliveryCharges') // working fine


nga.field('deliveryCharges.value') // error
/*
Console showing error:
Error: t is null
*/

```

**Comment by fzaninotto** [comment]
I'll need more details. Can you paste an example entitty from your REST endpoint?

**Comment by Dev2014** [comment]
This error is occuring in editionView(). 

Json response containing some attributes that are optional server side. In editionView() if json response doesn't return the 'deliveryCharges' attribute (as shown above), and if I try to update the entity with new values in 'deliveryCharges' by entering charges in input text:
```javascript
nga.field('deliveryCharges.value')
```
then it return the error mentioned above.

In contrast, if the server return a value for 'deliveryCharges.value' then in editionView it get prefilled with value and works as desired. Kindly try to regenerate the issue. Let me know if you need more info.

**Comment by Dev2014** [comment]
Detailed firebug error stack trace:
![_temp](https://cloud.githubusercontent.com/assets/6710614/9655561/904b6536-524f-11e5-9f85-4ca97d685be2.png)

**Comment by dsinghr** [comment]
I figured it out. Actually 'deliveryCharges' from endpoint was returning null and while adding attribute to it. It was throwing "t is null" error. I configured my server to not to send null values in response, and now everything is working.
