### ISSUE TITLE
AdminLTE theme

### ISSUE THREAD

**Issue by Zyles** [marmelab/ng-admin#648]
I like this project and the idea but I don't like the theme. How hard would it be to run any other custom bootstrap admin theme?

I think you should consider changing the default theme to http://almsaeedstudio.com/

It is open source and very nice.

Thanks.

**Comment by fzaninotto** [comment]
Hi,

ng-admin supports [theming](https://github.com/marmelab/ng-admin/blob/master/doc/Theming.md), so you can change the bootstrap admin theme you want.
