### ISSUE TITLE
Numbers and Floats should be right aligned

### ISSUE THREAD

**Issue by TimoSolo** [marmelab/ng-admin#658]
how do I right align numbers?

**Comment by Dev2014** [comment]
You can use template method.

**Comment by fzaninotto** [comment]
```js
nga.field('total', 'number')
   .cssClasses('text-right')
```

**Comment by TimoSolo** [comment]
Thanks. I'll do that. 
However, I do think numbers should default to right alignment. Its the standard in every spreadsheet I've used. 
(http://ux.stackexchange.com/questions/13795/is-there-a-standard-to-left-justify-text-and-right-justify-numeric-values)

**Comment by fzaninotto** [comment]
You're right, I'll whange the default.

**Comment by TimoSolo** [comment]
nice! Thanks
