### ISSUE TITLE
actions for business commands?

### ISSUE THREAD

**Issue by abstratt** [marmelab/ng-admin#665]
I tried to find documentation for this but could not find anything. Can ng-admin expose business actions that can be applied to the API resources? For instance, I have an Expense resource, and I want to expose UI actions that allow the user to approve it or reject it (specifying a reason).

For an example of a similar application, check this [sample application](http://develop.cloudfier.com/services/ui/test-cloudfier-examples-expenses/root/source/). Browse the expenses and note how there actions such as Approve/Reject/Reconsider etc  as you select them. To be clear, I am not asking about a similar layout, just whether I can expose API-backed business operations such as those.

**Comment by fzaninotto** [comment]
You're using Angular.js. Anything that you don't know how to do with ng-admin, implement the feature using angular. That's the philosophy of ng-admin.

An example of custom action can be found in Posters Galore:

![image](https://cloud.githubusercontent.com/assets/99944/9715009/9cf1e0f2-555c-11e5-8f20-a1ce0bbbeaf7.png)

* https://github.com/marmelab/ng-admin-demo/blob/83b12a98f19828a7c263fdfae4f590d0b6574cc0/js/entities/reviews.js#L65
* https://github.com/marmelab/ng-admin-demo/blob/83b12a98f19828a7c263fdfae4f590d0b6574cc0/js/main.js#L18
* https://github.com/marmelab/ng-admin-demo/blob/83b12a98f19828a7c263fdfae4f590d0b6574cc0/js/directives/approveReview.js

**Comment by abstratt** [comment]
Thanks for the thorough explanation. I do think proper action support would be important for ng-admin. Opened a feature request (#670) for that.
