### ISSUE TITLE
Getting Started refers to config.js and admin.js

### ISSUE THREAD

**Issue by abstratt** [marmelab/ng-admin#671]
See:

https://github.com/marmelab/ng-admin/blob/master/doc/Getting-started.md

At times it mentions config.js, at others it mentions admin.js, which is confusing. Are they supposed to be the same thing (and if so, the inconsistency should be addressed) or are they actually two different files?

**Comment by fzaninotto** [comment]
Thanks for the heads up. There is only one file, named `admin.js`. The tutorial is now fixed.
