### ISSUE TITLE
reference field should honor target entity URL

### ISSUE THREAD

**Issue by abstratt** [marmelab/ng-admin#679]
I provide a URL computing function (instead of a simple string) for all my entities, and that is working fine.

However, when I declare a reference field having another entity as the target entity, apparently ng-admin will ignore the url function and try to compose the URL to fetch candidates to populate the reference field drop down by itself, which leads to a 404.

**Comment by abstratt** [comment]
As a workaround, I realize now I can declare the url function again when setting the target entity of a reference field.

If that is by design, go ahead and close it, I was expecting two different calls to nga.entity('foo') would return the same entity object.

**Comment by fzaninotto** [comment]
Could you paste some code to illustrate your point? I'm not sure I understand it clearly.

**Comment by abstratt** [comment]
A declare an entity like this:
```
nga.entity('products').url(urlBuilder)
```
where urlBuilder is a function. Then later when configuring a different related entity:

```
nga.entity('items').url(urlBuilder)
    ...
    .field('itemProduct', 'reference')
    .targetEntity(nga.entity('products').url(urlBuilder))
    .targetField(nga.field('productName'));
```

I was surprised that I had to set the URL function again when relating items to products. My expectation was that doing it once for the products entity should be enough, but is not (ng-admin ends up using the default url).

**Comment by fzaninotto** [comment]
Indeed, `nga.entity()` is a constuctor. If you want to reuse the same entity, you'll have to pass it through (see [how we did it in the demo](https://github.com/marmelab/ng-admin-demo/blob/2d3166e211d9a18a6ac9267d5b70a9d12ae8c613/js/products/config.js#L28)).

So this is by design.
