### ISSUE TITLE
Nested property column doesn't sort properly

### ISSUE THREAD

**Issue by khuppenbauer** [marmelab/ng-admin#680]
Is it possible to sort by a nested property?
I want to sort a list of books by the author's name (not by the id)
The field in the listView is defined as "author.name" but the _sortField in the sort request is still "author" and not "author.name"

**Comment by fzaninotto** [comment]
Not in ng-admin, but using a request interceptor you can probably do it easily.

**Comment by khuppenbauer** [comment]
Thx for the answer. Is there a generic way to get the "original" field configuration or is it more hardcoded there?

**Comment by fzaninotto** [comment]
Sorry, I misread your question. This is a bug indeed.
