### ISSUE TITLE
help for Referenced_List not working

### ISSUE THREAD

**Issue by ngiacobbe** [marmelab/ng-admin#687]
Hi guys,
was trying to learn basics of ng-admin and I was setting up a one-to-many relationship on a show view but I got all entities(not just the one in the relationship) of entity displayed despite the targetReferenceField(model_id) on this test data:

Entity1:[ {"id":1,"model_id":4,"code":"65"...},{"id":2,"model_id":3,"code":"66"...}]
Entity2: {"id":3,"modelNumber":469,"name":"Test"...}

Entity2 has many Entity1 via model_id and I want to display all entity1 related to an entity2 in a showView using referenced_list type

ng-admin configuration for entity2 show view

``` js
entity2.showView().fields([
        nga.field('id'),
        nga.field('modelNumber'),
        nga.field('entity1_list', 'referenced_list')
            .targetEntity(entity1)
            .targetReferenceField('model_id')
    ]);
```

it seems that `model_id=entity2.id` filter is not executed somehow or am I doing something wrong on config/data side 

thanks

**Comment by jpetitcolas** [comment]
Can you check your API call via the Chrome console?

For these getting started questions, come on [Gitter](https://gitter.im/marmelab/ng-admin). :)

**Comment by fzaninotto** [comment]
Hi @ngiacobbe, did you manage to solve your problem?

**Comment by ngiacobbe** [comment]
Hi @fzaninotto yes thanks to @jpetitcolas and ng-adming gitter, actually was my bad because of a missing implementation in the Rest API
