### ISSUE TITLE
Is there a way to use textAngular's taApplyCustomRenderers with ng-admin?

### ISSUE THREAD

**Issue by edrpls** [marmelab/ng-admin#689]
Hi, I want to save the content of the wysiwyg value to the server in order to display custom embeds from soundcloud and vimeo. I've [found that the way](http://stackoverflow.com/a/25027216/1335287) to do it is using taApplyCustomRenderers from textAngular, but I'm not sure how it would integrate with ng-admin.

Thanks for your help.

**Comment by fzaninotto** [comment]
For now, you'll need to use a `template` field instead of a WYSIWYG field, with the exact markup you want. In the future, all field types may support the `.template()` method.
