### ISSUE TITLE
Is it possible to nest collection list results?

### ISSUE THREAD

**Issue by stanlemon** [marmelab/ng-admin#69]
Is there a way to allow for the collection returned by a collection request to be nested under a "results" property?  Something akin to this:

```
{
  "results": []
}
```

Rather than just

```
[]
```

For the response?

Thanks for your help!

**Comment by sebest** [comment]
This should be added to the wiki here: https://github.com/marmelab/ng-admin/blob/master/doc/API-mapping.md

**Comment by sebest** [comment]
and it seems that the way to do it now is:
```
  RestangularProvider.addResponseInterceptor(function (data, operation, what, url, response, deferred){
      if (operation === 'getList') {
          return data.results;
      }
      return data;
  })
```

**Comment by fzaninotto** [comment]
Yep, `entity.interceptor()` is removed in latest versions, and the right way to do it is correctly described in the API-mapping doc.
