### ISSUE TITLE
Default value in initial filter state

### ISSUE THREAD

**Issue by marknelissen** [marmelab/ng-admin#690]
It would be nice to have an option when defining the filters to give them a default value. The use case we have, is that the default view of the list should be to only show the clients of the current user, but with an option to deactivate this filter to view all clients. Currently this is not possible, since the permanent filter cannot be interacted with by the user, and we cannot set a default value in a regular filter, that is applied on first/initial visit to the page.

The idea is to be able to specify what the initial state of the filters should look like, including values, on first visit or after reset, instead of the current behaviour of setting all filters to blank.

**Comment by fzaninotto** [comment]
Already done in #639, please use the master branch.
