### ISSUE TITLE
Replacing REST with Websockets

### ISSUE THREAD

**Issue by rszczypka** [marmelab/ng-admin#692]
This project looks really good and thank you for all the work you have put into it.
I wonder how easy would it be to replace REST with a websocket? 
Any suggestions where to start?

I'm thinking about using https://github.com/wilk/ng-websocket
and most of the list tables will work in real time. 

I would really appreciate your comments.

**Comment by fzaninotto** [comment]
Hi, this is a great idea, but not for ng-admin. 

We choose to use one-way databinding in many cases for performance reason (e.g. in the listView), and that wouldn't reflect changes in the backend side broadcast by the websockets. Besides, all the REST plumbing in ng-admin is done by Restangular, and we don't intend to redo it all. Lastly, REST is a HTTP format, and I don't know any related standard for websockets (apart from [WAMP](http://wamp.ws/), which is still very young IMO).

So if you want to build an admin based on websockets, and use ng-admin as a base, be my guest! But I doubt any of your work can be reused in ng-admin.
