### ISSUE TITLE
baseApiUrl

### ISSUE THREAD

**Issue by Shazam14** [marmelab/ng-admin#695]
Hello,
does it apply to sails also? because i tried to use http://localhost:1337 but it is giving me the same ?_sort=id&page=1&per_page=10 and state error unchanged.

**Comment by fzaninotto** [comment]
ng-admin is designed to work with a given flavor of REST. If your REST service has a different flavor, you'll have to map the two flavors, as explained in the [API mapping documentation](https://github.com/marmelab/ng-admin/blob/master/doc/API-mapping.md).

I don't know about sails.js.

**Comment by Shazam14** [comment]
Ok noted.


Thank you! 


Sent by Outlook for Android





On Mon, Sep 21, 2015 at 1:23 AM -0700, "Francois Zaninotto" <notifications@github.com> wrote:












ng-admin is designed to work with a given flavor of REST. If your REST service has a different flavor, you'll have to map the two flavors, as explained in the API mapping documentation.



I don't know about sails.js.
