### ISSUE TITLE
How to separate the ng-admin configuration into multiple configuration blocks?

### ISSUE THREAD

**Issue by GeBeater** [marmelab/ng-admin#699]
I am going to separate the ng-admin configuration into multiple configuration blocks to prevent a bloated configuration and achieve some kind of "Separation of Concerns". I want to configure the entities, the dashboard, the menue, the application and and all other components independently.

This intention required to inject the affected objects (like the ng-admin application) into the AngularJS configuration blocks which only possible with providers and constants (see [Developer Guide - Module Loading & Dependencies](https://docs.angularjs.org/guide/module)).

So I have alienated a provider in the way below to realize my intention. __However it feels bad. Has anyone a better solution?__

_ngadmin.application.provider.js_
```javascript
(function() {
  'use strict';

  angular
    .module('app.ngadmin')
    .provider('adminApplication', adminApplication);

  /** @ngInject */
  function adminApplication(NgAdminConfigurationProvider) {
    var application = null;
    var provider = {
      getApplication: function() {
        if (application === null) {
          application = NgAdminConfigurationProvider.application('');
        }
        return application;
      },
      $get: function() {
        return {};
      }
    };
    return provider;
  }
})();
```

_ngadmin.application.config.js_
```javascript
(function() {
  'use strict';

  angular
    .module('app.ngadmin')
    .config(config);

  /** @ngInject */
  function config(adminApplicationProvider, APIConfig) {
    adminApplicationProvider.getApplication().title('TBD').baseApiUrl(APIConfig.BASE_URI + '/');
  }
})();

```

The issue also mentioned in #608

**Comment by fzaninotto** [comment]
[ng-admin-demo](https://github.com/marmelab/ng-admin-demo/blob/gh-pages/js/main.js) is a great example for wht you're trying to achieve.

**Comment by GeBeater** [comment]
Thanks for your response. I had already noticed the example you are mentioned. However that does not solve the conceptual. The example plain "includes" code separated in multiple files or functions. That is not the "software engineering" way I am looking for. Not least because the example is not really unit testable.

**Comment by fzaninotto** [comment]
Not unit testable? All entity configs use plain old dependency injection, so they're unit testable in isolation (even without Angular.js). I don't know what you're looking for. And since when inclusion is a bad practice?

I don't understand your point, that must be because I'm a bad software engineer.

**Comment by GeBeater** [comment]
Whoops Francois! I hope that you are not feel offended!? Sorry! :-(

I am going to create separated packages or rather components with the AngularJS tools and would like using the dependency injection mechanism of AngularJS. I would not started to using any require calls inside any functionality of the application.

**Comment by fzaninotto** [comment]
Well, if you want to avoid putting all your code in a single file (THAT is a bad practice), you'll have to use `require` anyhow (do you prefer adding several dozen `<script>` tags to your HTML?). 

Look at how we define services as standalone functions in ng-admin, then [register them as services](https://github.com/marmelab/ng-admin/blob/9b443ec9ecd737374e772e58dd50a3035946d8fc/src/javascripts/ng-admin/Main/MainModule.js) only in the Angular context.

To my mind, if you need angular.js to test a service, you're too much coupled to your framework.
