### ISSUE TITLE
Can not change request operation with using addFullRequestInterceptor

### ISSUE THREAD

**Issue by AlexH7** [marmelab/ng-admin#705]
For a deleting operation my application should use PUT method instead DELETE.
So, I catch my 'remove' operation on addFullRequestInterceptor and I try to change it to 'put' operation for updating some other element.

    myApp.config(['RestangularProvider', function (RestangularProvider) {
        RestangularProvider.addFullRequestInterceptor(function (element, operation, what, url, headers, params) {
    if (operation == "remove") {
            operation = "put";
        }

        return {
            operation: operation
        };        
    });

But ng-admin continues to do request with DELETE method. Is it some bug or my mistake? And how I can resolve my issue?

**Comment by AlexH7** [comment]
I have used for changing POST to PUT:
  entity.createMethod('put'); 
But as for changing 'DELETE' to 'PUT' there are no decision yet.

**Comment by SebLours** [comment]
Hi,

I don't think you can do that with a request interceptor ...

Look at the RestWrapper, perhaps you can extend it with your own logic.

```javascript
RestWrapper.prototype.deleteOne = function(entityName, url) {
    return this.Restangular
    .oneUrl(entityName, url)
        .customDELETE();
};
```

**Comment by AlexH7** [comment]
I have used $httpProvider for this goal:
            httpProvider.interceptors.push('httpInterceptor');

            $provide.factory('httpInterceptor', function ($q) {
                return {
                    // optional method
                    'request': function (config) {
                        if (config.deleteEntityMethod) {
                            config.method = config.deleteEntityMethod;
                        }

                        return config;
                    },               
                };
            }

            RestangularProvider.addFullRequestInterceptor(function (element, operation, what, url, headers, params, httpConfig) {
                httpConfig.deleteRule = "PUT";
                
                return {
                            httpConfig: httpConfig
                        };
            }

It works for me.

**Comment by fzaninotto** [comment]
Confirmed, the way to go is to use an interceptor on `$http`, as explained by @AlexH7
