### ISSUE TITLE
maFilter custom template

### ISSUE THREAD

**Issue by cmnstmntmn** [marmelab/ng-admin#710]
i am trying to rewrite the **maFilter** directive, by passing a custom template to it.

but, on [this line](https://github.com/marmelab/ng-admin/blob/master/src/javascripts/ng-admin/Crud/filter/maFilter.js#L22) , there's `${filterWidgetTypes}`, and the **map** involved, does not behave properly.

**Comment by cmnstmntmn** [comment]
fixed, **lodash** was required, but never loaded

`npm install lodash --save` should work

**Comment by fzaninotto** [comment]
I understand that there is no bug in ng-admin, so I close this issue. Feel free to repoen it if you think something is wrong in the source.
