### ISSUE TITLE
replacing angular-bootstrap with angularStrap

### ISSUE THREAD

**Issue by githubGabriela** [marmelab/ng-admin#715]
Hey guys,

Did you considered replacing angular-bootstrap with angularStrap in ng-admin?
AngularStrap offers some features than angular-bootstrap doesn't provide(e.g. timepicker).
I don't know if you are using some features from angular-bootstrap that angularStrap doesn't provide. 

Thankx!

**Comment by fzaninotto** [comment]
Hi,

No, we haven't considered that. That would imply a major rewrite of many directives, so it's very unlikely that we do that in the near future.
