### ISSUE TITLE
Fields' template function is not defined

### ISSUE THREAD

**Issue by ilyabo** [marmelab/ng-admin#716]
Contrary to the [documentation](https://github.com/marmelab/ng-admin/blob/master/doc/Configuration-reference.md#general-field-settings) the `.template()` function is not defined on fields.

Having this:
```
    nga.field('amount', 'number')
            .format('$0,000.00')
            .template('<span ng-class="{ \'red\': value < 0 }"><ma-number-column field="::field" value="::entry.values[field.name()]"></ma-number-column></span>')
``` 

Results in exception: 
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to:
TypeError: nga.field(...).format(...).template is not a function
```

Using `0.9.0-dev`

**Comment by fzaninotto** [comment]
The built files were not updated. I've just done it in e8a9b13.

**Comment by ilyabo** [comment]
thanks, that was quick!

**Comment by ilyabo** [comment]
I need some more help, though :)

can I do something like this via `.template()`:
```
    nga.field('logo')
      .template('<img src="api/organization/logo::entry.values[field.id()]">'),
```
or do I need to create a custom type with custom renderers?

**Comment by fzaninotto** [comment]
Of course you can. Just use Angular's templating system:

```js
 nga.field('logo')
      .template('<img src="api/organization/logo{{ entry.values.logo }}">'),
``` 

Note that the current ` value`  is always in the scope, so you can simply write:

```js
 nga.field('logo')
      .template('<img src="api/organization/logo{{ logo }}">'),
```

Hope that helps.

**Comment by ilyabo** [comment]
Yes, thanks a lot!  (new to angular, would prefer to use react-admin, but it doesn't seem to be developed as actively)

**Comment by frank0ch0a** [comment]
Hi I installed by  bower, and I received the same error , how update to new version ? I need clone repository?

**Comment by fzaninotto** [comment]
Yes, you need to clone the repository, or use `marmelab/ng-admin` as a npm dependency.
