### ISSUE TITLE
Enhancement, order fields on view by order function

### ISSUE THREAD

**Issue by jamespsterling** [marmelab/ng-admin#719]
When defining a view by extending another view, I'd like to be able to order fields in custom order.

**Comment by fzaninotto** [comment]
what do you mean, 'extending another view'? Could you show us some code?

**Comment by jamespsterling** [comment]
For example I have a creation view defined above, and the edit view:
```
    submissions.editionView().fields(
        nga.field('submittedById', 'reference')
            .label('Submitted By')
            .targetEntity(user)
            .targetField(nga.field('name'))
            .editable(false),

        nga.field('dateSubmitted', 'datetime')
            .label('Date Submitted')
            .format('medium')
            .editable(false)
            .order(1),

        nga.field('dateAccepted', 'datetime')
            .label('Date Accepted')
            .format('medium')
            .editable(false),

        nga.field('updatedById', 'reference')
            .label('Updated By')
            .targetEntity(user)
            .targetField(nga.field('name'))
            .editable(false),

        nga.field('dateUpdated', 'datetime')
            .label('Date Updated')
            .format('medium')
            .editable(false),
        submissions.creationView().fields()
    ).actions(['<approve-submission review="entry"></approve-submission>', 'list', 'show', 'delete']);
```

I'd like to be able to choose the order of the fields on the UI render.

**Comment by fzaninotto** [comment]
Then why don't you put them in another order? It's just a JS array, do whatever you want with it, like calling `sort()` on it. I don't see what ng-admin can do here, it's your responsibility IMO.

**Comment by jamespsterling** [comment]
When the submission creation view is merged with the edition view, I have little control over how the fields are ordered.

**Comment by fzaninotto** [comment]
Then define all the fields upfront, and define their order when settings the `.fields()`. You have the power of JavaScript to help you, so [The Only Limit Is Yourself™](http://zombo.com/).
