### ISSUE TITLE
list view with cursor based pagination

### ISSUE THREAD

**Issue by guptachirag** [marmelab/ng-admin#720]
is it possible to use ng-admin listview with cursor based pagination ?

I am able to get the first page but cannot figure out how to get next page based on cursor provided in response of first page

**Comment by fzaninotto** [comment]
Did you read https://github.com/marmelab/ng-admin/blob/master/doc/API-mapping.md#pagination?

**Comment by guptachirag** [comment]
Yes i did, In the given example offset is calculated using ng-admin params but in my case cursor is a long string which can not be calculated using "_page", "_perPage" parameters.It needs to be stored somewhere on client to be used in next page request.

**Comment by fzaninotto** [comment]
Can you elaborate on the long string calculation? And if it most be stored client-side, then store it client-side, I don't see the problem.

**Comment by guptachirag** [comment]
Cursor string is calculated on server.I generally store it in data attribute of "next" button and append it with URL when that button is clicked.I could not figure out how to do it in ng-admin.

**Comment by fzaninotto** [comment]
So you need:

- a response interceptor to catch and store the cursor on `getList` requests
- a request interceptor to change the pagination parameters with the one stored previously.

It's all in Restangular, and described in https://github.com/marmelab/ng-admin/blob/master/doc/API-mapping.md.
