### ISSUE TITLE
Support for specifying a different URL for filter and reference queries

### ISSUE THREAD

**Issue by spfjr** [marmelab/ng-admin#722]
I noticed that you can specify a non-default URL for different entities and views, but I don't see anything about being able to specify a URL for a filter or reference query.

I'm using Spring JPA and Spring Data REST on the backend. By default for each entity, it creates the basic request handlers for the common HTTP methods. You can create other endpoints/query methods, but those are mapped to /{entityName}/search/{queryName}. An example of a filter query would be `/animals/search/findByNumberOfLegs?numLegs=4`. An example of a reference list query would be `/species/search/findByGenusId?genusId=15`.

It would be nice to be able to use the default URL for normal entity queries and be able to specify another URL for filter and reference queries.

**Comment by fzaninotto** [comment]
It's not supported by ng-admin, however you can do it with an ` $http`  interceptor (see https://github.com/marmelab/ng-admin/blob/master/doc/API-mapping.md#nested-relationships-urls).
