### ISSUE TITLE
embedded list related

### ISSUE THREAD

**Issue by vsharm22411** [marmelab/ng-admin#723]
Hi, 
noticed that the embedded list issue is being resolved (WIP)

When is it going to be completed ? 
when we download the branch, there are missing files (js files - examples/blog/build/sinon-server.js).  how do we use the branch code

Pls advise

**Comment by jpetitcolas** [comment]
For the record, the WIP PR is #714.

**Comment by vsharm22411** [comment]
Hi, 
When we download the branch (ng-admin-embedded-list) and try to use this as a module with our application, system throws an error of unknown field type 'embedded_list'.

How do we use this branch into the main software (or is there some way to download and use )

Vikas

**Comment by fzaninotto** [comment]
The work is ongoing, in a branch. If you want to use the branch, you must rebuild ng-admin. However, I don't recommend it until it's merged to master (which should occur sometime next week).

Also, for this kind of question, please use the Gitter room - it's better than polluting the mailbox of all the people who watch the project.

**Comment by jpetitcolas** [comment]
The Gitter link: https://gitter.im/marmelab/ng-admin
