### ISSUE TITLE
referenced_list or reference_many fields as filters

### ISSUE THREAD

**Issue by josephwmorse** [marmelab/ng-admin#727]
Is there a way to use a referenced_list or reference_many field as a filter field?  Neither seems to work for me - referenced_list generates an explicit error, and reference_many just doesn't work.  This is the relevant code (using the 0.8.0 release):

<pre>
projects.listView()
.filters([
    nga.field('id','number'),
    nga.field('name'),
    nga.field('state', 'reference_many')
        .targetEntity(admin.getEntity('states'))
        .targetField(nga.field('name'))
        .label('State')
])
</pre>

If this is not supported, is there a workaround to implement category searches (i.e. state=California OR state=Texas)?

**Comment by Gargam** [comment]
Same here.

The doc mentions that it should work "Filter fields can be of any type, including reference. This allows to define custom filters with ease."

I guess referenced_list and reference_many has been added after.

**Comment by fzaninotto** [comment]
`referenced_list` cannot be used as a filter - I don't see how it would work. `reference_many` should work, it's a bug indeed.
