### ISSUE TITLE
Can't have a reference field targeting a template field.

### ISSUE THREAD

**Issue by TheBlusky** [marmelab/ng-admin#729]
Hi ! Very nice ng app :-)

I have the follwing entities :

    var localisation = nga.entity('localisations');
    localisation.listView().fields([
        nga.field('code_cp'),
        nga.field('nom'),
        nga.field('pays'),
        nga.field('clean','template')
            .template("{{ entry.values.code_cp }} {{ entry.values.nom }} ({{ entry.values.pays }})")
    ]);
    admin.addEntity(localisation);

    var maison = nga.entity('maison');
    bien.listView().fields([
        nga.field('id'),
        nga.field('ref'),
        nga.field('localisation', 'reference')
            .targetEntity(localisation)
            .targetField(nga.field('clean'))
    ]);

When I go to the "Localisation" entity page, I have a "clean" columns.
When I go to a "Maison" entity page, the "Localisation" columns is empty.
If I use "targetField(nga.field('nom')), it's working.

So I guess, reference can't target a template field.
Is it a bug, a feature, or an enhancement request ?

Thanks !

EDIT:
I got kind of a workaround, redefining the cleanfield n targetField function : 

    bien.listView().fields([
        nga.field('id'),
        nga.field('ref'),
        nga.field('localisation', 'reference')
            .targetEntity(localisation)
            .targetField(nga.field('nom')
                .template("{{ entry.values.code_cp }} {{ entry.values.nom }} ({{ entry.values.pays }})"))
    ]);
    bien.editionView().fields([
        nga.field('id'),
        nga.field('ref'),
        nga.field('localisation', 'reference')
            .targetEntity(localisation)
            .targetField(nga.field('nom')
                .template("{{ entry.values.code_cp }} {{ entry.values.nom }} ({{ entry.values.pays }})"))
            .remoteComplete(true, {
                searchQuery: function(search) {
                    return {q:search};
                }
            }),
    ]);

It's working on the "listView" page, but not on the "editionView" page.

**Comment by fzaninotto** [comment]
It's normal that you need to define the field for each view - ` nga.field()` isn't a getter, it's a factory function.

What do you mean by

> It's working on the "listView" page, but not on the "editionView" page.

Because I managed to have template fields work as targetField in a reference in an editionView.

**Comment by TheBlusky** [comment]
Ok, so using a template in a listView, it's working fine:
http://i.imgur.com/K5v9qP3.png

However, on editView. Using this code:

    bien.editionView().fields([
        nga.field('id'),
        nga.field('ref'),
        nga.field('localisation', 'reference')
            .targetEntity(localisation)
            .targetField(nga.field('clean','template')
                .template("{{ entry.values.code_cp }} {{ entry.values.nom }} ({{ entry.values.pays }})"))
            .remoteComplete(true, {
                searchQuery: function(search) {
                    return {q:search};
                }
            }),
    ]);

I got the following screen  (and if I click on the autoCompleteFied, it's empty):
http://i.imgur.com/iCWjvIB.png

And it's not an API issue, cause using this code:

    bien.editionView().fields([
        nga.field('id'),
        nga.field('ref'),
        nga.field('localisation', 'reference')
            .targetEntity(localisation)
            .targetField(nga.field('nom')
            .remoteComplete(true, {
                searchQuery: function(search) {
                    return {q:search};
                }
            }),
    ]);

I got the following screen :
http://i.imgur.com/PklNMgW.png

**Comment by TheBlusky** [comment]
As I was unable to perform this action, I added my custom field in a request interceptor. It's working fine, but it's still a workaround.

**Comment by fzaninotto** [comment]
Ok, I can reproduce and confirm it's a bug.

**Comment by fzaninotto** [comment]
That's not a bug. The dropdown displays options using a string, and allowing directives in there is a problem. So templates for targetField are not interpreted. 

There is, however, an alternative: the `map()` function. See for instance how the customer filter field does in [the Posters Galore demo](https://github.com/marmelab/ng-admin-demo/blob/8a1bec89a3e12ff24ba14b17363caad4ff47d01d/js/commands/config.js#L30-L36):

```js
            nga.field('customer_id', 'reference')
                .label('Customer')
                .targetEntity(admin.getEntity('customers'))
                .targetField(nga.field('last_name').map((v, e) => e.first_name + ' ' + e.last_name))
                .remoteComplete(true, {
                    searchQuery: function(search) { return { q: search }; }
                }),
```

**Comment by TheBlusky** [comment]
Merci ! Worked like a charm :-)
