### ISSUE TITLE
Issue with Permanent filters

### ISSUE THREAD

**Issue by vsharm22411** [marmelab/ng-admin#731]
I am trying use permanent filters in a referenced_list by relating organizations and relations. 

I am able to display the relations which are related to an organization but when i try to filter these by relationID by adding a permanent filter the URL does not contain the relationID as a query parameter. 

Pls advise

(function () {
    "use strict";

var myApp = angular.module('myApp', ['ng-admin']);

myApp.config(['NgAdminConfigurationProvider', 'RestangularProvider', function (NgAdminConfigurationProvider, RestangularProvider) {
    var nga = NgAdminConfigurationProvider;

    function truncate(value) {
        if (!value) {
            return '';
        }

        return value.length > 50 ? value.substr(0, 50) + '...' : value;
    }
    
//    function pagination(page, maxPerPage) {
//        return {
//            _start: (page - 1) * maxPerPage,
//            _end: page * maxPerPage
//        };
//    }

    RestangularProvider.addResponseInterceptor(function(data, operation, what, url, response) {
        if (operation == "getList") {
        // alert(response.headers('X-Total-Count'));
//        alert(response.headers('X-Total-Count'));
        
//            response.totalCount = 784;
        }
        return data;
    });
    // use the custom query parameters function to format the API request correctly
    

    RestangularProvider.addFullRequestInterceptor(function(element, operation, what, url, headers, params) {
        if (operation == "getList") {
//        	var Result = Get(url + '/count');
//        	alert(2);response.totalCount = Result.count;
        	alert(url);
            // custom pagination params
//            if (params._page) {
//                params._start = (params._page - 1) * params._perPage;
//                params._end = params._page * params._perPage;
//                
////                alert (params._start);
////                alert (params.end);
//            }
//            delete params._page;
//            delete params._perPage;
            // custom sort params
//            if (params._sortField) {
//                params._sort = params._sortField;
//                params._order = params._sortDir;
//                delete params._sortField;
//                delete params._sortDir;
//            }
            // custom filters
            if (params._filters) {
                for (var filter in params._filters) {
                    params[filter] = params._filters[filter];
                }
                alert(element);
                alert (what);
//                delete params._filters;
      	      }
        }
        return { params: params };
    });

    // create an admin application
    var admin = nga.application('Sinica Visualization 3')
       .debug(false) // debug disabled
      .baseApiUrl('http://localhost:8080/KIMWS_Rest/'); // main API endpoint
    // create a user entity
    // the API endpoint for this entity will be 'http://jsonplaceholder.typicode.com/users/:id
//    alert(1);
    var organization = nga.entity('organizations')
	.baseApiUrl('http://localhost:8080/KIMWS_Rest/')
	.identifier(nga.field('id'));
    // set the fields of the user entity list view
    // add the user entity to the admin application
    admin.addEntity(organization);

    alert(22);

    var person = nga.entity('persons')
    			.baseApiUrl('http://localhost:8080/KIMWS_Rest/')
    			.identifier(nga.field('id'));
    // set the fields of the user entity list view
    person.listView()
//    	.infinitePagination(true) // load pages as the user scrolls
//    	.pagination(pagination)
    	.fields([
        nga.field('id'),
        nga.field('person_id'),
        nga.field('person_name'),
		nga.field('person_category')

    ]);
//    alert(3);

    // add the user entity to the admin application
    admin.addEntity(person);

    var loc1 = nga.entity('locations')
        .baseApiUrl('http://localhost:8080/KIMWS_Rest/')
        .identifier(nga.field('id'));

    loc1.listView()
//    	.pagination(pagination)
    	.perPage(10) // limit the number of elements displayed per page. Default is 30.
    	.fields([
        nga.field('location_id')
    	.label('Location_ID'),
        nga.field('id'),
        
        nga.field('province_id'),
        nga.field('location_name'),
        nga.field('location_desc'),
        
        	
        	
//        nga.field('userId', 'reference')
//        .targetEntity(user)
//        .targetField(nga.field('username'))
//        .label('User')
            nga.field('location_lat'),
            nga.field('location_long')

    ]);
//    alert(5);
//alert(15);
        var news1 = nga.entity('news')
            .baseApiUrl('http://localhost:8080/KIMWS_Rest/')
            .identifier(nga.field('id'));
        	
    news1.listView()
    	
      .perPage(2) // limit the number of elements displayed per page. Default is 30.
        .fields([
        nga.field('id'),
        
        nga.field('newsSource'),
        nga.field('newsTitle'),
        nga.field('sectorName'),
        nga.field('newsDate')

    ]);
    var relation = nga.entity('relations')
            .baseApiUrl('http://localhost:8080/KIMWS_Rest/')
            .identifier(nga.field('id'));
    relation.listView()
    	.perPage(3)
        .fields([
        nga.field('id'),
        
        nga.field('relationID'),
        nga.field('relatedEntityID'),
        nga.field('hostEntityID'),
        nga.field('entityRelationType'),
        nga.field('relationName')
        ]);
    alert(9);        
    admin.addEntity(loc1);
    admin.addEntity(news1);
    admin.addEntity(relation);
    organization.listView()
    //.infinitePagination(true) // load pages as the user scrolls
    //.pagination(pagination)
        .title('Organization-list') // default title is "[Entity_name] list"
        .description('Listing') // description appears under the title
        .fields([
        nga.field('id'),
        nga.field('organization_id'),
        nga.field('organization_name'),
        nga.field('organization_category'),
        nga.field('organization_Desc')
    ])
    .listActions(['show']);

    organization.showView()
    //.infinitePagination(true) // load pages as the user scrolls
    //.pagination(pagination)
        .title('Organization') // default title is "[Entity_name] list"
        .description('Listings') // description appears under the title
        .fields([
//        nga.field('id'),
        nga.field('organization_id'),
        nga.field('organization_name'),
        nga.field('organization_category'),
        nga.field('organization_Desc'),

         nga.field('related_Location', 'reference_many') // ReferenceMany translates to a select multiple
             .targetEntity(loc1)
             .targetField(nga.field('location_name'))
             .isDetailLink(true)
             .attributes({ placeholder: 'Select some tags...' })
             .remoteComplete(true, {
                 refreshDelay: 300 ,
                 searchQuery: function(search) { return { q: search }; }
         })
         .cssClasses('col-sm-4'),
        
//        nga.field('related_News', 'json')
        
        nga.field('Rel_Loc', 'referenced_list') // Define a N-1 relationship with the comment entity
        .label('Related Location')
        .targetEntity(relation) // Target the comment Entity
        .permanentFilters({relationID: 1031})
        .targetReferenceField('relatedEntityID')
        	// Each comment with post_id = post.id (the identifier) will be displayed
//        	.permanentFilters({relationID: 1031,entityRelationType : 3061})
        .targetFields([ // Display comment field to display
            nga.field('id').label('ID'),
            nga.field('hostEntityID').label('Related Location'),
            nga.field('relationID'),
            nga.field('entityRelationType'),

            nga.field('relationName')
        

        ])
        
        
//         nga.field('related_News', 'embedded_list') // display list of related comments
//             .targetFields([
//                 nga.field('RelationName'),
//                 nga.field('RelatedEntityID'),
//                 nga.field('HostEntityID').label('Related EntityRef'),
//             ])

    ]);

        // customize header
        var customHeaderTemplate =
        '<div class="navbar-header">' +
            '<a class="navbar-brand" href="#" ng-click="appController.displayHome()">Sinica Visualization System-2</a>' +
        '</div>' +
        '<p class="navbar-text navbar-right">' +
            '<a href="https://github.com/marmelab/ng-admin/blob/master/examples/blog/config.js"><span class="glyphicon glyphicon-sunglasses"></span>&nbsp;View Source</a>' +
        '</p>';
        admin.header(customHeaderTemplate);

    // attach the admin application to the DOM and execute it
    nga.configure(admin);
}]);

}());

**Comment by fzaninotto** [comment]
Could you reformat the description? It's long and hard to read.

**Comment by vsharm22411** [comment]
The issue is with this code 
        nga.field('Rel_Loc', 'referenced_list') // Define a N-1 relationship with the comment entity
        .label('Related Location')
        .targetEntity(relation) // Target the comment Entity
        .permanentFilters({'relationID': 1031})
        .targetReferenceField('relatedEntityID')
        .targetFields([ // Display comment field to display
            nga.field('id').label('ID'),
            nga.field('hostEntityID').label('Related Location'),
            nga.field('relationID'),
            nga.field('entityRelationType'),
            nga.field('relationName')
                ])
        
This permanent filter is not being added to my REST URL

**Comment by vsharm22411** [comment]
you could review the source code as attached of the entire admin.JS

in this the permanentFilter is not working (organization.showview())

Regards

Vikas

**Comment by fzaninotto** [comment]
which version of ng-admin are you using?

**Comment by vsharm22411** [comment]
version 0.8.0

do i need to upgrade ?

**Comment by fzaninotto** [comment]
Yes, please upgrade with the latest HEAD and report here if you still have the issue.

**Comment by vsharm22411** [comment]
should I install using npm or download the latest zip ?

**Comment by fzaninotto** [comment]
Fetch master from this GitHub repository.

**Comment by fzaninotto** [comment]
Any news?

**Comment by vsharm22411** [comment]
Thanx for the solution. It works like a charm
