### ISSUE TITLE
Cannot use element transformers for array

### ISSUE THREAD

**Issue by evan-mark4s** [marmelab/ng-admin#733]
So my API GET response is wrapped inside a property like this.
```
{ values : [{...}] }
```
I've read the API mapping documentation about Restangular element transformers but that doesn't work for array.
Second problem, the element transformer must be defined per API path and this is troublesome.

It would be great if ng-admin can be configured to read the real data from a property instead of using element transformers.

**Comment by fzaninotto** [comment]
ng-admin doesn't deal with request/response transformers. That's Restangular's job. If you need a feature from Restangular, please open an issue in their bug tracker.

Please note that the next version of ng-admin allows you to map an inner array with the [`embedded_list`](https://marmelab.gitbooks.io/ng-admin/content/doc/reference/Field.html#-embedded-list-field-type) field type. That may help you.
