### ISSUE TITLE
make build runs into error

### ISSUE THREAD

**Issue by joschne** [marmelab/ng-admin#734]
I'd like to contribute and need to build ng-admin. Unfortunately the build process fails.

My Steps:
* I made a fork of marmelab/ng-admin 
* I installed it: `npm install joschne/ng-admin` 
* Inside the ng-admin folder I did `make install`. Until here everything works fine.
* When i run `make run` or `make build` this error occurs: 

`ERROR in ./src/javascripts/ng-admin.js
Module parse failed: /Code/node_modules/ng-admin/node_modules/ng-annotate-loader/loader.js!/Code/node_modules/ng-admin/src/javascripts/ng-admin.js Line 6: Unexpected token
You may need an appropriate loader to handle this file type.
| require('./ng-admin/Crud/CrudModule');
| 
| import Factory from 'admin-config/lib/Factory';
| 
| var factory = angular.module('AdminDescriptionModule', []);
 @ multi ng-admin`

I think, ng-annotate-loader got correctly installed by `make install`...
What am I missing? Thx for your help!

**Comment by fzaninotto** [comment]
I cannot reproduce your issue on a fresh install. Which version of Node & npm are you using? Could you paste the result of the `npm ls` command?

**Comment by joschne** [comment]
I use those versions:
node v0.12.0
npm v2.5.1

the result of `npm ls` is:
`ng-admin@0.9.0-dev (git://github.com/joschne/ng-admin#eb7614ec507a8517dddb96e964608bee94d1a6b9) /Code/node_modules/ng-admin`

**Comment by fzaninotto** [comment]
I can't reproduce the issue with node 0.12, and the build runs smoothly on Travis CI (node 4.0). Try removing `node_modules` and running `make install` again.

I won't dig any further, sorry.

**Comment by joschne** [comment]
I'll try that, thank you anyway!
