### ISSUE TITLE
creationView  referenced_list add new item

### ISSUE THREAD

**Issue by temala** [marmelab/ng-admin#735]
hi,
first of all thanks for this great tool, I just whant to ask if thiere a way to add new reference item on the referenced_list section

thanks

**Comment by fzaninotto** [comment]
You can insert a button to link to the creationView of the related entity, with the reference prefilled with the current entity ID. It's done in the blog demo: https://github.com/marmelab/ng-admin/blob/master/examples/blog/config.js#L167 (look for ` <ma-create-button>`.
