### ISSUE TITLE
Boolean field value is not properly submitted in editView and creationView

### ISSUE THREAD

**Issue by ilyabo** [marmelab/ng-admin#736]
For the following field:
```
      nga.field('intern', 'boolean')
        .validation({ required: true })
```

When submitting the edit form with 'Intern' checked, for some reason ```false``` is sent to the server:

![screen shot 2015-10-15 at 10 25 32](https://cloud.githubusercontent.com/assets/351828/10508424/649b0cb8-7327-11e5-8cb8-b4c3fe863cc2.png)

**Comment by fzaninotto** [comment]
Yep, I can reproduce the problem. It's probably due to #707. I'll inquire.

**Comment by frank0ch0a** [comment]
Hi! I got the the same issue when I tried to update boolean value.

**Comment by fzaninotto** [comment]
@frank0ch0a which version are you using? this has been fixed a couple weeks ago.

**Comment by frank0ch0a** [comment]
@fzaninotto I updated to last version and all works fine, thanks!
