### ISSUE TITLE
Override standard state change of a ng-admin view

### ISSUE THREAD

**Issue by Phocea** [marmelab/ng-admin#737]
Hello,

The problem I have is closed to #678 but cannot be solved by restangular.
I basically want to change the default state a view is going to after performing an action. For instance once a CREATE is done, nh-admin redirect to the editionView of the newly created objects.

In my use case I create an objectX, which in server side trigger the creation of several objects Y & Z.
I want once it has been created, redirect to object Y

I have managed to do so by configuring objectX like so

var objectX= admin.getEntity('objectX');
objectX.creationView()
        .title('New Object X')
        .fields([
            nga.field('id').validation({ required: true}),
            nga.field('title').validation({ required: true}),
           .....
        ])
objectX.editionView().fields(objectY.editionView().fields());
objectX.editionView().url(function() {
        return <pathToObjectY>+entityId;
    });

this work okish, but the displayed URL remain in the form
.../objectX/edit/entityId

Is it possible to do this in a cleaner way by overriding the routing one only on the objectX.creationView() ?

Thanks

**Comment by fzaninotto** [comment]
Can't you override the routing by setting a ui-router decorator, as explained [here](http://stackoverflow.com/questions/30394658/how-to-decorate-current-state-resolve-function-in-ui-router-current-function-is)?

**Comment by Phocea** [comment]
Thanks for the suggestion. i will investigate this path to ovveride what is defined in ng-admin routing.js and get back to you.
If successull it may be interesting to add an example to the documentation

**Comment by fzaninotto** [comment]
No news for some time, closing.

**Comment by Phocea** [comment]
No problem. We have not planned to investigate this as the work around prove enough for the moment. I will update the issue when investigated.
Thanks for the help
