### ISSUE TITLE
Export works incorrect after deleting filters and search query

### ISSUE THREAD

**Issue by AlexH7** [marmelab/ng-admin#738]
__Steps for reproduce:__
    1. Use some filter or search for your entities list.
    2. Delete your filter or search query after looking of new filtering results.
    3. Do the Export operation for this list and look on the results.

__Result:__
    The export results contains data from previous filtering operation.

__Expected:__
    The export results should contains data from the current list view.

**Comment by lucval** [comment]
Just accidentally bumped into this issue, quite annoying indeed.
+1

**Comment by lucval** [comment]
Fixed by #835

**Comment by re1naldo** [comment]
I still got incorrect result when filters were deleted. This also happened when I sorted records. Data in list view was sorted properly, but the exported result (CSV) was sorted by ID (descending). Am I missing anything here?

**Comment by lucval** [comment]
@re1naldo: if I understand your scenario correctly, when removing a filter your exported data is still containing (or missing) the previously filtered data?
I just tried all scenarios (i.e. data is either added, removed or both after removing a filter) and the exported CSV was always containing the correct records.

You do have a case though about the sorting order which is not fully respected by the export feature. My suggestion to you is to open a new issue and it would be nice if you could also work on a solution!

**Comment by re1naldo** [comment]
After using ng-admin from master branch, the filtering feature works fine now. I will open different issue regarding data sorting.
