### ISSUE TITLE
Custom view actions template not working

### ISSUE THREAD

**Issue by Phocea** [marmelab/ng-admin#739]
Hello,

I tried to follow the instructions found [here](https://github.com/marmelab/ng-admin/blob/4298be81cd16406701ebd9e838e3d4b9e2537cd5/doc/Configuration-reference.md#view-configuration) and [here](marmelab.com/blog/2014/12/05/ngadmin-04-eating-our-own-dog-food.html) to add a new custom action button to a list view but even the simplest code does not work.

I tried:
`var template = '<back-button></back-button>';
entity.listView.actions(template);`
and nothing get displayed. Same goes for
`var template = '<create-button></create-button>';
entity.listView.actions(template);`

If I add some text in the template like so, only the text get displayed:
`var template = '<back-button>text</back-button>';
entity.listView.actions(template);`

If I simply use:
`entitiy.listView().actions(['batch', 'export', 'create', 'back']);`
the button are displayed as expected

Is this a regression or am i missing something obvious?
What I am trying to achieve is to display a button to create the current entity or another entity from this listview, like:
`<create-button></create-button><create-button entity="myOtherEntity" size="sm"></create-button>`

**Comment by fzaninotto** [comment]
There was an error in the documentation: all the ng-admin directive names are prefixed with `ma-`, so you should try with `<ma-back-button>` instead of `<back-button>`. Sorry for that.
