### ISSUE TITLE
Trigger changes on edit entity form

### ISSUE THREAD

**Issue by ViacheslavSedletskyi** [marmelab/ng-admin#746]
**Steps for reproduce:**
 1. _Edit_ any `Entity`.
 2. Makes any changes in fields.
 3. Leave a _Edit_ form or click on any link.

**Result:**
 The changes get lost

**Expected:**
 Triggers custom validation form changes method (specific for `editionView()`configuration) and warn changes lost message with option to discard or save and transfer on other location

**Comment by fzaninotto** [comment]
That's a feature! If you don't save your changes, they get lost.
