### ISSUE TITLE
template() field method throws an error

### ISSUE THREAD

**Issue by 4ley** [marmelab/ng-admin#747]
I'm currently going through the [Getting started](https://github.com/marmelab/ng-admin/blob/master/doc/Getting-started.md#using-angular-directives-with-the-template-method) tutorial and encounter an error on the following line

    nga.field('q')
        .label('')
        .pinned(true)
        .template('<div class="input-group"><input type="text" ng-model="value" placeholder="Search" class="form-control"></input><span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span></div>')

Chrome dev tools throws
`TypeError: nga.field(...).label(...).pinned(...).template is not a function`

**Comment by gabehollombe** [comment]
@4ley - I had this problem, too.  I installed the latest ng-admin from master and it works, so I'm guessing `template` was a method introduced after 0.8.0.

Try `npm install git+ssh://git@github.com:marmelab/ng-admin.git --save`  and then refresh. Worked for me.

**Comment by 4ley** [comment]
I made a fresh installation yesterday, so I don't think it's this. I'm on
version 0.8.0.

@4ley <https://github.com/4ley> - I had this problem, too. I installed the
latest ng-admin from master and it works, so I'm guessing template was a
method introduced after 0.8.0.

Try npm install git+ssh://git@github.com:marmelab/ng-admin.git --save and
then refresh. Worked for me.

—
Reply to this email directly or view it on GitHub
<https://github.com/marmelab/ng-admin/issues/747#issuecomment-150100740>.

**Comment by fzaninotto** [comment]
I confirm, if you're using a version number in your `package.json`, you won't have the `template()` method. You need to point to master by setting the `ng-admin` dependency to `marmelab/ng-admin`.

**Comment by 4ley** [comment]
Will there be a stable release with this feature soon?

**Comment by fzaninotto** [comment]
No ETA at the moment. But we try to release ng-admin every 2-3 months.

https://github.com/marmelab/ng-admin/releases
