### ISSUE TITLE
How to implement authentication/login/signup procedures?

### ISSUE THREAD

**Issue by 4ley** [marmelab/ng-admin#749]
There have been [other](https://github.com/marmelab/ng-admin/issues/603) [questions](https://github.com/marmelab/ng-admin/issues/291) like this in the past and as far as I understood, there will be an implementation soon. So I have the following questions:

- Is there already something working, but undocumented for basic login/signup procedures?
- Do you know about tutorials or snippets on which I can take examples?

**Comment by fzaninotto** [comment]
Login/signup is outside of ng-admin' scope. You'll have to implement that on your own. 

An example for the login is [Poster's Galore Login](https://github.com/marmelab/ng-admin-demo/blob/8a1bec89a3e12ff24ba14b17363caad4ff47d01d/login.html), that you can test online at http://marmelab.com/ng-admin-demo/login.html.

As for what to do after login, it depends on the API security. If your API requires a specific header with a token that you got during login, then a Restangular Request Interceptor is the way to go. 

Also, please read the FAQ. 

https://marmelab.gitbooks.io/ng-admin/content/doc/FAQ.html#my-api-requires-authentication-how-can-i-set-it-up
