### ISSUE TITLE
Failed to load template

### ISSUE THREAD

**Issue by hbprotoss** [marmelab/ng-admin#752]
Failed to load template `bootstrap/match.tpl.html`, `bootstrap/choices.tpl.html`, `bootstrap/select.tpl.html` when using `reference` and `referenced_list`. Dependencies of `ui-select`?

ng-admin version: 0.8.0 installed from npm

**Comment by fzaninotto** [comment]
which version of ng-admin are you using: `ng-admin-only.js` or `ng-admin.js`?

Also, this doesn't seem to happen on the master branch, try installing from npm but using `marmelab/ng-admin` to get the HEAD.

**Comment by TheBlusky** [comment]
Same issue here, using "ng-admin.min.css" and "ng-admin.min.js" found here: https://github.com/marmelab/ng-admin/tree/master/build.

Related code:

     var user = nga.entity('user');
     user.listView().fields([
        nga.field('id'),
        nga.field('username'),
        nga.field('email')
    ]);
     user.editionView().fields([
        nga.field('username'),
        nga.field('email'),
        nga.field('user_permissions', 'reference_many')
            .targetEntity(permission)
            .targetField(nga.field('name'))
     ]);
     admin.addEntity(user);

**Comment by hbprotoss** [comment]
@fzaninotto , using ng-admin.js(ng-admin@0.9.0-dev, marmelab/ng-admin), same code example with @TheBlusky .

**Comment by hbprotoss** [comment]
@fzaninotto how can I build a non-minimized version?

**Comment by fzaninotto** [comment]
I rebuilt the css and js files and pushed them to master. Can you try again?

@hbprotoss you can't. Use the sourcemaps instead.

**Comment by fzaninotto** [comment]
Bump. Any updates?

**Comment by fzaninotto** [comment]
No news for several months, closing.

**Comment by cedricfrancoys** [comment]
Just had the same issue. 
In case it helps: the problem was because I had set up a HTTP request interceptor.

Here is a quick workaround from my code : 

```
 .factory('httpInterceptor', [ 'qnConf', function(qnConf) {  
                var httpInterceptor = {
                    request: function(config) {
                        if(config.url.indexOf('.html') < 0) { // <-- prevent updating URL when requesting .html files
                            config.url = qnConf.url+'?'+config.params.operation;
                            delete config.params.operation;
                        }
                        return config;
                    },
                    response: function(response) {
                        if(typeof response.data.message == 'undefined') {
                            response.data.message = '';
                        }   
                        return response;
                    }                    
                };
                return httpInterceptor;
            }])
```
