### ISSUE TITLE
Embedded List - Reference as targetFields causes empty ui-select

### ISSUE THREAD

**Issue by stuartforster** [marmelab/ng-admin#754]
Using the new 'embedded_list' type; if one of the targetFields for this embedded_list is that of 'reference' - in editionView you are shown the ui-select but it does not have any values populated, in showView the value is also empty. There doesn't appear to be an initial api call to fetch the values for this referenced entity when it is within an embedded list. This is in both 'show' and 'edit' views.

**Example:**

The below correctly populates a ui-select dropdown when used (the exercise entity is valid in both cases).

```js
nga.field('exercises', 'reference_many')
  .targetEntity(admin.getEntity('exercise'))
  .targetField(nga.field('name'))
```

The below however will show a dropdown with an empty list for exercise:

```js
nga.field('exercises', 'embedded_list')
  .targetFields([
    nga.field('exercise', 'reference')
      .targetEntity(admin.getEntity('exercise'))
      .targetField(nga.field('name')),
    nga.field('reps')
  ]);
```

However, If I set 'remoteRefresh' to true then it will proceed to update the ui-select correctly (with an initial call after I focus the select and with future updates):

```js
nga.field('exercises', 'embedded_list')
  .targetFields([
    nga.field('exercise', 'reference')
      .targetEntity(admin.getEntity('exercise'))
      .remoteRefresh(true)
      .targetField(nga.field('name')),
    nga.field('reps')
  ]);
```

However, using remoteRefresh() doesn't work on the show page (I wouldn't expect it too!), but this means I cannot get a value to show for 'exercise name', instead I get a blank name (or the id - without using reference).

**Comment by manind007** [comment]
Hi,
I am also facing same problem. Is there any solution?
