### ISSUE TITLE
Hide a row from editionView depending on some conditions

### ISSUE THREAD

**Issue by geryslava** [marmelab/ng-admin#755]
Hi 

I've used ng-admin for only 2 weeks, so, please, forgive me if I've misunderstood something.

I would like to be able to hide a whole row from editionView - label+field - depending on current value of some other field.

If I set cssClasses to 'ng-hide' it hides only fields but not the label and the row still exists.

Is there any solution of my issue?

Thanks a lot!

**Comment by fzaninotto** [comment]
Nope, you can't do that with field configuration ; you'll have to use a custom template for the edition view, see for instance https://github.com/marmelab/ng-admin-demo/blob/gh-pages/js/products/config.js#L90.

I know it's a bummer, so I'm keeping your issue open as a feature request.

**Comment by geryslava** [comment]
Thank you for the reply!
