### ISSUE TITLE
Use related entity to map a reference

### ISSUE THREAD

**Issue by thiagoterleski** [marmelab/ng-admin#757]
Hello, how can i use the map `.targetField(nga.field('name').map((v,e) => e.name)),` to get a field in related entity?

For example, i have the entity 'student', and when i edit or create a new student, i need to make a select 'reference' with the school class and school name, but the school class e school are diferent entities where for each school class have an school associated.

**Wich i need is like this:**
`.targetField(nga.field('name').map((v,e) => e.name + ' from school' + e.school.name)),`

Thanks a lot!

**Comment by fzaninotto** [comment]
Well, it works just like what you wrote, see e.g. [the Posters Galore demo](https://github.com/marmelab/ng-admin-demo/blob/319466729aa7cc15bf0baa79ce8caf18ef99cef9/js/reviews/config.js#L89).
