### ISSUE TITLE
entry is undefined for cssClasses (before data is actually received)

### ISSUE THREAD

**Issue by lucval** [marmelab/ng-admin#762]
Hi all,
when using function(entry) in field's cssClasses exception "entry is undefined" is raised. I did a bit of debugging and it looks as this exception is raised before the actual data is received (in fact the cssClasses function then completes without issues).
Does not look as a big problem so far, besides that all those error messages in the log are quite  annoying.

To reproduce: create a field with a cssClasses attribute which implements a function that uses the entry.values object.

I am using the latest ng-admin release (pull the repo today).

Luca

**Comment by fzaninotto** [comment]
Hi lucval,

As explained in [the documentation](http://ng-admin-book.marmelab.com/doc/reference/Field.html#general-field-settings),

> A list of CSS classes to be added to the corresponding field. If you provide a function, it will receive the current entry as first argument, to allow dynamic classes according to values. **The function will also be called without entry for table headers.**

That's why you should test the existence of the `entry` in the `cssClasses` function. 

I pushed a small doc update to make that clearer (55697c0).
