### ISSUE TITLE
No depth in entry.values object

### ISSUE THREAD

**Issue by lucval** [marmelab/ng-admin#763]
Hi,
this is an issue which appeared in ng-admin v0.9.1. Trying to access nested object in entry.values will result in an exception because complex objects are undefined.

Take as an example this JSON object:
```
{
    "fname": "test",
    "lname": "001",
    "telephone": {
        "mobile": "123456789"
    }
}
```
Now this field definition will succeed:
```
nga.field('customer_name, 'template')
    .template(function (entry) {
        return entry.values.fname+' '+entry.values.lname;
    }),
```
While this one will fail:
```
nga.field('customer_number, 'template')
    .template(function (entry) {
        return entry.values.telephone.mobile;
    })
```
with exception "Error: entry.values.telephone is undefined".

As a workaround one could expand every nested object in a response interceptor but I am pretty sure this is not an expected behavior.

Luca

**Comment by fzaninotto** [comment]
ng-admin 'flattens' JSON properties by default, to make it easy to reference them using dot notation (e.g. `nga.field('telephone.mobile')`. 

Some fields disable flattening: `json`, `template`. But you have to pass the name of the field you want to map, so in your example, use `nga.field('telephone', 'template')` to disable flattening on the ` telephone` property.

**Comment by F3L1X79** [comment]
@fzaninotto 
Thank you for the tip! But is it possible to hide the column 'telephone' created (ie: on the list view) in this example?
