### ISSUE TITLE
Can't get mongodb documents displayed properly

### ISSUE THREAD

**Issue by mrmayfield** [marmelab/ng-admin#766]
I have configured ng-admin to display mongodb documents. These documents however don't have a numerical id, they have a mongo objectId instead, so the route users/___ is based off of the objectID.

I can get ng-admin to correctly ascertain how many documents there are, so I can go through pages correctly, but the individual documents are not displayed.

Is this because of there not being an ID for the documents? Can I config restangular to use the objectID instead of a numerical value? Thanks.

**Comment by fzaninotto** [comment]
Two pointers: 

- the entity's `identifier()` method, to define a custom identifier field (http://ng-admin-book.marmelab.com/doc/reference/Entity.html)
- Restangular interceptors, to transform data between the API response and what ng-admin uses (http://ng-admin-book.marmelab.com/doc/API-mapping.html)
