### ISSUE TITLE
How to catch and handle 401 error?

### ISSUE THREAD

**Issue by thachp** [marmelab/ng-admin#767]
I am trying to catch 401 response from a web service.  For some reasons,  this piece of codes never get executed.  I expect to see "response" in my console.   Any idea?
       
     RestangularProvider.addResponseInterceptor(function (data, operation, what, url, response) {        
        console.log("response", response);
        if (operation == "getList") {
            var contentRange = response.headers('Content-Range');
            response.totalCount = response.headers('X-Total-Count');
        }
        return data;
    });

![image](https://cloud.githubusercontent.com/assets/1495371/11034024/f55485da-869c-11e5-8671-17ff3351e825.png)

**Comment by thachp** [comment]
I just found my solution... but open to other suggestion.

In main.js from ng-admin-demo, I added my own error handling thus overriding   MainModule.run(require('./run/ErrorHandler'));

    // add error.js 
    export default function errorHandler($rootScope, $state, $window, notification) {
    $rootScope.$on("$stateChangeError", function handleError(event, toState, toParams, fromState, fromParams, error) {
        if (error.status == 404) {
            $state.go('ma-404');
            event.preventDefault();
        }
        else if(error.status == 401) {
            console.log("handle 401 error here.");
            throw error;
        }
        else {
            notification.log('State change error: ' + error.message, { addnCls: 'humane-flatty-error' });
            throw error;
        }
    });
    }

    errorHandler.$inject = ['$rootScope', '$state', '$window', 'notification'];

    // in main.js require the new error.js file
    myApp.run(require('./error'));

**Comment by fzaninotto** [comment]
Did you try using [Restangular's ErrorInterceptor](https://github.com/mgonto/restangular#seterrorinterceptor)?

**Comment by thachp** [comment]
Thank you.. ErrorInterceptor works too.
