### ISSUE TITLE
#/ should redirect to #/dashboard

### ISSUE THREAD

**Issue by thachp** [marmelab/ng-admin#768]
Repro(s)

http://marmelab.com/ng-admin-demo/#/ -> should redirect to http://marmelab.com/ng-admin-demo/#/dashboard

Instead it gets "Not Found" error.

**Comment by fzaninotto** [comment]
Where does the `/#` url come from?

**Comment by fzaninotto** [comment]
Bump, this url is normally not public.

**Comment by thachp** [comment]
Yes, it is not normally public.   I am not sure how I was able to get to the #/ hash, but I got there somehow.  Should this be intentional for ng-admin?  

I think this problem should be delegate to the application using ng-admin.  For example, in ng-admin-demo, these codes do what I want to do.

    // main.js
    // after this line myApp.config(['$stateProvider', require('./segments/segmentsState')]);
    // add this snippet

    myApp.config(function($stateProvider, $urlRouterProvider) {
        // For any unmatched url, route to /dashboard
        $urlRouterProvider.otherwise("/dashboard");
    });

**Comment by fzaninotto** [comment]
Normally you should never get this url. I'm closing the issue, feel free to reopen it if you find a way to trigger a transition to this route from within the app.
