### ISSUE TITLE
Label property is ignored in list/cred/edit views

### ISSUE THREAD

**Issue by fedotxxl** [marmelab/ng-admin#769]
Create entity
````
nga.entity("items").label("DVDs")
````
Open list/create/edit pages, check header:

* Items list
* Create new item
* Edit item

Expected:
* DVDs list
* Create new DVD
* Edit DVD

**Comment by fzaninotto** [comment]
True, that's a bug

**Comment by OverZealous** [comment]
OK, this just caught me. :+1:
