### ISSUE TITLE
Help! In CreateView I can have dependencies in the fields of type "reference".

### ISSUE THREAD

**Issue by vcenturion** [marmelab/ng-admin#770]
By selecting a value in a ComboBox filtered by that value in another ComboBox.

Thanks

**Comment by fzaninotto** [comment]
There is an example about that in the documentation: http://ng-admin-book.marmelab.com/doc/reference/Field.html#-choice-and-choices-field-types

**Comment by vcenturion** [comment]
Thanks for the answer, but that applies to fields of type "choice". How it would be for the fields of type "reference"?

**Comment by fzaninotto** [comment]
You'll have to write a custom directive for that ; ng-admin doesn't provide one out fo the box.
