### ISSUE TITLE
String Array type render as tags list 

### ISSUE THREAD

**Issue by huvber** [marmelab/ng-admin#773]
Is It possible to render a field like
```json
{
   "parents": ["Categoria1","Categoria2",...]
}
```
in the same way as `referenced_list' like:
![image](https://cloud.githubusercontent.com/assets/5032333/11089837/66611550-886d-11e5-88be-7b9a8e5436b9.png)

**Comment by fzaninotto** [comment]
Yes, but you'll have to write a custom directive using ui-select for that - ng-admin doesn't provide a built-in directive.
