### ISSUE TITLE
Links should use `ui-sref` or `href` whenever possible to allow for open-in-new-tab

### ISSUE THREAD

**Issue by OverZealous** [marmelab/ng-admin#775]
Right now, all in-app links are using `ng-click` and calling a function, which means it's not possible to open a page in a new tab or new window.

Since everything has a unique URL, it would be nice if ng-admin used `ui-sref` to navigate whenever possible, which would automatically set up things like proper `href` attributes.

(I might be able to scrape some time together to look at adding this in a PR if this is something others desire, too.)

**Comment by lucval** [comment]
Nice feature, I'm on board!

**Comment by fzaninotto** [comment]
Can you elaborate on the use case of opening links in a new tab, by giving me an example?

**Comment by OverZealous** [comment]
Seems pretty straightforward: I want to be able to middle-click on a link within the interface (sidebar, list item, other links) and have it open in a new tab.  Or maybe I want to right-click and choose open in a new window.  Or maybe right-click and copy a link, so I can share it with someone.

As for why, again, it's not that crazy: maybe I want to compare to objects, so I want to open one in a new tab.  Or maybe I'm looking at a widget, and I also want to open the user in a new tab so I can look at both at once.  I'm not really sure "I'd like to open this in a new tab" really needs a more complex use case. :smile: 

Right now, everything is using pure JavaScript for links, which means that none of the links are _actually_ links, even though they have a specific URL.  It's the equivalent of the old `href="javascript:void(0)"`.

If `ng-admin` used `ui-sref="«state»(«params»)"` whenever possible, rather than `ng-click`, then all those links would get the `href` set, so you can do the above.

**Comment by fzaninotto** [comment]
Now I understand better, thanks!

**Comment by OverZealous** [comment]
That's awesome! Thanks! Looking forward to the 1.0 release.
