### ISSUE TITLE
Updated to 0.9, now getting `t.choices` is not a function

### ISSUE THREAD

**Issue by OverZealous** [marmelab/ng-admin#778]
Every time I switch to an edit page, I'm now getting this error:

```
Error: t.choices is not a function
r/<.compile/<.pre@http://localhost:3001/adm/js/vendor/ng-admin/build/ng-admin.min.js:15:2543

«snipped Angular call stack »

 <ma-choice-field class="ng-isolate-scope" field="::field" entry="entry" value="value">
```

I've narrowed it down to [line 36 of maChoiceField.js](https://github.com/marmelab/ng-admin/blob/master/src/javascripts/ng-admin/Crud/field/maChoiceField.js#L36).  I don't know exactly what's wrong.  I think it's a mistake, because it calls the function _then_ uses the result.

Looks like the change was made in commit 0f0693647f252783d7cb4b0ecd6f1ef00c333167.

If it matters, these fields are using a custom function for the choices.  It's a bit of a hack to allow me to asynchronously load some meta data from the server, but it shouldn't affect anything.  The way it works is like this:

```js
let someChoices = [];
app.config(function(...) {
    field.choices(() => someChoices);
});

...

app.run(function ($http) {
    // load remote values
    someChoices = remoteValues;
});
```

I'd make a minimal test case, but I'm honestly trying to figure out how to do that, since you need a RESTful backend.

**Comment by fzaninotto** [comment]
I really wonder about your error. I've never seen it myself. And it seems that it doesn't set a `&` directive attribute as a function... Which Angular version are you using?

**Comment by OverZealous** [comment]
Angular 1.4.5.  What you said in the PR makes sense, but I definitely got that error consistently.  I'll try upgrading again later today.

**Comment by OverZealous** [comment]
BTW: I didn't think `foo: '&?'` was a valid use for optional expressions.  It seems like a mistake to be overriding the passed in expression in the scope property like that.

**Comment by fzaninotto** [comment]
Why is it a mistake?

**Comment by fzaninotto** [comment]
> Angular 1.4.5

That's why. ng-admin is tested on angular 1.3. Migration to 1.4 is not yet started (cf #567)

**Comment by OverZealous** [comment]
Because it's a function created on the scope to call back the expression, and it's being overridden with a static property, breaking the binding.  It makes the logic harder to follow, too, because it switches from a function to an array at some point.

---

Really? I thought I just read that v0.9 was going to be the switch to ng 1.4, since 0.8 was the last to support 1.3.x.

That sucks for me. :frowning:

**Comment by OverZealous** [comment]
OK, this fix worked for me on Angular 1.4.7:

```js
var choices = (angular.isFunction(scope.choices) && scope.choices()) ? scope.choices : (field.choices ? field.choices() : [])
```

**Comment by fzaninotto** [comment]
That still doesn't make sense. Does the following work?

```js
var choices = (typeof scope.choices == 'function' && scope.choices()) ? scope.choices() : (field.choices ? field.choices() : []);
```

0.8 was supposed to be the latest version built on Angular 1.3, but we packed too many features in 0.9 not to release it before breaking compatibility. You'll have to wait a bit for 1.4 compatibility.

**Comment by fzaninotto** [comment]
Note: I tracked down the BC Break in Angular 1.4 to this commit: https://github.com/angular/angular.js/commit/6a38dbfd3c34c8f9efff503d17eb3cbeb666d422

**Comment by OverZealous** [comment]
Yup, looks like that's the change.

The code from above is almost the same thing as mine, I'm just using Angular's built-in `isFunction`, rather than `typeof`.  I assume it would work the same.

The other difference is you are calling `scope.choices()` for the assignment, which is different than the existing code, which looks more like mine:

```js
var choices = scope.choices() ? scope.choices : (field.choices ? field.choices() : []);
```

**Comment by OverZealous** [comment]
Thank you, sir! :-)

**Comment by KonstantinYegupov** [comment]
This fix is not yet added to built files and cannot be easily installed via Bower, I presume?..

**Comment by fzaninotto** [comment]
It is added to built files. To get it from bower, you must reference the master branch (see http://stackoverflow.com/a/16951315 for directions).

**Comment by KonstantinYegupov** [comment]
I've tried and that didn't work - built files were updated 20 days ago and the fix was added 19 days ago...

**Comment by fzaninotto** [comment]
It should be fixed by now, I've published a new build a couple days ago.

**Comment by mikeplavo** [comment]
I'm reading the documentation (Getting-started chapter) and i have the  same error when i tried to display the users filter in the post listview section.

I am using angularjs 1.5.0
Should have UI to wait a bit for  a 1.5 compatibility.?
