### ISSUE TITLE
How to mark field as invalid after server validation?

### ISSUE THREAD

**Issue by dadmin-admin** [marmelab/ng-admin#782]
Hello. Is it possible to add server validation to the form?

Here the description of expected workflow:
1. User submits the form
2. Server validates data
3. On incorrect data server return error messages
4. Client marks fields as invalid + display error messages per field
5. On any field value change field is marked as valid and error message is hidden

**Comment by fzaninotto** [comment]
That's an enhancement. And the problem is that REST doesn't standardize validation error reponses at all. So I guess the answer for that will be #777

**Comment by re1naldo** [comment]
After the addition of `onSubmitError`, is it possible to display error messages below each field? In the example, you only used `notification.log('...')`, which only set an error message for the whole form.

**Comment by fzaninotto** [comment]
You'll have to override the default `maField` template to display these error messages close to the field. We use angular's built-in form validation, which doesn't support this out ouf the box.

**Comment by Abolfouz** [comment]
Hello,
Please, I am trying to use the onSubmitError handler but I am getting the following error:
users.creationView(...).onSubmitError is not a function

**Comment by re1naldo** [comment]
Did you use ng-admin from master branch? #833

**Comment by Abolfouz** [comment]
No, I have just used it. and the following error appeared 

`TypeError: t(...) is null`
