### ISSUE TITLE
Exception thrown with nested properties with null values

### ISSUE THREAD

**Issue by justinm** [marmelab/ng-admin#789]
The following field configuration causes an exception to be thrown when trying to save an object if the value of the property is null.

nga.field('a.b', 'embedded_list') // { a: null }

I've submitted a pull request for admin-config that addresses the issue: marmelab/admin-config#51

**Comment by fzaninotto** [comment]
Fixed by https://github.com/marmelab/admin-config/pull/51. Thanks for the PR!
