### ISSUE TITLE
Redirection while changing from filtered list view.

### ISSUE THREAD

**Issue by roma7** [marmelab/ng-admin#792]
Hi.

Thank you for the greate tool.

I have:
- List page with filters applied, say products/list?search={"user_id":1}
- List page, say users
- Slow rest api, response time is more then 0.5 sec (another option -- page makes several api requests, so state change takes more than 0.5 sec).

When I navigate from first page to second, ng-admin redirects me back to the first page but without filters.

As far as I understand the cause of the behavior is that [UpdateFilters](https://github.com/marmelab/ng-admin/blob/da7f3a1975a4b9c159b040b13ea3df3b3bd2d563/src/javascripts/ng-admin/Crud/list/ListLayoutController.js#L103) is executed when the state change is not completed.

The magic number 0.5 sec is from [here](https://github.com/marmelab/ng-admin/blob/da7f3a1975a4b9c159b040b13ea3df3b3bd2d563/src/javascripts/ng-admin/Crud/list/ListLayoutController.js#L44)

     $scope.$watch(
            () => this.search,
            _.debounce((newValues, oldValues) => {
                if (newValues != oldValues) {
                    this.updateFilters();
                }
            }, 500),
            true
        );

The demonstration html is below. ng-admin.min.css,  ng-admin.min.css, FakeRest.min.js, sinon.js are supposed to be in the same directory.
- click "users" in the menu,
- click "All related products"
- click "users" menu item 

Thank you again.

    <!DOCTYPE html>
    <html>
        <head>
            <link rel="stylesheet" href="ng-admin.min.css">
        </head>
        <body ng-app="myApp" ng-strict-di>
            <div ui-view></div>
            <script src="ng-admin.min.js" type="text/javascript"></script>
            <script src="FakeRest.min.js" type="text/javascript"></script>
            <script src="sinon.js" type="text/javascript"></script>
            <script>
                var data = { users: [{id:1}], products:[{id:1}]};

                var restServer = new FakeRest.Server();
                restServer.init(data);
                var server = sinon.fakeServer.create();
                server.autoRespond = true;
                server.autoRespondAfter = 600;
                server.respondWith(restServer.getHandler());

                var myApp = angular.module('myApp', ['ng-admin'])

                myApp.config(['NgAdminConfigurationProvider', function (nga) {
                    // create an admin application
                    var admin = nga.application('Issue', false)
                        .baseApiUrl('/')
                    ;
                    var users = nga.entity('users')
                    admin.addEntity(users);
                    users.listView()
                        .fields([
                            nga.field('products')
                                .template('<ma-filtered-list-button entity-name="products" filter="{ user_id: entry.values.id }" ></ma-filtered-list-button>')
                        ]);

                    var products = nga.entity('products');
                    admin.addEntity(products);

                    products.listView()
                        .fields([nga.field('id')])
                    ;

                    admin.menu(nga.menu()
                        .addChild(nga.menu(admin.getEntity('users')))
                    );
                    admin.dashboard(nga.dashboard().template(''));
                    nga.configure(admin);
                }]);
            </script>
        </body>
    </html>

**Comment by fzaninotto** [comment]
That's not a bug. Filters are not persistent, except when navigating within the same entity (e.g. from products list to products show).

What you are asking is an enhancement to persist active filters, even when browsing to another entity. I'm not sure it's something we want to support.

**Comment by roma7** [comment]
I am very sorry, but you do not understand me. I do not want persistent filters. Let me explain another way.

Please take the Posters Galore demo application and make it nearer to the real life by setting api response timeout  in  [api.js](https://github.com/marmelab/ng-admin-demo/blob/gh-pages/js/api.js#L16). Change

  server.autoRespondAfter = 0;

to 

  server.autoRespondAfter = 600;


(600 is just to be sure. Most probably even 50 will be enough).

Open, say, http://marmelab.com/ng-admin-demo/#/customers/list?search={%22has_ordered%22:%22false%22}

Now click to the menu item  "Reviews". 

I am pretty sure, that you will find yourself at the http://marmelab.com/ng-admin-demo/#/customers/list instead of Reviews page.

**Comment by fzaninotto** [comment]
OK, you're right, there is a bug. Investigating.
