### ISSUE TITLE
Is it possible to disable dashboard and make any other page as default one?

### ISSUE THREAD

**Issue by fedotxxl** [marmelab/ng-admin#793]
Hello. Is it possible to disable dashboard and make any other page as default one?

**Comment by fzaninotto** [comment]
You can add [custom pages](http://ng-admin-book.marmelab.com/doc/Custom-pages.html), and I guess you can decorate the router to intercept the `/` route. But there is no built-in way.

**Comment by dadmin-admin** [comment]
To do it had to create another module, configure `$urlRouterProvider` and add it as dependency to main module before `nd-admin`... 

````
angular
    .module("app.before", ["ui.router"])
    .config(function($urlRouterProvider) {
        $urlRouterProvider.when('', '/another-page');
    });

angular
    .module("app", ["app.before", "ng-admin"])
```

I think it make sense to make it configurable

**Comment by fedotxxl** [comment]
To do it had to create another module, configure `$urlRouterProvider` and add it as dependency to main module before `nd-admin`... 

````
angular
    .module("app.before", ["ui.router"])
    .config(function($urlRouterProvider) {
        $urlRouterProvider.when('', '/another-page');
    });

angular
    .module("app", ["app.before", "ng-admin"])
```

I think it make sense to make it configurable

**Comment by fzaninotto** [comment]
Your solution is fine, and making it configurable is hard (because of the sequence of Angular's configuration execution).

**Comment by windmaomao** [comment]
this works great, in case we want to make it configurable, we could just customize the otherwise (ui.router) of ng-admin, or hook into start event and do a redirect ? just a thought.
