### ISSUE TITLE
list view: getCssClasses for the whole row

### ISSUE THREAD

**Issue by fedotxxl** [marmelab/ng-admin#794]
Hello
Our list view also contains deleted items. In this case they should be marked somehow (change background color for the row) + actions / selection checkbox should be hidden. 
I thought to apply special `CSS` to these rows but it looks like ng-admin doesn't support dynamic classes per row. 

Can you add it?

**Comment by fzaninotto** [comment]
Fixed by #772

**Comment by fzaninotto** [comment]
Oops, no, sorry for the fast close. Reopening.

**Comment by dadmin-admin** [comment]
Please check these commits:

https://github.com/fedotxxl/admin-config/commit/aebba3da32541cd98ea4ccf1210a220271cd5411
https://github.com/fedotxxl/ng-admin/commit/b9c2046241d6e41cf350d0fdf18aa4fae6355138

**Comment by fedotxxl** [comment]
Please check these commits:

https://github.com/fedotxxl/admin-config/commit/aebba3da32541cd98ea4ccf1210a220271cd5411
https://github.com/fedotxxl/ng-admin/commit/b9c2046241d6e41cf350d0fdf18aa4fae6355138

**Comment by fzaninotto** [comment]
@fedotxxl great, I suggest you make a PR out of it

**Comment by fedotxxl** [comment]
Created https://github.com/marmelab/admin-config/pull/52 / https://github.com/marmelab/ng-admin/pull/795 but I'm not sure that suggested method names / implementation is the best way to solve the problem

**Comment by fzaninotto** [comment]
Well, PRs are a better way to discuss that than an external repo!

**Comment by fedotxxl** [comment]
thank you! it works!

**Comment by lucval** [comment]
It would be nice to have this feature available for referenced_list as well.

**Comment by fzaninotto** [comment]
@lucval yes it would be nice. I think it's not very hard, would you like to give it a try?

**Comment by lucval** [comment]
@fzaninotto got a bit of spare time and done it (#844)
