### ISSUE TITLE
count lines in an entity

### ISSUE THREAD

**Issue by Fr4ncx** [marmelab/ng-admin#797]
I want to display in the dashboard how much customers  i have in the Db.(like http://marmelab.com/ng-admin-demo/#/dashboard)
How can i do that?

var worker = nga.entity('workers').identifier(nga.field('_id'));
worker._views.ListView._fields.length

Any suggestion?:)

**Comment by lucval** [comment]
If you include the X-Total-Count header in your GET responses, then you could use Restangular to extract and use that value.

**Comment by fzaninotto** [comment]
You should ask that in an Angular.js mailing list - this isn't related to ng-admin IMO.
