### ISSUE TITLE
After record creation, edit view is blank

### ISSUE THREAD

**Issue by jamespsterling** [marmelab/ng-admin#799]
After I create a record, I'm taken to the editView, but the view is blank. There is a call to my API, but it's a request to list all records rather than just that one newly created record. Any idea what's going on? Shouldn't the request after create do a get for that specific record?

**Comment by Phocea** [comment]
Do you have an id:<value> in your POST response
ng admin is using the value of the id field to do the redirect to the editView. If your API is something like /myEntities/<id> to get a particular MyEntity and /myEntities/ to get them all, the behaviour you describe may happen

**Comment by jamespsterling** [comment]
Yes, my API is returning an ID value. Is it expecting a JSON formatted response?

**Comment by fzaninotto** [comment]
yes, indeed, see https://github.com/marmelab/ng-admin/blob/caf78d5f21d05d7c359807b0be5d81117f44961c/src/javascripts/ng-admin/Crud/form/FormController.js#L57-L58

**Comment by Phocea** [comment]
I simply return something like:
´{ id: <id_value>}´

If needed you can add this id in your payload usig restangular. In my particular case POST return the self url and I have an interceptor defined like such:

´
function responseInterceptor(RestangularProvider) {
    RestangularProvider.addResponseInterceptor(function(data, operation, what, url, response) {
        var extractedData = data;

		// Get id from the self response and add it to an id object
		if (operation == 'post') {
			var str = response.data.self
			var entityId = str.substring(str.lastIndexOf("/")+1);
			data['id'] = entityId;
			extractedData = data;
		}
		
		if (extractedData == null) {
			extractedData = [];
		}
      return extractedData;
    });
}
´

**Comment by jamespsterling** [comment]
Thanks for the responses, this is exactly what I needed to know!
