### ISSUE TITLE
Regex validation pattern

### ISSUE THREAD

**Issue by jamespsterling** [marmelab/ng-admin#800]
The field/form validation is not allowing dashes with this pattern, however it should,
```javascript
nga.field('username')
    .attributes({ placeholder: 'No space allowed, 5 chars min' })
    .validation({ required: true, pattern: '[A-Za-z0-9\.\-_]{5,20}' }),
```

**Comment by fzaninotto** [comment]
ng-admin is using angular.js validation (see [the input directive](https://docs.angularjs.org/api/ng/directive/input)). Your bug is probably an Angular bug, please open an Issue in the Angular.js repository.

**Comment by jamespsterling** [comment]
thanks, will do
