### ISSUE TITLE
label flag in template doesn't seem to work

### ISSUE THREAD

**Issue by huvber** [marmelab/ng-admin#801]
I using the ```template``` function to alter the view of one of my field in the ``èditionView``` like this:
```javascript
...
nga.field('images.small').map(function(value,field){ return encodeURIComponent(value); })
        .template('<img src="{{value}}" alt="{{value}}" />',true),
...
```
As you can see I wanted to see the image and I put to true the *not label* parameter. But I'm still have the label as you can see from the image below.
![image](https://cloud.githubusercontent.com/assets/5032333/11238311/fd23e900-8de4-11e5-829f-4d40b8c4f6f9.png)

**Comment by jamespsterling** [comment]
I'm seeing the same thing.

**Comment by fzaninotto** [comment]
The built files were not refreshed after the "with label" feature was added. It was done in caf78d5. Could you try again?

**Comment by jamespsterling** [comment]
Confirmed working for me now.

**Comment by fzaninotto** [comment]
Great, closing.
