### ISSUE TITLE
Building dashboard is not incremental

### ISSUE THREAD

**Issue by Phocea** [marmelab/ng-admin#802]
Hello,

I would like to be able to build my dashboard incrementally, by defining what the structure of my dashboard in different .js files.
From my test, and what is stated in the documentation, call to  admin.dashboard(nga.dashboard()) reset the dasboard, which stop the behavior I would expect.

For instance, the menu can be build incrementally by writing code like:
`
admin.menu(require('./core/menu')(nga, admin)); // create the base level menu
admin.menu().addChild(require('./moduleA/menu')(nga, admin)); // Add the moduleA submenu
admin.menu().addChild(require('./moduleB/menu')(nga, admin));// Add the moduleB submenu
`
If I try something similar with the dashboard:
`
admin.dashboard(nga.dashboard().template(require('./html/dashboard.html')));; // create the base dashboard, only set the template
admin.dashboard(nga.dashboard().addCollection(nga.collection(admin.getEntity('entityA')))); // Add a collection of entityA to the base dashboard
`
Then only the last admin.dashboard call is used.
Coudl this be listed as possible enhancement ? If you point me in the right place where this code is done i dont mind looking into it.
Or is there some other way to do what I want?

Thanks!

**Comment by fzaninotto** [comment]
`Application.menu()` and `Application.dashboard()` behave exactly the same: given  parameter, they become setters, and with no parameter, they are getters.

For your example, just use the same syntax with the dashboard as with the menu:

```js
admin.dashboard(nga.dashboard().template(require('./html/dashboard.html')));; // create the base dashboard, only set the template
admin.dashboard().addCollection(nga.collection(admin.getEntity('entityA')))); // Add a collection of entityA to the base dashboard 
```

I think you got confused between `nga.dashboard()`, which is a factory function, and `admin.dashboard()`, which is a smart getter.

**Comment by Phocea** [comment]
Ho dear .. i need an holiday :)
Thanks :)
