### ISSUE TITLE
Edition view does not load entire entity after  save changes

### ISSUE THREAD

**Issue by kinnrot** [marmelab/ng-admin#805]
Lets say I have a field x that his value is calculated on server side based on field y
if I update x value via admin ui, click save, than server side changes y returns it, but the change is not reflected on ui without refreshing the page

**Comment by fzaninotto** [comment]
I guess it's related to #777

**Comment by kinnrot** [comment]
Yep, I think that for my issue there is a very simple solution...

// Form Controller
.updateOne(view, restEntry, this.originEntityId)
        .then(() => {
            this.progression.done();
            this.notification.log('Changes successfully saved.', { addnCls: 'humane-flatty-success' });
        }, this.handleError.bind(this));

just need to take the result from update one and update the $scope.entity attributes...

Should I create a pull req?

**Comment by fzaninotto** [comment]
no, the default behaviour should be to keep the current entity.

**Comment by kinnrot** [comment]
@fzaninotto 
Ok,
Found another way, just intercept the update one with a state reload after update, simple and do the work for me.
```

angular.module('crud')
  .config([
    '$provide', function ($provide) {
      $provide.decorator('WriteQueries', [
        '$delegate',
        '$state',
        function ($delegate, $state) {
          var originalUpdateOne = $delegate.updateOne;
          $delegate.updateOne = function () {
            return originalUpdateOne.apply($delegate, arguments).
              then(function () {
                $state.reload()
              });
          };
          return $delegate;
        }]);
    }
  ]);
```

**Comment by fzaninotto** [comment]
Interesting approach, albeit a bit hacky. Thanks for sharing it!
