### ISSUE TITLE
No flexibility, in top right action buttons at all.

### ISSUE THREAD

**Issue by kinnrot** [marmelab/ng-admin#809]
For example, I got a listView with filter, And I want the create button at the top right corner to take the filter value as a default value for new entities created when a filter was set. how can I do it?

**Comment by fzaninotto** [comment]
Hi! Thanks for asking. The solution is quite simple indeed:

1. be polite
2. change the title of your issue to explain what YOU can't do, rather than what you think ng-admin can't do
3. [RTFM](http://ng-admin-book.marmelab.com/doc/reference/View.html#general-view-settings)
