### ISSUE TITLE
label not hide when entry is null

### ISSUE THREAD

**Issue by hoangmanh09it** [marmelab/ng-admin#811]
on my filed like that
 nga.field('sub', 'template')
        .cssClasses(function(entry) { 
            if (!entry.values.sub) return 'hidden';
         })
    .label('Sub Categories'),

when entry is null label usually show on display

**Comment by fzaninotto** [comment]
That's normal. If you want to override the field AND the label, you'll have to override the entire row template (recently added in #772).
