### ISSUE TITLE
listView filters: if field type is date, filter lost on page reload

### ISSUE THREAD

**Issue by lucval** [marmelab/ng-admin#816]
The issue comes when, for instance, you want to access a filtered page via its link or if you navigate back to a previously filtered list. In such cases the list is first shown with the correct filter(s) in place but after few seconds the page reloads automatically and the filter is excluded from the GET request (and removed from the shown filters if not pinned).

This behavior does not present itself when datetime is used as field type.

**Comment by kinnrot** [comment]
+1

**Comment by kinnrot** [comment]
@lucval - For now I'm working with datetime field type, and the filter persist after refresh
