### ISSUE TITLE
ng-admin-min is too big to download

### ISSUE THREAD

**Issue by exquisite2007** [marmelab/ng-admin#819]
As the `ls` show below, ng-admin.min.css is about 1.5M and ng-admin.min.js is about 900k,
is there a way to speed up to download those too files? is there public CDN?
or is there a guide to lead me use ng-admin-only.*?

thanks
MacBook-Pro:build$ ls -lh
total 29536
-rw-r--r--  1 lihongwei  staff   8.6K Oct 30 16:58 ng-admin-only.min.css
-rw-r--r--  1 lihongwei  staff   104B Oct 30 16:58 ng-admin-only.min.css.map
-rw-r--r--  1 lihongwei  staff   570K Oct 30 16:58 ng-admin-only.min.js
-rw-r--r--  1 lihongwei  staff   4.8M Oct 30 16:58 ng-admin-only.min.js.map
-rw-r--r--  1 lihongwei  staff   1.5M Oct 30 16:58 ng-admin.min.css
-rw-r--r--  1 lihongwei  staff    99B Oct 30 16:58 ng-admin.min.css.map
-rw-r--r--  1 lihongwei  staff   895K Oct 30 16:58 ng-admin.min.js
-rw-r--r--  1 lihongwei  staff   6.7M Oct 30 16:58 ng-admin.min.js.map

**Comment by fzaninotto** [comment]
This is being addressed in #743 (ping @jeromemacias)
