### ISSUE TITLE
Validator for password confirmation

### ISSUE THREAD

**Issue by Irrealist** [marmelab/ng-admin#820]
Is there a way to access other fields in a validator function?
I'd like to compare the value of a password confirmation field with the password field.

**Comment by fzaninotto** [comment]
Yes! It's still undocumented, but the `validator` function of a field receives the field value as first argument, and all the entry values as second argument, see https://github.com/marmelab/admin-config/blob/a5581d82c308ad3d547e8ae17b2e52f79a9dffa5/lib/View/View.js#L235.

**Comment by MHDFawaz** [comment]
Hello,

How can I check for confirm password while typing and return ng-error class, not after submit the form
