### ISSUE TITLE
How work with urls

### ISSUE THREAD

**Issue by frank0ch0a** [marmelab/ng-admin#821]
Hi ! I configured all endpoints and create my views , all works fine, but I need to use the follow url /analytics/questionnaires , it is not a endpoint is a custom request to make a statistics graphics should I to make a interceptor to consume this webservice?, any example? sorry I'm novice, thanks

**Comment by fzaninotto** [comment]
I think the [Custom Pages](http://ng-admin-book.marmelab.com/doc/Custom-pages.html) doc chapter answers that. Feel free to reopen if I misunderstood your request.
