### ISSUE TITLE
Add totals row after listView

### ISSUE THREAD

**Issue by marcovisona** [marmelab/ng-admin#823]
Hello,
   I was wondering if is there a way to add a row at the bottom of a list view to display some aggregate data from the listview. For instance the sum or average of values of a column.

Thanks in advance, and thank you for this great piece of code!

**Comment by fzaninotto** [comment]
You can still override the datagrid directive (see http://ng-admin-book.marmelab.com/doc/Theming.html#customizing-directives-templates). In general, when you don't find a way to achieve what you want through ng-admin config, there should always be a way to do it otherwise with Angular.js.
