### ISSUE TITLE
validator function is called only on saving entity

### ISSUE THREAD

**Issue by fedotxxl** [marmelab/ng-admin#824]
Suppose we've got number field with custom validator function. When user sets any number value the field is marked as correct. When user tries to save entity validator function throws an error -> entity is not saved but all fields are still marked as valid.

1. Isn't it better to call validator function on change and mark field as not valid?
2. Isn't it better to mark field as not valid when validator function throws an error?

**Comment by fzaninotto** [comment]
The *view* validation function is designed specifically for cross-field validation, or for validations that shouldn't be done in realtime. If you want to do a simple *field* input validation, use the field `validation()` method: this one operates in realtime and shows feedback on the right field line.

http://ng-admin-book.marmelab.com/doc/reference/Field.html#general-field-settings

**Comment by gartner** [comment]
The validation() method for a field can take a function for custom validation:

validation({validator: function(val) {...}})

But this function is first called on submit the form, not in real time like other validations.

**Comment by gameffective** [comment]
Hi, 
Is there any news on this problem? validator called only on submit?
