### ISSUE TITLE
Building a multipart form with ng-admin to post an attribute and file data to the server

### ISSUE THREAD

**Issue by gabehollombe** [marmelab/ng-admin#826]
How can you build a creation view form with two fields: a name, and a file?

The file field type lets you easily select a file as part of a form, but it immediately posts it to an endpoint that you configure. That endpoint returns the created filename, which you can then refer to when you submit the form.

This strategy doesn't work for me. I need ng-admin to let me select a file, enter a name for the file, and then submit both pieces of data as a multipart encoded POST when I submit the form.

I think this might be possible with some clever uses of custom Angular directives, but I'm not sure about the right way to go about it. Any ideas?

**Comment by pntripathi9417** [comment]
Any solutions to this issue. I am also trying to add same functionality. I am unable to figure out a decent way.

**Comment by fzaninotto** [comment]
As explained in StackOverflow (please don't multipost your questions), this is not implemented in ng-admin. Try the following pointer for directions on how to do it in Angular.js alone (to be integrated as a custom template): http://stackoverflow.com/questions/28902727/multipart-request-with-angularjs
