### ISSUE TITLE
Singleton edit/show views

### ISSUE THREAD

**Issue by btyoung** [marmelab/ng-admin#828]
The API I'm attempting to work with has two natural singletons in it, ``settings`` and the user ``profile``.  At present, it doesn't seem that editing these types of endpoints is supported (correct me if I'm wrong of course).

This seems like it would be a common problem, so I was going to see about implementing it. However, I'm filing an issue to see if either someone else is already working on this, or if it is generally considered a bad idea for some reason that escapes me.

My proposed interface would be:

```
myApp.config(['NgAdminConfigurationProvider', function (nga) {
  var admin = nga.application('My App Management').baseApiUrl(ROOT + 'api/');

  // Settings
  var settings = nga.entity('settings');
  settings.singletonEditView().fields([
    nga.field('setting1'),
    nga.field('setting2'),
    nga.field('setting3'),
  ]);
  settingsView.addTo(admin);
  
  [ Add other entities .... ]

  nga.configure(admin);
}]);
```

where ``GET:/api/settings/`` returns the settings, while PUT/PATCH/POST updates it. Presumably, if singletonEditView or singletonShowView were called, it would prevent the existing views for listable items from being generated.

I intend to dig into this soon, so let me know if there is anything I should change in my approach.

**Comment by fzaninotto** [comment]
After reflection, this is something that I don't want to support in ng-admin. It's simple to add as a custom page, and to hangle directly via Restangular. Adding a level of indirection via ng-admin for that purpose, which is quite rare IMO, is probably not the best thing to do. Thanks anyway for your contribution.

**Comment by garethsb** [comment]
@fzaninotto Would you mind explaining your rejection of this idea in a bit more detail? I have to support two similar REST APIs, one of which has an endpoint /widgets/{id}, and the other of which has a singleton /widget endpoint. I would like to reuse the widget nga.entity's showView (and maybe later editView) to interact with the singleton /widget. Is this possible with a custom page as you proposed?
