### ISSUE TITLE
filters field transform problem with "$" character

### ISSUE THREAD

**Issue by Orlo666** [marmelab/ng-admin#829]
Hi, 
I've got problem with filters and transform function. I need to return dict like this: {"$regex":value}.
First query works great, but after change in filter value (for example removing one letter), there is no request on my api. However if i return {"regex":value}, it works without problems. Is it bug, or correct behavior? 
Thanks. 
My code:
```javascript
element.listView().filters([
    nga.field('title')
        .map(v => fromRegex(v))
        .transform(v => toRegex(v))
        .pinned(true);
)]
function fromRegex(value, entry){
    if (value ){
        var newValue = value['$regex'];
        newValue = newValue.replace('.*','');
        newValue = newValue.replace('.*','');
        return newValue;
    }
}
function toRegex(value, entry){
    return value && {"$regex":".*" + value  + ".*"};
}
```

**Comment by fzaninotto** [comment]
From ng-admin's point of view, there is no difference is there is a `$` or not. Do you have a Restangular interceptor somewhere looking for such characters? If not, the problem comes from Restangular, not ng-admin.

I'm closing this issue as there is nothing we can do in ng-admin.
