### ISSUE TITLE
Redirect to list view after entry was created

### ISSUE THREAD

**Issue by fedotxxl** [marmelab/ng-admin#833]
Hello. Is it possible to execute custom logic after entry was created (e.g. redirect to list view instead of edit view)?

**Comment by fzaninotto** [comment]
Nope, but that feature request already exists (cf #777).

**Comment by re1naldo** [comment]
I saw you had added creation and edition hooks (#898). Is page redirection possible now? How to redirect page to listview after record creation?

**Comment by fzaninotto** [comment]
Yes you can, #898 has doc, read it.

**Comment by re1naldo** [comment]
I have tried it, but got an error: `TypeError: onSubmitSuccess is not a function`.

**Comment by fzaninotto** [comment]
You must use the master branch, the hooks are not yet available in any released package.

**Comment by gerardp** [comment]
Any estimated release data with this feature?

**Comment by fzaninotto** [comment]
No, sorry. Use the master branch until then.
