### ISSUE TITLE
Reference by any other than ID field

### ISSUE THREAD

**Issue by fedotxxl** [marmelab/ng-admin#834]
Hello. 
Suppose I've got two fields:
1. References to entity `B` by ID
2. References to entity `B` by my_custom_unique_id

I can use `map` function to get `my_custom_unique_id` instead of `id`. But how can I customize URL in second case?

**Comment by fzaninotto** [comment]
Can you please elaborate? I don't understand your problem.

**Comment by fedotxxl** [comment]
In general the question is:

is it possible to customize URL which will be used to retrieve referenced entity (configured for specific field, not globally)?

**Comment by fzaninotto** [comment]
Did you try `singleApiCall()`? Something like:

        myField.singleApiCall(refIds => {
            return { 'my_custom_unique_id[]': refIds };
        });

**Comment by jpetitcolas** [comment]
No feedback. Closing the issue. Feel free to re-open it if required.
