### ISSUE TITLE
After creation of an item, I get editView with no item ID

### ISSUE THREAD

**Issue by KonstantinYegupov** [marmelab/ng-admin#838]
After I have finished creating an item, I am redirected neither to the item list page, nor to a new "create item page", but to an edit page with no item ID selected (URL `/#/users/edit/`).

This is very surprising. Why does such thing as an empty edit view exist at all? And why am I redirected there?

Could not find anything in the documentation - https://github.com/marmelab/ng-admin/blob/master/doc/reference/View.md only has detailed settings for listView.

Running Angular 1.4 btw, maybe that has something to do with it.

**Comment by fzaninotto** [comment]
ng-admin is not yet compatible with Angular 1.4 (refs #567). However, I don't think that the problem comes from that. What is the REST response to the POST request sending the newly created page? It's supposed to contain the created object, with an identifier value.

**Comment by KonstantinYegupov** [comment]
Ah. I feel like the expectation for POST to return the entity should be documented somewhere. And, moreover, it'd be nice for ng-admin to handle missing entity ID gracefully, rather than showing a completely wrong page.

Editing item immediately after its creation seems like not the most popular use case. Maybe creationView should be configurable to allow going to the items list or to "create another" screen?

**Comment by daniel-rosiak** [comment]
@KonstantinYegupov have you manage to solve this issue somehow? I would like to redirect to list instead of edition too.

**Comment by fzaninotto** [comment]
#898 now allows custom hook after creation. Closing.
