### ISSUE TITLE
Set perPage = 0 (or -1) for reference fields by default

### ISSUE THREAD

**Issue by fedotxxl** [marmelab/ng-admin#841]
Currently this values equls to 30 items. It leads to following problems:

1. Only first 30 items are available to be choosen - there is no way to choose other ones
2. If you will try to create item with default-values related_id: XXX, where XXX is not in list of first 30 items it will lead to JS exception (e.g. "Create related comment" from examples)

**Comment by fzaninotto** [comment]
There must be a limit. Ng-admin has to be scalable by default. So `perPage` will remain with a default value of 30. Use `remoteComplete()` if you need more, or increase the `perPage()` in your field.

As for your second point, it's a bug, so I'll reference it in another issue.
