### ISSUE TITLE
OPTIONS method called on entity removal instead of DELETE

### ISSUE THREAD

**Issue by blynkkk** [marmelab/ng-admin#847]
Hello, When I'm trying to remove entity from "list view" server get OPTIONS method instead of DELETE. Why is that? How this behavior could be changed?

**Comment by fzaninotto** [comment]
That's CORS: it takes two requests to make a cross-origin communication. The first ("preflight") request uses the OPTIONS method, then, if the server answers with an agreement, the DELETE request follows. Nothing specific to ng-admin here (see [this tutorial on CORS](http://www.html5rocks.com/en/tutorials/cors/) for instance).

**Comment by blynkkk** [comment]
Thanks!
