### ISSUE TITLE
Layout breaks for boolean fields (Ubuntu, firefox, MacOs, safari)

### ISSUE THREAD

**Issue by doom369** [marmelab/ng-admin#852]
![boolean_field_breaks](https://cloud.githubusercontent.com/assets/1536494/11762479/6de67ef0-a0f0-11e5-94b5-521e0ceb99fa.png)

Also how to remove 'undefined' from selection? (Not full screen mode)

**Comment by fzaninotto** [comment]
Is it in an embedded list? I can't reproduce on a normal list.

To remove the "undefined" option, make the field required.

**Comment by doom369** [comment]
Yes, this is for embedded list. It has a lot of space, but look like layout has small allowed % .

**Comment by doom369** [comment]
![large_break](https://cloud.githubusercontent.com/assets/1536494/11794688/46b57756-a2bb-11e5-9b00-5a37da9470c4.png)
