### ISSUE TITLE
editable(false) for ID field makes it value invisible

### ISSUE THREAD

**Issue by doom369** [marmelab/ng-admin#853]
I have next code :

```
            nga.field('profile.dashBoards', 'embedded_list')
                .targetFields([
                    nga.field('id').editable(false),
```

this makes ID field invisible on UI. Removing 'editable(false)' makes field to appear. Ubuntu, Firefox. 

![editable_false](https://cloud.githubusercontent.com/assets/1536494/11762708/62a05a7c-a0f8-11e5-9a0f-c2f21ddd1e53.png)

But editable(false) works for String field for parent/root entity.

**Comment by fzaninotto** [comment]
Bug confirmed, I can reproduce.
