### ISSUE TITLE
Can´t build & run exemple application

### ISSUE THREAD

**Issue by RicardoArdito** [marmelab/ng-admin#859]
I´m trying to clone ng-admin in order to make some customizations we will need (and maybe contribute, if I can). 

I succesfully followed the instructions to "contribute" (clone / make install / make run), but when I run the application I get some errors:

Uncaught SyntaxError: Unexpected token .
fakerest-init.js:5 Uncaught ReferenceError: FakeRest is not defined
ng-admin.min.js:35397 Uncaught TypeError: Cannot set property 'true' of undefined
ng-admin.min.js:7914 Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to:
Error: [$injector:modulerr] Failed to instantiate module ng-admin due to:
Error: [$injector:modulerr] Failed to instantiate module ui.select due to:
Error: [$injector:nomod] Module 'ui.select' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

It seems there are some unresolved references, but I was not able to find out what is happening. 

Could someone help us ?

Thanks, 

Ricardo.

**Comment by fzaninotto** [comment]
What's your platform and node / npm version ?

**Comment by RicardoArdito** [comment]
Hi Francois,

It´s a Windows machine:

{ npm: '2.11.3',
  http_parser: '2.3',
  modules: '14',
  node: '0.12.7',
  openssl: '1.0.1p',
  uv: '1.6.1',
  v8: '3.28.71.19',
  zlib: '1.2.8' }

Thanks for your help!

Ricardo.

De: Francois Zaninotto [mailto:notifications@github.com]
Enviada em: terça-feira, 15 de dezembro de 2015 05:55
Para: marmelab/ng-admin <ng-admin@noreply.github.com>
Cc: Ricardo Ardito <ricardo@tecnovia.com.br>
Assunto: Re: [ng-admin] Can´t build & run exemple application (#859)


What's your platform and node / npm version ?

**Comment by fzaninotto** [comment]
Can you try replacing line 41 of `webpack.config.js` from

    { test: /\.js/, loaders: ['babel'], exclude: /node_modules\/(?!admin-config)/ },

to

    { test: /\.js/, loaders: ['babel'], exclude: /node_modules[\/\\](?!admin-config)/ },
