### ISSUE TITLE
Share application between different configuration files.

### ISSUE THREAD

**Issue by dataxa** [marmelab/ng-admin#861]
Since I would like to configure each entity in different configuration file, I would like to know how would you share application object created by nga.application between different configuration blocks?

**Comment by fzaninotto** [comment]
ng-admin-demo does exactly that, see https://github.com/marmelab/ng-admin-demo/blob/97bb9e1279731e2f60761fad3ffd6a156ac027b4/js/main.js#L32-L59

**Comment by dataxa** [comment]
I see you use some kind of third party AMD? Can it be done using only angular?

**Comment by kinnrot** [comment]
You can, but it's less recommended. 
You can define a provider for each config file, that exports (via $get method) a method that receives the application object and add the relevant entity configuration.

**Comment by dataxa** [comment]
But what about other way around? Would this be a good or a bad solution? 
```
app.provider("ngaApplication" , [function(){

	var admin;

	this.get = function(nga){
		if(!admin){
			admin = nga.application('My backend').baseApiUrl('http://hmvc.ee/rest/');
			nga.configure(admin);
		}
		return admin;
	};

	var that = this;
	this.$get = ["NgAdminConfigurationProvider" , function(nga){
		return that.get(nga);
	}];
}]);
```

And using:
```
app.config(["NgAdminConfigurationProvider" , "ngaApplicationProvider" , function(nga , ngaApplication){
	var group = nga.entity('group');
	ngaApplication.get(nga).addEntity(group);
}]);
```
