### ISSUE TITLE
Angular 2.0 branch possible?

### ISSUE THREAD

**Issue by auvipy** [marmelab/ng-admin#866]

**Comment by auvipy** [comment]
I will be happy to help

**Comment by fzaninotto** [comment]
This won't come from us, we don't have the need for it. feel free to start working on it on your side.

**Comment by auvipy** [comment]
I want to use ng-forward to make the angular 1.x code and push the changes to a WIP branch. Is this seems ok to you?

**Comment by fzaninotto** [comment]
Yes, no problem.

**Comment by mozey** [comment]
auvipy do you still plan on creating an Angular 2.0 branch?

**Comment by auvipy** [comment]
I will go for a react+redux admin

**Comment by fzaninotto** [comment]
For your information, we've just release a React+Redux admin ourselves, it's called [marmelab/admin-on-rest](https://github.com/marmelab/admin-on-rest).
