### ISSUE TITLE
How to register new chaining field method like CssClasses(), Label(), remoteComplete()?

### ISSUE THREAD

**Issue by thachp** [marmelab/ng-admin#867]
Where in the core ng-admin lib codes can I register custom chaining method like remoteComplete()?
I would like to chain .disableSort(true) to each field.

For example,

      post.editionView().fields([
      nga.field('id'),
      nga.field('tags', 'reference_many')
          .targetEntity(tag)
          .disableSort(true)
          .targetField(nga.field('name'))
          .remoteComplete(true) // populate choices from the response of GET /tags?name=XXX
      ]);

There is a need for me to implement enhancement #372

**Comment by lucval** [comment]
Here: https://github.com/marmelab/admin-config/blob/master/lib/Field/Field.js

**Comment by thachp** [comment]
Awesome, thank you.
