### ISSUE TITLE
Issue with custom directive to upload excel

### ISSUE THREAD

**Issue by frank0ch0a** [marmelab/ng-admin#873]
Hello I created custom directive to upload excel file this is not working , o upload a excel sheet, when I upload the file, I get the following TypeError: Cannot set property 'columnDefs' of undefined, my code, it seem that the data is no passing from controller to directive.

Module
          var myApp = angular.module('myApp', ['ng-  admin','ngStorage','chart.js','ui.grid']);

Controller

    myApp.controller('MainCtrl', ['$scope', function ($scope) {

    var vm = this;

    vm.gridOptions = {};

     vm.reset = reset;

     function reset() {

        vm.gridOptions.data = [];
        vm.gridOptions.columnDefs = [];
      }
      }]);

Directive

     myApp.directive('fileread', ['$http', function ($http) {

       return {
       restrict: 'E',
       scope: {
       opts: '='
        },

    link: function ($scope, $elm, $attrs) {

     $elm.on('change', function (changeEvent) {
      var reader = new FileReader();

        reader.onload = function (evt) {
        $scope.$apply(function () {
         var data = evt.target.result;

       var workbook = XLSX.read(data, {type: 'binary'});

       var headerNames = XLSX.utils.sheet_to_json(   workbook.Sheets[workbook.SheetNames[0]], { header: 1 })[0];

       var datasheet = XLSX.utils.sheet_to_json( workbook.Sheets[workbook.SheetNames[0]]);

       console.log(datasheet);

       $scope.opts.columnDefs = [];

       headerNames.forEach(function (h) {
         $scope.opts.columnDefs.push({ field: h });
       });

       $scope.opts.data = datasheet;
       var json_string = JSON.stringify($scope.opts.data);
       console.log(json_string);

       $elm.val(null);
        });
      };

       reader.readAsBinaryString(changeEvent.target.files[0]);
     });

    }, template:
       '<div ng-controller="MainCtrl as vm">'+
       '<button type="button" class="btn btn-success" ng-click="vm.reset()">Reset Grid</button>'+
       '<br />'+
       '<br />'+
       '<div id="grid1" ui-grid="vm.gridOptions" class="grid">'+
       '<div class="grid-msg-overlay" 
        ng-show="!vm.gridOptions.data.length">'+
        '<div class="msg">'+
        '<div class="center">'+
          '<span class="muted">Select Spreadsheet File</span>'+
          '<br />'+
          '<input type="file" accept=".xls,.xlsx,.ods" fileread=""     opts="vm.gridOptions" multiple="false" />'+
           '</div>'+
          '</div>'+
       '</div>'+
     '</div>'+
     '</div>'

      }

     }]);

Template from I am calling the directive

Dashboard Template

       var customDashboardTemplate =
       '<div class="row dashboard-starter"></div>' +
       '<question-stats></question-stats>'+
       '<div ng-controller="MainCtrl" >'+
       '<fileread>'+
       '<button type="button" class="btn btn-success" ng-click="reset()">Reset Grid</button>'+
       '<br />'+
       '<br />'+
       '<div id="grid1" ui-grid="gridOptions" class="grid">'+
       '<div class="grid-msg-overlay" ng-show="!gridOptions.data.length">'+
       '<div class="msg">'+
       '<div class="center">'+
        '<span class="muted">Select Spreadsheet File</span>'+
        '<br />'+
        '<input type="file" accept=".xls,.xlsx,.ods" fileread=""  opts="gridOptions" multiple="false" />'+
         '</div>'+
         '</div>'+
         '</div>'+
         '</div>'+
         '</fileread>'+
         '</div>'+
        '<div class="row dashboard-content">' +
       '<div class="col-md-6">' +
        '<div class="panel panel-green">' +
         '<ma-dashboard-panel collection="dashboardController.collections.last_users"  entries="dashboardController.entries.last_users" datastore="dashboardController.datastore"></ma-dashboard-panel>' +
        '</div>' +
      '</div>'+

    '<div class="col-md-6">' +
        '<div class="panel panel-yellow">' +
          '<ma-dashboard-panel collection="dashboardController.collections.last_tips"  entries="dashboardController.entries.last_tips" datastore="dashboardController.datastore"></ma-dashboard-panel>' +
        '</div>' +
        '</div>'+
      '</div>'+
      '</div>'
       ;

**Comment by fzaninotto** [comment]
Don't cross-post questions. Refs #872

**Comment by frank0ch0a** [comment]
I'm sorry , but my intention was not to cross -post , but I'm worried because I do not get the solution and have not your experienced , thank you and excuse me for post again.
