### ISSUE TITLE
Filter : How to disable auto submission

### ISSUE THREAD

**Issue by cookingkode** [marmelab/ng-admin#879]
I have 2 pinned  text filters. I want users to enter (leisurely) values and then use an explicit submit button to make the API call. Is there a way I can override the default filter behaviour of debounce and auto submission to API

I thought of doing a check in addFullRequestInterceptor() to make sure both params are present. But still this may mean that truncated fields and does not look like a clean solution..

**Comment by fzaninotto** [comment]
You'll have to implement your own filter form directive in replacement for `<ma-filter-form>`, and override the `listView` template to call it.

A more hackish way would be to override the `listLayoutController` through an angular decorator.

**Comment by huvber** [comment]
wasn't a better idea to put an option to active/deactive it? Most of the time the autosubmission is very annoying especially when you deal with a lot of entries. At least an autosubmission that submit after a space char would be more clever imo

**Comment by paulief** [comment]
+1 I'd love this feature as well, it'd be nice to keep some load off the server
