### ISSUE TITLE
Ng-admin causes webpack to hang in production mode

### ISSUE THREAD

**Issue by jontonsoup** [marmelab/ng-admin#880]
There seems to be a known bug that webpack / uglifyjs can'y minify code that has already been minified by uglifyjs in certain situations. This is preventing me from installing ng-admin in production because webpack is hanging on the build versions of ng-admin. 

Any solutions / thoughts?

**Comment by jpetitcolas** [comment]
You should give a try to last master version. We reviewed the way ng-admin is embedded with module bundlers, and it should be faster.
