### ISSUE TITLE
referenced_list does not respect entity specific baseApiUrl

### ISSUE THREAD

**Issue by dirkaholic** [marmelab/ng-admin#883]
I'm trying to build an admin interface that connects different admin API's in one app. ng-admin is the perfect way to do that. So I'm having one main admin api that I configure when creating the app like this:

```
var admin = nga.application('Admin interface')
            .baseApiUrl(location.protocol + '//' + ENTITY1_ADMIN_API_HOST + (ENTITY1_ADMIN_API_PORT ? ':' + ENTITY1_ADMIN_API_PORT : '') + ENTITY1_ADMIN_API_BASE_PATH + '/')
```

I have added an admin provider for an entity served by this api like this:

```
app.config(function($provide, NgAdminConfigurationProvider, RestangularProvider) {
        $provide.factory("Entity1Admin", function() {
            var nga = NgAdminConfigurationProvider;
            var entity1 = nga.entity('entity1').readOnly();
            ...
}
```

Then I have another entity from a second admin API defined like this:

```
app.config(function($provide, NgAdminConfigurationProvider, ENTITY2_ADMIN_API_HOST, ENTITY2_ADMIN_API_PORT, ENTITY2_ADMIN_API_BASE_PATH) {
        $provide.factory("TwitterAdmin", function() {
            var nga = NgAdminConfigurationProvider;
            var entity2 = nga.entity('entity2').baseApiUrl(location.protocol + '//' + ENTITY2_ADMIN_API_HOST + (ENTITY2_ADMIN_API_PORT ? ':' + ENTITY2_ADMIN_API_PORT : '') + ENTITY2_ADMIN_API_BASE_PATH + '/');
            ...
```

So far so good. I'm able to build the admin interface for editing both entities. Now I want to link them using a referenced list, so I add this for the first entity:

```
            entity1.showView()
                .fields([
                    nga.field('metadata', 'referenced_list')
                        .targetEntity(nga.entity('entity2'))
                        .targetReferenceField('id_entity')
                        .targetFields([
                            nga.field('id').label('ID'),
                            nga.field('value').label('description')
                        ])
                        .permanentFilters({
                            entity: 'team' // display only the metadata relevant for entity1
                        })
```

that should show all results from entity2 related to entity1 with applying a filter. 

It works for entities on the same host but in this case it tries to make make a connection to ENTITY1_ADMIN_API_HOST instead of ENTITY2_ADMIN_API_HOST as well which is wrong.

**Comment by dirkaholic** [comment]
Any news / comments on this ?

**Comment by jotadepicas** [comment]
@dirkaholic Hi, I'm having a related issue (I think). Have a look at this comment https://github.com/marmelab/ng-admin/issues/765#issuecomment-184648213

It seems to me that, if you use the variable to refer to `targetEntity`, and if you apply the workaround mentioned in #765 that I linked above, you should get your code to work.

I've found that if you use `nga.getEntity` instead of the variable, you have to re-define everything again. I didn't had a problem with the base API url like you, but had a simillar problem with `.identifier()` being ignored. 

Hope that helps!

**Comment by pdhoward** [comment]
Having the same problem. @dirkaholic -- did you get your code working?

**Comment by dirkaholic** [comment]
No, I use a ```ma-filtered-list-button``` now instead of the ```referenced_list``` so that I have at least a button pointing to the information which I wanted to show directly.

**Comment by dirkaholic** [comment]
Hi, one note: It might be possible to solve that by replacing 

```
.targetEntity(nga.entity('entity2'))
```
with
```
.targetEntity(nga.entity('entity2').baseApiUrl(location.protocol + '//' + ENTITY2_ADMIN_API_HOST + (ENTITY2_ADMIN_API_PORT ? ':' + ENTITY2_ADMIN_API_PORT : '') + ENTITY2_ADMIN_API_BASE_PATH + '/'))
```

when defining the target entity for the referenced list. At least this works for reference where the same issue occurs. Can not test with referenced_list right now as I do not have the use case any more.

**Comment by jpetitcolas** [comment]
@dirkaholic method is the easiest way to achieve this purpose. Closing the issue.

Feel free to re-open it if it doesn't solve your usecase.
