### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by d1b1** [marmelab/ng-admin#886]
Morning, I ran across your project and was stunned. I have been lementing the need to write custom API CRUD Admin UIs for all my projects. Your work in this project is amazing and super intuitive.

Got a direction question. Have you though about or explored the ability to the API to digest and schafold from existing API specs? For example, swagger JS. The ability to define an API and have it scale into the Admin layer, but still support extending and configurations would be very valuable. 

Thanks!

**Comment by fzaninotto** [comment]
Hi Stephan, and thanks for the feedback.

A question similar to yours was asked very quickly after ng-admin was initially published, see #32 for discussion. 

Also, we've created a (third-party) library to do that for Symfony, see https://github.com/marmelab/NgAdminGeneratorBundle. 

Anyway, that's not the responsibility of ng-admin core.
