### ISSUE TITLE
Can't submit form where a json field is required

### ISSUE THREAD

**Issue by josephwmorse** [marmelab/ng-admin#892]
<pre>
nga.field('details','json')
    .map(function(v,e){return angular.fromJson(v)})
    .transform(function(v,e){return angular.toJson(v)})
    .validation({required:true})
</pre>

This form will not submit even when I have entered valid json in the details field.  I have tested on Firefox 24.7 and Chrome 36.0.  This is with the 0.9.1 ng-admin release.

**Comment by fzaninotto** [comment]
Why do you need the toJSON/fromJSON stuff? you need to encode a JSON string into a JSON document? That's weird.

**Comment by josephwmorse** [comment]
The JSON editor expects the value of the field to be an object, not a string.  But of course the value has to be sent across the wire as a string.  So you need the map and transform functions to deserialize and serialize the object you are editing.  This is what the field displays like in the editor WITHOUT the map/transform:
<pre>
"{\"example_list\":[{\"example_key\":\"example_value\"},{\"example_key\":\"other_example_value\"}]}"
</pre>

and this is what it displays like when the fromJson/toJson functions are included:
<pre>
{
    "example_list": [
        {
            "example_key": "example_value"
        },
        {
            "example_key": "other_example_value"
        }
    ]
}
</pre>

For the record, setting .validation({required:true}) prevents submission of the form regardless of whether the map and transform functions are used.

**Comment by fzaninotto** [comment]
I still don't understand. The response body for the GET request to read an entity is already a JSON document, why would you encode a JSON string inside a JSON document?

**Comment by josephwmorse** [comment]
I have an entity ('project') that has an attribute ('config_details') that is a JSON object.  The config_details field is a configuration file with a dynamic set of key/value pairs, and it is stored on the server as a JSON-encoded string.  When we edit that field on the client, we'd like to use the JSON editor instead of just a textarea.  Is that not supported?  One of the reasons we decided to use ng-admin was the built-in JSON editor.

**Comment by fzaninotto** [comment]
the `json` filed type assumes that the value is a JavaScript object, not a string. If the value for your object is indeed a string, you'll need an element transformer to turn it into a string (see http://ng-admin-book.marmelab.com/doc/API-mapping.html).

**Comment by josephwmorse** [comment]
Oh so I can't use .map() to do that?  angular.fromJson(v) returns a JavaScript object - I thought I could just do that to convert from a string to an object.  When I do that, everything works fine except when I set .validation({required:true}).  You are saying the validation won't work unless the value is an object even before the .map function is applied?
