### ISSUE TITLE
ng-admin-only.min.js contains angular?

### ISSUE THREAD

**Issue by vasiakorobkin** [marmelab/ng-admin#893]
When I'm including `ng-admin-only.min.js` file into my build, next warning appears in browser console:
```
WARNING: Tried to load angular more than once.
```

So I've looked at `ng-admin-only.min.js` file contents and noticed [this line](https://github.com/marmelab/ng-admin/blob/master/build/ng-admin-only.min.js#L23)
It makes me think that `ng-admin-only.min.js` contains minified version of angular despite of fact that it is "standalone".

Am I right? Is it some bug in `ng-admin-only.min.js` building process?

**Comment by fzaninotto** [comment]
Yes, that's a known issue, that @jeromemacias started to fix a while ago in #743.

**Comment by mappedinn** [comment]
which version solved the issue?
Thanks :)

**Comment by laptevn** [comment]
Why the issue was closed?
The same problem with version 0.9.1.

**Comment by pacproduct** [comment]
I'm also having the same issue with version 0.9.1: When including ng-admin like so:
`<script src="lib/ng-admin/ng-admin-only.min.js"></script>`

It tells me the following in Chrome's dev console:
`WARNING: Tried to load angular more than once.`
