### ISSUE TITLE
make embeded_lists not editable in editionView

### ISSUE THREAD

**Issue by pelim** [marmelab/ng-admin#894]
how can i make a an embeded_list not editable in the editionView?

**Comment by fzaninotto** [comment]
Override the field template, or use another type than `embedded_list`.

**Comment by fomojola** [comment]
Leaving this here for anyone else who stumbles upon this: add this to the embedded_list field to use a datagrid in the editionView.

`.template('<ma-embedded-list-column field="::field" value="::value" datastore="::datastore"></ma-embedded-list-column>')`

The template comes from https://github.com/marmelab/ng-admin/blob/master/src/javascripts/ng-admin/Crud/fieldView/EmbeddedListFieldView.js
