### ISSUE TITLE
Handling very basic "embedded_list"

### ISSUE THREAD

**Issue by Dsls** [marmelab/ng-admin#895]
Hello,

I am trying to handle embedded_lists, which are simple array of elements (no field name, just a list of strings).

It seems that adding a "embedded_list" field requires to use targetField(). However, in the case of a simple liste of strings, there is no named field.

Any clue on how to handle that ?

Thanks in advance,

Regards,
Bruno

**Comment by fzaninotto** [comment]
`embedded_list` isn't designed for that use case. Write a custom directive (it should only take a few lines of code), or use the `json` type instead.
