### ISSUE TITLE
Spring Data HATEOAS support

### ISSUE THREAD

**Issue by boxhead201** [marmelab/ng-admin#896]
Hi;

  Are there any plans to get this project to work with Spring Data's HATEOAS?  More specifically, being able to work with referenced entities within entities?  Right now I am having to put in a ton of mapping in to "pull up" attributes from child JSON objects in order to get ng-admin to see these attributes.  This works for the most part, but I am unable to PUT entities easily because of Spring Data's semantics on how dependent entities should be saved; e.g. different URL, and multiple URL calls may need to be done for a single object update.  I am sorry for the vagueness, I can elaborate if absolutely necessary.

**Comment by fzaninotto** [comment]
No, there are no such plans. Feel free to fork the project and add the feature on your side, though.

**Comment by boxhead201** [comment]
Hi Fzaninotto;

  Thanks for your response.  Do you think you could give me some rough pointers on what I need to modify in your codebase in order to achieve what I am after ?

**Comment by fzaninotto** [comment]
To get started, take a look at:

* src/javascripts/ng-admin/Crud/routing.js
* src/javascripts/ng-admin/Crud/repository/ReferenceRefresher.js
* src/javascripts/ng-admin/Crud/column/maReferenceColumn.js
* src/javascripts/ng-admin/Crud/column/maReferenceManyColumn.js
* src/javascripts/ng-admin/Crud/field/maReferenceField.js
* src/javascripts/ng-admin/Crud/field/maReferenceManyField.js
* src/javascripts/ng-admin/Crud/form/FormController.js
