### ISSUE TITLE
maDateField doesn't support changing value

### ISSUE THREAD

**Issue by fedotxxl** [marmelab/ng-admin#899]
`value` of `maDateField` may be changed by external function (let's assume that I've got custom button wich changes entry value). 

expected: `maDateField` should display new value
result: `maDateField` displays old value

**Comment by fzaninotto** [comment]
true, maDateField should watch changes on `value` to keep two way data binding. Would you like to work on a patch?

**Comment by ifokeev** [comment]
need it too :(
