### ISSUE TITLE
Populating choices with Ajax

### ISSUE THREAD

**Issue by TheBlusky** [marmelab/ng-admin#907]
Hello !
I would like to populate choices in my application in Ajax (because many_to_many fields doesn't seems to be editable, like referenced_list).

So here is my actual code :

	export default function (nga, admin) {

		var options_choices = require('./options_choices')(nga, admin);

		var user = admin.getEntity('user');
		user.listView().fields([
			nga.field('id'),
			nga.field('nom')
		]);
		user.editionView().fields([
			nga.field('nom'),
			nga.field('options', 'choices')
				.choices(options_choices),
		]);
		return user;
	}

and :

	export default function (nga, admin){
		var options_choices = [XXX POPULATE THID IN AJAX XXX]
		return options_choices.map(choice => {
			return { label: choice, value: choice }
		})
	};

Any idea how to perform this ?
Thanks !

**Comment by SebLours** [comment]
For me it's a reference.
You can create a new entity for your options choices and set as reference for your user entity.
This new entity can be just create for this case with an only ListView enabled.

**Comment by fzaninotto** [comment]
Yep, the right way is just what @SebLours explained.
