### ISSUE TITLE
Adding a template to the embedded-list 

### ISSUE THREAD

**Issue by DNWEIJ** [marmelab/ng-admin#910]
Hello, 

I was wandering how to add a template to an embedded-list. 
As far as i have seen now, this is handled directly in the embedded-list code: maEmbeddedListField.js, where a template is defined and used.

I have been able to add a template with .template()  in the config, as a (silly) example....
var addressEmbeddedTemplate('<div>hello</div');
nga.field('adress', 'embedded_list').template(addressEmbeddedTemplate).label('Address').

Question is how to add the fields from the respective entity? In other words, how do i get the corresponding fields from the 'address' object into the template?
In the embedded template in maEmbeddedListField, the reference is direct but know i need to reference it from 'outside'.

I would like to change the current layout from key value pair to a address format such as:
  street housnumber
  zipcode city state 
  country
This seams  more appealing to me. 

Much appreciated for your help.

**Comment by fzaninotto** [comment]
Hi,

You should write a custom directive for that. embedded_list is too generic for your need.
