### ISSUE TITLE
require is not defined when trying to customize the view for entire app

### ISSUE THREAD

**Issue by beatelite** [marmelab/ng-admin#912]
following this: http://ng-admin-book.marmelab.com/doc/Theming.html#customizing-the-view-templates-for-the-entire-application

Put the code in my main.js file 

```
var myTemplate = require('text!./assets/listView.html');
var admin = nga.application('My Application');
admin.customTemplate(function(viewName) {
    if (viewName === 'ListView') {
        return myTemplate;
    }
})

```

and I get the error 
`"require is not defined "`

in the console. Any idea why?

**Comment by fzaninotto** [comment]
Use requirejs or Webpack to be able to use module features.

**Comment by beatelite** [comment]
So just to be clear because I didn't see this in the docs, should I just install either of them via npm and load their scripts on the page?

Is there somewhere in the docs this is mentioned? It's possible I missed it. I'm a skimmer at best. ;)

**Comment by beatelite** [comment]
figured it out. Followed a tutorial on webpack and was able to get it up and running. Thanks
