### ISSUE TITLE
Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to: Error: [$injector:unpr] Unknown provider: maMenuBarProvider

### ISSUE THREAD

**Issue by beatelite** [marmelab/ng-admin#913]
First. I love this project. I was spending weeks doing something from scratch when I found this. Great job!

I'm attempting to override the template for the maMenuBar directive using this [guide](https://github.com/marmelab/ng-admin/blob/master/doc/Theming.md#customizing-directives-templates):

I've got this in my main.js file:

```
myApp.config(function(NgAdminConfigurationProvider, $provide) {
        // Override textarea template
        $provide.decorator('maMenuBar', ['$delegate', function ($delegate) {
       
            $delegate[0].template = '';
            $delegate[0].templateUrl = '../tpl/sideBarView.html';

            return $delegate;
        }]);

        // ...
});
```

I'm getting this error: 
```

Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to:
Error: [$injector:unpr] Unknown provider: maMenuBarProvider
```

Any idea why? Do you have any more tutorials on theming? It would be a big help.

**Comment by fzaninotto** [comment]
Did you try adding the `Directive` suffix?

```
$provide.decorator('maMenuBarDirective', ['$delegate', function ($delegate) {
```

**Comment by beatelite** [comment]
Ok that worked. However, now I am getting the exact same menu to show up. Even though I have this defined:

```
myApp.config(function(NgAdminConfigurationProvider, $provide) {
        // Override textarea template
        $provide.decorator('maMenuBarDirective', ['$delegate', function ($delegate) {
            // You can modify directly the template

            $delegate[0].templateUrl = '/app/themes/ar-admin/app/assets/tpl/sideBarView.html';

            return $delegate;
        }]);

        // ...
});
```

in my sideBarView.html template, I have:
```

<div class="navbar-default sidebar sidebar-menu" role="navigation" compile="menu.template()">
    <h1> TESTING</>
</div>

```


However, the original menu shows up. When I check the console network tab, I see a 200 on the sidBarView.html. If I change the path to sideBarView.html, I get a blank space where the menu used to be. 

This is unexpected. I assumed creating a new template would override the existing template for the directive but this does not seem to be the case. Any suggestions?

**Comment by beatelite** [comment]
I didn't fix this perse, but I did end up creating my own custom menu via a directive.
