### ISSUE TITLE
update entry

### ISSUE THREAD

**Issue by ifokeev** [marmelab/ng-admin#915]
Is there a way to update entry in the list view? 
I have the custom button that update state for my entry and I want to update it in the list view.

**Comment by beatelite** [comment]
I found this by searching. Not a complete answer but could get you on the right path : https://github.com/marmelab/ng-admin/issues/287

**Comment by ifokeev** [comment]
@beatelite I found this https://github.com/marmelab/ng-admin-demo/blob/9b9c9e15311cd72edddde7c2b54081791f7ab7d4/js/reviews/approveReview.js#L20 and updating $state now. Not a good solution, but it works.

**Comment by fzaninotto** [comment]
Not supported by ng-admin, use your own directives for that.
