### ISSUE TITLE
"Stage change error" change

### ISSUE THREAD

**Issue by daniel-rosiak** [marmelab/ng-admin#917]
Is it possible to change text "Stage change error" or somehow disable build errorHandler ?

**Comment by fzaninotto** [comment]
Probably, by configuring ui-router. See for instance https://github.com/angular-ui/ui-router/issues/1783#issuecomment-76976396.

**Comment by daniel-rosiak** [comment]
Well that way I get two notifications when error occurs: first with:  "Stage change error" and the second one that I configured using this solution.
So that solution just adds another errorHandler and has no influence on that declared in node_modules/ng-admin/src/javascripts/ng-admin/Main/run/ErrorHandler.js.

**Comment by fzaninotto** [comment]
Ah, sorry, you're right. This one can't be disabled then.

**Comment by Phocea** [comment]
@fzaninotto We could avoid the issue if errorHandler was using a Service/Provider.
Then using $decorator anyone can do whatever they want.

Would this be an acceptable change inside ng-admin if I propose it?
