### ISSUE TITLE
Tagging on the fly with multiselect list 

### ISSUE THREAD

**Issue by beatelite** [marmelab/ng-admin#919]
Loving this app-framework so far. Really fantastic job - teaching me a few new things to boot!

I know you use ui-select for the mutli-select. Does ng-admin have field to allow users to enter their own tags on the fly?

ui-select supports it with the "tagging" option. https://github.com/angular-ui/ui-select/wiki/ui-select#attributes

Wondering if ng-admin has any magic support under the hood for it.

**Comment by fzaninotto** [comment]
Nope, you'll have to use a custom field template / directive for that.
