### ISSUE TITLE
Adding params to the end of the GET request for a post

### ISSUE THREAD

**Issue by beatelite** [marmelab/ng-admin#920]
For the api I'm using,  I need to get access to some additional properties on a GET request,by using
 '`?context=edit`' 
appended to the end of the request. so the final route would look something like this:

` /post/1?context=edit`

I did see this: http://ng-admin-book.marmelab.com/doc/API-mapping.html#filtering

It looks like that might be for returning a list of filtered content though.

Never used restangular before (always $resource). Does this need to happen via an interceptor? Or how should I go about it?

I can post in Restangular too if this is not an appropriate place.

**Comment by fzaninotto** [comment]
Yes, you should use Restangular for that.
