### ISSUE TITLE
ui-bootsrap $uibModal service throwing major shade

### ISSUE THREAD

**Issue by beatelite** [marmelab/ng-admin#922]
**Summary:**
Trying to get a modal in my custom page to work but getting error

**Reproduction Steps:**
 I injected $uibModal into my directive's controller, loaded the ui-bootstrap/ng-animate scripts and required the ui-boostrap and ng-animate on the app as a dependency to my angular app. 

**Current results:**
 I keep getting this error: 
`Error: [$injector:unpr] Unknown provider: $animateCssProvider <- $animateCss <- $uibModalStack <- $uibModal`

Looks like it's related to [ng-animate requiring angularjs 1.4.+](https://github.com/angular-ui/bootstrap/issues/5139) 

I saw that you're working on updating to require angular 1.4.+ here https://github.com/marmelab/ng-admin/issues/567 Is that coming out soon or should I unbundle all of ng-admin, load angular myself and then redeclare all the ng-admin dependancies? Which I can do but seems like overkill if you have the move coming soon.

**Comment by fzaninotto** [comment]
Angular 1.4 is not yet supported. Compatibility is on top of our todo list, but I can't give you an estimate date.

**Comment by d1b1** [comment]
+1 Ran into the same problem trying to use angular modal service. Tried to unbundle and found it lead to a range of version issues.

**Comment by d1b1** [comment]
Is there a roadmap of coming features? I am working around the angular version issue that prevents ngAnimate from working.

**Comment by alexisjanvier** [comment]
The master branch of ng-admin now uses angular 1.4. I updated ui-bootstrap in the PR #957 and I'll try to implement `$uibModal` very soon.

**Comment by alexisjanvier** [comment]
I tested the ui-modal on ng-admin with an updated ui-bootstrap. It seems working on my side.

**Comment by fzaninotto** [comment]
#947 fixes the issue.
