### ISSUE TITLE
Hiding label with fieldViewconfiguration

### ISSUE THREAD

**Issue by Gu3** [marmelab/ng-admin#930]
Hi ! 
Thanks for your amazing job ! I started using your project since 2 weeks. 

I need to custom some fields, and create new one.. So after reading the cookbook, I have a little problem. 

I have a new field : Fieldset. I've created a new FieldsetField, + FieldsetView + fieldsetDirective to manage the template. So far, so good ! But I want to hiding the fieldset label (not just the fieldset but all the parents div, to win some width..). 

I know It's possible in the field configuration, if the second parameters of template is === true.
But I can't find a way in my situation... 

Any ideas ?  
Cheers.

**Comment by fzaninotto** [comment]
You can try calling:

```js
myField.templateIncludesLabel(true)
```
