### ISSUE TITLE
SockJS - [WDS] Disconnected

### ISSUE THREAD

**Issue by alecgibson** [marmelab/ng-admin#934]
We're running ngAdmin, but it keeps polling for `http://localhost:8000/sockjs-node/info?t=XXX`

This results in a 404, and a JavaScript console error of `[WDS] Disconnected!`

Is this a fault of our setup? If so, I can't find any documentation describing how to fix or set up SockJS.

**Comment by alecgibson** [comment]
Assuming this is to do with the bundled webpack-dev-server? Is there any way to disable it if we don't need it? I've got a temporary fix by locally commenting out line `74947` of `ng-admin.min.js`:
`newConnection();`

**Comment by fzaninotto** [comment]
I think this was fixed in #923. Can you test with the master branch?

**Comment by fzaninotto** [comment]
It is fixed, closing. Feel free to reopen if you still have the issue on master branch.
