### ISSUE TITLE
Accessing formController or Reference fields from Custom Page

### ISSUE THREAD

**Issue by d1b1** [marmelab/ng-admin#935]
Hi, I am looking for a way to create a custom Page that access Refernces. Is it possible to access more the nga fields and configurations?

**Comment by fzaninotto** [comment]
I have no idea what you're talking about. References are used by ng-admin for its own pages. If you want to make a custom page, call Restangular directly, you don't need ng-admin for that.

**Comment by d1b1** [comment]
Sorry, upon review my question was poorly worded. 

I will try again. I have now spent a good amount of time working ng-admin for two projects. The standards show, create and edit views are great, but I am trying to add more custom directives while accessing the features of the library. I am trying to find ways to access ng-admin fields from within directives, modals etc. 

Are there any examples of modals or more detailed templates?
