### ISSUE TITLE
Create an external link in the tab menu?

### ISSUE THREAD

**Issue by nicolashardy** [marmelab/ng-admin#939]
Hello,

I'm trying to create an absolute link in the tab menu on the left

If i try this

`admin.menu(nga.menu()
         .addChild(nga.menu()
         .title('Test')
         .link('http://www.google.fr')
         .active(function(path) {
            return path.indexOf('http://www.google.fr') === 0;
         })
         )
     );`

The link is #http://www.google.fr :(

How can I make it ?

Thanks

**Comment by fzaninotto** [comment]
The `Menu` objects accept a ` template()` method, in which you can put the HTML/Angular code you want. That's what you should use. I'll update the doc to reflect that.
