### ISSUE TITLE
Sorting problem when exporting data

### ISSUE THREAD

**Issue by re1naldo** [marmelab/ng-admin#941]
**How to reproduce issue:**
1. Sort data with different order than initial setup.
2. Do the export operation.

**Result:**
1. Data in CSV is sorted by ID (descending).
2. The exported result only contains data from the first page.

**Expected result:**
1. Data in CSV is sorted properly.
2. The exported result contains data from all pages.

**Comment by fzaninotto** [comment]
I can reproduce the sorting problem, not the pagination problem.
