### ISSUE TITLE
how to bind a ng-admin table to other ui-view

### ISSUE THREAD

**Issue by liuziliang** [marmelab/ng-admin#943]
I want to build a table in some other dom element in a web page, such as modal window or  tab divs, is there any way to change the ng-admin table to render to another ui-view?

**Comment by fzaninotto** [comment]
ng-admin is separated into components. If you want to uses these components outside of ng-admin pages, you can, but you must know what you're doing. Otehrwise, look at the [Theming doc](http://ng-admin-book.marmelab.com/doc/Theming.html) for what's currently supported out of the box.
