### ISSUE TITLE
Outdated version of restangular causing bug with lodash

### ISSUE THREAD

**Issue by jontonsoup** [marmelab/ng-admin#948]
The current version of restangular in ng-admin has a bug with the latest version of lodash:

https://github.com/mgonto/restangular/issues/1298

This should be solved by updating to the latest version of restangular and recreating the builds. 

I can make a PR if that is helpful. 

Best,
Jon

**Comment by alexisjanvier** [comment]
I opened the PR about that (https://github.com/marmelab/ng-admin/pull/950).
Thanks for your help !
