### ISSUE TITLE
Is there a way to include csrftoken?

### ISSUE THREAD

**Issue by wyx2000** [marmelab/ng-admin#955]
Is there a setting to turn it on? I could not make my DRY to not check csrftoken

**Comment by fzaninotto** [comment]
What's a DRY?

**Comment by wyx2000** [comment]
DRFDjango rest framework


Sent from my Samsung device

-------- Original message --------

**Comment by fzaninotto** [comment]
There is no support for CSRF token in ng-admin. But you can use Restangular interceptors to update requests before ng-admin sends them. It's up to you to do it.
