### ISSUE TITLE
Embedded fields + choice field choices function

### ISSUE THREAD

**Issue by tgeorges** [marmelab/ng-admin#958]
I want to use a choice field in embedded list field. 
The main functionnality is working, but, when I want to filter choice list using choices function (instead of array), I need to access the parent entry values, in order to filter list depending on choices in the parent entry.

This is a very common use case I will need to have different subtypes (ie they are sharing a lot but not all) of data in embedded list.

Is it an existing functionality, is it planned ?

By the way, I need to do the same things for the validator.

Thanks

**Comment by tgeorges** [comment]
By the way, I need

**Comment by jpetitcolas** [comment]
May the `choice.choices()` method solve your issue?

Look for `choices(function(entry) {` on [Field doc](https://ng-admin-book.marmelab.com/doc/reference/Field.html).

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

Thanks for using ng-admin!
