### ISSUE TITLE
Problem with DateField

### ISSUE THREAD

**Issue by fzaninotto** [marmelab/ng-admin#961]
JS error in ng-admin-demo in creation view

**Comment by alexisjanvier** [comment]
There is also a problem with filter `visited since` in vistor's list. I think it's linked to the same problem with the new `uib-datepicker-popup` (since ui-bootstrap has been updated). That is the error :  
```
angular.js:12722 Error: [$compile:ctreq] Controller 'ngModel', required by directive 'uibDatepickerPopup', can't be found!
```

**Comment by sm-g** [comment]
Is demo site updated? Adding 'visited since' filter on http://marmelab.com/ng-admin-demo/#/customers/list?search=%7B%22has_ordered%22:true,%22has_newsletter%22:false%7D redirects back to this url.
