### ISSUE TITLE
Specifying a field twice breaks the field ordering

### ISSUE THREAD

**Issue by KonstantinYegupov** [marmelab/ng-admin#963]
Encountered with a code somewhat like this:

    var fields = {
        name: nga.field('name').editable(false),
        somethingElse: nga.field('somethingElse'),
        ... };
    entity.editionView().fields([
        nga.field('id').editable(false),
        fields.name,
        fields.somethingElse,
        fields.name,
        fields.yetAnotherField, 
        ....
    ]);

Specifying a same field twice will cause the order of remaining fields to be shuffled unpredictably. Yes, it's a configuration error, but it should be handled more gracefully.

**Comment by fzaninotto** [comment]
Configuration error and edge case, ng-admin won't deal with it.
