### ISSUE TITLE
Referencing nested ids with ng-admin

### ISSUE THREAD

**Issue by NadavK** [marmelab/ng-admin#964]
I am trying to reference the orders object with nested ids:
```javascript
{"user":
    "id": 1,
    "orders": [
        {"order_id": 100},
        {"order_id": 101}
]}
```

This is the view definition:
```javascript
user.showView().fields([
    nga.field('orders.id', 'reference_many')
        .targetEntity(order)
        .targetField('id')
]);
```

The code above returns the following error:

> (state change error: e.targetField(...).name is not a function)

Can someone can help?

Note: Also posted on [SE](http://stackoverflow.com/questions/35838555/referencing-nested-ids-with-ng-admin)

**Comment by fzaninotto** [comment]
As [explained in the doc](http://ng-admin-book.marmelab.com/doc/Relationships.html#array-of-foreign-keys), `reference_many` is relevant when you have an array of foreign keys. In your example, you don't have an array of (scalar) foreign keys, but an array of objects. If you want to use `reference_many`, you have to use a Restangular Interceptor to make the entity look like what ng-admin expects.

**Comment by fzaninotto** [comment]
Also, please don't cross-post your question everywhere, it gives maintainers and volunteers more work.
