### ISSUE TITLE
Theming: Angular Material Design

### ISSUE THREAD

**Issue by cpursley** [marmelab/ng-admin#965]
Maybe this goes beyond the scope of this project, but an Angular Material Design version of ng-admin would be really great. [Material Start](https://github.com/angular/material-start) seems like a good starting place. I'm assuming it would be a matter of making the templates dynamic based on some type of config settings. Anyone else interested?

**Comment by cpursley** [comment]
*(feel free to label as enhancement)*

**Comment by fzaninotto** [comment]
We won't switch to Material Design for the near future, the Bootstrap ecosystem answers most of our needs already.
