### ISSUE TITLE
Have to set base URL for exclusively restangular 

### ISSUE THREAD

**Issue by xydac** [marmelab/ng-admin#967]
Hi,
Even after using below for setting base URL, 

`var admin = nga.application('Admin').baseApiUrl('https://api-url/wc-api/v3/'); // main API endpoint`

I had to exclusively set base URL for Restangular as below:

`RestangularProvider.setBaseUrl('https://api-url/wc-api/v3/');`

Shouldn't this be default behavior after setting  the initial base url ?
I had to do so in case i had to use `Restangular.one()`

**Comment by d1b1** [comment]
+1 and it means and interceptors have to be duplicated outside admin.

**Comment by fzaninotto** [comment]
Nope, ng-admin shouldn't mess with YOUR Restangular. I understand the unexpected surprise, but Restangular being global, it's not responsible to modify it - it could break things up somewhere else.
