### ISSUE TITLE
There is a 'onchange' event in a nga.field 'choice'??

### ISSUE THREAD

**Issue by ManuelFunciona** [marmelab/ng-admin#970]
Hi Team,

I am a beginner with 'ng-admin' and I wonder if there is a 'onchange' event in a nga.field of type 'choice'.

My app is multilingual and when I edit a news, depending on the language you choose in nga.field 'choice', charge the news in one language or another.

Is this possible??

Thanks all people.

**Comment by josephwmorse** [comment]
Since ng-admin is built on AngularJS, you can add a ng-change attribute:

nga.field('language','choice').choices(['EN','ES']).attributes({'ng-change':changeFunc})

**Comment by windmaomao** [comment]
Thanks @josephwmorse , interesting, how does this function will notify the rendering of another field, I'm wondering about this.

**Comment by jpetitcolas** [comment]
@windmaomao: you should `$watch` your `language` attribute in another (probably) custom directive. Closing the issue as this is not related directly to `ng-admin`. Feel free to ask some help on our [Gitter](https://gitter.im/marmelab/ng-admin). :)
