### ISSUE TITLE
Integration with existing application

### ISSUE THREAD

**Issue by LeonardoGentile** [marmelab/ng-admin#973]
This is more a question than an issue: is it possible to integrate ng-admin with an existing application using a minimalistic approach? Meaning, using only the services, the ORM mapping, the form generation and other utilises but taking out routing, templates, ui and so on?

If yes, how? Is there a section in the Doc?

**Comment by jpetitcolas** [comment]
I never heard about such a usage. It would be quite difficult in my opinion, as we didn't split our code to favorize this kind of use.

The simplest way to achieve it is perhaps to embed only the features you want with Webpack, something like:

```
const dateField = require('ng-admin/javascripts/ng-admin/Crud/field/maDateField');
```

But it would probably requires a lot of efforts.

Closing the issue. Do not hesitate to ask for help on our [Gitter](https://gitter.im/marmelab/ng-admin). :)
