### ISSUE TITLE
upload not work

### ISSUE THREAD

**Issue by hmendes00** [marmelab/ng-admin#974]
here's my code

`companies.creationView()
.fields([
nga.field('name')
.validation({ required: true }),
nga.field('logo', 'file').uploadInformation({ 
'fileName': nga.field('name') + '.png',
'url': (baseurl + 'companies/logos'),
'method': 'PUT'})
]);`

butt do I need to put some server-side code?
how can I see the image?

thank you.

**Comment by jpetitcolas** [comment]
@hmendes00: yes, you need server-side code. The `file` field just send your file data to the server. It doesn't store it anywhere (this is server duty).
