### ISSUE TITLE
Get nested entity collection from a specific type

### ISSUE THREAD

**Issue by 3kynox** [marmelab/ng-admin#975]
Hello, I would like to achieve get nested entities by specify a type available in a discriminator number : 

```json
{
  "id": 1,
  "date_creation": "2016-03-09",
  "date_modification": "2016-03-09",
  "moyens_comm": [
    {
      "id": 2,
      "adresse": "99, Rue de la Colline",
      "code_postal": "34570",
      "ville": "Vailhauquès",
      "latitude": 43.6672437,
      "longitude": 3.7227233,
      "disc": 3
    },
    {
      "id": 5,
      "email": "b.martins@cw.fr",
      "disc": 2
    },
    {
      "id": 9,
      "numero": "01 02 03 04 05",
      "disc": 1
    }
  ],
  "nom": "MARTINS",
  "prenom": "Bruno",
  "date_naissance": "1977-12-16"
}
```

Basically, disc types is at follow : 
- 1 -> Telephone
- 2 -> Email
- 3 -> Adress

All this types inherits from moyens_comm (translate as communication ways).

I currently display results in specific categories, but response is quite weird : 

```javascript
nga.field('moyens_comm', 'embedded_list')
            .label('Telephones')
            .targetEntity(nga.entity('telephone'))
            .targetFields([
                nga.field('numero')
            ])
          nga.field('moyens_comm', 'embedded_list')
              .label('Emails')
              .targetEntity(nga.entity('email'))
              .targetFields([
                  nga.field('email')
              ]),
          nga.field('moyens_comm', 'embedded_list')
              .label('Adresses')
              .targetEntity(nga.entity('adresse'))
              .targetFields([
                  nga.field('adresse'),
                  nga.field('code_postal'),
                  nga.field('ville')
              ])
```

gives : 

![](http://i.imgur.com/0MlYoqg.png)

Any advices doing this in a proper way ?

Tks

**Comment by pelim** [comment]
if the order of [moyens_comm] is in every request the same this cloud easily done by

`nga.field('moyens_comm[0].address')
`
otherwise you could map the api response with an interceptor
https://github.com/marmelab/ng-admin/blob/master/doc/API-mapping.md

or simply try to user the map and transform function 

https://github.com/marmelab/ng-admin/blob/master/doc/reference/Field.md#general-field-settings

**Comment by fzaninotto** [comment]
Thanks @pelim!
