### ISSUE TITLE
Pagination not working

### ISSUE THREAD

**Issue by bvigga** [marmelab/ng-admin#977]
Hi
I am using ng-admin ver 0.9.x and I can't get pagination to work either on the dashboard or listview. I have over 100 records in users table and would like to limit this to 10 users per page. Instead ng-admin pulls all the records in collection. I have followed the learning examples to the letter. I am missing something I am not aware of?

**Here is what my REST api returns **

[
{
    "_id": "533b064b121d8a138ed6baeb",
    "userid": "Abc",
    "name": "CDF",
    "email": "1a2@gmail.com",
    "privilege": "Student",
    "classes": [
      {
        "year": 2014,
        "class": "Pilot"
      }
    ],
    "schoolCode": "NASS",
    "imageUrl": "image/img_placeholder.jpeg"
  },
  {
    "_id": "533b0674121d8a138ed6baec",
    "userid": "ABC",
    "name": "EFG",
    "email": "1b1@gmail.com",
    "privilege": "Student",
    "classes": [
      {
        "year": 2014,
        "class": "Pilot"
      }
    ],
    "schoolCode": "NASS",
    "imageUrl": "image/img_placeholder.jpeg"
  }
]

**Here is my admin defined:**
 var admin = nga.application('Admin Tool')
        .baseApiUrl('http://localhost:3000/api/')
        .title('Teacher Tool');

    var user = nga.entity('users')
        .identifier(nga.field('_id'));

**The list view:**
    user.listView()
        .title('All users')
        .description('List of users')
        .perPage(10)
        .fields([
            nga.field('userid'),
            nga.field('name'),
            nga.field('email'),
            nga.field('privilege'),
            nga.field('schoolCode').label('School')
        ])

**The custom dashboard:**

admin.dashboard(nga.dashboard()
        .addCollection(nga.collection(user)
            .name('users')
            .title('SAC Users')
            .perPage(5)
            .fields([
                nga.field('userid'),
                nga.field('name'),
                nga.field('email', 'email')
            ])
            .sortField('name')
            .sortDir('DESC')
            .order(1)
    )
        .template(customDashboardTemplate)
);

**Comment by Phocea** [comment]
For the paging to work your must return X-Total-Count in your response header or totalcount has one of your response properties. See https://github.com/marmelab/ng-admin/blob/master/doc/API-mapping.md#total-number-of-results

**Comment by bvigga** [comment]
Hi,
Forgive my naivety but how do I modify my rest api below to return X-Total-Count and Content-Range response headers with their values. Any code snipet would suffice.
I am fairly new to the express/node programming.

app.get('/api/users', users.requiresLogin, users.findAll);

Thanks

**Comment by Phocea** [comment]
This all depends on the technology stack you are using. i dont have a node server, so cant help you there. Look at your REST API contract. The X-Total-Count is a message header param, may be easier to add the totalCount parameter to your message body.

**Comment by wiill** [comment]
@bvigga encoutered the same problem as you.

First, set the header this way (based on Nodejs express)
`res.setHeader('X-Total-Count', rows.length);`

And send only the results paginated by the request:

`res.json(rows.slice(_start, _end));`

rows being all the results for the database query
 (I use the Restangular interceptor provided in the [Getting Started](https://github.com/marmelab/ng-admin/blob/master/doc/Getting-started.md))

**Comment by fzaninotto** [comment]
This is not related to ng-admin, closing.
