### ISSUE TITLE
Group fields in edition/creation view?

### ISSUE THREAD

**Issue by eddyLazar** [marmelab/ng-admin#978]
Is there a way to group fields in view or how could it be implemented?

**Comment by FelixMalfait** [comment]
Same here, I have about 100 fields and I would be really keen to know how to group them into tabs?
Maybe there's a way to tweak something with cssClasses?
Thanks a lot

**Comment by jefbarn** [comment]
+1
I need this for the App I'm working on. Don't really like the tabs, but will probably try to implement this by allowing fields have 'parent' nodes somehow.  Basically I want it to look like the JSON output in a way (maybe without all the table cruft)  Can probably get it up and running with a custom directive.

**Comment by FelixMalfait** [comment]
I came up with a solution to add tabs. It works great but it's a very very ugly tweak so I'm not going to post it here.
If interested please let me know.

**Comment by eddyLazar** [comment]
I'm interested) 
Let's make it less ugly

**Comment by FelixMalfait** [comment]
Well I would have warned you ;)
https://gist.github.com/FelixMalfait/1d3869c83769cf2af434
Basically:
1) I'm adding a css class to each field to identify which tab it belongs to (tasks.config.js)
2) I define a function to show/hide fields for that have given classes (tools.js)
3) I'm adding a fake field which inserts the tabs  (tasks.config.js)
4) On load, every fields are loaded by ng-admin, the <init-tabs> directive allows to hide the field that don't belong to the current tab (taskTabs.html, initTabs.js)
I never do JS so I'm sure we can work to make something better :)

**Comment by fzaninotto** [comment]
Take a look at #657 for an alternative approach. 

Adding support for other layouts isn't in the scope of ng-admin for the near future. If you have too many fields on a single screen, your admin is probably not usable anyway ;)

**Comment by Phocea** [comment]
@FelixMalfait Would you mind reposting your gist please ? Link seems broken. Thanks

**Comment by gotthardp** [comment]
Hello. I just made [a gist](https://gist.github.com/gotthardp/eedbd85b5304f562fca555a7d6a7d491) showing how to add tabsets to ng-admin. A screenshot of the tabs is [here](https://github.com/gotthardp/lorawan-server/blob/master/doc/images/admin-node.png).
