### ISSUE TITLE
PUT payload contains entire entity object instead of just fields defined in editionView

### ISSUE THREAD

**Issue by drobinson** [marmelab/ng-admin#983]
I would expect that if it's possible to define fields for the editionView then by default only those fields should be included in the PUT payload to the resource.  

If this is possible (and just not the default behavior) can you point me in the right direction? From what I can see, this cannot be done with the Restangular interface provided.

**Comment by drobinson** [comment]
I can see that this has been answered by @fzaninotto here: http://stackoverflow.com/questions/34628928/ng-admin-can-editionview-only-update-the-changed-fields

but can you provide a bit more information on how this can be done, or consider moving some of that functionality into ng-admin?  From what I can see, it's not possible to add a decorator to a controller.

**Comment by SebLours** [comment]
If you use the master branch, you can use the `prepare` method on the `view`.
https://github.com/marmelab/ng-admin/blob/master/src/javascripts/ng-admin/Crud/routing.js#L389

If you just want to quickly clean your entry values
```javascript
var editionView = entity.editionView()
    .fields([
        ...
    ])
    .prepare(function (entry) {
        delete entry.values.my_property;
        delete entry.values.my_other_property;
    })
;
```
or to just keep the property which has a field in the view
```javascript
var editionView = entity.editionView()
    .fields([
        ...
    ])
    .prepare(function (view, entry) {
        var fieldNames = view.fields().map(field => field.name());

        Object.keys(entry.values).forEach(property => {
            if (fieldNames.indexOf(property) == -1) {
                delete entry.values[property]
            }
        });
    })
;
```
It's not finalized but it can help you ...

**Comment by drobinson** [comment]
Great thank you - I ended up using your last example in tandem with a Restangular addFullRequestInterceptor to remove the ID from the PUT but still allow ng-admin to construct the resource endpoint:

myApp.config(['RestangularProvider', function(RestangularProvider) {
    RestangularProvider.addFullRequestInterceptor(function(element, operation, what, url, headers, params, httpConfig) {
        if(operation == 'put') {
            delete element.id;
        }
        return element;
    });
}]);

**Comment by fzaninotto** [comment]
So short story: it's not possible in ng-admin, but possible via a Restangular interceptor.
