### ISSUE TITLE
File upload: Access model in embeded_list 

### ISSUE THREAD

**Issue by etouraille** [marmelab/ng-admin#987]
Hi folks !

I want to access model in an embeded_list, in the exemple bellow, the field menu_recipes has many recipes, and i need to access recipe id in an an upload url, what is the proper syntax for recipe.id ? How can i access this value ?

```
     `nga.field('menu_recipes', 'embedded_list')
            .targetFields([
                nga.field('recipe.title'),
                nga.field('recipe.id'),
                nga.field('image','file').uploadInformation(
                        { 
                            'url': settings.baseUrl + 'fr/media/upload?ref_id='+ recipe.id +                                    '&ref=OpnRecipeBundle\\Entity\\Recipe', 
                            'apifilename': 'files' 
                        })
        ])`
```

**Comment by Kmaschta** [comment]
Hello,

As explained in the [README](https://github.com/marmelab/ng-admin/blob/master/README.md), the GitHub issue tracker is for bugs and enhancement requests.
So I close this issue, but feel free to write a question on [StackOverflow with the tag `ng-admin`](http://stackoverflow.com/questions/tagged/ng-admin).

Thanks for using ng-admin!
