### ISSUE TITLE
Datetime field no longer accepts null value

### ISSUE THREAD

**Issue by bobthekingofegypt** [marmelab/ng-admin#988]
Before updating to latest master you used to be able to have a non required datetime field and set its defaultValue to null.

After the update to latest ui-bootstrap you can't do this.

https://github.com/marmelab/ng-admin/blob/master/src/javascripts/ng-admin/Crud/field/datepickerPopup.js

This directive on the datepicker will take your null value and convert it to a new Date(null), then you end up with a 1970's date value in your datepicker.

**Comment by fzaninotto** [comment]
True, that's a regression. Marking it as bug.
