### ISSUE TITLE
ng-admin filters

### ISSUE THREAD

**Issue by Fr4ncx** [marmelab/ng-admin#999]
I want to change the search fields on the filter (list view). This is the code :

```js
filters([
          nga.field('project', 'reference')
                .label('Project')
                .targetEntity(project)
                .targetField(nga.field('nome'))
                .remoteComplete(true, {
                    refreshDelay: 200,
                    searchQuery: function(search) { return { q: search }; }
                })
        ])
```

But the query is [http://localhost:3000/days?_order=DESC&_sort=id&admin=1&limit=30&offset=0&project=138475ABC48]( )

I want the name of the project in the query not the ID.

Any suggestion ? Thank you!

**Comment by SebLours** [comment]
The reference filter use the entity identifier field.
In your case, if you want to filter an entity by `project` name, you need to set your `project` identifier as name 

```js
 var project = nga.entity('projects').identifier(nga.field('name'));
```

You can also keep your `project` entity with an id identifier and create another `project` entity (using the same API) with an identifier field set as name.

**Comment by fzaninotto** [comment]
Thanks @SebLours!
